### ISSUE TITLE
I'm not sure I understand how Proxitok work

### ISSUE THREAD

**Issue by whatbh** [libredirect/libredirect#102]
The current behavior of Tiktok is redirect www.tiktok.com to proxitok.herokuapp.com. This does not really add any value. Let me explain. 

For example, Invidious/Piped replace the Youtube embed video with its embed widget, as well as redirect Youtube homepage. Firstly, I'm expecting Tiktok redirect should work similar to this. In fact, let take [this news with Tiktok embed](https://nypost.com/2022/03/08/man-whips-tiktok-with-mistaken-flash-of-his-penis/) for example, Tiktok redirect breaks the embed widget rather than showing any replacement. 

Secondly, say I want to watch Tiktok video, and I'm expecting videos on www.tiktok.com are replaced by the proxified frontend, rather than bringing me to Proxitok. Proxitok has "Trending" and "Discover" page, but I'm not sure where are these data based on, the US? Maybe that's how it supposed to work? I have to trade off regional content delivery for less invasive tracking?

**Comment by ManeraKai** [comment]
> Tiktok redirect breaks the embed widget rather than showing any replacement.

Don't worry, this can easily be fixed. I'll add support for TikTok embeds once ProxiTok supports them.

> but I'm not sure where are these data based on, the US?

I didn't find any settings related to regional. I advice you to create an issue on [ProxiTok Github Page](https://github.com/pablouser1/ProxiTok)

**Comment by whatbh** [comment]
Ah, thanks a lot. I only thought that Proxitok support embeds already.

**Comment by ManeraKai** [comment]
I released a new version with the fix: https://github.com/libredirect/libredirect/releases/tag/v1.5.1
