### ISSUE TITLE
other setting of invidious via addon seeting are missing

### ISSUE THREAD

**Issue by rezad1393** [libredirect/libredirect#104]
can you add

Preferred DASH video quality: 
subtitle 
and 
 Show related videos:
Show annotations by default:
Automatically extend video description:
Interactive 360 degree videos (requires WebGL):
Save playback position: 

btw I think the new update (1.5 or 1.5.1) resets the cockies (or something) for instances even if I dont use the setting from addon.

so for example I would put proxy video and set quality at DASH from website preferences but when I click save and get redirected back to video page, the video is played at 720p (normal not DASH) and it is downloaded from googlevideo.com so not proxied.

this is before I set any option in addon for invidious except the url.
when I disable this addon this issue goes away.  

as a workaround in the meanwhile I will use the addon setting and set quality from there but this is still a bug.
remember that bug that user couldnt reset volume after setting it and it would get added as url parameters?
I think when you removed parameters, you replaces them with cookies (or localstorage or something) and now even when user doesnt set them or maybe because in addon they are set as default, the addon resets (or removes) the related cookies.
just a guess.

**Comment by ManeraKai** [comment]
I think I should use the naming scheme of invidious rather than putting my 'siplified' names.

**Comment by ManeraKai** [comment]
I'll add all the options, I won't add the visual preferences for now as I want to merge those with other frontends:
![LibRedirect Options- YouTube 2022-03-12](https://user-images.githubusercontent.com/40805353/158017350-6034ae87-47f6-440c-8f73-a4f26becd879.png)

**Comment by ManeraKai** [comment]
This is how the UI looks like, I still didn't implemented there logic yet but just for keeping you up-to-date. btw I fixed the cookie bug and it will now respect any cookies unless the extension has a value that overwrites them.

**Comment by rezad1393** [comment]
thank you for fast response,
but the bug also needs to be fixed.
that cookies reset (or whatever causes that with this addon the instance preferences gets reset) bug.

**Comment by ManeraKai** [comment]
> btw I fixed the cookie bug and it will now respect any cookies unless the extension has a value that overwrites them.

...

**Comment by ManeraKai** [comment]
@rezad1393 There's a problem though. LibRedirect won't overwrite cookies if the settings is set to `Default`, but if you changed the settings and then you revert them back to `Default`, then the extension won't overwrite the previously assigned cookie from the extension so the value will stay to the previous one.
If you want to use LibRedirect, then you should only use it's settings. I can add an import button with a url input to import cookie values from a specific instance.

**Comment by rezad1393** [comment]
> @rezad1393 There's a problem though. LibRedirect won't overwrite the cookie if a setting is set to `Default`, but if you changed the setting and then you revert it back to `Default`, then the extension won't overwrite the previously assigned cookie from the extension so the value will stay to the previous one. If you want to use LibRedirect, then you should only use it's settings. I can add an import button with a url input to import cookie values from a specific instance.
> 
> Did you understand what I said? it's hard to understand by just writing.
update:
it may have been the instance fault.
but what made me confused was that, that instance did that not always but most of the times. so I found another instance.
but more importantly if I re-enable your add-on then the setting of the new instance that doesn't have that issue are also reset but they are reset only once. so after re-enabling the add-on I can set them once more in the instance and they seem to stick. 
hopefully.
update :
no they dont if I change the instance to another instance then change back to the correct instance  in addon.
I think changing the setting in the addon , only if I just change the instance url in addon, resets the setting of the instance.


but if you add those setting in the addon and the work with no url parameters then it is way better for me and others because then I can disable cookies and localstorage for this instances in firefox and have better security.

btw can you be a dear and try to add nitter setting too? can it be done like the invidious one? or it is not possible?

**Comment by ManeraKai** [comment]
I think the instances are just fine and stable, it's just the extension. I'm almost finished with adding all the settings and will commit soon.

**Comment by rezad1393** [comment]
> I think the instances are just fine and stable, it's just the extension. I'm almost finished with adding all the settings and will commit soon.

thanks.
but I have seen it happens (Almost sure)  with some instance with addon disabled.
but I may have been wrong.

of course adding the setting for invidious (and finger crossed nitter too?) would be great and I can remove cookie access for those sites.

**Comment by ManeraKai** [comment]
> and finger crossed nitter too?

I plan to add settings for Nitter and even a way to follow users so when you open the home page it will be like this:
https://nitter.fdn.fr/@AJEnglish,@cnnbrk,@FoxNews

**Comment by ManeraKai** [comment]
>  I can remove cookie access for those sites.

The extension already uses cookies to interact with the settings. How is that?

**Comment by rezad1393** [comment]
> > I can remove cookie access for those sites.
> 
> The extension already uses cookies to interact with the settings. How is that?

I have set firefox to remove storage (localstorage (this folder that gets big .mozilla/firefox/PROFILE/storage/default/) and cookies to be deleted for all domains upon restart of firefox,except those that I have set. so I am hoping your addon sets it whenever I open a link to an instance? maybe? finger crossed?
if not then just please fix the cookies issue so that I add those instances to my exception from storage removal.

btw if your addon uses cookies then the issue I reported in this ticket still exist and needs to be fixed.

**Comment by ManeraKai** [comment]
The bug is almost like a conflict, If you plan to use the LibRedirect. You should only use it's settings. Now that almost all the settings are supported, this should be the way to go. And I think upon restart it will regenerate all the cookies again from it's saved data from local storage (different from LocalStorage).

**Comment by rezad1393** [comment]
> 

thank you.
also the firefox setting that removes the domains setting doesnt remove addon setting so if the addon sets the cookies at firefox restart (as you say , I am not so sure) then there is no issue and it has the advantage of working on all instances instead of me setting instances setting from their webpage one by one.

**Comment by ManeraKai** [comment]
Man things are getting complicated. This is what I'm planning to do:
I'll add a button for enabling custom settings for invidious. When this button is enabled, The extension will start using only it's settings and overwrite everything in the cookies other than the unsupported values. There will be no `Default` option in the settings, but rather the default option will be the default value that comes from a vanilla invidious instance. I'll check invidious docs for that.

**Comment by ManeraKai** [comment]
Here are the default settings:
![image](https://user-images.githubusercontent.com/40805353/158063132-c84f2b92-8bfd-40d8-ae5b-098021dae98d.png)

**Comment by ManeraKai** [comment]
Now there's a button for enabling custom settings (off by-default). Any settings that aren't supported yet will be preserved:
![image](https://user-images.githubusercontent.com/40805353/158066182-a5f0bd84-52ed-4a14-ae6b-1871dc8b4273.png)
The issue has been fixed. I'll close it.
If you face any problem, just write it here 👍
