### ISSUE TITLE
[Chrome] Manifest issue(s) preventing installation

### ISSUE THREAD

**Issue by lx-is** [libredirect/libredirect#106]
Trying to install the extension on a Chromium browser results in manifest errors, preventing it from installing. However removing the whole `chrome_settings_overrides` section fixes? this.

---

When installing from src folder:
![1-opti](https://user-images.githubusercontent.com/100533118/157985454-c0b8d46a-4889-46e7-80a1-792a05d3dada.jpg)

After seeing this error, I did some research and came across [this](https://developer.chrome.com/docs/extensions/mv3/settings_override/) documentation. So I tried the following:

```JSON
  "chrome_settings_overrides": {
    "search_provider": {
      "name": "LibRedirect",
      "search_url": "https://libredirect.onion/?q={searchTerms}",
      "favicon_url": "assets/images/libredirect-16.png",
      "encoding": "UTF-8",
      "is_default": false
    }
```
(added `"is_default": false`)

and then I get this error:
![screen-opti](https://user-images.githubusercontent.com/100533118/157985765-d41a4096-bfb7-4f67-bce0-cda04a148029.jpg)

So then I added `"keyword": "libredirect"` and got the following error:
![lib-opti](https://user-images.githubusercontent.com/100533118/157985881-06c75148-dbb1-41f8-b832-5c3659b0b32c.jpg)

After realizing fixing each error is going to seemingly result in more and more errors, I just tried removing the whole `chrome_settings_overrides` section and that allowed me to install the extension. Even without this section, it still works from what I can tell.

---

-macOS 12
-Chromium v101

**Comment by IronMaltese** [comment]
This happens in brave too :/

**Comment by lx-is** [comment]
The latest. I first tried the one from releases but still happens when downloading the latest directly from the repository.

**Comment by ManeraKai** [comment]
Some ways of installing give no errors while others give. Have you tried dragging the `.crx` file to `chrome://extensions/`?
![image](https://user-images.githubusercontent.com/40805353/157995849-d5de7771-75cb-4e3c-9bbb-0e75efee2790.png)

**Comment by lx-is** [comment]
But yeah, dragging the .crx from releases results in the error.

**Comment by ManeraKai** [comment]
> Oh, I feel stupid — there's a dedicated branch for Chrome. This branch installs perfectly. Sorry!

No!! don't use it

**Comment by lx-is** [comment]
![screen](https://user-images.githubusercontent.com/100533118/157996026-65b901cc-8284-415f-8251-ee34dd1b6f2a.jpg)

101.0.4939.0

**Comment by ManeraKai** [comment]
Try to enable `Developer mode` and kill and reopen the browser.

**Comment by lx-is** [comment]
Developer mode is already enabled :/

**Comment by ManeraKai** [comment]
You use windows?

**Comment by ManeraKai** [comment]
oh right I forgot, sorry 😅

**Comment by ManeraKai** [comment]
Try changing it to be like this:
```json
  "chrome_settings_overrides": {
    "search_provider": {
      "name": "LibRedirect",
      "keyword": "libredirect",
      "search_url": "https://libredirect.onion/?q={searchTerms}",
      "favicon_url": "assets/images/libredirect-16.png",
      "encoding": "UTF-8",
      "is_default": false
    }
```
I removed the favicon_url

**Comment by lx-is** [comment]
![1](https://user-images.githubusercontent.com/100533118/157996636-2cdab521-a448-40cd-89db-b78a410c090e.jpg)

**Comment by ManeraKai** [comment]
```json
"chrome_settings_overrides": {
    "search_provider": {
      "name": "LibRedirect",
      "keyword": "libredirect",
      "favicon_url": "https://raw.githubusercontent.com/libredirect/libredirect/master/src/assets/images/libredirect-16.png",
      "search_url": "https://libredirect.onion/?q={searchTerms}",
      "encoding": "UTF-8",
      "is_default": false
    }
```

**Comment by lx-is** [comment]
That worked!

**Comment by ManeraKai** [comment]
so it needs a url rather than a local file for it's icon. hmm...
Does this one work?
```json
"chrome_settings_overrides": {
    "search_provider": {
      "name": "LibRedirect",
      "keyword": "libredirect",
      "favicon_url": "/assets/images/libredirect-16.png",
      "search_url": "https://libredirect.onion/?q={searchTerms}",
      "encoding": "UTF-8",
      "is_default": false
    }
```

**Comment by lx-is** [comment]
![screenshot](https://user-images.githubusercontent.com/100533118/157996991-5230c5e0-d5c7-4b0b-be0f-4c628535b949.jpg)

**Comment by ManeraKai** [comment]
So it requires a url everytime, local files won't work. So... If you go to your settings and for search engines, do you find libredirect?
`chrome://settings/search`

**Comment by lx-is** [comment]
![search](https://user-images.githubusercontent.com/100533118/157997263-61a70896-3307-4c8e-ae62-e5ef1ec01783.png)

**Comment by ManeraKai** [comment]
Man this is so different from linux, If you activate it and enabled it as the default search engine, will it work and redirect you to a searX instance?

**Comment by lx-is** [comment]
It works if I use the shortcut word `libredirect`, so for example `libredirect github`.

**Comment by lx-is** [comment]
And I don't think this is a macOS difference, probably just a difference in Chrome v101 vs v99.

**Comment by ManeraKai** [comment]
nice! It means it's working, I'll commit the new manifest changes.

**Comment by ManeraKai** [comment]
>  Though maybe not as someone above commented that the issue happens on Brave.

I meant the design. I think as you said it's about the version.
