### ISSUE TITLE
https://libredirect.onion/ added as search engine?

### ISSUE THREAD

**Issue by rezad1393** [libredirect/libredirect#108]
why is there a https://libredirect.onion/ added as search engine?

**Comment by ManeraKai** [comment]
I explained everything here: https://github.com/libredirect/libredirect/issues/101#issuecomment-1063937736

**Comment by IronMaltese** [comment]
I know the url doesn't matter, but I think people get more confused with a .onion address, are you able to change it to libredirect.search or something like that

**Comment by ManeraKai** [comment]
I chose `.onion` because no one on earth can create a url like that.

**Comment by kevinlekiller** [comment]
Perhaps [.invalid](https://datatracker.ietf.org/doc/html/rfc6761#section-6.4) would avoid confusion?

**Comment by ManeraKai** [comment]
Great Idea! changed them.
