### ISSUE TITLE
Twitter doesn't redirect: Content Security Policy directive: "manifest-src 'self'"

### ISSUE THREAD

**Issue by j1cs** [libredirect/libredirect#110]
Entering to https://twitter.com/twitter shows the twitter page saying "Something went wrong. Try reloading." and the "Try Again" button.

Inspecting the chrome developer console says:
```
Refused to load manifest from 'https://nitter.sethforprivacy.com/manifest.json' because it violates the following Content Security Policy directive: "manifest-src 'self'".

12Refused to connect to '<URL>' because it violates the following Content Security Policy directive: "connect-src 'self' blob: <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL>".

Refused to connect to 'https://nitter.pussthecat.org/i/api/1.1/attribution/event.json' because it violates the following Content Security Policy directive: "connect-src 'self' blob: https://*.pscp.tv https://*.video.pscp.tv https://*.twimg.com https://api.twitter.com https://api-stream.twitter.com https://ads-api.twitter.com https://aa.twitter.com https://caps.twitter.com https://pay.twitter.com https://sentry.io https://ton.twitter.com https://twitter.com https://upload.twitter.com https://www.google-analytics.com https://accounts.google.com/gsi/status https://accounts.google.com/gsi/log https://app.link https://api2.branch.io https://bnc.lt wss://*.pscp.tv https://vmap.snappytv.com https://vmapstage.snappytv.com https://vmaprel.snappytv.com https://vmap.grabyo.com https://dhdsnappytv-vh.akamaihd.net https://pdhdsnappytv-vh.akamaihd.net https://mdhdsnappytv-vh.akamaihd.net https://mdhdsnappytv-vh.akamaihd.net https://mpdhdsnappytv-vh.akamaihd.net https://mmdhdsnappytv-vh.akamaihd.net https://mdhdsnappytv-vh.akamaihd.net https://mpdhdsnappytv-vh.akamaihd.net https://mmdhdsnappytv-vh.akamaihd.net https://dwo3ckksxlb0v.cloudfront.net".
```

![Screenshot at 2022-03-13 19-37-38](https://user-images.githubusercontent.com/4707766/158082317-3a4896dd-192e-4f2c-b92f-9542b2e843a7.png)
![Screenshot at 2022-03-13 19-38-41](https://user-images.githubusercontent.com/4707766/158082319-e9b0e6b6-9d7e-4bd2-b19a-a8e510f497e9.png)

Version: 1.5.3
I installed the crx by dragging it onto the browser. In this case is Brave [Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)]

**Comment by ManeraKai** [comment]
Dose this happen everytime?

**Comment by j1cs** [comment]
Exactly. With every mobile.twitter.com too. Weird because it just started yesterday and in the night started to stop working (in my timezone of course)

**Comment by ManeraKai** [comment]
I think something is wrong with the new release. I'll see what it is.

**Comment by ManeraKai** [comment]
Seems something is wrong with Brave itself

**Comment by ManeraKai** [comment]
I can't access the first link:
![image](https://user-images.githubusercontent.com/40805353/158215508-4fe13a6a-e443-4a69-9e39-57079dac2026.png)
The first one should be `url https://twitter.com/` but it's not. Try to enable and disable shields. It will reload the page and redirect properly:
![image](https://user-images.githubusercontent.com/40805353/158215710-3ee5e8e4-732f-4250-8732-e5e81efdebdc.png)

**Comment by ManeraKai** [comment]
This is how the first url in console should look like: 
![image](https://user-images.githubusercontent.com/40805353/158215887-d5f1059c-f6f4-4133-9634-107e5b91ee83.png)
btw I added a line to write to console. It's not in the `.crx` and the console I'm viewing the for the extension itself, you access it through here:
![image](https://user-images.githubusercontent.com/40805353/158216012-7597c35c-8a35-4232-8898-08ea9599be63.png)

**Comment by j1cs** [comment]
Indeed. I just reproduced your steps and yeah enable and disable brave shields "works"

**Comment by ManeraKai** [comment]
I can't do anything about it on my side. I tried changing some settings in brave but with no success. Idk.

**Comment by j1cs** [comment]
I see. well I removed all configuration (deleted folders) and started with a fresh brave. I'll put everything back to the way it was before manually and see if there is something that reproduces the error again.

**Comment by j1cs** [comment]
I went to Application then Storage in the tabs from the developers tools , "Clear site data" and the error disappear.
