### ISSUE TITLE
Allow only redirect part domain

### ISSUE THREAD

**Issue by linsui** [libredirect/libredirect#114]
I want to redirect twitter.com but I don't want to redirect twimg.com. It would be great if I can only redirect twitter.com. Thanks!

**Comment by ManeraKai** [comment]
You can add a regex to the exception list: `^https?:\/{2}(pbs\.|video\.|)twimg\.com`. This is the same exact one that LibRedirect uses and it will cut it all off.

**Comment by linsui** [comment]
Great! Thanks!
