### ISSUE TITLE
Add Apple Maps

### ISSUE THREAD

**Issue by TanKot** [libredirect/libredirect#116]
Requesting the dev to add Apple Maps As an alternative to google maps

**Comment by Mennaruuk** [comment]
Example:

From:
`https://maps.google.com/maps?q=1+hacker+way+menlo+park+california+united+states&gs_lcp=DLgCQIgAHAABQgEBlggAEBhAEADDCxdROFC6hLgICDBAEJcYAIQADwHNBAEABAQgQAIBgxBCAy3BQlOGddBoOmDIDEACABQRyQhQSChgDABMMIAIgyAQhkAEAQeAgBCyUCMCFACIgk2AAzREAAQAECExSEA2jyLEcCCQhnJcMAsoBMAAgQtxIAQgTAI0GAFMAYAIEORQgEgXLBQAIgQQIBsggn9IHIGCAAFA4ADgEDUChjwQHGxDBDATEEAI2ABxoAEEg0gMDAhAdCCoMAEAIKQBBAB6vYAADAIDAAAORIxAC4CQKxAEAGwIBhwGwEqAGMIIABuxQAIwhEA2&um=1&ie=UTF-8&sa=X&ved=wJQh2wH_2UM8I-s0KvUAaAWdD2XAQxKE5oXBjCVhAEoAhU3`

To:
`https://duckduckgo.com/?q=1+hacker+way+menlo+park+california+united+states&t=h_&ia=web&iaxm=maps`

**Comment by TanKot** [comment]
Yep Just Like This ☝️

**Comment by ManeraKai** [comment]
Please read the discussion in #70
