### ISSUE TITLE
Chromium version update from GitHub

### ISSUE THREAD

**Issue by TotalCaesar659** [libredirect/libredirect#118]
[Bypass Paywalls](https://github.com/iamadamdev/bypass-paywalls-chrome) extension isn't in Chrome WebStore as LibRedirect, but it has [internal updates](https://github.com/iamadamdev/bypass-paywalls-chrome/blob/master/src/updates/updates.xml) from GitHub. Could you implement smth similar like this?

**Comment by ManeraKai** [comment]
I've now added the instructions to README. Tested it and worked correctly. Hopefully it'll work fine. Hopefully...

**Comment by ManeraKai** [comment]
I'll close the issue, any problem you face and write it here 👍

**Comment by IronMaltese** [comment]
This is incredible! Thank you so much

**Comment by ManeraKai** [comment]
Problem: Because of this issue: https://github.com/libredirect/libredirect/issues/125 I change the [steps](https://github.com/libredirect/libredirect/blob/master/chromium.md) to install as `Load unpacked` instead of just dragging the `.crx` file. This though changes the extension ID and it won't update as it updates from the `.crx` files in the release page that have a different ID. If you installed the extension first time through the `.crx` file in the extension. It'll update just fine as I sign everything with the same private key.

I want to know how to sign a `source code` in that sense.

**Comment by ManeraKai** [comment]
Further reading and I found that the Bypass Paywalls is a copy or something from [bypass-paywalls-clean](https://addons.mozilla.org/en-US/firefox/addon/bypass-paywalls-clean/)? [context](https://twitter.com/Magnolia1234B/status/1378745740147765249)

Anyway, I found this in that original extension's repo: https://gitlab.com/magnolia1234/bypass-paywalls-chrome-clean/-/blob/master/allowlist/README.md
This will add the `.crx` signing key you can say to a whitelist. This would be the solution hopefully.

**Comment by ManeraKai** [comment]
@IronMaltese go to this folder: https://github.com/libredirect/libredirect/tree/master/allowlist and do it as instructed for brave. Then try to install this `.crx`: [libredirect-1.5.8.crx.zip](https://github.com/libredirect/libredirect/files/8338249/libredirect-1.5.8.crx.zip) btw unzip it first. I can't just upload a `.crx` here.

**Comment by TotalCaesar659** [comment]
@ManeraKai I use Ungoogled Chromium with [Chromium Web Store](https://github.com/NeverDecaf/chromium-web-store), extension that changes original store. It has internal updates [too](https://github.com/NeverDecaf/chromium-web-store/blob/master/updates.xml), so you can look at this.

**Comment by ManeraKai** [comment]
Fixed!!!! Thanks @TotalCaesar659! You should add the `key` key to your manifest. It's weird that tried that before with not success. Thankfully though it's working now. I'll release two releases right now and see if it will update or not.

**Comment by ManeraKai** [comment]
Sadly. Still not working. The ids are the same. Even when unzipping the `.crx` that itself is working just fine with updates. idk what's happening. Will look further into it as why `Load unpacked` doesn't accept updates.

**Comment by ManeraKai** [comment]
@IronMaltese tell me when you're available. Will try something on your machine. I'll try the older idea of adding the `.crx` to the allowlist

**Comment by IronMaltese** [comment]
I sadly won't be available today or tomorrow, but I should be free Saturday

**Comment by ManeraKai** [comment]
https://developer.chrome.com/docs/extensions/mv2/external_extensions/#prereqs

**Comment by IronMaltese** [comment]
💀💀💀 Rip

**Comment by IronMaltese** [comment]
Just add this prerequisite to the chromium download and this can be closed

**Comment by ManeraKai** [comment]
I will add two ways:
1. For Linux users using the `.crx` where the extension where it will update automatically.
2. For Windows, Mac users using the `load unpacked` where it won't update automatically.

**Comment by bingoxo** [comment]
can there be a workaround with brave browser ?

**Comment by ManeraKai** [comment]
Nope :/ maybe there's a workaround but it will be so so complex getting into system files and adding my signing key and I still didn't try it to know if it will work.

**Comment by bingoxo** [comment]
@ManeraKai 
you mean a solution like the one at https://gitlab.com/magnolia1234/bypass-paywalls-chrome-clean/-/blob/master/allowlist/README.md ?

i volunteer to test it , where do i get the signing key ?

**Comment by ManeraKai** [comment]
I shouldn't gave you the signing key rather you just put the .crx in the allow list
