### ISSUE TITLE
Extension does not work on waterfox classic aka old firefox

### ISSUE THREAD

**Issue by kolva3** [libredirect/libredirect#119]
i know mock me for using waterfox classic
version 1.2.2 is the last version that works on classic before the new UI that breaks the settings and redirects, now on the firefox addons website it says "Works with firefox 48.0 and later, android 48.0 and later" and I just want to know if this is a bug or an accidental versioning issue

**Comment by Mennaruuk** [comment]
![image](https://user-images.githubusercontent.com/52135169/158930315-27fa3d4a-0ba4-4e44-9612-8ca02463d790.png)
[More about SyntaxError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_token)

**Comment by ManeraKai** [comment]
I have those errors:
![image](https://user-images.githubusercontent.com/40805353/158955715-5d05239e-d880-4c6f-b08c-2adf00846862.png)

**Comment by ManeraKai** [comment]
I just can't support old versions. I think I should add min_version

**Comment by ManeraKai** [comment]
I'm sorry @kolva3 but I can't support it. I'll close the issue.
