### ISSUE TITLE
searxng vs searx

### ISSUE THREAD

**Issue by Mennaruuk** [libredirect/libredirect#120]
Hey Manera.

So, I checked the list of instances over at https://searx.space. The list is maintained by the searxng team. However, the list has searx and searxng instances mixed, presenting an issue for users who want to exclusively use one project.

I already filed an issue letting the searxng team know about this, but do you happen to know an easy way to check whether instances are searx or searxng? I manually checked them (see below), so for now the values are there, but what about in the future? I see that when you hover over the instance links at searx.space, you can see the title attributes (the **URL** column below) containing searx or searxng for the vast majority of them. Maybe these can be fetched from time to time, and these values can act as the basis for something like radio buttons or dropdown menu allowing users to choose which project? Thank you very much.

| Instance                                 | URL                                         | Type                             |
|------------------------------------------|---------------------------------------------|----------------------------------|
| https://search.ononoki.org/              | https://github.com/searxng/searxng          | searxng                          |
| https://paulgo.io/                       | https://github.com/paulgoio/searxng         | searxng                          |
| https://searx.tiekoetter.com/            | https://github.com/tiekoetter/searxng       | searxng                          |
| https://searx-private-search.de/         | https://github.com/TordenskjoldJr/searxng   | searxng                          |
| https://northboot.xyz/                   | https://github.com/searxng/searxng          | searxng                          |
| https://searx.be/                        | https://github.com/searxng/searxng          | searxng                          |
| https://search.mdosch.de/                | https://github.com/searxng/searxng          | searxng                          |
| https://search.bus-hit.me/               | https://github.com/searxng/searxng          | searxng                          |
| https://s.zhaocloud.net/                 | https://github.com/searxng/searxng          | searxng                          |
| https://swag.pw/                         | https://github.com/searxng/searxng          | searxng                          |
| https://searxng.zackptg5.com/            | https://github.com/searxng/searxng          | searxng                          |
| https://serx.cf/                         | https://github.com/inoblue/searxng          | searxng                          |
| https://searx.mha.fi/                    | https://github.com/searxng/searxng          | searxng                          |
| https://searx.ebnar.xyz/                 | https://github.com/searxng/searxng          | searxng                          |
| https://searx.gnous.eu/                  | https://github.com/searxng/searxng          | searxng                          |
| https://searx.bar/                       | https://github.com/searx/searx              | searx                            |
| https://search.stinpriza.org/            | https://salsa.debian.org/debian/searx       | searx                            |
| https://search.asynchronousexchange.com/ | https://github.com/searx/searx              | searx                            |
| https://www.webrats.xyz/                 | https://github.com/theeddie/webratsxyz      | WebRats.xyz (searxng underneath) |
| https://anon.sx/                         | https://github.com/searx/searx              | searx                            |
| https://search.disroot.org/              | https://github.com/searx/searx              | searx                            |
| https://searx.fmac.xyz/                  | https://github.com/searxng/searxng          | searxng                          |
| https://searx.ru/                        | https://github.com/searx/searx              | searx                            |
| https://searx.gnu.style/                 | https://github.com/dasj19/searx             | searx                            |
| https://searx.theanonymouse.xyz/         | https://github.com/searx/searx              | searx                            |
| https://searx.prvcy.eu/                  | https://github.com/searx/searx              | searx                            |
| https://searx.webheberg.info/            | https://github.com/searx/searx              | searx                            |
| https://searx.nevrlands.de/              | https://github.com/searx/searx              | searx                            |
| https://search.jpope.org/                | https://github.com/searx/searx              | searx                            |
| https://searx.pwoss.org/                 | https://github.com/searx/searx              | searx                            |
| https://www.gruble.de/                   | https://github.com/searx/searx              | searx                            |
| https://procurx.pt/                      | https://github.com/searx/searx              | searx                            |
| https://searx.stuehieyr.com/             | https://github.com/searx/searx              | searx                            |
| https://searx.divided-by-zero.eu/        | https://github.com/searx/searx              | searx                            |
| https://search.neet.works/               | https://github.com/searxng/searxng          | searxng                          |
| https://searx.sp-codes.de/               | https://github.com/searx/searx              | searx                            |
| https://searx.xyz/                       | https://github.com/searx/searx              | searx                            |
| https://searx.rasp.fr/                   | https://github.com/searxng/searxng          | searxng                          |
| https://searx.tuxcloud.net/              | https://github.com/searx/searx              | searx                            |
| https://searx.tux.land/                  | https://github.com/searx/searx              | searx                            |
| https://searx.bissisoft.com/             | https://github.com/searx/searx              | searx                            |
| https://search.snopyta.org/              | https://github.com/searx/searx              | searx                            |
| https://searx.roflcopter.fr/             | https://github.com/searx/searx              | searx                            |
| https://searx.netzspielplatz.de/         | https://github.com/searx/searx              | searx                            |
| https://searx.dresden.network/           | https://github.com/searx/searx              | searx                            |
| https://searx.mastodontech.de/           | https://github.com/searx/searx              | searx                            |
| https://sx.catgirl.cloud/                | https://github.com/searx/searx              | searx                            |
| https://searx.solusar.de/                | https://github.com/searx/searx              | searx                            |
| https://suche.uferwerk.org/              | https://github.com/searx/searx              | searx                            |
| https://suche.tromdienste.de/            | https://github.com/searx/searx              | searx                            |
| https://search.trom.tf/                  | https://github.com/searx/searx              | searx                            |
| https://searx.zecircle.xyz/              | https://github.com/searx/searx              | searx                            |
| https://searx.run/                       | https://github.com/searx/searx              | searx                            |
| https://searx.nakhan.net/                | https://github.com/searx/searx              | searx                            |
| https://suche.dasnetzundich.de/          | https://github.com/searx/searx              | searx                            |
| https://searx.nixnet.services/           | https://github.com/searx/searx              | searx                            |
| https://searx.esmailelbob.xyz/           | https://github.com/searx/searx              | searx                            |
| https://searx.mxchange.org/              | https://github.com/searx/searx              | searx                            |
| https://search.antonkling.se/            | https://github.com/searx/searx              | searx                            |
| https://searx.josie.lol/                 | https://github.com/searx/searx              | searx                            |
| https://jsearch.pw/                      | https://github.com/searx/searx              | searx                            |
| https://engo.mint.lgbt/                  | https://github.com/searx/searx              | searx                            |
| https://search.ethibox.fr/               | https://github.com/searx/searx              | searx                            |
| https://searx.org/                       | https://github.com/searx/searx              | searx                            |
| https://searx.zapashcanon.fr/            | https://salsa.debian.org/debian/searx       | searx                            |
| https://timdor.noip.me/searx/            | https://github.com/searx/searx              | searx                            |
| https://searx.openhoofd.nl/              | https://github.com/searx/searx              | searx                            |
| https://dynabyte.ca/                     | https://github.com/searx/searx              | searx                            |
| https://searx.tyil.nl/                   | https://github.com/searx/searx              | searx                            |
| https://search.zdechov.net/              | https://salsa.debian.org/debian/searx       | searx                            |
| https://searx.roughs.ru/                 | https://github.com/searx/searx              | searx                            |
| https://searx.ninja/                     | https://github.com/searx/searx              | searx                            |
| https://trovu.komun.org/                 | https://github.com/searx/searx              | searx                            |
| https://searx.everdot.org/               | https://github.com/searx/searx              | searx                            |
| https://search.st8.at/                   | https://github.com/searx/searx              | searx                            |
| https://searx.thegreenwebfoundation.org/ | https://github.com/searx/searx              | searx                            |
| https://searx.slash-dev.de/              | https://github.com/searx/searx              | searx                            |
| https://searx.lavatech.top/              | https://github.com/searx/searx              | searx                            |
| https://darmarit.org/searx/              | https://github.com/return42/searxng         | searxng                          |
| https://nibblehole.com/                  | https://github.com/searx/searx              | searx                            |
| https://spot.ecloud.global/              | https://gitlab.e.foundation/e/cloud/my-spot | Spot (a searx fork)              |

**Comment by ManeraKai** [comment]
I'll wait for now to see if they will fix it from there side.

**Comment by ManeraKai** [comment]
Separated them. If you encountered any problem, just write it here. I'll close the issue.
