### ISSUE TITLE
Old Reddit not redirecting properly

### ISSUE THREAD

**Issue by prettyv** [libredirect/libredirect#122]
When setting the Reddit frontend to "Old Reddit", Firefox shows a "The page isn't redirecting properly" error since a few versions. Seems to me like `old.reddit.com` is itself now being redirected to the configured frontend, which breaks when "Old Reddit" is the selected one, ending in a loop.

**Comment by ManeraKai** [comment]
Tested it and I think it's fixed now. If anything happens, just write it here 👍
