### ISSUE TITLE
Do not redirect imgur delete links

### ISSUE THREAD

**Issue by fabianski7** [libredirect/libredirect#124]
According to rimgo readme, it is read-only, so requesting the deletion of images is not a supported function and probably won't be either.

Example of such a url: `https://imgur.com/delete/qlqRNsXde2JkEWI`

**Comment by ManeraKai** [comment]
If any one wants to post an image on imgur. He should disable the redirections completely, but I'll do that as I think still people use this link

**Comment by fabianski7** [comment]
Well, I don't post images on imgur directly.
I use a capture software that sends images directly there, without having to go to the site

**Comment by ManeraKai** [comment]
Is there any other links that are commands?

**Comment by fabianski7** [comment]
No. At least not where I found this one.

**Comment by fabianski7** [comment]
Thanks @ManeraKai!
