### ISSUE TITLE
Chrome download only works for Linux

### ISSUE THREAD

**Issue by IronMaltese** [libredirect/libredirect#125]
I'm using Brave on MacOS and when I follow the steps everything goes well until I drag the file into brave and get an error that directs me to https://support.brave.com/hc/en-us/articles/360017914832-Why-am-I-seeing-the-message-extensions-disabled-by-Brave-?hl=en-US

**Comment by ManeraKai** [comment]
Can you show me a screen recording?

**Comment by ManeraKai** [comment]
This too: https://stackoverflow.com/questions/19109046/manually-install-add-extension-to-chrome-on-mac-os-x

**Comment by IronMaltese** [comment]
https://user-images.githubusercontent.com/89056889/159187051-7e8443e3-a031-4216-8e0c-7fbb7b41a02f.MOV

**Comment by Anatharias** [comment]
Same here with Brave [Version 1.36.111] it states that it might have been added without me knowing and prevents enabling it.

**Comment by ManeraKai** [comment]
So you're saying that it was installing properly before? Try to install it using the unpacked feature:

https://user-images.githubusercontent.com/40805353/159202824-0706e53b-7163-4acf-8b0d-e9bc1eb18574.mp4

**Comment by IronMaltese** [comment]
This worked for me, the Read.me file should be updated to accomodate MacOS and Windows users, Thanks for the quick response

**Comment by ManeraKai** [comment]
I'll make it the same for all as it won't affect and won't give warnings about ***unsigned*** extensions.
