### ISSUE TITLE
exonip services domain change

### ISSUE THREAD

**Issue by 3ship** [libredirect/libredirect#126]
Currently displayed on nitter.exonip.de:

>All privacy services that were previously accessible as subdomains of exonip.**com** (nitter.exonip.com, piped.exonip.com, etc.) are now accessible as subdomains of the new domain privacy.com.com (nitter.privacy.com.com, piped.privacy.com.com, etc.).

The German text says that exonip.**de** services are now available under privacy.com.de (nitter.privacy.com.de, piped.privacy.com.de, etc.)

It should be noted that the .com.com domain is for some reason currently blocked by uBlock Origin under "Badware risks":

![screencap-2022-03-20-201226-764x543](https://user-images.githubusercontent.com/47889681/159178840-6dd5dd31-7c67-4cd5-b0b2-fab0d3d1e255.png)

**Comment by ManeraKai** [comment]
You should open an issue on [Nitter](https://github.com/zedeus/nitter)'s page. The instances list is automatically fetched from them without intervention from us. They should update it.

**Comment by 3ship** [comment]
I filed a bug in Nitter's repo.

There's also a libreddit service under `libreddit.exonip.de`

I assume that's fetched from somewhere else?

**Comment by ManeraKai** [comment]
Yeah it's fetched from there Wiki: https://github.com/zedeus/nitter/wiki/Instances
If they uodated the wiki/list, it'll be automatically updated in LibRedirect.

**Comment by 3ship** [comment]
Hi. I was talking about the Teddit instance under `libreddit.exonip.de`
Apparently it's fetched from here: https://codeberg.org/teddit/teddit/raw/branch/main/instances.json
The exonip instance is no longer listed in it, so I don't think it needs to be reported.

The Nitter instance has also been edited according to https://github.com/zedeus/nitter/issues/583 so I'm gonna close this issue.

**Comment by ManeraKai** [comment]
> Apparently it's fetched from here: https://codeberg.org/teddit/teddit/raw/branch/main/instances.json

This is teddit's instance list. The instance is a libreddit intsance not a teddit. Here is libreddit's list: https://github.com/spikecodes/libreddit#instances

btw we still didn't add the implementation of automatically fetching instances from libreddit as there's no `.json` file. There are issues opened about this and if it wasn't done, I think we'll scrap the Github page for the list.
