### ISSUE TITLE
How to exempt YouTube Movies from the redirect?

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#130]
You can watch DRM protected movies on YouTube, either by renting/buying them, or when they're available to watch for free. For obvious reasons, Private Frontends like Invidious cannot allow the playback of these films. They can only be seen on YouTube itself. 

Seeing as the extension allows for redirect "exemptions" based on URL and/or Regex, I'm curious what the most optimal redirect condition would be.

**Comment by ManeraKai** [comment]
This should be as a default feature. Do you have any urls or examples?

**Comment by MintMain21** [comment]
https://www.youtube.com/watch?v=0BeivZj9OyU

This redirects to Invidious. Granted I can easily go to YouTube from here, but it's inconvenient never the less.

Likewise, using this link https://www.youtube.com/channel/UCuVPpxrm2VAgpH3Ktln4HXg only works when redirects are disabled. 

Privacy Redirect allows YouTube links to work when accessed from the preferred Invidious Instance. It would appear as if that functionality is not recreated in this extension.

**Comment by ManeraKai** [comment]
> https://www.youtube.com/watch?v=0BeivZj9OyU

I just can't detect that url. It's just an ID

> Likewise, using this link https://www.youtube.com/channel/UCuVPpxrm2VAgpH3Ktln4HXg only works when redirects are disabled.

Though I can detect this one since it's just one channel. You should open an issue on invidious though to tell them so they'll have a nice page saying that DRM protected videos aren't supported by invidious for obvious reasons.

**Comment by ManeraKai** [comment]
Any updates @MintMain21?

**Comment by ManeraKai** [comment]
Are you alive @MintMain21?

**Comment by MintMain21** [comment]
I'm not using LibRedirect anymore. I've migrated back to Privacy Redirect. Sorry.

**Comment by ManeraKai** [comment]
I'll close this issue then as it should be implemented from invidious side rather than ours. There should be a description of why this page isn't supported.
