### ISSUE TITLE
Redirecting Twitter to Nitter breaks text encoding

### ISSUE THREAD

**Issue by austinhuang0131** [libredirect/libredirect#135]
eg. Visiting https://tw.artemislena.eu/ with LibRedirect (v1.5.7) on shows the source code of the page, it doesn't render. For https://nitter.net/ it seems to show the source code in a different text encoding.

Presumably because you're messing with the headers... Wouldn't it be better to only apply whatever manipulation you got only on URLs ending with `/embed`?

**Comment by ManeraKai** [comment]
I only apply headers to urls that have a type of sub_frame:
![image](https://user-images.githubusercontent.com/40805353/159834722-1ac6a0ae-9bdb-4772-bde0-7df415f78a15.png)
Found a way to fix it though. I don't know when you return the same header (the last line of the code in the image), it breaks it.

**Comment by austinhuang0131** [comment]
Persists. Please reopen.

**Comment by ManeraKai** [comment]
Sorry, small typo `=` => `==`

**Comment by ManeraKai** [comment]
It's fixed on my machine. Fixed on yours @austinhuang0131right?

**Comment by austinhuang0131** [comment]
Yes
