### ISSUE TITLE
Medium: exceptions to make

### ISSUE THREAD

**Issue by mizzunet** [libredirect/libredirect#137]
Would be able to make exception for Medium for links `medium.com/tag/*` `medium.com/@*`

For example, https://medium.com/tag/books redirects to https://scribe.rip/tag/books
https://medium.com/@jessicalexicus

>Scribe just tried to parse the Medium URL but wasn't able to. Scribe is only built to display articles. It's not built to browse or search Medium, it's users, hashtags, comments, or anything else.

Thanks

**Comment by ManeraKai** [comment]
Added them. I'll close the issue.

**Comment by x51mon** [comment]
Here medium.com does not get replaced although it would work:  
[https://medium.com/@joeri.juramento/extending-signals-multi-device-design-8ac764f97e7d](https://medium.com/@joeri.juramento/extending-signals-multi-device-design-8ac764f97e7d)

**Comment by ManeraKai** [comment]
Oh I see. It should not redirect and thing that is
`https://medium.com/@joeri.juramento` but it should redirect
`https://medium.com/@joeri.juramento/extending-signals-multi-device-design-8ac764f97e7d`

**Comment by EdwardLangdon** [comment]
I am reopening this issue as Medium subdomains aren't redirected, For Example : https://onezero.medium.com/elon-musk-tries-to-buy-twitter-whats-actually-happening-fd631f1e7817.

So, According to the Regex Medium subdomains should also be redirected.

**Comment by EdwardLangdon** [comment]
You should take the subdomain part `Onezero` and add it as @Onezero in the URL like this - https://medium.com/@OneZero/elon-musk-tries-to-buy-twitter-whats-actually-happening-fd631f1e7817

**Comment by EdwardLangdon** [comment]
Doing so only will redirect to Scribe.

**Comment by EdwardLangdon** [comment]
Accidentally Closed the issue. When using Keyboard Shortcuts.

**Comment by ManeraKai** [comment]
Fixed it. It should work, hopefully...

**Comment by EdwardLangdon** [comment]
I will check from the source again and tell you.

**Comment by EdwardLangdon** [comment]
@ManeraKai I checked from the source and it works as it should and excepted. So, I am closing this issue.
