### ISSUE TITLE
Nitter: Enable Custom Settings (like Invidious and Piped)

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#138]
Like Invidious and Piped, Nitter can store Custom settings as cookies (Theme, Enabling Video Playback, showing distractions, etc).

Options to persist these settings like for Invidious and Piped would be welcome.

**Comment by ManeraKai** [comment]
yep. You can even add your custom ones to for their cookies to be modified too.

**Comment by ManeraKai** [comment]
You may feel the extension is a little bit slower and unresponsive. I'll optimize it more. For now, Nitter has a Settings page!
