### ISSUE TITLE
Piped

### ISSUE THREAD

**Issue by Loki-L1130** [libredirect/libredirect#14]
Piped is Privacy-oriented YouTube Frontend which is like Invidious but uses Javascript. I think you can add it as a Separate option instead of mixing in the Invidious Instance Pool.

Open Issue in Main repo : https://github.com/SimonBrazell/privacy-redirect/issues/181

**Comment by den7007** [comment]
Would be great to integrate this so there is no need to install another add-on just for Piped (For the meantime, am using theirs: https://addons.mozilla.org/en-US/firefox/addon/piped-redirects/)

**Comment by Loki-L1130** [comment]
Yeah, I am also. The Thing is we can make them to can implement Invidious Redirect like there and just redirect to the Invidious Instance we want by just adding an Exception.

**Comment by Loki-L1130** [comment]
Instances list to be added : https://github.com/TeamPiped/Piped/wiki/Instances

**Comment by Loki-L1130** [comment]
Just remove the `api` before implementing because it was to used to use between the Instances in the Own Pool of Instances

**Comment by ManeraKai** [comment]
What `api` do you mean?

**Comment by ManeraKai** [comment]
The [instances list](https://github.com/TeamPiped/Piped/wiki/Instances) is the weirdest list I've seen so far. I've eventually got all the URLs correct except for `moomoo.me`.

**Comment by ManeraKai** [comment]
Added it: https://github.com/libredirect/libredirect/commit/b4fcdf26ead7072f02d29be7e4b26c572dfbbf4a

**Comment by Loki-L1130** [comment]
I mean in the instances list remove `api` from URL so it might not return a 404 error or a raw JSON data.

**Comment by Loki-L1130** [comment]
Is it separate from Invidious ?

**Comment by ManeraKai** [comment]
> Is it separate from Invidious ?

Ofc, you can choose between it and invidious in the settings pages

**Comment by Loki-L1130** [comment]
Will this be in a New Release or by hitting Update Instances ?

**Comment by Loki-L1130** [comment]
I think you can also consider this - https://github.com/SimonBrazell/privacy-redirect/issues/181#issuecomment-1019173916

Even redirecting invidious to Piped links if we want invidious links not to redirect we can use an Exception rule which will be useful. This is actually working of the Official Piped extension but there is not exception like in Lib or Privacy redirect.

**Comment by ManeraKai** [comment]
> Will this be in a New Release or by hitting Update Instances ?

Update instances only updates a [json file](https://github.com/libredirect/instances/blob/main/data.json) containing a list of working insances. This new code should be in a new release.

**Comment by ManeraKai** [comment]
> I think you can also consider this - https://github.com/SimonBrazell/privacy-redirect/issues/181#issuecomment-1019173916
Even redirecting invidious to Piped links if we want invidious links not to redirect we can use an Exception rule which will be useful. This is actually working of the Official Piped extension but there is not exception like in Lib or Privacy redirect.

Why do you want to redirect invidious links?

**Comment by Loki-L1130** [comment]
> > I think you can also consider this - [SimonBrazell#181 (comment)](https://github.com/SimonBrazell/privacy-redirect/issues/181#issuecomment-1019173916)
> > Even redirecting invidious to Piped links if we want invidious links not to redirect we can use an Exception rule which will be useful. This is actually working of the Official Piped extension but there is not exception like in Lib or Privacy redirect.
> 
> Why do you want to redirect invidious links?

Because Piped is better than Invidious in terms of overall Use, Performance and Stability and unlike Slow development of Invidious it is developing at a faster rate and the community like it.

**Comment by Loki-L1130** [comment]
That is also why I told you that if we need Invidious we can make a exception. If you are worried that other users will not know better make a notice about it when using the feature.

**Comment by ManeraKai** [comment]
I mean the only links that the user will click are youtube links, I didn't see any invidious link other than in matrix rooms

**Comment by ManeraKai** [comment]
I already made Piped the default option, users can however choose the frontend they want: 
![image](https://user-images.githubusercontent.com/40805353/152537862-3287bc11-5c3a-425b-915d-5be4076bd4a1.png)

**Comment by ManeraKai** [comment]
Same thing goes for Translate, Search, Reddit. All have multiple frontends that you can choose which one in the settings. However, the best option is the default option.

**Comment by Loki-L1130** [comment]
I think you should use the Official Piped Redirects extension, enable it and then click on Invidious and YouTube Links with Libredirect disabled.

**Comment by Loki-L1130** [comment]
You will then understand by what I mean

**Comment by ManeraKai** [comment]
I've done that, yeah redirecting Invidious links to Piped, but why? No one uses invidious links to share media.

**Comment by ManeraKai** [comment]
Maybe I'm missing something?

**Comment by Loki-L1130** [comment]
> Maybe I'm missing something?

Because privacy oriented guys like Techlore in their surveillance Report and majority of matrix users use Invidious links of Instead of YouTube which is very much old schooled and broken often at sometimes so you don't get to like to view it and also in Piped we have an account system like Piped and settings that apply cross site. But in Invidious we need to have the settings already and need to save it as a cookie and also we may clear and many consequences to face with Invidious such as Google Captchas & limits number of users or Video Player Broke, etc.

That is why I also propose a solution add a banner in the section and use of exception solves this.

**Comment by ManeraKai** [comment]
I see, I'll make it when `invidious` is selected to forward `youtube` and `piped` urls to it. Same thing for piped, it will redirect `youtube` and `invidious` links to it. Same for FreeTube too...

> That is why I also propose a solution add a banner in the section and use of exception solves this.

If a person chose to view videos in a specific Frontend, then I don't think they want to have exceptions. If someone requested that feature (`exceptions`), I'll add it.

What do you think @Loki-L1130 ?

**Comment by Loki-L1130** [comment]
@ManeraKai I think this is pretty much a great Idea to implement. Both Invidious and Piped users gets benefit of this.

With the exceptions, You don't need to do anything as in the exceptions menu of Libredirect, If we add a URL it is automatically excluded from redirection. That's it. You just need to force the URLs to redirect to specific Frontends.

This is personal Question, How to actually use the Freetube Redirect because I haven't used it from the start ?

**Comment by Loki-L1130** [comment]
Does the settings you have for Invidious do apply to Piped too ?

**Comment by alefvanoon** [comment]
> Does the settings you have for Invidious do apply to Piped too ?

No, I don't think Piped have this options.

**Comment by alefvanoon** [comment]
> Does the settings you have for Invidious do apply to Piped too ?

No, I don't think Piped have this options.
CC: @FireMasterK

**Comment by ManeraKai** [comment]
> This is personal Question, How to actually use the Freetube Redirect because I haven't used it from the start ?

Just install FreeTube, and select it as a frontend, this is how it redirects in code: https://github.com/libredirect/libredirect/blob/master/src/assets/javascripts/helpers/youtube/youtube.js#L239

original: `https://www.youtube.com/watch?v=J4osVFVeQrI`
new:      `freetube://https://www.youtube.com/watch?v=J4osVFVeQrI`

**Comment by ManeraKai** [comment]
> Does the settings you have for Invidious do apply to Piped too ?

Not yet, but that is a nice idea btw.

**Comment by FireMasterK** [comment]
> No, I don't think Piped have this options.
> CC: @FireMasterK

A full list of parameters can be found at https://piped-docs.kavin.rocks/docs/parameters/

**Comment by Loki-L1130** [comment]
> original: `https://www.youtube.com/watch?v=J4osVFVeQrI` new: `freetube://https://www.youtube.com/watch?v=J4osVFVeQrI`

So, It automatically opens Videos in Freetube even it is an embed ?

**Comment by Loki-L1130** [comment]
> Not yet, but that is a nice idea btw.

@FireMasterK Could help you ya ?

**Comment by ManeraKai** [comment]
> So, It automatically opens Videos in Freetube even it is an embed ?

This might be a problem. I thought of it before to add an extra option for embeds if FreeTube was selected.

**Comment by ManeraKai** [comment]
I forgot I added the disable freetube part for only embeds. Now I just need to add an additional setting.
![image](https://user-images.githubusercontent.com/40805353/152641416-7ba88bf1-07b3-41a2-9dc3-5e3774e88996.png)

**Comment by Loki-L1130** [comment]
> > So, It automatically opens Videos in Freetube even it is an embed ?
> 
> This might be a problem. I thought of it before to add an extra option for embeds if FreeTube was selected.

I am just asking not a feature request.

**Comment by ManeraKai** [comment]
> I am just asking not a feature request.

It became a feature request, no problems with that 👍

**Comment by Loki-L1130** [comment]
Kai, Can you also look onto this ?

https://github.com/TeamPiped/Piped-Redirects/issues/10#issue-1030091296

**Comment by Loki-L1130** [comment]
Consider this : https://github.com/TeamPiped/Piped/issues/786#issuecomment-1030610237 before full implementation of Piped.

**Comment by ManeraKai** [comment]
Isn't the extension considered as the full implementation?

**Comment by Loki-L1130** [comment]
> Isn't the extension considered as the full implementation?

Yeah, It is but it has issues with replacing embeds of Shorts Videos alone.

**Comment by ManeraKai** [comment]
in invidious redirection: just delete of the `/shorts` path
https://github.com/libredirect/libredirect/blob/master/src/assets/javascripts/helpers/youtube/youtube.js#L268

**Comment by Loki-L1130** [comment]
So, You mean it is possible on Piped like you did for Invidious or does @FireMasterK do need to change anything on the Frontend side ?

**Comment by ManeraKai** [comment]
Youtube shorts are just like regular videos.

> do need to change anything on the Frontend side ?

No need, hopefully

**Comment by Loki-L1130** [comment]
So, You made the shorts video to be like a normal Video - Right ?

**Comment by ManeraKai** [comment]
yep

**Comment by Loki-L1130** [comment]
Great, Then, I think everything is solved and Piped is Ready for Deployment.

**Comment by ManeraKai** [comment]
Just test it first if you can.

**Comment by Loki-L1130** [comment]
Sure, But How ?

**Comment by Loki-L1130** [comment]
> Does the settings you have for Invidious do apply to Piped too ?

Maybe this is pending.

**Comment by ManeraKai** [comment]
If you find a YouTube short link, try to remove the `/shorts` thingy. This needs a phone btw.

**Comment by Loki-L1130** [comment]
Sure, I do have a Shorts Video Link. Check it out here : https://www.youtube.com/shorts/ilC3t2VvOw0

**Comment by ManeraKai** [comment]
And it's working: https://piped.kavin.rocks/watch?v=ilC3t2VvOw0

**Comment by Loki-L1130** [comment]
Yeah, It is but what if instead of `/shorts` it shows `/watch?v=` in URL

**Comment by ManeraKai** [comment]
Piped iteself redirected that. I can added though myself to LibRedirect, no big deal

**Comment by Loki-L1130** [comment]
But I mean the UI. Go to this Issue, https://github.com/TeamPiped/Piped-Redirects/issues/10 

and see this video : 
![image](https://user-images.githubusercontent.com/87981739/152644933-ec85d0da-d49d-4c72-beae-a62a03025328.png)

**Comment by ManeraKai** [comment]
I'll see what I can do.. weird stuff tbh

**Comment by ManeraKai** [comment]
> and see this video :

@Loki-L1130 can you give the link of the site?

**Comment by Loki-L1130** [comment]
It is [Inoreader](https://inoreader.com), My RSS reader where I have my YouTube Subscriptions.

**Comment by Loki-L1130** [comment]
Kai, You used a confused Emoji. What's up with the thing. Is there ways I can help.

**Comment by ManeraKai** [comment]
I need a site that has an iframe of a youtube shorts video

**Comment by Loki-L1130** [comment]
I think there is none available like that. Your best bet would be using Inoreader(Closed Source) with an Alias or Feedbin (Premium, OpenSource with trial no credit card needed) which also suffers from this.

**Comment by Loki-L1130** [comment]
ManeraKai, I tried the new Version of Libredirect. But the Shorts video is not in the 16:9 ratio like in the Movies.

**Comment by ManeraKai** [comment]
> @ManeraKai, I tried the new Version of Libredirect. But the Shorts video is not in the 16:9 ratio like in the Movies.

I think that should be a bug in the iframe. I can't do anything about it.
I've helped and even made short YouTube links as normal ones, that didn't help apparently.

**Comment by Loki-L1130** [comment]
Okay, I think that is in the hands of @FireMasterK . We shall see about it later.

**Comment by Loki-L1130** [comment]
Thanks for adding Piped.
