### ISSUE TITLE
Invidious Preferences Not Working 

### ISSUE THREAD

**Issue by SD745** [libredirect/libredirect#141]
Tested a number of settings on different instances but no cookie is created nor any URL parameters for them

**Comment by ManeraKai** [comment]
* Are the instances in the list? If they're custom, then type them in the custom list.
* Have you enabled custom instances?
* Does the option of disabling invidious working in the first place?

**Comment by SD745** [comment]
Yes I have used the default list, checked custom instances but it's empty. It does indeed redirect from YT to Invidious minus the preferences set.

**Comment by ManeraKai** [comment]
Are you using invidious or libredirect settings?

**Comment by MintMain21** [comment]
After you toggle the settings in LibRedirect, have you tried refreshing the page? I've found that if I edit preferences in real time, I have to reload currently open tabs in order for the updated preferences to be applied.

**Comment by SD745** [comment]
I am using the LibRedirect settings for Invidious, tested changing parameters for open tabs also doesn't seem to work, the frontends settings themselves do work with the extension not interfering

**Comment by MintMain21** [comment]
Maybe you could try clearing your cookies, and then let the extension recreate them?

**Comment by MintMain21** [comment]
Maybe you could try clearing your cookies, and then let the extension recreate them?

**Comment by ManeraKai** [comment]
@SD745 still not working after updates?

**Comment by SD745** [comment]
> @SD745 still not working after updates?

Yes still not working for me

**Comment by ManeraKai** [comment]
I think there's an extension that is deleting cookies on your side. It's just really weird.

**Comment by SD745** [comment]
Okay I just did another round of testing and realised it might be due to using containers, I tested in private windows too but didn't realise that was also bugged, but after recreating steps outlined in #153 it does indeed generate a cookie.

**Comment by ManeraKai** [comment]
I see. I'll close this issue then and complete discussion in #153.
