### ISSUE TITLE
Enhancement: Preference for Homepage on Invidious?

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#142]
When using Piped with custom preferences, I can choose between two Homepage options: Trending and Feed.

Invidious has Homepage preferences similar to the Comment preferences. I can choose between Popular, Trending, or Search. I typically prefer to set the homepage to Search, as I prefer the cleaner "distraction free" homepage. 

The ability to set this preference as the default for any instance I redirect to (similar to preferences for Comments, Recommended Videos, Video Quality etc) would be welcome.

**Comment by EdwardLangdon** [comment]
There is no Search Homepage in Piped. If you want a clean One. Use Feed, If you do not use an account.

**Comment by MintMain21** [comment]
Feed is what I use in Piped.

I'm not asking about Piped, I'm asking about Invidious.

If you can't be bothered to learn how to read, at the very least learn the difference between the letters I and P, you arrogant spoiled brat.

(I'm sorry, that was very rude of me. Expect a full apology on MySpace next Febuary the 31st)

**Comment by EdwardLangdon** [comment]
Okay, I still don't get it. @ManeraKai will help you.

**Comment by MintMain21** [comment]
Ugh.

I want LibRedirect to enforce my preffered INVIDIOUS Homepage on every  INVIDIOUS Instance the same way it already enforces on INVIDIOUS my prefferences for comments, video quality, etc.

It can already enforce preffered PIPED homepages, albiet PIPED offers onlu Trending and Feed. INVIDIOUS offers Trending, Popular, and Search. Between those three, I like Search best.

Is that clear?

**Comment by ManeraKai** [comment]
Yeah just adding support for more preferences.
This is the checklist support till now:
![image](https://user-images.githubusercontent.com/40805353/160272046-5f81e4de-2e32-48e5-9e6a-b5ebef14c1f5.png)

**Comment by MintMain21** [comment]
Thank you.

And I legitmately apologize for being rude earlier. I had crueler corners of the internet on the brain, but Github is significantly more polite from my experience, and I should not behave that way here or anywhere if I want a better internet.

**Comment by EdwardLangdon** [comment]
> And I legitmately apologize for being rude earlier.

That's Fine. I get it now. Thanks for explaining.
