### ISSUE TITLE
[Feature Request] Add HTTP login support back

### ISSUE THREAD

**Issue by TheFrenchGhosty** [libredirect/libredirect#143]
**Related to https://github.com/SimonBrazell/privacy-redirect/issues/49**

My Invidious instance (https://invidious.pussthecat.org/) is semi-private and behind an HTTP login.

Privacy Redirect properly supports URL behind HTTP login with the format `https://username:password@invidious.pussthecat.org` however, for whatever reason this was removed in Libredirect. When adding this URL as a custom instance, the addons automatically rewrite the instances link removing the login.

Please add support back for it, this breaks embeds.

https://user-images.githubusercontent.com/47571719/160289529-fc8bf9a2-e3b4-4b42-bfec-26c6fd36930c.mp4

**Comment by ManeraKai** [comment]
I think it's now working. Try it.

**Comment by TheFrenchGhosty** [comment]
@ManeraKai Works perfectly, thanks!

PS: You might want to word-wrap the entered instance, because if the password is long, it's a problem (the X to remove the instance isn't visible).
![s](https://user-images.githubusercontent.com/47571719/160728473-4878efee-0a10-4bea-99f0-795ad4ee7251.png)

**Comment by ManeraKai** [comment]
>  You might want to word-wrap the entered instance

Did that. I'll close the issue.
