### ISSUE TITLE
It shouldn't redirect to instances that are down

### ISSUE THREAD

**Issue by HarleyQuinn-Z6** [libredirect/libredirect#146]
When it redirects to an instance that is down I don't know what to do. Should I remove the instance from the options? And then if it gets back up how do I know? Do I need to be checking instances all the time to make sure they are up before using the extension?

**Comment by IronMaltese** [comment]
This could be a good question to add to the wiki

**Comment by IronMaltese** [comment]
Also you should enable redirect away from offline instances in libredirect settings

**Comment by Dyras** [comment]
@IronMaltese That feature doesn't seem to work 100% though. I'm using Firefox and when I'm re-directed to a Reddit instance that is down, like https://reddit.phii.me/ it just fails to load.

**Comment by IronMaltese** [comment]
I believe this is a copy of #99

**Comment by ManeraKai** [comment]
I released a new version on Firefox, This issue is a duplicate. Though if the problem still persists, just write here. I'll close the issue.
