### ISSUE TITLE
Enhancement: Prefrences for Themes on Invidious/Piped/Nitter

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#147]
The only option for themes is to control the theme of the extension itself, and to apply that theme to all the sites. The problem with this is that this usually sets the theme preference for individuals sites (as a Cookie) to either Light and Dark, and fails to swap one cookie for the other at the appropriate interval. 

What I would like instead, is individual theme options for each frontend that offers it, and for these options to be summarized as (at least) Light, Dark, and Auto. This way, the user should only have to set their cookie preference for each service to one of the three, and if set to Auto then detection of the desired theme will no longer be dependent on the extension, but rather the frontend itself.

**Comment by ManeraKai** [comment]
Invidious and Piped don't use the toggle that is `Apply Theme to sites`. Instead just enable the custom settings for e.g Invidious and it will apply the dark theme just for Invidious.

**Comment by MintMain21** [comment]
What I want is a setting to force Dark, Light, or Auto to all Instances, as some are either Dark or Light by default, and I prefer Auto.

**Comment by ManeraKai** [comment]
Just select dark mode in the Generals. Then enable custom settings for invidious

**Comment by MintMain21** [comment]
I shouldn't have to do that. That's the intention behind this feature request.

I do not want to manually set "Auto" theme for every instance that does not use it by default.

**Comment by MintMain21** [comment]
I'm asking, in addition for the option to set the default theme in the extension, to select preffered themes in each frontend.

They all have different options, but they typically default to either Light, Dark, or Auto.

I want to set the theme of each instance to "Auto" by default.

**Comment by ManeraKai** [comment]
I see.

So you want for every service/frontend to have it's own theme settings rather than a general one in the `Generals` page. It may have more options for something like Nitter that has more than just one theme option.

**Comment by MintMain21** [comment]
That's why at minimum all I want is "Light, Dark, Auto". Those three should be options on every frontend.

**Comment by MintMain21** [comment]
For what it's worth, my big problem with the "General" option as-is is that it sometimes fails to detect when the theme changes.

I found that by toggling the general setting from Light back to System, everything was working how I wanted again. So, maybe this enhancement isn't really neccesary? Idk.

**Comment by ManeraKai** [comment]
> For what it's worth, my big problem with the "General" option as-is is that it sometimes fails to detect when the theme changes.

That's weird

> So, maybe this enhancement isn't really neccesary? Idk.

Nitter has many theme options. SearX has weird theme options too. They can't share one setting

**Comment by ManeraKai** [comment]
I see that SearX has many other settings that should be added. I'll do them in a separate issue. For now I've finished Nitter, Invidious, and Piped. Piped-Material has it's setting just a switch so it's not important to be separated.
