### ISSUE TITLE
Add Privacy Policy

### ISSUE THREAD

**Issue by EdwardLangdon** [libredirect/libredirect#148]
This issue is to make a Privacy Policy for Libredirect, And also a reminder(Sort of) for @ManeraKai and me to write it.

**Comment by ManeraKai** [comment]
I've modified the existing one: https://github.com/libredirect/libredirect/blob/master/Privacy-Policy.md

**Comment by EdwardLangdon** [comment]
Okay, Seems Great !. I will make PR for the Website and then close this issue.
