### ISSUE TITLE
Add Nitter Instance

### ISSUE THREAD

**Issue by Loki-L1130** [libredirect/libredirect#15]
Add https://nitter.silkky.cloud Instance in Nitter.

**Comment by rimthekid** [comment]
The instances list is [here](https://github.com/libredirect/instances)

**Comment by Loki-L1130** [comment]
I just hit Update Instances and checked the List of Instances and it is not there int he Extension.

**Comment by ManeraKai** [comment]
Maybe a refresh problem? Does restarting the browser help?

**Comment by ManeraKai** [comment]
Also, maybe this is causing the issue: https://github.com/libredirect/instances/commit/cae75bfc3b70456348da67f49716f24e16ad31d5

**Comment by Loki-L1130** [comment]
> Maybe a refresh problem? Does restarting the browser help?

No, It doesn't

**Comment by ManeraKai** [comment]
So it's a new naming scheme issue. We'll try to push an update this day @alefvanoon?

**Comment by alefvanoon** [comment]
> So it's a new naming scheme issue. We'll try to push an update this day @alefvanoon?

Yes, I will do it.

**Comment by alefvanoon** [comment]
Done.
Update your LibRedirect.
