### ISSUE TITLE
going to start.duckduckgo.com will open a download pop-up of post3.html

### ISSUE THREAD

**Issue by lucamp** [libredirect/libredirect#150]
**description**
- clear browser cache and cookies (just to be sure)
- go to [start.duckduckgo.com](https://start.duckduckgo.com)
- a download pop-up of post3.html will appear

disabling the libredirect extension or going back to 1.5.6 resolve this issue

**system**
libredirect 1.5.9
Firefox 91.7.0esr

![Screenshot from 2022-03-29 20-36-14](https://user-images.githubusercontent.com/15078341/160683977-04fbdd7e-e4c6-49c7-b608-7b174fcd95d0.png)

**Comment by Bob131** [comment]
https://github.com/libredirect/libredirect/blob/17e2e094c9020f8eebfb7b6de5012c57273044a4/src/assets/javascripts/helpers/twitter.js#L196

Looks like `&&` should be `||`?

**Comment by Bob131** [comment]
Could also be because 2bc2316b502f3b09f2f187fee11ec66a7b806e0a hasn't been tagged in a release yet.

**Comment by MintMain21** [comment]
I've had similar bugs with not just DDG, but also Wikiless, wherein it starts downloading and/or displaying random images typically associated with the redirect and/or search query. 

It doesn't seem to be a security vulnerability (yet), but it should be addressed nevertheless.

**Comment by ahatdude** [comment]
Just happened to me too while going to google.com (I turned off the "search" redirect).
Except for me it was trying to download a file called "app" (no extension)

Hopefully it gets fixed soon, thanks for the great product :-)

**Comment by ManeraKai** [comment]
@Bob131 You're right.

**Comment by ManeraKai** [comment]
Does the new release 1.6.0 fix the problem?

**Comment by lucamp** [comment]
> Does the new release 1.6.0 fix the problem?

on [start.duckduckgo.com](https://start.duckduckgo.com) no issue

**Comment by ManeraKai** [comment]
The others?

**Comment by lucamp** [comment]
> The others?

google and wikiless are fine

**Comment by Bob131** [comment]
Yep, looks good to me too

**Comment by ManeraKai** [comment]
btw Thanks @Bob131 for the fix! I'll close this issue.
