### ISSUE TITLE
Bug: Delayed/Failed Redirects from Discord Android into Firefox Android.

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#152]
I use this extension on Fennec F-Droid (a stable fork of Firefox with the Firefox Nightly "Custom Add-On Collection" feature), and when redirecting links from Discord (mostly Twitter and Instagram) it loads the OG site first, and only redirects when I manually reload.  I've used Privacy Redirect under the same conditions, and redirects worked consistently with Twitter at least.

**Comment by ManeraKai** [comment]
Does Privacy Redirect still work like that till now. Have you tested that these days?

**Comment by ManeraKai** [comment]
I'll close the issue as there's a mobile app for this: github.com/libredirect/libredirect/issues/75#issuecomment-1095675654
Please use the mobile app rather than LibRedirect on your phone.
