### ISSUE TITLE
Bug: Invidious Prefrences are not enforced in Private Mode (unless the Toolbar Pop-up is activated)

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#153]
To recreate (on Windows 10 Firefox)

1. Set custom Invidious Settings to be applied by Cookie.
2. Open a Private Window and initiate a YouTube Redirect
3. Invidious will load with the instance's default settings, not the preferred settings.
4. Reload the page, Invidious should remain the same
5. Toggle the Toolbar Pop-Up (or otherwise interact with the extension's UI), then reload.
6. Only after "waking up" the extension will the preferred cookies be loaded and applied to the current instance. 

Presumably, this should also be recreatable on Firefox Linux, if not Chromium Browsers. Untested on Android.

Update: Preferences are also not enforced in Firefox Containers.

**Comment by ManeraKai** [comment]
> Update: Preferences are also not enforced in Firefox Containers.

Does the extension stops working completely with containers or it can get activated by opening the Pop-Up like the Private Window's case?

**Comment by MintMain21** [comment]
Redirects work in Containers. It's the saved Preferences by the extension that don't.

**Comment by ManeraKai** [comment]
Do they start working when you launch the Pop-Up though?

**Comment by MintMain21** [comment]
Nope.

**Comment by ManeraKai** [comment]
1. It's doing so for the Private Window because it's a completely new session. It's the same problem as when launching the browser the first time through opening a link.
2. It's also doing so for containers as they separate cookies.

I can't solve the first one as the extension hasn't started in the first place.
I don't want to play much with the second one tbh.

**Comment by SD745** [comment]
If it helps I can confirm that the cookies were working with containers when the extension was in version 1.4.1, I believe after the code was changed around the 1.46 release it hasn't been working since

**Comment by ManeraKai** [comment]
So you're saying that if you revert back to one of the old releases, it will work correctly with containers. Please try that.

**Comment by ManeraKai** [comment]
Containers aren't in Firefox anymore. There like a separate extension. I won't inject a js script just for that.

Now Private mode is working correctly and you don't need to launch the popup for it to work. Though it need a little weird trick to get it working.
