### ISSUE TITLE
This extension downloads "jail" file on any Reddit page even if Reddit is disabled.

### ISSUE THREAD

**Issue by axzxc1236** [libredirect/libredirect#154]
It didn't happen yesterday, I 100% suspect it has something to do with 1.5.9.

I am using Firefox 98.0.2, system language is Chinese Traditional.

The content of jail file is part of Reddit's web page source code.

![Peek 2022-03-30 08-43](https://user-images.githubusercontent.com/3145859/160729291-25121cee-a533-464a-a571-a3f9393ce14b.gif)
[jail.zip](https://github.com/libredirect/libredirect/files/8375899/jail.zip)

**Comment by kub1c** [comment]
I'm also seeing similar behaviour on the 1.5.9 version of this extension, although I am on Firefox Nightly 100.0a1. 

The problem seems to be related to files of type `subdocument`: for me, the extension tries to download `minimize` (which is also a `subdocument`) on Reddit and `post3` on DuckDuckGo. Haven't tested out too many other sites, but sites without subdocuments aren't asking to download things (e.g. YouTube).

**Comment by silverwings15** [comment]
related to this and #150, i'm getting the following popup when opening any link in reddit

![image](https://user-images.githubusercontent.com/10742312/160770330-988d9302-4eeb-4b13-a3fd-a2b3869cd0dd.png)

**Comment by Krisseck** [comment]
I am getting this on multiple websites too, for example on google.com results page it downloads file called `app`, with the content of the search results page.

All this happens even though I have search redirect disabled.

**Comment by Celuni** [comment]
Same for me, a good example is https://translate.google.de
Once you start typing you get a bunch of downloads.

FF 98.0.2

**Comment by idotj** [comment]
Idem here, same version 1.5.9 and Firefox 98.0.2
For the moment the only fix is to disable the extension :(

**Comment by arjpar** [comment]
I have the same issue where loading certain sites will download files. Using FF 98.0.2.

**Comment by StevenSee** [comment]
FF 98.0.2
This is happening when I try to expand a youtube link on Reddit with Reddit Enhancement Suite addon installed.

**Comment by arjpar** [comment]
1.6 seemed to fix the issue on my end too.

**Comment by ManeraKai** [comment]
@metronidazole I think it was just a problem from our side.
