### ISSUE TITLE
Bug: Extension not redirecting if browser is started via link

### ISSUE THREAD

**Issue by ValiumBear** [libredirect/libredirect#158]
Tested on latest Firefox and the extension will not redirect if browser is started via opening a link.
In case of YouTube I see it tries to connect to instances after YouTube website is loaded but that's about it. Twitter and Reddit just don't do anything.

If I wait about 5 seconds after Firefox launch everything works fine. Is this fixable?
Perhaps it's related to #152?

**Comment by ManeraKai** [comment]
I really don't know what to do with this. Does anyone have any idea?

**Comment by EdwardLangdon** [comment]
How about implementing Suspending all network activity until Libredirect is loaded ?
Like uBlock Origin does for loading all filterlists.

**Comment by ManeraKai** [comment]
Funny thing is even SimonBrazell has commented on a Firefox bug related to this: https://bugzilla.mozilla.org/show_bug.cgi?id=1378459 (you'll see him in the last comments).

I didn't see any commit he made to fix. Does this happen too with PrivacyRedirect?

**Comment by ManeraKai** [comment]
@EdwardLangdon  I think uBlock Origin is able to that as it handles only sub requests that aren't the main url in the adress bar. Read this and it's still not fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1653237

In LibRedirect I can see that the main url in the address bar sends the request without me knowing, but it can't request more as LR has started redirecting sub urls.

**Comment by ManeraKai** [comment]
Will reopen this issue if there's any progress from Firefox's side.
