### ISSUE TITLE
Entire page gets redirected if extension detects embedded instance as offline when "Auto Redirect of offline instances" is on

### ISSUE THREAD

**Issue by Elaborendum** [libredirect/libredirect#159]
When going to a site with, in this case, a YouTube embed that the extension will redirect to Invidious, the page will load until the video gets redirected, and the instance is detected as offline, which causes the entire page to redirect to either a CSS file or an image. This pretty much makes the page inaccessible as long as the redirect is active.

You can see it happen here, https://youtubeembedcode.com/en/.

**Comment by ManeraKai** [comment]
Does this still happen?

**Comment by Elaborendum** [comment]
No, seems like it's working correctly now. So I'll close it.
