### ISSUE TITLE
Libredirect using Piped-Material doesn't respect the autoplay setting on embeddable videos

### ISSUE THREAD

**Issue by Dyras** [libredirect/libredirect#160]
Hello! I'm using Libredirect, with Piped-Material for YouTube links, and for whatever reason the autoplay isn't respected; the videos autoplay regardless of my settings.

Example:
https://www.patreon.com/alexmasse
Give it 4-5 seconds and the video starts playing

My settings:
![image](https://user-images.githubusercontent.com/12563436/161271092-b0743035-cef8-4ea4-866e-a7bff6921b28.png)

**Comment by ManeraKai** [comment]
This is not a problem on our side. It even happens with Piped. I had earlier experience with Autoplay with Piped and It's not working as expected. Please open an issue on their side. I'll close this one.
