### ISSUE TITLE
theguardian.com videos are broken

### ISSUE THREAD

**Issue by lucamp** [libredirect/libredirect#161]
theguardian.com videos are broken

### steps
- go to an article with a video at theguardian.com like [this](https://www.theguardian.com/global/video/2022/mar/30/life-as-a-refugee-in-calais-the-ukraine-war-is-a-wake-up-call-video)
- wait till the page is fully loaded

Two different behaviours based on libredirect youtube setting:

**piped instances**
audio starts to play with no video
play button does not work

**invidious**
play button does not work

**Comment by ManeraKai** [comment]
Because of it's use of the YouTube API. Double tap the video and it will play fullscreen without issues. A replication of YouTube's API from invidious or Piped side is needed for this to work. That is not easy though.

**Comment by ManeraKai** [comment]
YouTube, Twitter, Wikipedia and more all have translations in Arabic; ex:
YouTube => يوتيوب
Twitter => تويتر
Wikipedia => ويكيبيديا
They should be included too.

**Comment by lucamp** [comment]
> Because of it's use of the YouTube API. Double tap the video and it will play fullscreen without issues. A replication of YouTube's API from invidious or Piped side is needed for this to work. That is not easy though.

under general -> exceptions I put

`https://www.theguardian.com`

but the video is not playing on youtube, but with the alternative I chose.

Am I missing something about how exceptions works?

**Comment by ManeraKai** [comment]
No there's a problem with exceptions too #164

**Comment by EdwardLangdon** [comment]
I can replicate this issue and it is same for me as @lucamp

**Comment by EdwardLangdon** [comment]
Update : I checked my Web Console. Request are being made to piped not eve after allowing Guardian in Exceptions.

There is a possibility that TheGUardian has CSRF policy for their site which makes us unable to play the video even though the request is replaced by Piped.

**Comment by ManeraKai** [comment]
@EdwardLangdon You can play it without problems using invidious.

**Comment by ManeraKai** [comment]
The only way is to bypass them. I can't replicate the YouTube API with LibRedirect. It's not it's purpose. I've corrected how exceptions work and you can make it as an exception or double tap the video if you can handle that.
