### ISSUE TITLE
Exceptions aren't respected

### ISSUE THREAD

**Issue by realpixelcode** [libredirect/libredirect#164]
LibRedirect does not seem to respect exceptions that have been set on the general settings page. For example, the Maps redirection breaks https://flightradar24.com for me so I added the domain both with and without `www.` to the exceptions but that doesn't have any effect.

**Comment by ManeraKai** [comment]
Well technically it's not broken, rather you're using it wrong. This exception is just for the main url, e.g `https://www.youtube.com/watch?v=A1kzr5ldsbU`. You're using it to also bypass all the sub requests in that page. We have this type of exceptions but in the YouTube settings for embeds. Where when you add there an exception. It will not redirect anything from that site including the main url and the sub requests. However I think they should be merged to the generals tab. That way exceptions can be made for everything else not just YouTube redirections.

**Comment by ManeraKai** [comment]
They should now be working as you expect them too.

**Comment by ManeraKai** [comment]
They should now be working as expected.

**Comment by realpixelcode** [comment]
Oh, okay 😅 Maybe the settings page should tell the user what the exceptions are to, in order to prevent confusion.

**Comment by ManeraKai** [comment]
Now it will prevent everything from the `main_frame` urls till the `sub_frame` urls. I should though add some explanation to many settings as they're just vague in meaning and can't even translate well to other languages.
