### ISSUE TITLE
Enhancement: optionally filter links on copy

### ISSUE THREAD

**Issue by 0n-s** [libredirect/libredirect#165]
Currently LibRedirect only redirects to alternative frontends when you open them in your browser. I'd like to propose that it do the same when you use the "Copy Link" button (Firefox's button label, may be different on other browsers). This would be nice because when you'd like to share a video with your friends, you could link it via a Piped instance, & they would benefit from it even if they don't have LibRedirect or any similar extensions. Obviously one can also just edit the link manually, but that doesn't work too well with a click-to-open model that most things use, from terminals with IRC clients all the way to the newest chat platforms out there.

I also propose that this feature be made optional. ~~For a web browser I don't see any good reason to prefer the official frontend over an alternative one, especially for simple stuff like just sharing it with other people.~~ [1] However, if you'd like to feed a link (or, more especially, lots of links, any single link is easy to edit) to a program that scrapes data from said website, they probably wouldn't know how to get around it. Programs like [yt-dlp](https://github.com/yt-dlp/yt-dlp) work around this by [hardcoding a list of instances](https://github.com/yt-dlp/yt-dlp/blob/ad210f4fd460574436dc65d3c3cee041c905c46f/yt_dlp/extractor/youtube.py#L291), but this is not exactly perfect for obvious reasons, e.g. what if your favorite instance isn't on the list? Having to wait for the next release of the program for that would be a bummer.

But I don't exactly think that encouraging every scraping program out there to parse around every frontend is very practical anyway, & many of them wouldn't even benefit much from alternative frontends as they don't implement anywhere close to the full functionality of a browser that many sites require to track you with greater granularity, they wouldn't benefit from the site being lighter by much (if at all), & so on & so forth.

I also imagine another way it could be made optional is if it used its own context menu button, maybe a button with the LibRedirect icon saying "Copy Raw Link" or whatnot. Thinking about it, that's probably the better way to do it. But I'd like to hear what you think.

[1]: after more thought, I realize there can be good reasons to use the official frontends in some cases. Say, if you follow people on Twitter. AFAIK Nitter has no support for that ATM. But in this case you would just probably turn off said redirect quickly. Either way, this statement is extraneous & taking it out doesn't change the rest of what I've said, so just ignore it. Well, except the part about sharing it with other people, I suppose that still applies since it's kind of the crux of this feature request.

**Comment by EdwardLangdon** [comment]
This is similar to https://github.com/SimonBrazell/privacy-redirect/issues/43 to this issue in Privacy Redirect.

We are tracking it here : https://github.com/libredirect/libredirect/issues/17#issuecomment-1086596261

Great that you made a separate issue. So, we can keep track of this.

**Comment by EdwardLangdon** [comment]
But this would make Libredirect to use the ClipBoard API. Which users might feel uneasy because they might think that we would copy of Clipboard Data and sell it. Some Conspiracy might happend. But as you said it is a better thing to make it as an optional.

Kai, We also need to write this in the wiki. If we are gonna do that.

**Comment by ManeraKai** [comment]
Also this: #74

**Comment by 0n-s** [comment]
>But this would make Libredirect to use the ClipBoard API. Which users might feel uneasy because they might think that we would copy Clipboard Data and sell it. Some Conspiracy might happen.

That might unfortunately be true. Best bet is probably just to publish an educated fact-check like [the one uBlock Origin published](https://github.com/gorhill/uBlock/wiki/Can-you-trust-uBlock-Origin%3F) when it received similar concerns. Considering the current popularity of said extension even among privacy-conscious users, however, this may be a glimmer of hope.

**Comment by ManeraKai** [comment]
Problem is that this requires a reverse function for every frontend. It may be easy for some like YouTube as I really don't change much, but it may get complicated as with bibliogram. I may start adding it, but not for every frontend.

**Comment by ManeraKai** [comment]
I may add it just as a button in the popup as I really don't want to touch clipboard stuff and it will be disabled by default if I done that. Having just a button is much more simple.

**Comment by ManeraKai** [comment]
We got into our first problem or second as I had one with twitter.
I can't redirect: https://proxitok.herokuapp.com/video/7061265241887345946
to: https://www.tiktok.com/@keysikaspol/video/7061265241887345946

I should know the username first that is `@keysikaspol`.

The solution would be to keep the username in the url from proxiTok's side, this and other frontends problem were the main reasons why I didn't want to make a "reverse function" for redirections

**Comment by ManeraKai** [comment]
ProxiTok has been solved as the url structure has changed and is now including the username. I've added the most popular needed once.
