### ISSUE TITLE
Requests on other sites not redirecting as expected

### ISSUE THREAD

**Issue by xnaas** [libredirect/libredirect#166]
e.g. When there's an imgur link on Reddit and I click the expando (from [RES](https://redditenhancementsuite.com/)), it looks like the request still goes out to imgur and not a rimgo instance.

Is the request supposed to be redirected? Am I missing something? Working as intended?

**Comment by xnaas** [comment]
Exmaple:

https://user-images.githubusercontent.com/8271327/161387382-d1ff4f3b-eed6-4d67-a76f-07151537672f.mp4

*Clicking* on the imgur link, of course, goes to a rimgo link.

**Comment by ManeraKai** [comment]
Does this also happen when you click on the post. Is the issue related to using RES or even without it?

**Comment by xnaas** [comment]
Without RES, Reddit serves `https://external-preview.redd.it/<rest_of_link>` when expanding an imgur link.

**Comment by ManeraKai** [comment]
I think it should be working right now. It was just a small url type bug.

**Comment by ManeraKai** [comment]
@xnaas It's working now right?

**Comment by xnaas** [comment]
I'll let you know after I have a bit to test. Apologies for the delay.

**Comment by ManeraKai** [comment]
So...?

**Comment by xnaas** [comment]
Apologies again for the delay. Seems to be working great now. :)

**Comment by ManeraKai** [comment]
Can you show me?

**Comment by ManeraKai** [comment]
Look, it will ofc request the data from i.imgur.com, but is it actually receiving it back from i.imgur.com? or that LR redirected the request and fooled it to thinking so. This is why we're having some problems with CSP on some sites bc those sites are not getting fooled by it and detect if there's a redirection. So check the response on those requests and also check LR console log.

**Comment by ManeraKai** [comment]
In the latest version it's working properly thankfully using RES too

**Comment by ManeraKai** [comment]
I'll close the issue, but when the release happens and you still experience the same problem, I'll reopen the issue again.
