### ISSUE TITLE
Issues to import here

### ISSUE THREAD

**Issue by ghost** [libredirect/libredirect#17]
I think these are some fundamental issues that need to be imported from the Main repo and Make it available on Libredirect.

Here are the Issues :
344, 340, 320, 313 (Imgur to Imgin) [Private alternative to Imgur] must be looked in, 290, 271, 260, 251, 236, 210, 287, 101, 43, 35, 201, 194, 156, 139, 114

https://github.com/SimonBrazell/privacy-redirect/issues/___ (View the Issues by replacing ___ with the numbers for eay access) Sorry, I cannot link for that because I'm on the move.

These are the Issues I think that needs to be implemented in Libredirect. These are in No Particular Order.

**Comment by ManeraKai** [comment]
https://github.com/SimonBrazell/privacy-redirect/issues?q=344++340++320++313+290+271+260+251+236+210+287+101+43+35+201+194+156+139+114

**Comment by Loki-L1130** [comment]
@ManeraKai Any new issues to be closed here ?

**Comment by ManeraKai** [comment]
They're really unique and weird ideas. I try to look them every time. I didn't found one to close.

**Comment by Loki-L1130** [comment]
I understand. May @alefvanoon could help out. But he's dead.

**Comment by ManeraKai** [comment]
https://github.com/SimonBrazell/privacy-redirect/issues?q=313+236+210+43+35+201+194+139+114+

**Comment by ManeraKai** [comment]
https://github.com/SimonBrazell/privacy-redirect/issues?q=313+236+210+43+35+201+139+114

**Comment by ManeraKai** [comment]
https://github.com/SimonBrazell/privacy-redirect/issues?q=313+236+210+43+35+201+139

**Comment by Mennaruuk** [comment]
#ThirtyFive/AMP issue is interesting.

Apps like DeAMPify work ["by first being set as the default URL handler for AMP-specific URLs. Once you open a link with the application, DeAMPify scrapes the AMP’s HTML for the page’s original URL."](https://9to5google.com/2017/07/21/deampify-application-bypass-amp-links/) Not a great approach to scrape the HTML of all pages.

Chrome extension Redirect AMP to HTML [initially worked](https://www.ghacks.net/2019/08/29/disable-amp-in-firefox-and-chrome-with-the-redirect-amp-to-html-extension/) by setting an opt-out Cloudflare cookie that forced sites to serve the non-AMP links, but that was [deprecated](https://github.com/da2x/amp2html/commit/cccac411da1f8a5a16c40cf5fed7942ddddc0c7d) after Cloudflare [announced](https://blog.cloudflare.com/announcing-amp-real-url/) a new way where AMP can be served while showing the original URL. Not only is this outdated, but [Cloudflare raises a red flag](https://www.law.uchicago.edu/news/matthew-prince-00-discusses-cloudflare-cloud-computing-journal) for some privacy advocates.

There is an extension called [Aelisya](https://github.com/BirdInFire/Aelisya-Tweaker/) that has [a bunch of rules](https://github.com/BirdInFire/Aelisya-Tweaker/blob/6628ab475cef018a495ba0cd97ab73a9ab9d22a5/rules.json) blocking AMP Project links.

But it's [AmputatorBot ](https://github.com/KilledMufasa/AmputatorBot)that has the most potential. It claims to have a 97% success rate at blocking AMP links. The [rules ](https://github.com/KilledMufasa/AmputatorBot/blob/0725d6dca3d4b2dfd2d3a158dfb6ea0489fd1eee/static/static.txt)block links containing `/amp, amp/, .amp, amp., ?amp, amp?, =amp, amp=, &amp, amp&, %amp, amp%, _amp, amp_`.

**Comment by ManeraKai** [comment]
@Mennaruuk Isn't this really out of scope do you think?

**Comment by Mennaruuk** [comment]
When I looked into the post you linked, there were people who said that redirections away from AMP fall under privacy redirection. In my opinion, I definitely agree with you, it's superfluous. I'm wondering how a desktop user stumbles upon an AMP link, that's like a needle in the haystack, virtually all of AMP conversions are on mobile, and there are [extensions ](https://chrome.google.com/webstore/detail/amp-browser-extension/mccnchmofleakpdohkmljohfckgpdehb)[dedicated ](https://chrome.google.com/webstore/detail/%E2%9A%A1%EF%B8%8F-desktop-amp/igokgmnkplcfgnegidccbgmlnecaffhh)to serving the desktop user an AMP link. If anyone wants to de-AMPify links, they can install an extension like Redirect AMP to HTML or Aelisya for MS Edge. I keep thinking about the purpose of the project: a web extension that redirects popular sites to alternative privacy-friendly frontends and backends. To me, de-AMPifying doesn't fall under this.

**Comment by ManeraKai** [comment]
^

**Comment by ManeraKai** [comment]
https://github.com/SimonBrazell/privacy-redirect/issues?q=313+236+210+43+201+139

**Comment by EdwardLangdon** [comment]
https://github.com/SimonBrazell/privacy-redirect/issues?q=236+210+43+201+139

**Comment by ManeraKai** [comment]
https://github.com/SimonBrazell/privacy-redirect/issues?q=236+210+201+139

**Comment by EdwardLangdon** [comment]
@ManeraKai Any ETA on this Issue - https://github.com/SimonBrazell/privacy-redirect/issues/210 ?

Because, I am stuck in consent.youtube.com when copying and pasting link from an app and I hate doing so. Issue present only in Chromium not in Edge.

**Comment by EdwardLangdon** [comment]
Any updates on this ?

**Comment by ManeraKai** [comment]
No.

**Comment by EdwardLangdon** [comment]
I think this is fixed - https://github.com/SimonBrazell/privacy-redirect/issues/201 - Right ?

**Comment by EdwardLangdon** [comment]
I sort of understand it will test and report it here or matrix.

**Comment by ManeraKai** [comment]
https://github.com/SimonBrazell/privacy-redirect/issues?q=236+201

**Comment by EdwardLangdon** [comment]
https://github.com/SimonBrazell/privacy-redirect/issues?q=201

As 139 is not planned and inefficient to do.

**Comment by IkelAtomig** [comment]
Closing as the last pending one is tracked in a separate issue
