### ISSUE TITLE
Add a section to flag broken frontends in libredirect

### ISSUE THREAD

**Issue by rdncNT** [libredirect/libredirect#171]
for example, https://libreddit.40two.app doesn't work anymore. It would be useful if there was a way to flag it inside the extension to make your and our work easier

Amazing project by the way, thanks a lot!

**Comment by EdwardLangdon** [comment]
Well, Instances that are broken/offline is redirected to another Instances. You can see here how we add instances to Libredirect : https://github.com/libredirect/libredirect/wiki/FAQ#where-the-hell-are-those-instances-coming-from 

There is nothing we can do about this. Better ask in Libreddit repo to remove it from the list or contact the Instance owner.

I hope you get it.

**Comment by ManeraKai** [comment]
@rdncNT it's my fault that I didn't implement a way to automatically fetch libreddit instances yet. I'll do it though.

**Comment by ManeraKai** [comment]
Not LibReddit is automatic!! You can press the `Update Instances` in the settings page to get the latest up-to-date list.

**Comment by m77e4t** [comment]
Change the label for this issue.

**Comment by EdwardLangdon** [comment]
Sure !

**Comment by ManeraKai** [comment]
Added it. I'll improve the script more in the future so it will be more reliable.

**Comment by le-jun** [comment]
> Now LibReddit is automatic!! You can press the `Update Instances` in the settings page to get the latest up-to-date list.

Not sure to understand correctly, is it live yet? I’m running the 1.6.2 build and it’s a pain to be redirected to dead instances.

**Comment by ManeraKai** [comment]
Yeah today was a new release, upgrade to version 1.6.3

**Comment by Dyras** [comment]
@ManeraKai 40two.app is still in the addon, and if you're sent there you're never redirected to another instance.
![image](https://user-images.githubusercontent.com/12563436/171997601-68dceffd-7fe6-4ac1-b42a-83f13bbfa224.png)

**Comment by ManeraKai** [comment]
Update your instances list and it will go away:
![image](https://user-images.githubusercontent.com/40805353/171997684-e476b0f4-798c-4673-ba48-6a8078f75749.png)

**Comment by Dyras** [comment]
Ah, is this ever done automatically? If so, how often?

**Comment by ManeraKai** [comment]
Till now it's not. Why? We're discussing this in this thread: https://github.com/libredirect/libredirect/issues/293#issuecomment-1143611688
