### ISSUE TITLE
redirect from duckduckgo bang for wikipedia is broken

### ISSUE THREAD

**Issue by lucamp** [libredirect/libredirect#173]
# steps
- on libredirect's settings choose only a single working wikipedia instance, eg wikiless.org
- go to [https://start.duckduckgo.com](https://start.duckduckgo.com)
- search something using !w or !wikipedia bang (eg !w europe)

# current behaviour
search results in a broken link

**Comment by ManeraKai** [comment]
Just a small Regex bug. Fixed it.
