### ISSUE TITLE
Rimgo supports embedded Imgur images

### ISSUE THREAD

**Issue by Cade66** [libredirect/libredirect#175]
Hi,

LibRedirect's 1.6.2 doesn't handle embedded Imgur images via its Rimgo component.
Rimgo itself handles embedded Imgur components (tested separately with the Redirector extension).

Example : https://greasyfork.org/en/scripts/29420-google-dwimages

**Comment by ManeraKai** [comment]
This is related to issue #166 Where the url type isn't a `sub_frame` rather it's an `image` type. The url whitelist is now like [this]( https://github.com/libredirect/libredirect/blob/31c642fc90490471ea6903b148b201f0557d8da0/src/assets/javascripts/helpers/imgur.js#L110-L117=).

**Comment by Cade66** [comment]
#166 states the issue is fixed, but it isn't on Greasyfork. I'm surprised you close this post. I have to disable Rimgo in LibRedirect and get it handled with Redirector : cumbersome.

**Comment by ManeraKai** [comment]
I didn't release the fix. Run it form the source code
