### ISSUE TITLE
Is it possible to have support for Firefox Mobile on Android?

### ISSUE THREAD

**Issue by kartikdc** [libredirect/libredirect#176]
Don't know about add-on ecosystem so thought I would ask here. Seems like the newer Firefox Mobile browser for Android supports add-ons. I use uBlock Origin in it which is the only thing that makes browsing the web a bearable experience on mobile.

Was wondering if support for Firefox Mobile has even been considered or explored. All the websites that I want to be redirected from (Twitter and Reddit) are especially horrendous on mobile and constantly hound you to install their shitty apps. So there is a need for an add-on like this (if not this specific add-on) for mobile.

Feel free to close the issue if this is outside the scope of what the developers plan on doing. Just trying to test the waters here.

**Comment by ManeraKai** [comment]
No it's really in the scope of this extension. We discussed this earlier and every release I release it for mobile too. Complete the discussion here #75

**Comment by kartikdc** [comment]
Thanks. I searched for mobile rather than android therefore found nothing. Sorry about that. Will close the issue.

**Comment by ManeraKai** [comment]
I also searched before, but seems that Firefox adds only **Recommended** extensions. I think you should install it manually.
