### ISSUE TITLE
Disable the redirection for specific websites

### ISSUE THREAD

**Issue by JVT038** [libredirect/libredirect#177]
So in #164 I read that the exceptions just make sure that certain URLs aren't redirected.
But is there a way to make sure that when I'm on `www.mydomain.com` that the redirections won't apply? This is useful for iframes, or other websites where the redirections sometimes break the website. 
Because I'm currently using a website where I constantly have to temporarily disable the redirection for the website to work (the site loads YouTube images / thumbnails, and they aren't shown when turning on the redirection)

**Comment by ManeraKai** [comment]
I already did that in the same issue: https://github.com/libredirect/libredirect/issues/164#issuecomment-1087659932
I think I just didn't release a new version.

**Comment by ManeraKai** [comment]
@JVT038 Are you alive?

**Comment by JVT038** [comment]
Yeah, I'm using the latest version (1.6.2) on Firefox and it still doesn't work.
The exception I set doesn't work for the websites

**Comment by ManeraKai** [comment]
I didn't release a new version that's why. Can you test it from the source code?

**Comment by ManeraKai** [comment]
@JVT038 still alive?

**Comment by ManeraKai** [comment]
@JVT038 I released a new version. Please check if the problem has been fixed or not.

**Comment by JVT038** [comment]
It works now, thank you
