### ISSUE TITLE
Port Extension

### ISSUE THREAD

**Issue by Loki-L1130** [libredirect/libredirect#18]
Please port the Extension to Both Safari and Chrome.

**Comment by ManeraKai** [comment]
@alefvanoon

**Comment by Loki-L1130** [comment]
@alefvanoon It would be great if you give .crx file for chromium in the Releases Page.

**Comment by alefvanoon** [comment]
> @alefvanoon It would be great if you give .crx and .xpi files separately in the Releases Page instead of the Source Code.

I will do this from the next version.

**Comment by ManeraKai** [comment]
Does page_action work with chrome?

**Comment by alefvanoon** [comment]
> Does page_action work with chrome?

Not today.

**Comment by ManeraKai** [comment]
?! will work tomorrow?

**Comment by alefvanoon** [comment]
> ?! will work tomorrow?

Depends on Google(chrome)'s decision.

**Comment by ManeraKai** [comment]
Is there any upcoming decision. Because I tried to compile it on a chromium browser and it didn't.

**Comment by ManeraKai** [comment]
If I removed page_action, then obviously page_action won't work

> "browser_specific_settings": { 

hmm..

**Comment by alefvanoon** [comment]
Yes :(
Chrome have issues with the manifest file

**Comment by ManeraKai** [comment]
It's as @SimonBrazell said: github.com/SimonBrazell/privacy-redirect/pull/319#issuecomment-985895209

**Comment by alefvanoon** [comment]
Maybe we should be Firefox only...

**Comment by ManeraKai** [comment]
xD, everyone uses chromium, it's a small feature that can be removed on chromium verions. Brave users will be mad at you

**Comment by alefvanoon** [comment]
> xD, everyone uses chromium, it's a small feature that can be removed on chromium verions. Brave users will be mad at you

I would be happy if extension works on chrome.

I get this error even after deleting page_action:
![image](https://user-images.githubusercontent.com/53198048/152205018-601fdc72-b161-418d-b35e-d1e342198067.png)

**Comment by ManeraKai** [comment]
btw what's this?
 "browser_specific_settings": {
    "gecko": {
      "id": "7esoorv3@alefvanoon.anonaddy.me",
      "strict_min_version": "67.0"
    }
  }

**Comment by ManeraKai** [comment]
Your error doesn't happen to me. Instead the second error you got is the first one on my chromium.

**Comment by alefvanoon** [comment]
> btw what's this?
> 
> ```json
>  "browser_specific_settings": {
>     "gecko": {
>       "id": "7esoorv3@alefvanoon.anonaddy.me",
>       "strict_min_version": "67.0"
>     }
>   }
> ```

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings

**Comment by ManeraKai** [comment]
Doesn't google chrome require it? weird.

**Comment by alefvanoon** [comment]
> Doesn't google chrome require it? weird.

Nope :)
Just firefox requires the browser_specific_settings

**Comment by alefvanoon** [comment]
This [post](https://blog.shahednasser.com/making-your-extension-compatible-with-both-chrome-and-firefox/) helped me.

**Comment by Loki-L1130** [comment]
Is there anyway I can use the New release in Chromium ?

**Comment by ManeraKai** [comment]
If chromium supports adding a browser_action button (the button on the toolbar) and a page_action button (the button in the address bar) at the same time, then yeah you can. Sadly, this isn't enabled as for clutter purposes I think. We may remove that button if we can get the extension to redirect to a new instance if the current one isn't online.

**Comment by Loki-L1130** [comment]
What is the Button on the addressbar actually. I noticed it in inside the address bar where the URL is.

**Comment by Loki-L1130** [comment]
[Fixed in new Release v1.3.5 ](https://github.com/libredirect/libredirect/releases/tag/v1.3.5). So, Closing this.
