### ISSUE TITLE
Redirect m.imgur.com

### ISSUE THREAD

**Issue by kartikynwa** [libredirect/libredirect#180]
Not sure about the edge cases but from what I have seen of imgur, m.imgur redirection should work same as plain imgur.

Don't know js but could be as simple as modifying:

https://github.com/libredirect/libredirect/blob/8ae5a4092cb237a390ea5995c23c8a308f6b3417/src/assets/javascripts/helpers/imgur.js#L5-L7

to:

```js
 const targets = [ 
     /^https?:\/{2}(i|m|).?imgur\.com(\/.*)?$/ 
 ]; 
```

If this is the case you'd like me to file a PR feel free to let me know.

**Comment by ManeraKai** [comment]
@EdwardLangdon It's not a bug rather than an enhancement.

**Comment by ManeraKai** [comment]
@kartikynwa it's for media/videos right?

**Comment by kartikynwa** [comment]
@ManeraKai Albums as well

**Comment by kartikynwa** [comment]
@ManeraKai Actually I am not sure. Give me some time. Will look into it and post back.

**Comment by kartikynwa** [comment]
@ManeraKai Some example links:

- https://m.imgur.com/gallery/hduyL
- https://m.imgur.com/gallery/ameSx2X
- https://m.imgur.com/a/Y6cimPF
- https://m.imgur.com/a/z3eDUQx
- https://m.imgur.com/xtn4JxC?r
- http://m.imgur.com/2x7Mfw5

Looks pretty similar to normal imgur links.

**Comment by EdwardLangdon** [comment]
> @EdwardLangdon It's not a bug rather than an enhancement.

I mentioned like that because according to regex it should redirect those links. That's why.

**Comment by ManeraKai** [comment]
You're right.

**Comment by kevinlekiller** [comment]
> ```js
>  const targets = [ 
>      /^https?:\/{2}(i|m|).?imgur\.com(\/.*)?$/ 
>  ]; 
> ```

Could change to:

`/^https?:\/{2}([im]\.)?imgur\.com(\/|$)/`

**Comment by ManeraKai** [comment]
Added yours @kevinlekiller. Does it work now @kartikynwa?

**Comment by kartikdc** [comment]
Works now. @ManeraKai

(Can close the issue.)

**Comment by kartikynwa** [comment]
@ManeraKai Works. Thanks.

**Comment by ManeraKai** [comment]
It was @kevinlekiller work.
