### ISSUE TITLE
Nitter embeds broken

### ISSUE THREAD

**Issue by catwithbanana** [libredirect/libredirect#183]
Sometime late this afternoon Nitter embeds stopped working on all of my devices, mobile and desktop. The embeds simply show as black squares with no information, though clicking through to the full Nitter page works fine. I tried resetting my settings, which often fixes issues, but that has no effect on this problem.

I'm not sure if the problem is on Nitter or LibRedirect's end. I'm happy to provide more information if necessary to diagnose the issue. Thank you!

Screenshot of the issue:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/75995110/162597313-3171d975-3349-4b39-99d7-de0078c5e423.png">

**Comment by catwithbanana** [comment]
Embeds unfortunately still do not work after the 1.6.3 update

**Comment by EdwardLangdon** [comment]
@catwithbanana Can you give the link to the site where you want the embed to be replaced by Libredirect ?

**Comment by catwithbanana** [comment]
> @catwithbanana Can you give the link to the site where you want the embed to be replaced by Libredirect ?

Sure thing. The tweets on this page, for instance, used to be replaced as expected and then suddenly stopped working on all devices:

https://famiboards.com/threads/nintendo-switch-sports-announced-launches-april-29th.1907/

**Comment by ManeraKai** [comment]
I think the website changed some of its code.

**Comment by EdwardLangdon** [comment]
I don't see the embeds replaced too. Just Loading....

**Comment by catwithbanana** [comment]
All of the embeds on this website worked until a few days ago, so it makes sense that something changed on their end. I have an account on the site and could reach out to admin there for more detail if necessary.

Could libredirect do anything to mitigate the change? Perhaps one of the changes referenced in #20 , which allegedly could fix this issue on several other types of sites.

I apologize for being so particular about this -- As far as I know LibRedirect is the ONLY way to get tweet embeds working while using ETP strict on Firefox, so it's essential functionality for me and many others. So many websites these days rely on embedded tweets, and I don't want to have to turn my tracking protection off every time I access them. 

Thank you for your hard work...as always let me know how I can help!

**Comment by ManeraKai** [comment]
Select the iframe and then delete this iframe. It should show the iframe working:
![delete_a_element](https://user-images.githubusercontent.com/40805353/165742473-dbe7e821-4fce-49fd-bd0d-63cf7daf370f.png)
I don't know what to delete and what to not delete. Websites differ so much.

**Comment by catwithbanana** [comment]
Unfortunately I don't know anything about programming or development. Is there any other developer or resource we could consult for help answering these issues? 

I'm willing to contribute money towards a developer and/or bounty that could devise a durable solution for fixing Nitter embeds across most websites. When the feature works LibRedirect is, as far as I know, the only way to view Twitter/Nitter embeds while keeping Firefox's Strict Enhanced Tracking Protection (and the resulting dynamic First Party Isolation) activated. It's a killer feature, since so many websites incorporate Twitter embeds these days.

Thank you as always for your amazing work on LibRedirect!

**Comment by Victor239** [comment]
I can confirm this issue is happening for me as well on a [different website](https://www.rooshvforum.com/threads/project-veritas-thread.29431/page-13), pretty sure it's a LibRedirect issue as this website had the Nitter embeds working before whilst the site very rarely gets it's software updated.

**Comment by ManeraKai** [comment]
Keep in mind that it's not just the site rather it's third party packages and even twitter's API.

**Comment by ManeraKai** [comment]
It's almost Nitter's problem till now than ours, we really can't do but just redirect, Nitter's job is to make itself a decoy that fools sites into thinking it's twitter. We LibRedirect can't do that.

**Comment by ManeraKai** [comment]
This issue was discussed before #20 and there is an opened issue in Nitter: https://github.com/zedeus/nitter/issues/586
