### ISSUE TITLE
Enhancement: Android System-wide

### ISSUE THREAD

**Issue by soulspark666** [libredirect/libredirect#184]
I was just thinking if there is a way to make this system-wide, for both root and non-root using things like 
[AdAway](https://github.com/AdAway/AdAway), [Blokada](https://github.com/blokadaorg/blokada)
and custom filter list to redirect to privacy-friendly alternatives since that will be much easier than implementing extension since it will be a very long time before we get extensions on Android.
Since right now I know only two browsers with support
[Kiwi](https://github.com/kiwibrowser), and Firefox Nightly #75 .
Thanks for going through this selfish request.

**Comment by ManeraKai** [comment]
I think there should be a mobile app

**Comment by soulspark666** [comment]
Would love it if there exists an app, but app do have issues running in the background and have a constant battery drain.
That is why I proposed a filter-based approach.

**Comment by ManeraKai** [comment]
It doesn't need to stay in the background. When opening a link, the option that says open with triggers and launches the app.

**Comment by soulspark666** [comment]
Ok, you are suggesting a type of privacy based browser which incorporates libredirect, that will be a nice idea but still not system-wide, I was thing something that works for opening links in any browser without the need for an extension.
But now I think of it if I have an app installed like Twitter, Pixiv, etc, then filter based things will definitely cause issues with its working, until someone knows a way to skip those.

**Comment by ManeraKai** [comment]
Yeah it can run on any browser. When openning a link on WhatsApp, you open it with LibRedirectMobile instead of Twittter. The LibRedirectMobile app launches, modifies the link and opens it again. Now you can open it with any program that supports this link, ex: Firefox supports https:/nitter.net/sadasdjasd or Chrome supports https://nitter.net/sadkjasdlk So you'll open it again with your own browser. I think some apps can interpret those links like NewPipe maybe. But this is the logic.

**Comment by ManeraKai** [comment]
I know Flutter that is cross-platform with Android and iOS and even desktop platforms. I'll see what I can do but don't expect it to be ready tomorrow.

**Comment by soulspark666** [comment]
Thanks, will be looking forward to it.

**Comment by austinhuang0131** [comment]
There is UntrackMe already

**Comment by soulspark666** [comment]
@austinhuang0131 isn't that just a browser, with features like libredirect embedded in it?

**Comment by austinhuang0131** [comment]
No, it's a system-wide app

**Comment by soulspark666** [comment]
ok, will try and let you know

**Comment by ManeraKai** [comment]
@austinhuang0131 I tried to use it once but it didn't work and here I totally forgot about it.

**Comment by ManeraKai** [comment]
I tried it now and it's working correctly.

**Comment by ManeraKai** [comment]
So... I'll close this issue as there's already an app called [UntrackMe](https://f-droid.org/packages/app.fedilab.nitterizeme/). I may add it in the README so no one will get lost.
