### ISSUE TITLE
Unable to set Libredirect as Search Engine.

### ISSUE THREAD

**Issue by EdwardLangdon** [libredirect/libredirect#187]
![image](https://user-images.githubusercontent.com/101938856/162996976-402d760a-ca92-427c-b0ea-6df9c2c18fab.png)

As you can see in the above Screenshot. I am unable to see Libredirect in the list of Search Engines.

This problem is through out Chromium not present in Firefox.

**Comment by ManeraKai** [comment]
yep: ![image](https://user-images.githubusercontent.com/40805353/163365744-fabfc907-f109-4f15-84de-182c69dded65.png)

**Comment by ManeraKai** [comment]
yep
![image](https://user-images.githubusercontent.com/40805353/163367728-9b2e77a9-1483-4e06-bedc-a83e4a310a6e.png)
![image](https://user-images.githubusercontent.com/40805353/163367851-42572973-1f44-472d-919b-1cfd2c859d55.png)

**Comment by EdwardLangdon** [comment]
So, It means that Libredirect needs to be the search Engine forcefully and cannot be changed.

**Comment by ManeraKai** [comment]
No, changing the homepage won't add a search engine.

**Comment by EdwardLangdon** [comment]
So, What's the reason it cannot be set as default ?

**Comment by ManeraKai** [comment]
If you see the errors in chromium, you'll see this: 
![image](https://user-images.githubusercontent.com/40805353/163371006-3e7a57b7-525a-4a16-8e03-4954b06e4a3f.png)

**Comment by ManeraKai** [comment]
I think it's part of the transition to Mv3

**Comment by EdwardLangdon** [comment]
Because of chromium blocking the overrides to be applied it cannot be set as Default Search Engine

**Comment by EdwardLangdon** [comment]
> I think it's part of the transition to Mv3

So, That's why I think we need to think about a way supporting or a Branch of Libredirect which is Mv3

**Comment by ManeraKai** [comment]
Now how the hell will we support chrome_overrides_settings in Mv3 if it's disabled?!

**Comment by EdwardLangdon** [comment]
I talking about Mv3 separately.

**Comment by EdwardLangdon** [comment]
> Now how the hell will we support `chrome_settings_overrides` in Mv3 if it got removed?!

I don't know. I haven't read the docs

**Comment by ManeraKai** [comment]
I'll see if Qwant can do anything to this. They want it more than us.

**Comment by ManeraKai** [comment]
> I talking about Mv3 separately.

See the warning: https://developer.chrome.com/docs/extensions/mv3/settings_override/

**Comment by EdwardLangdon** [comment]
> I'll see if Qwant can do anything to this. They want it more than us.

So, Can we reopen this as they will be mostly likely working on this.

**Comment by ManeraKai** [comment]
np 👍

**Comment by EdwardLangdon** [comment]
Hmm, Seems like you are right. We shall see. Will bookmark this issue to look back later.
