### ISSUE TITLE
Broken in Opera

### ISSUE THREAD

**Issue by einstein95** [libredirect/libredirect#188]
libredirect version: 1.6.2
Opera version: LVL3 (core: 85.0.4341.65) (x86_64)

Opera doesn't seem to like the menus part of the extension
```
Permission 'menus' is unknown or URL pattern is malformed.
```
```
Uncaught TypeError: Cannot read properties of undefined (reading 'create')
Context:
pages/background/background.html

Stack Trace:
pages/background/background.js:253 (anonymous function)
```

additionally
```
Uncaught SyntaxError: Unexpected token 'export'
Context:
pages/popup/popup.html

Stack Trace:
assets/javascripts/localise.js:37 (anonymous function)
```

**Comment by einstein95** [comment]
Attempting to go to a twitter link, for example, doesn't redirect at all (and breaks loading in twitter, as if the API was being blocked)

**Comment by ManeraKai** [comment]
Does it load the twitter page and break it at the same time or just doesn't redirect the the twitter page works fine?

**Comment by einstein95** [comment]
Ok, so based on what @j1cs said in #110, clearing "Cache Storage" for Twitter in the devtools fixes this. This is different from loading the page with "Disable Cache" set.

**Comment by ManeraKai** [comment]
> This is different from loading the page with "Disable Cache" set.

?

**Comment by einstein95** [comment]
In the network tab, you can check "Disable Cache" which merely removes any "Last-Modified" headers from the requests. This doesn't remove the cache.
