### ISSUE TITLE
[Question] Medium to Scribe, I'm puzzled

### ISSUE THREAD

**Issue by Cade66** [libredirect/libredirect#19]
Hi,

Be it LibRedirect, be it [Scribe's solution to redirect Medium posts to Scribe via the Redirect extension](https://scribe.rip/faq),  there's a point which puzzles me.
This is not related to LibRedirect itself, but rather to the logic of Scribe's redirection. No way to contact Scribe's developer so if LibRedirect's developer or anyone else has the answer, many thanks.

Medium to Scribe redirections send all Medium requests to Scribe (scribe.rip in my case/choice). This means basically that medium's homepage `https://medium.com` is redirected to `https://scribe.rip` which of course has no content.

The only logic I found in this redirection is to consider that the user never opens Medium's homepage, but uses the redirection in the context of Web searches on the Medium site, i.e.` https://duckduckgo.com/?q=%s+site:medium.com`. In this scenario, Medium to Scribe is perfect, but otherwise I remain puzzled that the redirection code does not include an exception for `https://medium.com/` as such...

I hope you get the idea!

Many thanks and long life to LibRedirect.

**Comment by ManeraKai** [comment]
I didn't finish reading but here's Scribe developer's email: edward@edwardloveall.com

**Comment by ManeraKai** [comment]
As I understand you want to not redirect if it's the home page i.e `https://medium.com/`, but redirect every other request i.e `https://ftrain.medium.com/big-data-small-effort-b62607a43a8c` because the home page for scribe doesn't give anyway to search, correct?

**Comment by Cade66** [comment]
This is correct. I'm presently writing to Scribe's developer at the address you indicated.

Yes, the idea is that the optimal scenario would be that redirects from medium to scribe handle only pages scribe is able to handle and allow otherwise visiting all other medium pages without disruption.

What do I mean by that? First of all of course medium's homepage. But even so and then, some links on medium aren't handled correctly : for instance those of the form `https://medium.com/tag/* ` ... and even if I narrow redirecting medium to scribe via a search engine (i.e. `https://duckduckgo.com/?q=%s+site:medium.com`) some results lead to `500 Something went wrong` error page at scribe.rip

It's not really my _wish_, it's more the idea that the very redirection concept, as presently thought, leaves a range of failed redirections, and that's what _puzzles_ me indeed.

As I said, I'm contacting right now Scribe's developer, notifying him of this post. When I get his answer I'll resume it here.

Thanks!

**Comment by ManeraKai** [comment]
I speak Arabic, English, little of Turkish :)

It's like there are still pages that aren't supported yet. It's really hard though to detect them.
Is the option of adding to the `500 Something went wrong` pages a redirect link to that medium like in invidious?
![image](https://user-images.githubusercontent.com/40805353/151702503-db55148b-1347-41b4-8294-a16a8a58370a.png)

**Comment by Cade66** [comment]
No, not like with Invidious. Testing right now with the REDIRECT filter provided at https://scribe.rip/faq . I'm **not** running _LibRedit_ at this time. I had only tested it to compare with previously installed _Privacy Redirect_ - I do not know if _LibRedit_ runs the same code as the _REDIRECT_ filter.

Anyway : Filter disabled - Medium.com (homepage) opened - Filter enabled - Clicking on the `https://medium.com/tag/self` button, which is redirected to `https://scribe.rip/tag/self` page which isplays :

![PageSaver-2022-01-30-15 08 17](https://user-images.githubusercontent.com/65161029/151703764-512db982-9a90-4c5f-a63f-0d83f176432c.png)

Several other links within medium.com pages do not redirect correctly to scribe.rip, not many but some. The logic of Scribe is obviously to handle Medium articles, which is understandable (that's the whole point) but without filtering pages it cannot manage (at least with the REDIRECT filter).

As I said above, if the user avoids the medium.com pages then 99% of search engines Web results are handled correctly because 99% of these results concern articles. But what happens to a user who wishes to visit Medium pages and at the same time read articles "cleaned up" with Scribe? That's the problem :=)

**Comment by ManeraKai** [comment]
I meant like invidious as that `Try heading back to home` button can do the same thing. Instead of saying `Try heading back to home`, it says `Visit the page on medium.com`. Click on the button and it heads you to https://medium.com/tag/self.

Do you want this approach from Scribe's side or an approach from our extension that detects those pages? The approach from us will be automatic. I don't think everyone likes to be automatically headed to a site they were trying to prevent it's javascript in the first place.

**Comment by Cade66** [comment]
That's a smart conclusion. I understand what you mean. IMO Scribe's link should forward to 'Visit the page on Medium' but then the REDIRECT filter will loop back to Scribe. An extension  can bypass that and redirect to the medium.com page. Consequently seems to me the extension could 'correct' the problem whilst the REDIRECT filter cannot. Personally I've added to the REDIRECT filter : `Exclude pattern: https://medium.com/tag/*` but I'd have to add several others as` https://medium.com/(tag|example1|example2)` which would handle all links not managed by Scribe, but that would be fastidious ; as you wrote above, "It's like there are still pages that aren't supported yet."

So, yes, I think that if LibRedirect would simply redirect unhandled scribe redirects to the original medium page then that would be a true advantage.

**Comment by ManeraKai** [comment]
> but then the REDIRECT filter will loop back to Scribe

This feature is already working with invidious. It's totally possible.

> LibRedirect would simply redirect unhandled scribe redirects to the original medium page

This is a good approach but having it automatically might annoy some users, a good middle option is to put a setting for it for the user to choose whether to be automatic redirecting or letting the him decide by clicking the link in the page that is `Visit the page on Medium`. What do you think?

**Comment by Cade66** [comment]
I didn't have an automatic redirection to the Medium "unhandled" page in mind but rather the latter option you propose : a redirected link is not handled by Scribe, Scribe page's mentions "Something went wrong" and here LibRedirect interferes and (replaces)/adds to the 'Try heading back to home' (with) a '`Visit the page on Medium'` : that seems to be the best and wisest solution :=)

**Comment by ManeraKai** [comment]
> and here LibRedirect interferes and (replaces)/adds to the 'Try heading back to home' (with) a 'Visit the page on Medium'

I think this should be Scribe's job. Had he responded?

> Without forgetting to not redirect Medium's homepage : https://medium.com/ of course!

I'll add this as an exception to the filter

**Comment by Cade66** [comment]
Nops, Scribe's developer hasn't answered yet, but the email has only been sent at 14:12 GMT ...
I entirely agree that what can be done with LibRedit (if I read you correctly) should in the first place be done by Scribe. If that was the case I wouldn't even have posted here for this topic! 

Now we know : LibRedit can correct what is obviously a Scribe unaccomplished development, which doesn't devalue Scribe's pertinence of course.
Now we linger to know : Scribe developer's comment (I've added a link to this GitHub post).

Looking forwards to LibRedit's future :=)

**Comment by edwardloveall** [comment]
Hi all! Scribe author here. I read through this, responded to @Cade66 and here's what I plan to do:

* Update the Error page to explain that Scribe only supports reading articles, not any other type of page
* Look into either updating the redirector regular expression to be smarter, or just point towards projects like this one that can handle more complex logic
* Consider ways I can make the experience better for non-article pages

I'm tracking some of that here: https://todo.sr.ht/~edwardloveall/Scribe/16

For transparency, I'm working on Scribe on nights and weekends and features don't happen very quickly so this might be a while. Thanks for your patience.

> The only logic I found in this redirection is to consider that the user never opens Medium's homepage, but uses the redirection in the context of Web searches on the Medium site, i.e. https://duckduckgo.com/?q=%s+site:medium.com.

The main use case I built the redirector logic for is when someone links to a Medium article from somewhere else on the web, like a Tweet or blog post. Clearly there are other medium links that people are visiting, but that's why it currently works the way it does. Obviously, some changes need to be made 🙂

**Comment by Cade66** [comment]
Thanks for the info, @edwardloveall. Your last paragraph clarifies it all.

**Comment by ManeraKai** [comment]
I see now that if you click e.g a profile of a writer, it will head you to the medium site and the extension will allow that. Is that good to you @Cade66?

**Comment by Cade66** [comment]
As far as I've understood, Scribe only handles articles so 2 possibilities :

1- The user is on Medium and clicks on a profile : the redirection should not apply (Scribe handles only articles)
2- The user is reading on Scribe an article which has been redirected from Medium and clicks on the article's author : the link should return to medium (Scribe handles only articles).

If you want my advice : _LibRedirect_ is a nicely crafted enhancement of forked _Privacy Redirect_, but including Scribe is maybe out of scope considering the way Scribe works. As the developer of Scribe wrote above,

> The main use case I built the redirector logic for is when someone links to a Medium article from somewhere else on the web, like a Tweet or blog post.

Perfectly suited as well for reading articles provided by Web search engines. But in all cases has to skip Medium's homepage ... 
Personally I use 2 redirections built for the REDIRECT extension, one redirects medium.com (no data) to medium.com : this blocks access to the second which redirects medium.com/DATA to Scribe as published by the developer at above mentioned https://scribe.rip/faq

From there on including Scribe in a redirection tool is a challenge maybe beyond pertinence, because it implies handling too many exceptions ...
Again, I don't think Scribe is fitted for LibRedirct no more than for Privacy Redirect ... but it's up to ypu, of course!

**Comment by ManeraKai** [comment]
I don't know who first added it, let me check

**Comment by Cade66** [comment]
I've just installed latest Libredirect 1.1.1 and I must say it's really very well carried out.
The Options page is a true delight, and smartly designed : intuitive
The two major points I've always been concerned with, 1- embedded YouTube videos (Piped in my case) and 2- redirections from Medium to Scribe appear to have been dealt with to an extent I didn't think would be possible.

@ManerKai, I'm impressed. Nice work, really. I'm off to AMO to rate it 5 stars.

**Comment by ManeraKai** [comment]
Isn't the version 1.3.1?

**Comment by Cade66** [comment]
> Isn't the version 1.3.1?

Version 1.3.1 of course! 

About Scribe : I was reserved, not on the pertinence of the project but on the feasibility of including it in a redirection extension. The way it's handled by LibRedirect seems more than acceptable given Scribe's very 'policy' is to handle only Medium's articles. I'll be using LibRedirect's Medium redirect in place of the code for the REDIRECT extension displayed at `https://scribe.rip/faq` from now given I'm keeping LibRedirect and disabling all the REDIRECT extension redirects I had been using up to now (YouTube, Instagram, Twitter, Reddit). Because Libredirect just does it, and does it nicely. I've also noticed the urlbar button to easily shift from one Redirect instance to another. Again, i'm amazed.

**Comment by ManeraKai** [comment]
Problem is, many people wanted it in Privacy-redirect. I think that was one of the main reasons for our team to add it before I came here. Including it here also helps in making it more popular and giving it attention. The Dev may even improve it much more because of that hopefully. We'll see what will happen in the future.
