### ISSUE TITLE
Search Settings

### ISSUE THREAD

**Issue by EdwardLangdon** [libredirect/libredirect#193]
Add Settings for all the Search Engines listed like Invidious and Nitter.

**Comment by ManeraKai** [comment]
I can't with Whoogle; the settings are just weird

**Comment by EdwardLangdon** [comment]
What about the others ?

**Comment by EdwardLangdon** [comment]
I see no Problems with Searx and StartPage.

**Comment by ManeraKai** [comment]
Totally possible. I even added the structure when I added theme support

**Comment by ManeraKai** [comment]
> I see no Problems with Searx and StartPage.

Really no need for StartPage. it's just one instnace

**Comment by EdwardLangdon** [comment]
> Really no need for StartPage. it's just one instnace.

But they would be worth it, IMO

**Comment by ManeraKai** [comment]
why?

**Comment by EdwardLangdon** [comment]
Mostly for Turning off Promotional Messages

**Comment by ManeraKai** [comment]
How is that?

**Comment by EdwardLangdon** [comment]
Well, you might be right that we can set settings for Startpage and forget about it. But implementing in LR means it will be forever. As you don't need to setup the cookies and won't forget it to set it up  again.

**Comment by ManeraKai** [comment]
cookies are persistent and they're the same as startpage. Reinstalling LR will reset the settings if you didn't export them.

**Comment by EdwardLangdon** [comment]
Well, Why not support StartPage too ?

**Comment by ManeraKai** [comment]
Because it's easy at all and it takes so much time and effort to make settings for a specific frontend/service. Many typos will come too as many things things connect together.

**Comment by ManeraKai** [comment]
And I don't want to bloat LR by adding settings that aren't needed at all as there's only one instance in the first place.

**Comment by m77e4t** [comment]
I agree with Manerakai here. 

Startpage is a fully fledged proper search engine which just uses google index. Startpage is not a proxy google metasearch engine like searx. Searx random instances usually go down once a week, so Libredirect cookie setting is useful for these instances. 
On another hand, to save Startpage preferences it has cookie functionality and URL saving method https://support.startpage.com/index.php?/Knowledgebase/Article/View/1238/5/what-is-the-settings-url like ddg has.

This feature will be quite extra (useless) which nobody will use (In my opinion).

**Comment by IronMaltese** [comment]
While I don't use Startpage, I just wanna say that for people that regularly clear their cookies or clear on exit (mainly Tor users) this feature would be useful, I'm not sure if they can save their preferences with the url, and accomplish this without cookies, but while this is all true, I don't think this feature should be added since there's so many private search engines and this extension should focus on alternative front ends unless a bunch of users want this feature

**Comment by whatbh** [comment]
Startpage user here. Startpage allow one to use a query string `prfe=XXXXXXXXXXXXXXXX` (can be found in Settings) to use their setting without bothering about cookies. Little to know, more than just bookmarking the link, one can append the query string to any Startpage request to use the preference. So if one search engine is `startpage.com?q=%s`, they can just append the preference string `startpage.com?q=%s&prfe=XXXXXXXXXXXXXXXX` and use that with saved preference, even if cookie is not present. Another way is to redirect Startpage search result page to new page including the preference string.

**Comment by ManeraKai** [comment]
I added the GENERAL, USER INTERFACE, PRIVACY pages. I didn't add ENGINES as it seems a little complex and has some values that should be retrieved from the server first. Seeing the ENGINES page really makes me think of making an option to just copy cookies from one selected instance to all the others. Having it like this won't force the user to work in LR's user interface as it's so much different than SearXNG. It will also speed up the process of supporting having new features (options) in the settings.
