### ISSUE TITLE
[BUG] Libredirect not redirecting anything

### ISSUE THREAD

**Issue by Generator** [libredirect/libredirect#194]
## Description
Since v1.6.3 none of the sites are redirecting on desktop and Android.
Already 'reset settings', same issue.

Libredirect: 1.6.3
Firefox (desktop): 99.0.1
Firefox (Android): 98.2.0

**Comment by ManeraKai** [comment]
Reinstall it.

**Comment by plague-doctor** [comment]
Nope. Reinstall doesn't do anything. 
On LibreWolf

**Comment by SoftwareRat** [comment]
Same problem:
Firefox: 99
Libredirect: 1.6.3
OS: Linux-based

**Comment by SoftwareRat** [comment]
> Reinstall it.
Thanks, it worked for me

**Comment by plague-doctor** [comment]
Ok works again, but had to make sure to remove all files related.

**Comment by wazlecracker** [comment]
> Ok works again, but had to make sure to remove all files related.

Could you specify what exactly you had to remove? Using librewolf as well.

**Comment by EdwardLangdon** [comment]
> Could you specify what exactly you had to remove? Using librewolf as well.

Just Uninstall from Librewolf. Close it and Then reopen and install it.

I think he means about installing from the `src`

**Comment by Generator** [comment]
Looks like it fixed itself on the desktop without doing noting!

**Comment by EdwardLangdon** [comment]
Great to know.

**Comment by kartikynwa** [comment]
Reinstalling fixed the issue for me on Firefox 99.0. Would be nice to know why.

**Comment by xnaas** [comment]
Reinstall worked for me on **Firefox 100.0b6**. I am curious what randomly broke the extension as well, if there's any insight on that. 😅

**Comment by ManeraKai** [comment]
I really want to know too.
