### ISSUE TITLE
Links to Mobile Wikipedia not being redirected

### ISSUE THREAD

**Issue by Mrnofish** [libredirect/libredirect#196]
Couldn't find a relevant issue, so I'm opening a new one.

Links to the mobile version of Wikipedia are not getting redirected, e.g. https://en.m.wikipedia.org/

These are encountered, regardless of the device being used, whenever folks share the mobile page instead, or it is saved somewhere, just to mention a couple instances.

Thanks for the useful extension.

**Comment by ManeraKai** [comment]
Fixed it. I'll close the issue. Any problem, just write it here 👍
