### ISSUE TITLE
Yahoo and bing redirect 

### ISSUE THREAD

**Issue by prorounak2005** [libredirect/libredirect#199]
It would mean a lot to me if a bing and yahoo redirect could be done to privacy respecting alternatives like searx.

**Comment by BobIsMyManager** [comment]
I would also reccommend adding [Ecosia](https://www.ecosia.org/) and [Yandex](https://yandex.com/) as that would cover the default search engines in most browsers

**Comment by ManeraKai** [comment]
What are the domains that you use for yahoo? do you use search.yahoo.com or yahoo.com too?

**Comment by ManeraKai** [comment]
@BobIsMyManager so Yandex as a "target" next to google and yahoo. And Ecosia as a "redirect" next to searx, qwant. right?

**Comment by BobIsMyManager** [comment]
> @BobIsMyManager so Yandex as a "target" next to google and yahoo. And Ecosia as a "redirect" next to searx, qwant. right?

No, ecosia as a target, as from their [privacy policy](https://info.ecosia.org/privacy), they are clearly not a private search engine

**Comment by ManeraKai** [comment]
you're joking right?

**Comment by ManeraKai** [comment]
@BobIsMyManager?

**Comment by IronMaltese** [comment]
Ecosia says it'll respect the user's privacy if so not track is on, is there a way to set a cookie or something that convinces ecosia this setting is on even if it isn't?

**Comment by ManeraKai** [comment]
I added it as a "redirect" and I treat it the same as Qwant, DuckDuckGo, and all those centralized services. No need for "cookies" anymore to track you and know who you are. @BobIsMyManager confused me though as what does he want.

**Comment by BobIsMyManager** [comment]
> you're joking right?

No, as by using ecosia, you must also agree to microsofts and yahoos privacy policy:

> We use elements of Microsoft Bing’s search index to deliver results. We never communicate IP addresses along with search queries. We only send IP addresses to Microsoft in obfuscated form, meaning we remove parts of the IP address when we store it. For example 192.168.152.223 becomes 192.168.XXX.XXX. These obfuscated addresses cannot be linked either to you or your searches, and are deleted from Microsoft’s system after 90 days. Microsoft uses the IP address for spam protection. For more information, please refer to their Privacy Statement.

> Personalized search is optional, and you can change your preference via our settings menu any time. If you use personalized search results, you get a unique identifier assigned from Microsoft Bing, which can tailor your search results based on your previous search history. This data gets deleted after 18 months. For further details, please refer to Microsoft’s Privacy Policy.

> We may use Yahoo´s services in some regions to deliver search results to you. When you search with Ecosia, Yahoo and their partners receive your IP address along with your search query, and delete both after no more than 90 days. For further information, please refer to Yahoo’s Privacy Policy.

**Comment by IronMaltese** [comment]
You should put a note next to Ecosia that they promise not to track you if you enable do not track

**Comment by ManeraKai** [comment]
> You should put a note next to Ecosia that they promise not to track you if you enable do not track

They can read it from the site.

**Comment by ManeraKai** [comment]
> > you're joking right?
> 
> No, as by using ecosia, you must also agree to microsofts and yahoos privacy policy:

Why do you want me to add as a "target" since it's not a "default" search engine in any of the browsers I know and the people that use it are using it because of their choice. Even yahoo isn't so convincing to add as a "target" as I can't see it as a "default" search engine in any of the browsers I know.

**Comment by BobIsMyManager** [comment]
> it's not a "default" search engine in any of the browsers I know

By default I meant that it is one of the search engine options built into most browsers

You dont have to add it if you dont want to tho, it was just a suggestion

**Comment by BobIsMyManager** [comment]
No I dont think it should be next to ddg or qwant.

> did you see it as a search engine option in any browser? 

Not in anything besides ecosias own browser for mobile

**Comment by BobIsMyManager** [comment]
Nope

**Comment by ManeraKai** [comment]
I think yandex is used by some browsers though as it's popular in russia

**Comment by BobIsMyManager** [comment]
But ofc edge uses bing and yandex uses, well, yandex

**Comment by ManeraKai** [comment]
bruh I didn't know they had a browser xD

**Comment by BobIsMyManager** [comment]
Well since they are russian google, they must have the complete package!

**Comment by prorounak2005** [comment]
> I would also reccommend adding [Ecosia](https://www.ecosia.org/) and [Yandex](https://yandex.com/) as that would cover all the default search engines in most browsers

Umm Ecoasia is really trash lol. I use searx , startpage , brave search and metager . I don't use duckduckgo anymore because they are censoring search results now sadly :( - https://twitter.com/yegg/status/1501716484761997318 . I mean who is he to decide who is right and who is wrong. Everyone has the freedom to take a side they want.

**Comment by ManeraKai** [comment]
> Well since they are russian google, they must have the complete package!

Google Doesn't have a browser but ddg does, fair point xD

**Comment by ManeraKai** [comment]
> I don't use duckduckgo anymore because they are censoring search results now sadly :( - https://twitter.com/yegg/status/1501716484761997318 ) . I mean who is he to decide who is right and who is wrong. Everyone has the freedom to take a side they want.

There's some talk about that that it's not considered as "censoring". More in this section in this video: https://youtu.be/p7hqqSHCrqg?t=110
btw I won't get into discussion about it here.

**Comment by prorounak2005** [comment]
> > I don't use duckduckgo anymore because they are censoring search results now sadly :( - https://twitter.com/yegg/status/1501716484761997318 ) . I mean who is he to decide who is right and who is wrong. Everyone has the freedom to take a side they want.
> 
> There's some talk about that that it's not considered as "censoring". More in this section in this video: https://youtu.be/p7hqqSHCrqg?t=110 btw I won't get into discussion about that here.

Hmmmmm - https://invidious.kavin.rocks/watch?v=OjWDfIpwEAQ

**Comment by ManeraKai** [comment]
Fair points @prorounak2005

**Comment by ManeraKai** [comment]
I'll close this issue as we've added bing and yandex.

**Comment by BobIsMyManager** [comment]
> > Well since they are russian google, they must have the complete package!
> 
> Google Doesn't have a browser but ddg does, fair point xD

Google chrome -_-

**Comment by IronMaltese** [comment]
> Google chrome -_-

Yeah I was wondering if I should say anything, lol🦭

**Comment by ManeraKai** [comment]
oh dear xD
