### ISSUE TITLE
Error handling response: TypeError: redirects.whoogle.i2p is not iterable

### ISSUE THREAD

**Issue by austinhuang0131** [libredirect/libredirect#200]
https://github.com/libredirect/libredirect/blob/a1c652f6dd38b87ab89b8c837c4c11b2cad95f57/src/assets/javascripts/helpers/search.js#L565

Apparently importing old settings send the extension into a crash loop

**Comment by ManeraKai** [comment]
> Apparently importing old settings send the extension into a crash loop

Yep, seems that it only happens on your side.

**Comment by ManeraKai** [comment]
Does it still happen @austinhuang0131?
