### ISSUE TITLE
Medium towardsdatascience.com custom domains not working

### ISSUE THREAD

**Issue by jamesWalker55** [libredirect/libredirect#202]
I've found a link that doesn't get redirected by LibRedirect:

```
https://towardsdatascience.com/how-to-make-windows-10-toast-notifications-with-python-fb3c27ae45b9
```

By manually replacing the domain, I am able to access the scribe version of the site, for example:

```
https://scribe.froth.zone/how-to-make-windows-10-toast-notifications-with-python-fb3c27ae45b9
```

**Comment by ManeraKai** [comment]
Don't worry, it's working correctly rather I just didn't release a new version. This was addressed before in #137
