### ISSUE TITLE
Twitter redirect not working?

### ISSUE THREAD

**Issue by soulspark666** [libredirect/libredirect#205]
Using Mozilla, reinstalled the extension, still the same issue.

If you require any logs please let me know

**Comment by ManeraKai** [comment]
Did you reset the all mighty settings?

**Comment by PAI5REECHO** [comment]
Something is very broken with this extension, it stopped redirecting for all sites even after doing reset settings. I had to uninstall it and reinstall it. After importing my old settings it kept using the default settings

**Comment by ManeraKai** [comment]
I think rapid change of the extension's  structure and the fast updates make it incompatible with previous versions. The solution to all this is to release only major versions. So there will be a time period of about a month between them.

**Comment by ManeraKai** [comment]
It's not about that it has "bugs" because I'm fixing everyone that pops up but rather just the updating process that is breaking everything.
