### ISSUE TITLE
#166, but for Bibliogram

### ISSUE THREAD

**Issue by xnaas** [libredirect/libredirect#206]
Similar to #166, I'm noticing the same for Bibliogram.

https://user-images.githubusercontent.com/8271327/163906120-0565c38c-01ad-413a-89d7-bc9aae4b11d7.mp4

As seen above, the requests are still going to Instagram, not Bibliogram.

**Comment by ManeraKai** [comment]
Sorry wrong ticket number; the commit is here: https://github.com/libredirect/libredirect/commit/8fb929399e0c7a7c622850ac87f36285968934b5

Funny that your previous one was 166 and this one is 206 xD.

Anyway this should work now.
