### ISSUE TITLE
ProxiTok video redirection and embed

### ISSUE THREAD

**Issue by pablouser1** [libredirect/libredirect#207]
Hi, some issues regarding ProxiTok:
- Recently TikTok changed https://www.tiktok.com/video/VIDEO_ID to https://www.tiktok.com/@USERNAME/video/VIDEO_ID. Libredirect still forces the old format, which is now deprecated
- Proxitok started supporting embeds, but Libredirect doesn't redirect urls from an iframe

**Comment by ManeraKai** [comment]
oh really nice! now I can make a "reverse function" out of it: https://github.com/libredirect/libredirect/issues/165#issuecomment-1101066835
