### ISSUE TITLE
Doesnt work in 100.0b8 (64-Bit) Developer Edition

### ISSUE THREAD

**Issue by 1muen** [libredirect/libredirect#211]
With the normal Firefox Version 99.0.1 (64-Bit) it works. With the dev edition it wont redirect me. Neither Reddit, twitter nor YoutTube or peertube.
The only error I see is 
![grafik](https://user-images.githubusercontent.com/49640488/164544310-a2228a3e-797d-4cfa-9c65-fefa2364b1be.png)
But I guess thats going to be fixed with #210 .
I have been clicking on "Untersuchen" (Debugging) and trying to set some breakpoints in the code responsible for peertube, but it doesnt give me the opportunity to debug.
Nothing helpful is printed to the console.

**Comment by ManeraKai** [comment]
I merged that PR

**Comment by ManeraKai** [comment]
I did use Firefox Developer edition version 1000.0b9 and it's working fine.

**Comment by ManeraKai** [comment]
Alive my friend?

**Comment by 1muen** [comment]
@ManeraKai yes :D Its working fine, if I use a new Profile. I think, I have too many tabs and windows open in my default profile. I think I maybe have 1000 tabs open. I have 19 Windows in different Worspaces open.

**Comment by ManeraKai** [comment]
Then I wont be surprised if your computer burned than to talk about LibRedirect.
