### ISSUE TITLE
Improve Qt URL handling for FreeTube rediect

### ISSUE THREAD

**Issue by sith-on-mars** [libredirect/libredirect#212]
I'm on the Tumbleweed KDE. Everything seemed to work fine when I was using Tumbleweed Gnome. However, after switching to KDE, the extension only opened the main app, but won't go to the YouTube link that it's trying to direct to.

Is there anything libredirect can do to solve it? Or maybe should I report the issue to KDE?

**Comment by ManeraKai** [comment]
Can you try the Firefox in flatpak or download it directly and see if it's maybe firefox's problem?

**Comment by sith-on-mars** [comment]
I don't think it's the problem with Firefox. I've tried the extension on Chromium and the result was the same.

**Comment by ManeraKai** [comment]
It's weird as I myself am using KDE (Kubuntu LTS)

**Comment by ManeraKai** [comment]
Did something happen on your side?

**Comment by ManeraKai** [comment]
Hello?

**Comment by sith-on-mars** [comment]
It could be a KDE or OpenSUSE issue. I'll report bug to them. For now, I'll close the issue.

**Comment by sith-on-mars** [comment]
Here is [the bug report](https://bugzilla.opensuse.org/show_bug.cgi?id=1199125) which I think it might be of help for you. I think Libredirect could have improved the URL handling of the YouTube redirect function in the Qt environment, as I quote here from a SUSE developer:

```
I gave it a try and I can reproduce the issue. The libredirect extension simply changes any https://youtube.com/watch?v=... url by prepending freetube://, resulting in e.g. freetube://https://www.youtube.com/watch?v=dQw4w9WgXcQ.
Qt's QUrl parses that as scheme=freetube host=https port=empty and converts it to freetube://https//www.youtube.com/watch?v=dQw4w9WgXcQ (no colon!). The freetube app can't handle that.

This can be reproduced easily by xdg-open freetube://https://www.youtube.com/watch?v=dQw4w9WgXcQ. The started freetube process gets the URL without colon as argument.

I don't think freetube://https://... is a valid URL, so IMO this is something for libredirect and freetube to figure out how to solve. Using an authority-less URL like freetube:https://www.youtube.com/watch?v=dQw4w9WgXcQ might work, as colons in filenames are allowed. As a workaround, freetube could handle the lost colon in the passed URL.
```

And the reason why the extension works on Gnome and Kubuntu, but not on a rolling distro like Tumbleweed KDE:
```
Gnome doesn't use Qt for URL handling. Kubuntu might either use an older version of Qt or KDE software with different behaviour or somehow not use KIO for handling the URL (missing browser integration?)
```

**Comment by ManeraKai** [comment]
well this url seems to work:
`freetube://https:www.youtube.com/watch?v=dQw4w9WgXcQ`

**Comment by sith-on-mars** [comment]
Have you read this?
`Gnome doesn't use Qt for URL handling. Kubuntu might either use an older version of Qt or KDE software with different behaviour or somehow not use KIO for handling the URL (missing browser integration?)`

It seems changing the way of URL handling from `freetube://https//www.youtube.com/watch?v=...` to `xdg-open freetube://https//www.youtube.com/watch?v=` would be a quick fix?

**Comment by ManeraKai** [comment]
yeah I read it. The url I wrote earlier isn't different and doesn't have double forward slash infront of `https`, I want to know if this quick fix would do it rather to talk to the Freetube dev as I can't manage to open `freetube://www.youtube.com/watch?v....`, I should write and use the `https` protocol.

**Comment by sith-on-mars** [comment]
> well this url seems to work: `freetube://https:www.youtube.com/watch?v=dQw4w9WgXcQ`

Without double forward slash, it doesn't work on my system. I don't have any coding/programming knowledge so my technological understanding can be quite limited...

**Comment by ManeraKai** [comment]
it works on my system when I open it through Firefox, not through `xdg-open`.

If it's like this then you should open an issue on [Freetube](https://github.com/FreeTubeApp/FreeTube) and tell them to delete the `https://` from their url handling. I can't do anything from my side.
