### ISSUE TITLE
Libredirect not redirecting in Edge

### ISSUE THREAD

**Issue by EdwardLangdon** [libredirect/libredirect#214]
So, I fired up MS Edge in my PC.

Pasted this link : https://www.reddit.com/r/StartpageSearch/comments/svago7/some_ui_fixes_or_improvements/

It straight up loaded reddit after refreshing the page only it loaded Libreddit.

**Comment by ManeraKai** [comment]
Dublicate #158

I don't know what to do with it as the LibRedirect hasn't started yet.

**Comment by EdwardLangdon** [comment]
I reopened this, How about implementing Suspending all network activity until Libredirect is loaded ?
Like uBlock Origin does for loading all filterlists.
