### ISSUE TITLE
Change "https://https://wiki.froth.zone" to "https://wiki.froth.zone" [Incorrect Wikiless instance]

### ISSUE THREAD

**Issue by vairag22** [libredirect/libredirect#216]
![image](https://user-images.githubusercontent.com/71322586/164912169-778d677e-90cf-4ee7-b934-b053c0417d64.png)

**Comment by BobIsMyManager** [comment]
Wikiless instances are automatically fetched, and therefore are not manipulated by the libredirect team, see [this comment](https://github.com/libredirect/libredirect/pull/172#issuecomment-1090402800).

**Comment by ManeraKai** [comment]
I think you just need to update the instances list. You'll find this in the general's page.

**Comment by EdwardLangdon** [comment]
https://codeberg.org/orenom/Wikiless/commit/4a0d9b3d9475e598ec11fa3a6001db4912f06ebf - As per the commit - The URL in the Instance lists is fixed by the Maintainer. So, It will be updated shortly by the Python Script.

So, Closing this issue. Please wait until the next update of Libredirect.
