### ISSUE TITLE
Add option for disabling redirects to instances that use Cloudflare

### ISSUE THREAD

**Issue by vairag22** [libredirect/libredirect#218]
Add an option in General Settings to untoggle all instances that use Cloudflare. Redirects those instances will only be possible if user manually toggles them.

**Comment by ManeraKai** [comment]
Is this really necessary? I don't want to play much with instances selection. I'll add a way to sort the instances by either latency or Cloudflare. This way it'll be easier for the user to deselect what he doesn't want.

**Comment by IronMaltese** [comment]
I understand that users can disable cloudflare instances manually, so that feature doesn't need to by be added if you don't want to, but the ability to select the best latency instance everytime isn't possible a without**** actively disabling all but one or a few instances right now, so auto select best latency instance would be a great feature that's not currently possible

**Comment by ManeraKai** [comment]
Problem with selecting best latency is that JavaScript doesn't really have a `ping` request and It just differs so much from a second to the other. Just try pressing on check latency and you'll see results almost random.

**Comment by ManeraKai** [comment]
I may add the option for redirecting off of Cloudflare instances but they'll still be checked. Like I'll treat them as if they were "offline instances" and you know how that works.

**Comment by EdwardLangdon** [comment]
I think that Disabling Instances with Cloudflare is Unnecessary. Because, Cloudflare is used as CDN by them for faster delivery of Content. So, What Privacy issue do you see here - @IronMaltese ?

**Comment by ManeraKai** [comment]
Can this be somewhat compared to hosting on AWS?

**Comment by lilithium-hydride** [comment]
A central entity knowing every website you visit and all content you load on it isn't the greatest for privacy. No different from concerns around AMP in my opinion.

**Comment by ManeraKai** [comment]
as talking with @alefvanoon he sent me this: https://community.cloudflare.com/t/what-data-does-cloudflare-actually-see/28660
so not only centralization but with no encryption. You (plural) have a point.

**Comment by vairag22** [comment]
> Back in 2003, Lee Holloway and I started Project Honey Pot as an open-source project to track online fraud and abuse. The Project allowed anyone with a website to install a piece of code and track hackers and spammers.
We ran it as a hobby and didn't think much about it until, in 2008, the Department of Homeland Security called and said, "Do you have any idea how valuable the data you have is?" That started us thinking about how we could effectively deploy the data from Project Honey Pot, as well as other sources, in order to protect websites online. That turned into the initial impetus for CloudFlare.

– Matthew Prince, CEO of Cloudflare ([source](https://web.archive.org/web/20170217121944/http://www.law.uchicago.edu/alumni/accoladesandachievements/matthew-prince-00-discusses-cloudflare-cloud-computing-journal))

**Comment by vairag22** [comment]
@ManeraKai The instances that use Cloudflare are listed in cloudflare.json, you could add a few SLOC that check if an instance from data.json is also in cloudflare.json then that instance is untoggled by default. Users who don't have any problems with Cloudflare can simply toggle the instances they like or toggle all. 

_(+1 for privacy by default)_

**Comment by vairag22** [comment]
@ManeraKai The instances that use Cloudflare are listed in cloudflare.json, you could add a few SLOC that check if an instance in data.json is also present in cloudflare.json then that instance is untoggled by default. Users who don't have any problems with Cloudflare can simply toggle the instances they like or toggle all. 

_(+1 for privacy by default)_

**Comment by ManeraKai** [comment]
> (+1 for privacy by default)

Well I can't argue with that. Didn't know it's to the point of disabling encryption.

**Comment by vairag22** [comment]
> Didn't know it was to the point of disabling encryption.

What you do mean?

**Comment by ManeraKai** [comment]
I didn't know Cloudflare has the encryption keys and can read the proxied data.

**Comment by ManeraKai** [comment]
This is a really rare usecase and most of the instances are normal not the opposite.

**Comment by Victor239** [comment]
Good to see the threat of Cloudflare is being recognised here. A browser extension I've also been using for a while is [True Sight](https://github.com/claustromaniac/detect-cloudflare-plus), which differentiate between sites using Cloudflare as a CDN or as a proxy (the latter meaning they have unencrypted access to visitor connections).

**Comment by IronMaltese** [comment]
> Good to see the threat of Cloudflare is being recognised here. A browser extension I've also been using for a while is [True Sight](https://github.com/claustromaniac/detect-cloudflare-plus), which can differentiate between sites using Cloudflare as a CDN or as a proxy (the latter meaning they have unencrypted access to visitor connections). 

I believe that Beatbump.ml uses cloudflare as a CDN and libredirect doesn't recognize this, but if this has no privacy impact, I don't think it should even be labeled, let me know if you disagree

**Comment by ManeraKai** [comment]
@snuffyDev

**Comment by snuffyDev** [comment]
Beatbump is entirely powered by Cloudflare. The app is hosted with Cloudflare Workers, uses Cloudflare for DNS, CDN, Workers KV (for static assets). But personally, I feel that the option to disable redirects for Cloudflare wouldn't be a bad idea. While I do trust Cloudflare (a lot more than I do Amazon, Google, etc.), some people just don't.

Although, having it on by default is sort of a double-edged sword from my perspective. Some people don't mind it, some people do. 

I will just add in my personal experience, at least from what I've seen over the past year of using their services (specifically talking analytics, as well as the logs [Managed Firewall Events, Workers]) they hold up to what their privacy claims, at least on the consumer-side of things. But the same things could be said about AWS CloudFront, or GCP's Cloud CDN in my opinion.

All in all, it wouldn't hurt to add it, but *how* you add it is the key thing imo.

**Comment by ManeraKai** [comment]
I'll disable beatbump by default. Invidious, Piped, etc... instances can read `music.youtube.com`. Anyone who wants beatbump can enable it in the settings.

**Comment by IronMaltese** [comment]
> I'll disable beatbump by default. Invidious, Piped, etc... instances can read `music.youtube.com`. Anyone who wants beatbump can enable it in the settings.

Is this only because of Cloudflare?

**Comment by ManeraKai** [comment]
Yes.

**Comment by vairag22** [comment]
All [kavin.rocks](https://status.kavin.rocks) instances including the main Piped instance [piped.kavin.rocks](https://piped.kavin.rocks) use Cloudflare. 

https://whois.com/whois/kavin.rocks:
> Domain: kavin.rocks
Registrar: Cloudflare, Inc
Registered On: 2019-09-19
Expires On: 2022-09-19
Updated On: 2021-08-25
Status: clientTransferProhibited
Name Servers: brad.ns.cloudflare.com, chloe.ns.cloudflare.com

**Comment by ManeraKai** [comment]
xD
![image](https://user-images.githubusercontent.com/40805353/166787324-09bec7af-f7e3-4123-8a84-8d4299eb7528.png)

**Comment by vairag22** [comment]
All of those instances use Cloudflare?

**Comment by ManeraKai** [comment]
Yes. People should really know about this. It's fake decentralization.
