### ISSUE TITLE
Any possibility to officially host it on the webstore ? (chromium)

### ISSUE THREAD

**Issue by BirdInFire** [libredirect/libredirect#221]
I ask this only because many user will fallback by default on the "privacy redirect" not as much maintained as your because they do not even know this project exist (since more than 80% of the user are on chromium based browser) i hope to see a volonteer who actually already have a google dev account approach the dev to "officially" publish it (because i actually manually update but it very veeeeery anoying process to do).

And since 1 time of 2 the data is lost during update and import do not work it's even more anoying.

I only ask to see if we (chrome based user) can hope or not.
Thanks

**Comment by ManeraKai** [comment]
We already made an account but it's more complicated than this: https://github.com/libredirect/libredirect/wiki/FAQ#why-not-manifest-v3

**Comment by BirdInFire** [comment]
> We already made an account but it's more complicated than this: https://github.com/libredirect/libredirect/wiki/FAQ#why-not-manifest-v3

ah it's a manifest V3 problem, i didn't know :/
