### ISSUE TITLE
Adding Mojeek's and Brave's search engine ?

### ISSUE THREAD

**Issue by BirdInFire** [libredirect/libredirect#222]
Why do i even propose that you will say ?, 
it's after a recent video of techlore who have opened my eye on meta search nearly all browser in the list a meta search engine (who rely on index of big tech (for the majority (searx is the only one to actually propose mojeek)).

so i hoped to see (with the warning of every centralized services) see these two private search engine who build their own index.
(because if they are more awareness on that maybe external search engine) will rely less on bing/google and use more mojeek and brave index.

Edit i would like the tought of the community since i do understand by their centralized principle they aren't perfect.

**Comment by ManeraKai** [comment]
I really don't have a problem adding them as we already have startpage. But should I add Brave Search as it's already the default search engine on Brave and it doesn't need redirection, or do people use it on other browsers?

**Comment by BirdInFire** [comment]
> I really don't have a problem adding them as we already have startpage. But should I add Brave Search as it's already the default search engine on Brave and it doesn't need redirection, or do people use it on Firefox?

for brave it's of course not for brave user but more vivaldi, edge, chrome, chromium, ungoogled chromium and so on.
i propose these two only because it's the only one (i know) who rely on their own index and are "private" (mean by that do not save research) by default.

**Comment by ManeraKai** [comment]
All chromium browsers don't support adding custom search engines. They did support this before but not now. That's why I only said Firefox.

I'll still add it since maybe some Firefox users will use it. But now I'm thinking of why adding Startpage and Brave Search if there's already extensions for them. Even Mojeek has an unofficial extension in Firefox Addons Store.
