### ISSUE TITLE
Use Gitlab or Codeberg

### ISSUE THREAD

**Issue by vairag22** [libredirect/libredirect#226]
Shouldn't an extension that redirects users to FOSS instances also use a FOSS git repository hosting service like GitLab or Codeberg? 😉

**Comment by EdwardLangdon** [comment]
That would be a mess and to handle the List ourselves. Some Community Contribution would be needed.

**Comment by ManeraKai** [comment]
It's okay. I can handle it as mostly it will be focused on GitHub. If we got enough users we may switch from GitHub, idk.

**Comment by EdwardLangdon** [comment]
@ManeraKai I don't understand what you or Vairag mean.

**Comment by ManeraKai** [comment]
What I mean is having a mirror repository that people can create issues on too. See my [SimplyTranslate Mobile](https://github.com/ManeraKai/simplytranslate_mobile#mirror-repos) mirror repos.

**Comment by EdwardLangdon** [comment]
I think it's easy to Mirror on Codeberg. If you have access to Libredirect Organization account.

**Comment by ManeraKai** [comment]
Yeah perfect! https://codeberg.org/LibRedirect
Already taken

**Comment by ManeraKai** [comment]
How about making a [Gogs](https://gogs.io/) repo?

**Comment by EdwardLangdon** [comment]
Yeah, Gogs might be perfect but more Collaboration won't be there. It will just act as an Mirror.

For the Codeberg I think, Something like this - https://codeberg.org/Libredrect-Official would be better.

**Comment by EdwardLangdon** [comment]
@ManeraKai How about an Organization like below in Codeberg ?

![image](https://user-images.githubusercontent.com/101938856/166183277-cc92ffb7-f614-47e1-aaf8-c40246b0cb78.png)

**Comment by ManeraKai** [comment]
> Yeah, Gogs might be perfect but more Collaboration won't be there. It will just act as an Mirror.

You're right

> For the Codeberg I think, Something like this - https://codeberg.org/Libredrect-Official would be better.

I don't know but I want to contact Codeberg admins and they might get something.

> @ManeraKai How about an Organization like below in Codeberg ?

what?

**Comment by EdwardLangdon** [comment]
> what?

In Codeberg, Instead of Converting an Account into an Organization like Github. You can create an Organization from your Own Codeberg account too. You will be assigned as the Owner or later transfer it though if you wish. Similar to Github Organizations. The Organization will be an Organization not an Independent account like in Github.

I think that this might be your Best bet as Libredirect is already under an Organization account you won't be struggling. Just Head to Codeberg.org and then you will se as below and create an org. That's it.

![image](https://user-images.githubusercontent.com/101938856/166190429-e785298e-1cd9-4dc7-8786-bdce7431ea6d.png)

**Comment by ManeraKai** [comment]
I already did that and stuck with that conflict. I created an organization from my account.

**Comment by alefvanoon** [comment]
@ManeraKai I invited you to the LibRedirect organization at Codeberg.
Sorry if it's too late.

**Comment by ManeraKai** [comment]
bruh it was yours xD.

**Comment by ManeraKai** [comment]
Now LibRedirect is on  [Codeberg](https://codeberg.org/LibRedirect) and we may even switch to it if we got enough one day.

**Comment by m77e4t** [comment]
It is also important to note that Github might kick out this repo and ban the main devs.
Github might receice legal notice from youtube, instagram, twitter etc to make them do that for violating some copyright/DMCA/some other legal jargon.

It is good that we have a mirror on codeberg.

**Comment by ManeraKai** [comment]
Still till now Invidious and Nitter aren't kicked, but a backup is necessary.
