### ISSUE TITLE
YouTube Embed redirects are broken

### ISSUE THREAD

**Issue by Elaborendum** [libredirect/libredirect#228]
I don't know when it started happening, but recently, YouTube embed redirections to both Invidious and Piped don't seem to work. The regular YouTube embed loads without getting redirected at all, and it plays normally without redirecting too. Happens independently of "Bypass Watch on YouTube" (what does this setting do anyway?) being enabled or not. I previously chose Freetube as my preferred front end, but I don't know if the issue started then.

You can see it on https://youtubeembedcode.com/en/.

**Comment by ManeraKai** [comment]
"Bypass Watch on YouTube" doesn't relate to this at all.

Can you please try selecting invidious as the frontend and see if it's still not working?

**Comment by ManeraKai** [comment]
Does it even redirect regular youtube links? try this one: https://www.youtube.com/watch?v=8dJyRm2jJ-U

**Comment by ManeraKai** [comment]
which embeds? the link you provide it was working on my side.

**Comment by ManeraKai** [comment]
Try to reset the settings and reinstall. This link is working too on my browser.

**Comment by ManeraKai** [comment]
>  Should I keep this issue open, or could this just be an isolated incident?

one second. Try to reinstall it not turning it on or off.

**Comment by ManeraKai** [comment]
oh sorry I read it in the opposite way 😅. I think it happened because of updating the extension or some incompatibility thing. Yes I think it's an isolated incident. I'll close the issue as you said.
