### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by Mehavoid** [libredirect/libredirect#229]
Hi, first of all, I want to say thank you for continuing to work on this extension.

When I was working on this [improvement](https://github.com/libredirect/libredirect/pull/227), I was confused by the structure of the project. Why doesn't this project use a linter? With the right setup, we can avoid these problems and achieve a unified code base style.

- Mixing [function expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/function) and [function declaration](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function): https://github.com/libredirect/libredirect/blob/2b4ea71e78309a144c2eb8d5534ae99f665e804d/src/assets/javascripts/helpers/instagram.js#L92-L97
- Using `equality` instead `Strict equality`: https://github.com/libredirect/libredirect/blob/2b4ea71e78309a144c2eb8d5534ae99f665e804d/src/pages/background/background.js#L129
- Using `var`: https://github.com/libredirect/libredirect/blob/2b4ea71e78309a144c2eb8d5534ae99f665e804d/src/pages/background/background.js#L82

**Comment by ManeraKai** [comment]
It uses a linter `npm run test`

The unifying does makes sense. I didn't notice there was a `var` in the script.

**Comment by ManeraKai** [comment]
btw I'll really change the structure and you even not see something like this:
```js

 const getProtocol = () => protocol; 
 function setProtocol(val) { 
   protocol = val; 
   browser.storage.local.set({ nitterProtocol: val }) 
   console.log("nitterProtocol: ", val) 
 } 
```

**Comment by ManeraKai** [comment]
Simplified it more in this commit: https://github.com/libredirect/libredirect/commit/a28cccfde07e76d1e70d2acfe1c2222d8b8ae705
