### ISSUE TITLE
Error parsing the URL [Medium]

### ISSUE THREAD

**Issue by Moxville** [libredirect/libredirect#23]
Hi,
Thanks for the nice Firefox Addon.
For the following links I get an error message. Any workaround for this ?
https://medium.com/topic/technology
https://medium.com/tag/relationships

![Medium-Error](https://user-images.githubusercontent.com/31923265/151814604-f166365f-887a-42a1-bd09-a36a75d39f64.png)

**Comment by ManeraKai** [comment]
Hello there!
This whole problem has been discussed here #19.
