### ISSUE TITLE
Add Pinafore

### ISSUE THREAD

**Issue by techcontributor** [libredirect/libredirect#232]
LibRedirect already has redirects for libre services such as [Odysee and Peertube](https://github.com/libredirect/libredirect/issues/78). So I thought it would be fitting to also add [Pinafore](https://github.com/nolanlawson/pinafore). Pinafore is a Mastodon front-end focused on speed and simplicity in a similar sense simpleertube and librarian are.

**Comment by EdwardLangdon** [comment]
I think it is better to use the Official Frontend.

**Comment by ManeraKai** [comment]
How will it redirect without an account?

**Comment by EdwardLangdon** [comment]
Pinafore is a Web client for Mastodon not a Private frontend like SimplerTube for PeerTube and Librarian for Odysee. 

We can add Pinafore if it acts like Invidious for YouTube, But it isn't, It's just a Client, Doesn't add any Privacy, More attack surface as you don't use the Web Frontend provided by your Instance instead a Third Party one.

Private Frontend and Web Client are different things to consider. I am pretty sure, We are not gonna add it.

**Comment by ManeraKai** [comment]
@IronMaltese:
![image](https://user-images.githubusercontent.com/40805353/166487745-359cd7e9-c1bb-4a3d-8f1e-fe59a427c705.png)

**Comment by ManeraKai** [comment]
Here are the apps that use mastodon, there are web apps, android, and even desktop apps: https://joinmastodon.org/apps

**Comment by IronMaltese** [comment]
The only real use case I can think of is if someone has a really slow internet connection and wants to use a lightweight mastodon client, this should definitely be off by default if it's added

**Comment by ManeraKai** [comment]
@IronMaltese xDD:
![image](https://user-images.githubusercontent.com/40805353/166523707-4b0725ba-1003-4c03-be7a-a4ff4fd9c508.png)

**Comment by ManeraKai** [comment]
@techcontributor The urls are so much different. It's a whole separate web app than Mastodon's web app:
Mastodon: https://noc.social/web/@risc_v
Pinafore: &nbsp;&nbsp;&nbsp;https://pinafore.social/accounts/114943
It'll be as complex as adding another frontend to google maps.

As @EdwardLangdon said, It's so much different compared to what Simpleertube and Librarian are.

Will not add this one. But I really liked Quetre :)

**Comment by IronMaltese** [comment]
Quetre is gonna be a great addition :) also despite this frontend not being added, it uses svelte and that's pretty cool🦭
