### ISSUE TITLE
Expanding setting preferences to all front-ends

### ISSUE THREAD

**Issue by ghost** [libredirect/libredirect#234]
Having a settings page for redirections is really useful if you like to use multiple instances and want a consistent experience. The following service redirections don't have this functionality or have it in a limited way:
- YouTube Music
- Instagram
- TikTok
- Reddit
- Pixiv
- Wikipedia
- Translate (SimplyTranslate already has this, but Lingva does not)
- Maps (both FacilMap and OpenStreetMaps don't have this)

**Comment by ManeraKai** [comment]
you mean the same settings like Invidious and Nitter have?

**Comment by ManeraKai** [comment]
will that would bee a looong issue xD.

**Comment by IronMaltese** [comment]
I would just like to see settings for lingva :3

**Comment by ManeraKai** [comment]
No don't worry, I'll do all of them. This is necessary for LibRedirect.

**Comment by ManeraKai** [comment]
Thinking of doing this: https://github.com/libredirect/libredirect/issues/193#issuecomment-1121823134
This will almost instantly close this issue

**Comment by IronMaltese** [comment]
I  honestly agree, since that's a lot more easy to maintain and won't affect user experience

**Comment by ManeraKai** [comment]
I'll add the button in the popup like this:
![Screenshot_20220515_134636](https://user-images.githubusercontent.com/40805353/168468963-8eb4047c-acbc-4a28-890e-aab99678d25b.png)
Pressing it will copy the settings from the current opened website to all the others. It won't be in the settings.

**Comment by ManeraKai** [comment]
- [ ] YouTube
- [x] Twitter
- [ ] Instagram
- [x] TikTok
- [x] Reddit
- [x] Search
- [ ] Translate
- [x] Wikipedia

**Comment by EdwardLangdon** [comment]
What does Unify Settings do ?

**Comment by ManeraKai** [comment]
No it's for all frontends now. There's no settings page for invidious, piped, nor any other frontend. Just settings for redirections.

**Comment by ManeraKai** [comment]
Invidious settings are like this now:
![image](https://user-images.githubusercontent.com/40805353/169317507-f2e6b22d-7b79-4025-a695-c4cb7803f9a9.png)

**Comment by IronMaltese** [comment]
That makes sense, I'm glad there's an easily maintainable way to replace the previous settings page for LR now, great work on this😁
