### ISSUE TITLE
Add LibreX

### ISSUE THREAD

**Issue by ghost** [libredirect/libredirect#238]
LibreX is a selfhostable search engine that is privacy focused. More information about the project here: https://github.com/hnhx/librex

**Comment by IronMaltese** [comment]
I really like this project! It's simple and minimalist, if this is added I'll definitely start using it

**Comment by ManeraKai** [comment]
what does it differ from something like searXNG?

**Comment by IronMaltese** [comment]
> what does it differ from something like SearXNG?

The interface is so much simpler as well as settings too

**Comment by IronMaltese** [comment]
@hnhx This should all be explained in the read.me since I didn't even know it filtered google results, also great job on the project, it looks great!😄

**Comment by ManeraKai** [comment]
Added by this PR: https://codeberg.org/LibRedirect/libredirect/pulls/8
