### ISSUE TITLE
Imgur => Rimgo

### ISSUE THREAD

**Issue by TheFrenchGhosty** [libredirect/libredirect#24]
https://codeberg.org/video-prize-ranch/rimgo

**Comment by ManeraKai** [comment]
@alefvanoon You told me about this one I think

**Comment by alefvanoon** [comment]
Yes, I'm waiting for an answer to this issue.

**Comment by ManeraKai** [comment]
What happened to the original [rimgu](https://codeberg.org/3np/rimgu)?

**Comment by TheFrenchGhosty** [comment]
@ManeraKai the project is unmaintained, this is an hard-fork/rewrite of it, in Go.

**Comment by ManeraKai** [comment]
Is there any problem facing with this implementation for rimgo?
