### ISSUE TITLE
Import Settings tool not working

### ISSUE THREAD

**Issue by mojo-jojo-7** [libredirect/libredirect#242]
I exported settings from one browser where I manually set everything and then imported it in another (both of them firefox) but no settings are changed

**Comment by EdwardLangdon** [comment]
I can confirm this for myself. Same setup as @mojo-jojo-7.

Tried Importing settings. It didn't work. It also doesn't work after reinstalling and trying to import after resetting settings.

Tried this on Firefox 100.0.1

**Comment by EdwardLangdon** [comment]
@ManeraKai Before making a New Release, You should fix this.
