### ISSUE TITLE
DuckDuckGo as redirect option?

### ISSUE THREAD

**Issue by mojo-jojo-7** [libredirect/libredirect#243]
Is it possible to add DDG as an option to redirect to alongside searx, etc? Afaik, privacy redirect had it. Is there a reason why it was removed? Thanks!

P.S. How about Brave Search as an option would be cool as well? It's turning out to be a quite nice search engine

**Comment by ManeraKai** [comment]
You can just set DDG as your default search engine.

Brave Search has an extension for Firefox that adds it as a custom search engine.
