### ISSUE TITLE
Make instance URLs clickable

### ISSUE THREAD

**Issue by mizzunet** [libredirect/libredirect#244]
![image](https://user-images.githubusercontent.com/10193999/167052711-eca1af49-e1da-41e3-8b50-afaf0cde1723.png)

 I personally would like this feature. This would simply be possible by setting `href` attribute.

 Currently, I copy-paste it.

What do you think?

Thanks for your great work (:

**Comment by ManeraKai** [comment]
tbh that's a really nice idea! Added it!
