### ISSUE TITLE
Settings Menu Frezes when adjusted Nitter Settings.

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#245]
Settings Menu becomes sluggish, often freezing, when adjusting Nitter Settings, including Cookies and preferred instances.

This does not happen when adjusting Invidious Settings.

Tested on Windows and Android Firefox.

**Comment by pidus** [comment]
Can confirm. Happens in Android Firefox Nightly. Android 11.

**Comment by ManeraKai** [comment]
This sluggishness" has been improved a lot in the latest versions. Still didn't release them

**Comment by MintMain21** [comment]
Well I'm looking forward to when they do release.

**Comment by ManeraKai** [comment]
I'm slowing releases down as updating LibRedirect seems to break it every time.
