### ISSUE TITLE
nitter.nixnet.services  login prompt on Firefox (for no reason).

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#248]
I do not have a Nitter Account on any instance, and yet I seem to get periodic pop-ups requesting I sign in to https://nitter.nixnet.services. This typically happens when testing the latency of Nitter Instances, but can also happen at unrelated points.

**Comment by ManeraKai** [comment]
Just uncheck it. I still didn't implement a way to cancel instances that require authentication as it's only this instance.

**Comment by MintMain21** [comment]
This happens even when that instance is unchecked. 

Perhaps it would be reasonable to remove it outright from a future release?

**Comment by ManeraKai** [comment]
I will add a way to uncheck instances that require authentication as I did with instances that use cloudflare. They're unchecked by default.
