### ISSUE TITLE
Improvements for "Test Instance Latency"

### ISSUE THREAD

**Issue by kartikynwa** [libredirect/libredirect#249]
I don't have knowledge of JavaScript so feel free to correct me if I have made any wrong assumption.

Had two suggestions for improvement:

1. Use async magic to make several requests in parallel. Currently according to my observations, all the requests are made synchronously/
2. Add ability to unmark instances which do not send a 200 response (or whatever you expect there).

Thoughts?

**Comment by ManeraKai** [comment]
I did them synchronously to not bottleneck each other. If the instance had some error, then you won't see a latency number on it. Though I could add a warning that this one isn't working like the timeout 5000ms+ warning.

**Comment by kartikynwa** [comment]
> Though I could add a warning that this one isn't working like the timeout 5000ms+ warning.

Yeah this would be nice.
