### ISSUE TITLE
how to remove parameters added at the end of url

### ISSUE THREAD

**Issue by rezad1393** [libredirect/libredirect#25]
I had this issue with the last addon with addon adding parameters to the ulr and there was no way to remove them
https://github.com/SimonBrazell/privacy-redirect/issues/162

basically once a user touch any setting in the youtube redirect section for parameters they get added to urls and there is no way to remove them and there is no way to reset the addon so if in the pristine addon installation the audio volume was 50 and user changes that to 51 then there will be a parameter added to urls of youtueb (even playlist or searches) and moving the audio option back to 50 doesnt remove that.

**Comment by ManeraKai** [comment]
So you want a reset button?
BTW, the reason behind adding those parameters is to keep consistency user experience across all the instances, but your feature isn't hard to add.

**Comment by rezad1393** [comment]
> So you want a reset button? BTW, the reason behind adding those parameters is to keep consistency user experience across all the instances, but your feature isn't hard to add.

I understand the reason behind it and it is a great feature , but once I change anything then that gets stuck added to end of urls and messes with a lot of urls.

maybe add a third option called "default" or "original" that just remove the parameters (I think the theme (dark light) has that)

and thanks for this addon and for carrying the torch.

**Comment by ManeraKai** [comment]
> if you mean that they would not get added to urls then that is correct.

yeah I meant that, the `reset` name isn't that correct, maybe `clear settings` or `orignal` or a delete button besides every setting will be a better design way.

> and thanks for this addon and for carrying the torch.

🚀

**Comment by ManeraKai** [comment]
?
![image](https://user-images.githubusercontent.com/40805353/152636548-8b18ed84-0484-4d1e-803d-698acfd050f0.png)

**Comment by ManeraKai** [comment]
There's a `True`,`False` and `Default` on switches now
