### ISSUE TITLE
Old Reddit: Redirects for Gallery links

### ISSUE THREAD

**Issue by 0lhi** [libredirect/libredirect#250]
Here's an example for a Gallery:

https://www.reddit.com/gallery/qnjjvh

Replacing www with old does not work:

https://old.reddit.com/gallery/qnjjvh

But this does:

https://old.reddit.com/r/OnePiece/comments/qnjjvh

Additional info:

*Old Reddit Redirect* had the same issue, but was fixed at https://github.com/tom-james-watson/old-reddit-redirect/issues/60.

**Comment by ManeraKai** [comment]
No need for it to be in the extension as there's already the extension you mentioned. Old Reddit got removed and will not show in the next release.
