### ISSUE TITLE
Instagram Reels links broken + how to fix it 

### ISSUE THREAD

**Issue by AnonWombat** [libredirect/libredirect#251]
LibRedirect doesn't open Instagram Reels links properly, but it's an easy fix!

Let's say you click on this Instagram link:
https://www.instagram.com/reel/CdEe0i6AHFF/?igshid=YmMyMTA2M2Y=

The redirect *should* take you to the following link that works properly:
https://bibliogram.pussthecat.org/p/CdEe0i6AHFF

Instead, the redirect takes you to a link that doesn't work:
https://bibliogram.pussthecat.org/p/reel/CdEe0i6AHFF

The issue seems to be that LibRedirect does not strip the /reel/ part from the link.

**Comment by ManeraKai** [comment]
Thanks!

**Comment by AnonWombat** [comment]
> Thanks!

Thanks for making the change!
:)
