### ISSUE TITLE
Instance lists not visible in Brave

### ISSUE THREAD

**Issue by mojo-jojo-7** [libredirect/libredirect#253]
I followed the steps to manually install the extension on Brave, but after installing, the default list of instances for each module is empty, or so it seems. The redirection itself works fine as far as I can tell, but I am not able to pick and choose instances. Manually added instances don't appear in the list either.

Brave version: 1.37.111
Extension version: 1.7.0

**Comment by ManeraKai** [comment]
Does resetting and reinstalling it help any?

**Comment by IronMaltese** [comment]
I had the same problem and it doesn't

**Comment by IronMaltese** [comment]
Checking latency of each instance brought them back though

**Comment by ManeraKai** [comment]
one minute. Are you installing directly from the source code?

**Comment by foldfree** [comment]
Same issue on chromium 90.x (debian) with the .crx binary.

It's not specific to Brave.

**Comment by EdwardLangdon** [comment]
Now, I agree with all other fellows, I have the same Issue.

Using Microsoft Edge Version 101.0.1210.47 on Windows 11

**Comment by ManeraKai** [comment]
I've modified the code a lot and now stuck in adding a feature and can't release a new version. I'll do as soon as possible though.

**Comment by IronMaltese** [comment]
> I've modified the code a lot and now stuck in adding a feature and can't release a new version. I'll do as soon as possible though.

No prob, it's not a major bug
