### ISSUE TITLE
Add Librarian instances to redirect Odysee

### ISSUE THREAD

**Issue by sonalder-darlene** [libredirect/libredirect#255]
Librarian is a LBRY/Odysee private front-end and I think LibRedirect users could benefits from as Odysee is not really privacy friendly but is gaining popularity for users that want to escape from YouTube monopoly.

The official git : https://codeberg.org/librarian/librarian

**Comment by IronMaltese** [comment]
This is already implemented in Libredirect, you just need to enable it in settings :)

**Comment by sonalder-darlene** [comment]
Why it isn't on the extensions shortcut ? only in the settings

**Comment by EdwardLangdon** [comment]
For that you need to tick the Checkbox in Customize Popup in General Settings. Like this : 

![image](https://user-images.githubusercontent.com/101938856/167654748-f7ed7310-5a05-40ee-8342-cc532cb963c0.png)
![image](https://user-images.githubusercontent.com/101938856/167654748-f7ed7310-5a05-40ee-8342-cc532cb963c0.png)

This is How you need to enable it in Popup.

@ManeraKai Apart from Technical FAQ, I think we need to some things based on usability too, I think.

**Comment by EdwardLangdon** [comment]
I am closing this issue, As you can understand from the above Pictures.
