### ISSUE TITLE
Implement numblr and tumbex (alternative front-ends to Tumblr).

### ISSUE THREAD

**Issue by Impeta** [libredirect/libredirect#256]
(my first ever issue into this repository, so apologizes for any incoming mistakes of mine :sweat_smile:)
This one seems pretty promising, though the author hasn't ever put out a working instance or two of it, and I haven't gotten the faintest idea on building it.
https://github.com/heyLu/numblr

There's also tumbex, but I don't think it's open source, much less really intended as private and insusceptible to spying.
https://www.tumbex.com/

**Comment by ManeraKai** [comment]
are there any instances in the first place?

**Comment by EdwardLangdon** [comment]
@ManeraKai We shouldn't add Tumbex as it is just like PixivMoe for Tumblr.

See the analytics it uses :

![image](https://user-images.githubusercontent.com/101938856/173212479-55a48375-d8de-4f9f-9905-1c98481e3f0c.png)

**Comment by ManeraKai** [comment]
@Impeta please add some instances and then reopen this issue.
