### ISSUE TITLE
Wrong title in YouTube redirecting settings

### ISSUE THREAD

**Issue by m-koushan** [libredirect/libredirect#257]
In YouTube redirecting settings when you select Invidious Frontend and Enable custom settings, If you go down you can see we have two options that are not same but their name are exactly like each other

![image](https://user-images.githubusercontent.com/50526840/168113658-3e4f919a-4e0e-4ae9-a271-0c945f949ab3.png)

I think the second one (according to the picture) is for comments 
Version: 1.7.0
Browser: Ungoogled Chromium Version 100.0.4896.60 64bit

**Comment by ManeraKai** [comment]
All those settings have been deleted to a better solution https://github.com/libredirect/libredirect/issues/234#issuecomment-1124015246

**Comment by ManeraKai** [comment]
Because I'm still working on this feature.

**Comment by IronMaltese** [comment]
@ManeraKai the option to save cookie preferences between instances should be in general LR settings instead of for each frontend and clearing cookies should not affect this, since this would be a useless feature for browsers like Tor otherwise

**Comment by ManeraKai** [comment]
I will make it persistent in a way but won't put it in the general tab as you should select an instance first to copy from. Like this doesn't relate to the general tab.
