### ISSUE TITLE
Add-on not performing redirects

### ISSUE THREAD

**Issue by Bob131** [libredirect/libredirect#262]
None of the redirects seem to be working since v1.6.3. Downgrading to v1.6.2 makes things work again.

**Comment by EdwardLangdon** [comment]
What Browser are you using and Platform ?

The Newest Addon Version is [1.7](https://github.com/libredirect/libredirect/releases/tag/v1.7.0)

Try updating the addon.

**Comment by Bob131** [comment]
> What Browser are you using and Platform ?

Firefox 100 on Fedora

> The Newest Addon Version is [1.7](https://github.com/libredirect/libredirect/releases/tag/v1.7.0)
> 
> Try updating the addon.

"Since v1.6.3" includes v1.7

**Comment by Bob131** [comment]
The problem is https://github.com/libredirect/libredirect/commit/d731d94a2d7761e6fea7f061d6dd13cfa4f380d5#diff-901f07e86a3ce9b05bc0354b70b97cf6e0b57dd3b3f7b80e6893d38cfccc478fR480. When https://github.com/libredirect/libredirect/commit/d731d94a2d7761e6fea7f061d6dd13cfa4f380d5#diff-901f07e86a3ce9b05bc0354b70b97cf6e0b57dd3b3f7b80e6893d38cfccc478fR466 is hit and the stored redirects were generated before the searxng split, `redirects.searxng` is undefined and the init function raises an exception, preventing the redirect handlers in `background.js` from ever getting registered.

**Comment by ManeraKai** [comment]
The code has changed A LOT since 1.7. Wait till version 2.0 and it will be fixed hopefully.
