### ISSUE TITLE
piped does not load youtube embedded video in the same page using Firefox

### ISSUE THREAD

**Issue by lucamp** [libredirect/libredirect#263]
Hi,
piped does not load youtube embedded video in the same page. No issue with invidious redirect.

For example, look the embedded video in the middle of this page
https://www.bufale.net/ammissione-in-diretta-tv-della-modifica-del-clima-e-ufficiale-tra-complottismo-e-disinformazione/

User needs to click "open site in new windows" to make it works.

I already removed and reinstalled libredirect, issue still present. 

Firefox 91.9.0esr (debian)
libredirect 1.7.0

Thanks
Luca

screenshot:
![Screenshot 2022-05-15 at 22-52-03  Ammissione in diretta TV della modifica del clima, è ufficiale tra complottismo e disinf](https://user-images.githubusercontent.com/15078341/168493313-1ee8db9e-80be-4f74-9c34-b8002aaa67dc.png)

**Comment by ManeraKai** [comment]
I think this is a similar problem that happened with Nitter instances where they have an http header that doesn't allow the site to be embedded.

Can you test the official instance and see if it works?
https://piped.kavin.rocks/

**Comment by lucamp** [comment]
> Can you test the official instance and see if it works? https://piped.kavin.rocks/

With official instance there is no issue. Do you mean that the issue is from a specific instance and I should open a bug there since it is not related with piped version?

**Comment by EdwardLangdon** [comment]
@datanomi Thanks to tell about it.

Are there any Encrypted form of ways to Contact you ?

**Comment by ManeraKai** [comment]
This also happened wit Nitter instances. I can't though tell all the instances maintainers so I made a function that removes the X-frame header as @datanomi  said: https://github.com/libredirect/libredirect/blob/98ade913c622623c241f581d665497a430228de6/src/assets/javascripts/helpers/twitter.js#L119-L135
I think I'll do the same with piped instances.

**Comment by datanomi** [comment]
> @datanomi Thanks to tell about it. Are there any Encrypted form of ways to Contact you such as Instant Messaging ?
> 
> I can confirm, it is fixed in the website @lucamp mentioned.

I've got XMPP on m@mha.fi and Signal on [+358414712199](tel:+358414712199)

**Comment by EdwardLangdon** [comment]
@datanomi XMPP is not Secure or Encrypted either. Data is stored in Plain Text in your Own Homeserver. I also cannot use Signal.

I will contact you via mail using PGP. I found your Website.

**Comment by EdwardLangdon** [comment]
@datanomi Is this what you see when using your Instance via Libredirect ?

![image](https://user-images.githubusercontent.com/101938856/173566553-32928416-84f1-4637-a1bc-3bef0f2ecf87.png)

Your Instance only does this on embeds not others.

**Comment by EdwardLangdon** [comment]
@datanomi Is this what you see when using your Instance via Libredirect ?

![image](https://user-images.githubusercontent.com/101938856/173566553-32928416-84f1-4637-a1bc-3bef0f2ecf87.png)

Your Instance only does this on embeds not others.

**Comment by datanomi** [comment]
> @datanomi Is this what you see when using your Instance via Libredirect ?
> 
> ![image](https://user-images.githubusercontent.com/101938856/173566553-32928416-84f1-4637-a1bc-3bef0f2ecf87.png)
> 
> Your Instance only does this on embeds not others.

Yeah, happens for me too. I'll look in to it.

**Comment by datanomi** [comment]
Fixed.

**Comment by EdwardLangdon** [comment]
I can confirm that. But what caused the issue and why was it happening ?

**Comment by datanomi** [comment]
> I can confirm that. But what caused the issue and why was it happening ?

Seems like after watchtower does a update to Piped, all containers related to Piped will need to be restarted too, otherwise problems may occur.
