### ISSUE TITLE
Redirecting from bypassed links doesn't redirect

### ISSUE THREAD

**Issue by CloverBadland** [libredirect/libredirect#264]
This issue doesn't exist in PrivacyRedirect.

<table>
  <tr>
    <th>With LibRedirect</th>
    <th>With PrivacyRedirect</th>
  </tr>
  <tr>
    <td>

https://user-images.githubusercontent.com/86160566/168620150-08fd0ffc-9c57-4f62-985c-37585791ba0b.mp4

</td>
<td>

https://user-images.githubusercontent.com/86160566/168620291-13706426-ba31-4027-87cf-a372dd53811f.mp4

</td>
  </tr>
</table>

**Comment by ManeraKai** [comment]
Take a screenshot of YouTube's settings page.

**Comment by EdwardLangdon** [comment]
I think you need to off the Bypass Function, Try this -

![image](https://user-images.githubusercontent.com/101938856/168626688-6634df46-6fa0-46ad-bea6-12fb677811ac.png)

I am sure it helps. So, Close the issue if it does.

**Comment by ManeraKai** [comment]
it should be on not off. btw I removed this option as it confused a lot of people and it's on by default and hard coded.

**Comment by EdwardLangdon** [comment]
Sorry, I misthought.

**Comment by CloverBadland** [comment]
![01](https://user-images.githubusercontent.com/86160566/168627359-7ed139e6-3d32-4ec0-b698-4d6d0414e443.png)

**Comment by ManeraKai** [comment]
one minute. It neither should be on or off. It's like this as I disable all redirections for that tab as it gives some problems without doing this. If you want redirections to work again. Then open a new tab.

**Comment by EdwardLangdon** [comment]
I thought, I was wrong, You sort of confused me.

@CloverBadland Please turn off the Bypass Function and try it for YouTube and Twitter. Sorry for the confusion, By the way.

**Comment by CloverBadland** [comment]
> one minute. It neither should be on nor off. It's like this as I disable all redirections for that tab as it gives some problems without doing this. If you want redirections to work again. Then open a new tab.

This is what I mean. It should redirect regardless of the bypass option.

**Comment by CloverBadland** [comment]
OK. I just wanted to point out that behavior.
