### ISSUE TITLE
Microsoft Edge says "This extension has malware"

### ISSUE THREAD

**Issue by charichard08** [libredirect/libredirect#269]
My Edge browser just disabled the extension because it detected malware. You can't view it in the store now either. It's still up on Firefox though. I should honestly just switch back to Firefox and ditch Micropenis though

Screenshots:
https://i.imgur.com/ZtswSa2.png
https://i.imgur.com/tJUXo8n.png

**Comment by SilentSkies** [comment]
It's also been removed from the Edge add-ons storefront 
![image](https://user-images.githubusercontent.com/23584592/169524261-df551eb0-5372-4f25-b1ad-a57542720a7d.png)

**Comment by ManeraKai** [comment]
Yeah they sent me a message about that too. I'll see whats wrong with it.

**Comment by ManeraKai** [comment]
They're saying they sent more details in another email but I still didn't receive it, waiting....

**Comment by wadbr** [comment]
I noticed some of the instances' domains were expired and were redirecting to random ads filled 'Buy this domain for very cheap only costs your first born's soul' or something, maybe that's the issue?

**Comment by EdwardLangdon** [comment]
Might be the cause, But it should be maintained by the Maintainers of the project.

**Comment by EdwardLangdon** [comment]
I think Kai, If MS ask for evidence may be link this issue.

**Comment by wadbr** [comment]
Any update on this? @ManeraKai

**Comment by ManeraKai** [comment]
I will update on 2.1

**Comment by EdwardLangdon** [comment]
You mean, you will release for v2.1 ?

Any replies yet ?

**Comment by ManeraKai** [comment]
Nothing, they just replied with an email that they are reviewing it but nothing else.

**Comment by Mennaruuk** [comment]
Still the case in September 2023:
![OnPaste 20230922-022044](https://github.com/libredirect/browser_extension/assets/52135169/add64374-ba86-47bb-9cbb-57d381e5af2f)

Anything new @ManeraKai ?

**Comment by ManeraKai** [comment]
Nope.
