### ISSUE TITLE
Add the ability to search through Instances

### ISSUE THREAD

**Issue by EdwardLangdon** [libredirect/libredirect#270]

**Comment by EdwardLangdon** [comment]
I mean the Total Instances list in Libredirect

**Comment by ManeraKai** [comment]
Just press CTRL+F

**Comment by EdwardLangdon** [comment]
Well, I know that and can do that, But I mean I want to do in Total such as, If I type, 'kavin.rocks' it shows all instances from other frontends too.

**Comment by ManeraKai** [comment]
so you mean you trust only one server and you want to use it across all frontends.
