### ISSUE TITLE
Support map redirects for sites using deprecated Google Maps JavaScript API v2

### ISSUE THREAD

**Issue by prettyv** [libredirect/libredirect#271]
As found on e.g. `https://ipres2022.scot/`, there are still sites using the old long since deprecated Maps JS API v2 as the iframe src, which redirects to a Embed API URL when specified in the `output` query parameter (here: `https://maps.google.com/maps?q=99%20George%20St%2C%20Glasgow%20G1%201RD&t=m&z=14&output=embed&iwloc=near`).

Maybe support for this form could be added to the maps helpers for better backwards compatibility. As is this triggers the fallback handling and tries to use the `/search` path for OpenStreetMap which doesn't work as `www.openstreetmap.org/search` currently returns a `x-frame-options: sameorigin` header.  Also the base URL for OpenStreetMap should be changed to include the `www` to save an unnecessary redirect.

**Comment by ManeraKai** [comment]
But in this page it's saying that it will no longer be working as of May 26, 2021, what?!

**Comment by EdwardLangdon** [comment]
Google Maps APIv2 doesn't even work any more.
