### ISSUE TITLE
Redirect doesn't work with Cloudflare Libreddit instances

### ISSUE THREAD

**Issue by Dyras** [libredirect/libredirect#276]
Hello. Please see the picture, it's easier than explaining:
![image](https://user-images.githubusercontent.com/12563436/169989826-9f2785c1-a597-4f76-833e-c1c114d2cd03.png)

Basically, I think Libredirect should notice the error 1033 and then try sending you to another Libreddit instance.

**Comment by ManeraKai** [comment]
There are ton of errors for Cloudflare ranging from 10XXX, 1XXX, 5XX as in this page: https://support.cloudflare.com/hc/en-us/sections/200820298-Cloudflare-Errors

I think I'll just make it as 500+. It was like that before but I made it to just some errors as it got crazy sometimes, though we have now a limit to only 5 auto redirections before stopping and not sticking in an infinite loop.

**Comment by anon238** [comment]
Afaik this should be fixed with Decentraleyes.

**Comment by EdwardLangdon** [comment]
What do you mean ?

**Comment by anon238** [comment]
> What do you mean ?

This was towards OP. Since I use that extension I’m never on a Cloudflare page tbh.

**Comment by ManeraKai** [comment]
btw cloudflare instances are unchecked by default now. So you won't get redirected to them in the first place unless you recheck them.
