### ISSUE TITLE
Bring Back Blocking Bypass in v2.0

### ISSUE THREAD

**Issue by EdwardLangdon** [libredirect/libredirect#277]
As of Version 2.0 in Libredirect, The Functionality of Blocking Bypass request such as `Watch on YouTube`, `Read on Reddit/Twitter` in the Frontends are removed, **Block Bypass function** in each Frontend do as the title says, Blocks bypassing Libredirect and Loading Offical Site.

Do you want the Function back or not ?

**Comment by peewoper** [comment]
Yes, by clicking those kind of buttons you explicitly say, that you want to visit the official website.

**Comment by ManeraKai** [comment]
@EdwardLangdon you're rephrasing confused me and everyone xD.

He wants to bring the toggle back to be able to not go to the official site rather be redirected again to another instance. By default it redirects you to go to the original site.

This function for redirecting to other instance is already replaced by the "change instance" button. So really not that important and having that toggle just under the code is much better for less confusion as many asked me about what does this setting do?

**Comment by EdwardLangdon** [comment]
If I wrote it wrongly, Then edit yourself, Kai.

>as many asked me about what does this setting do?

Why haven't you wrote about it in the FAQ ?

**Comment by ManeraKai** [comment]
> If I wrote it wrongly, Then edit this issue yourself in clear way, Kai.

👍️

> Why haven't you wrote about it in the FAQ ?

Because I start rethinking of the worthiness of the feature and resolved to what I now have said above.

**Comment by ManeraKai** [comment]
Will close the issue as @EdwardLangdon has finally agreed on it not being useful.
