### ISSUE TITLE
Redirect youtube-nocookie.com

### ISSUE THREAD

**Issue by sebastien46** [libredirect/libredirect#279]
youtube embeds coming from youtube-nocookie.com aren't being redirected, is there any particular reason this is occurring or is this fixable ?

**Comment by ManeraKai** [comment]
You sure? They are in the regex: https://github.com/libredirect/libredirect/blob/5abfe6f9f17bb1b46d4aca19e4daed359b4d761c/src/assets/javascripts/helpers/youtube/youtube.js#L17

**Comment by ManeraKai** [comment]
Hello?

**Comment by xfzv** [comment]
I'm having the same issue lately (Firefox / Libredirect version: 2.0.0).

The redirection works fine when entering a [youtube-nocookie embed](https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ) link in the address bar directly, but if the youtube-nocookie player is embedded in a web page, all I see is a black frame. After disabling Libredirect for YouTube and refreshing the page, the regular embedded YouTube player loads.

Tested on a default Firefox profile just to make sure mine wasn't the culprit.

**Comment by ManeraKai** [comment]
Turned out it was a typo: https://github.com/libredirect/libredirect/blob/v2.0.0/src/pages/background/background.js#L141

It should be
```js
if (!response) response = youtubeHelper.removeXFrameOptions(e)
```

**Comment by xfzv** [comment]
Still broken for me after updating to 2.1.0.

**Comment by ManeraKai** [comment]
give me a link where it's not working.

**Comment by xfzv** [comment]
https://deathgrind.club/posts/75872

And basically any embedded youtube-nocookie.com video on this website. Click on "View YouTube video" to show the embedded player.

![image](https://user-images.githubusercontent.com/78810647/173113039-7c3b1467-c685-493b-8d70-0705a22a38f0.png)

I can reproduce with my main Firefox profile as well as a fresh profile.

I don't know why but it works fine on my Android phone with Mull (101.2.0) and Libredirect 2.1.0 too (both mobile and desktop version of the website):

![image](https://user-images.githubusercontent.com/78810647/173113325-1ff282e6-b0d9-4cfd-a881-5bbe8d8014aa.png)

**Comment by ManeraKai** [comment]
It's a problem with security policy, I think I should now start modifying sites to accept invidious URLs too.

**Comment by ManeraKai** [comment]
Finally! Fixed this issue! It has been a problem for a long time and some people before you have mentioned it.

**Comment by sebastien46** [comment]
Hello again, although the issue now seems fixed, i think webpages still connect to youtube-nocookie.com, is that normal behaviour with Invidious ? ( seen on https://www.zoho.com/fr/crm with Invidious embed redirect)

**Comment by ManeraKai** [comment]
I think it states that it sent a request to youtube-nocookie.com but got a response from an invidious instance.

**Comment by sebastien46** [comment]
Alright then, have a nice one, also sorry for not replying earlier, I wasn't able to connect to my github account for some time.

**Comment by p1gp1g** [comment]
I still get CSP issues. For instance with wire (app.wire.com) and nextcloud news

**Comment by nickelswitte** [comment]
I also still have this issue. E.g. on reddit.com it is not being redirected. Is there anything that needs to be configured to make this work?
