### ISSUE TITLE
Instagram redirect

### ISSUE THREAD

**Issue by silverwings15** [libredirect/libredirect#28]
Hi, would it be possible to add https://imginn.com/ as an alternative Instagram frontend? Public Bibliogram instances are not very useful because they are all rate limited and you can't go back and view old posts.

Thanks for reading

**Comment by ManeraKai** [comment]
Doesn't it use the same api?

**Comment by silverwings15** [comment]
Yes it also uses the same Instagram public API, but for some reason it isn't rate limited and you can view older posts past the first page of results. out of the 4 bibliogram instances listed on https://farside.link/, only one (https://bibliogram.1d4.us/) is not rate-limited. The rest return the following error

502

Blocked by Instagram

Instagram is refusing to provide data to this server.
This server will only be able to load the first page of timelines.
This error is permanent.
[See here for more information.](https://lists.sr.ht/~cadence/bibliogram-announce/%3C20201218014302.855fa8a816be2f19da2f56e3%40disroot.org%3E)

**Comment by ManeraKai** [comment]
> [See here for more information.](https://lists.sr.ht/~cadence/bibliogram-announce/%3C20201218014302.855fa8a816be2f19da2f56e3%40disroot.org%3E)
I think I read that before. That's unfortunate. Wouldn't the same thing happen to https://imginn.com/ though?

**Comment by silverwings15** [comment]
it's definitely a strong possibility, but right now it works well so i'm just enjoying it. the main value add for me is the inclusion of a download button, makes grabbing media off the site a lot more straightforward. anyway it's just a friendly suggestion, decision is totally up to you. thanks for your time!

**Comment by ManeraKai** [comment]
I think bibliogram can become functional if more instances are added that are from people's homes as the blog said. That way blocking of the ip's from that region will be unlogical as there's other people living there.
I might add my home server instance: https://manerakai.asuscomm.com:450/

**Comment by ManeraKai** [comment]
Was a small typo.

**Comment by silverwings15** [comment]
awesome thank you!
