### ISSUE TITLE
Why does Libredirect add a cookie for every single instance listed?

### ISSUE THREAD

**Issue by SkMyPP** [libredirect/libredirect#280]
I was clearing out my cookies when I started noticing a bunch of websites I have never heard of & never even visited in the first place.
Turns out that all of them are from every single instance that's listed on the addon.

It's completely unacceptable to store such an obscene amount of cookies. Is there a setting to prevent cookies form every single instance to be stored?

**Comment by ManeraKai** [comment]
This was fixed in and will publish it in the upcoming release. It only now adds cookies for the selected instances and protocol only.
