### ISSUE TITLE
Cannot remove Libredirect from default search engines on Firefox.

### ISSUE THREAD

**Issue by SkMyPP** [libredirect/libredirect#281]
Every time I remove Libredirect from the default search engines on FIrefox, it always comes back after restarting the browser.

Personally, I don't even think it should be there in the first place. I can't think of a single good reason it should even be listed as a search engine shortcut to begin with.

**Comment by ManeraKai** [comment]
which version are you running?

**Comment by EdwardLangdon** [comment]
Well, I have the same issue on Firefox v100.0.2

**Comment by ManeraKai** [comment]
one minute, you want to select another search engine or to remove it all from the list?

**Comment by EdwardLangdon** [comment]
He means, He just want to remove Libredirect from the list of search engines in Firefox. If he did, It reappears. He don't like that behaviour.

Kai, To answer you - `to remove it all from the list`

**Comment by ManeraKai** [comment]
I see, so there's nothing wrong with it. LibRedirect is a search engine or rather a proxy to connect to multiple SearXNG, SearX, Whoogle instances.
