### ISSUE TITLE
Reddit is not persistent

### ISSUE THREAD

**Issue by anon238** [libredirect/libredirect#282]
Some of the redirects used randomly instances while I configure them to use only one, but it’s ignoring that. Any tips on this? By the way. Love the app. Thanks!

**Comment by EdwardLangdon** [comment]
We are about to release v2.0 today or tomorrow which will fix most of the things.

By the way, I am using v1.7.0 on Firefox 100.0.2. I don't face such issues.

I would suggest you to export settings and uninstall the extension, Restart Firefox and Install the extension and import your settings.

or You can wait.

**Comment by anon238** [comment]
> We are about to release v2.0 today or tomorrow which will fix most of the things.
> 
> By the way, I am using v1.7.0 on Firefox 100.0.2. I don't face such issues.
> 
> I would suggest you to export settings and uninstall the extension, Restart Firefox and Install the extension and import your settings.
> 
> or You can wait.

Great news! I can’t use Firefox as it’s extremely hungry for CPU. I’m on a Chromium browser.

**Comment by EdwardLangdon** [comment]
Well, Using Libredirect on Chromium has many errors and bugs reported which has been fixed. You can try v2.0 within couple of hours.

>I can’t use Firefox as it’s extremely hungry for CPU

I presume it's for your CPU because it's the reverse for my Device. Browser wars aside. I am closing this issue as v2.0 will fix things. You can reply on this issue though.

**Comment by anon238** [comment]
Yeah I meant for my CPU since I use a very old laptop, but great to hear that there will be an update! It’s so far my favorite extension. Thanks for maintaining.

**Comment by EdwardLangdon** [comment]
You should Thank @ManeraKai not me, Actually.

**Comment by anon238** [comment]
I’m thanking whoever maintains it, but all your reactions are pretty aggressive. Cheers buddy. Take a beer or something. Sheesh.

**Comment by EdwardLangdon** [comment]
> but all your reactions are pretty aggressive.

Maybe you are right because I am typing in a stressful condition. Need to take something definitely not a beer.
