### ISSUE TITLE
Black flash on switching pages

### ISSUE THREAD

**Issue by silverwings15** [libredirect/libredirect#286]
This only happens when using the light theme. Each time I navigate to a different page in the options, there's a black flash that appears and lasts about half a second. No equivalent white flash when using the dark theme

edit: version 2.0.0, FF 100.0.2 windows

**Comment by EdwardLangdon** [comment]
Might happen if you use RFP.

**Comment by silverwings15** [comment]
> Might happen if you use RFP.

my setup does have a lot of user.js modification, but RFP isn't among those. let me test on a fresh profile and see if it can be reproduced

**Comment by silverwings15** [comment]
yep, happens on a blank Icecat 91.9.1 ESR profile as well

https://user-images.githubusercontent.com/10742312/170833375-e10de1fe-1db7-41d8-af75-8d7c008350ed.mp4

**Comment by ManeraKai** [comment]
Because it defaults to dark theme then switches to white.
Same thing if you used the Arabic version of LR, it will first display the default English strings then the Arabic strings or any other language. I will see if there's a way to not load the page until `localise.js` (for translation) and `init.js` (for themes and other common settings) have been run and initialized.

**Comment by ManeraKai** [comment]
I'll do something like this:
![image](https://user-images.githubusercontent.com/40805353/170858740-cbf7c1dc-722f-4533-84cc-f8467e74be9b.png)
Where They are in one page and loading YouTube, Twitter... pages will be dynamic without opening a new page. It won't be static anymore.

**Comment by ManeraKai** [comment]
https://user-images.githubusercontent.com/40805353/170867082-6605e493-09f6-47e3-9812-c8d93117e4b0.mp4

**Comment by EdwardLangdon** [comment]
Seems like it will do the thing

**Comment by ManeraKai** [comment]
Fixed it! now even translation will stop flashing and we'll start supporting more languages!

**Comment by silverwings15** [comment]
awesome, thank you
