### ISSUE TITLE
Bring Back exceptions

### ISSUE THREAD

**Issue by Loki-L1130** [libredirect/libredirect#29]
Currently to use a specific instances we need to remove all the checkboxes. I think this is messy. Instead Old UI is better.

Why there is no exceptions Option ?

**Comment by ManeraKai** [comment]
The older way was more messy. I added a toggle all option for that specifically. The extension is for randomizing after all. I don't want to add more than one controller for this setting like the old one.

**Comment by Loki-L1130** [comment]
But there should be exceptions - Right ?

**Comment by Cade66** [comment]
Nothing messy in latest Libredirect 1.3.1 Options page, on the contrary : intuitive, logical, all or specific selection's) within two steps.
To summarize the Options : it' never been easier and quick to settle all preferences. IMO better isn't possible.

**Comment by ManeraKai** [comment]
I've added that section @Loki-L1130

**Comment by Loki-L1130** [comment]
Closing this, As it will be added in the Next release.
