### ISSUE TITLE
Unify settings not working in Firefox incognito

### ISSUE THREAD

**Issue by ThracianKnight1907** [libredirect/libredirect#291]
Hi,
I've been trying to use the unify settings in order to save some libredd.it preferences (like always use HLS), but it seems that it doesn't work in incognito mode on Firefox. This happens on every service though so it's not restricted to Libreddit. Is this a bug or a limitation of using private mode? Or am I misunderstanding what unify settings does?

Also clicking on copy raw gives me this string: [object Promise] (I don't know if it's related to the previous issue)

**Comment by ManeraKai** [comment]
Have you checked the instance to also work in incognito?
![image](https://user-images.githubusercontent.com/40805353/170838368-2e21b31e-7476-44e5-b6c2-3ebc893b581e.png)

**Comment by ManeraKai** [comment]
> Also clicking on copy raw gives me this string: [object Promise] (I don't know if it's related to the previous issue)

It was a typo, fixed.

**Comment by ThracianKnight1907** [comment]
Yes, the extension is enabled in private mode. I can replicate this by:

1) open a new private windows with `ctrl+shift+p`
2) open a libreddit instance, go to settings, enable hls, hit save then unify settings 
3) close with `ctrl+w`
4) when opening a new private window with libreddit hls isn't enabled

**Comment by ManeraKai** [comment]
This window is for initializing cookies in incognito mode. I think the implementation has some bugs only. Btw you where fast to capture a screenshot of that page xD

**Comment by ThracianKnight1907** [comment]
I wasn't fast, the page doesn't close by itself it just sits open until I close it

**Comment by ManeraKai** [comment]
oh I see, there's an error in it.

**Comment by kalekad** [comment]
Hi, I have noticed the same behavior in Tor Browser and Android Mull browser. 
Tried upgrading from 1.7 to 2.0.0/clean install of 2.0.0 , tried with reset, always with the same result.
In addition, the instance list is disappearing, redirection sometimes goes, sometimes not, and specifically for Instagram, sometimes the on/off state is not saved.

**Comment by anon238** [comment]
> Hi, I have noticed the same behavior in Tor Browser and Android Mull browser.
> Tried upgrading from 1.7 to 2.0.0/clean install of 2.0.0 , tried with reset, always with the same result.
> In addition, the instance list is disappearing, redirection sometimes goes, sometimes not, and specifically for Instagram, sometimes the on/off state is not saved.

I have the same issue. Redirecting is mostly not working for Twitter, Reddit and some others.

**Comment by ManeraKai** [comment]
@kalekad try to reset your settings. I believe your problem is something different.

**Comment by kalekad** [comment]
I have tried resetting the settings several times.
After reset the empty list of instances is restored(not after every reset), everything else mentioned here 

> Hi, I've been trying to use the unify settings in order to save some libredd.it preferences (like always use HLS), but it seems that it doesn't work in incognito mode on Firefox. This happens on every service though so it's not restricted to Libreddit. Is this a bug or a limitation of using private mode? Or am I misunderstanding what unify settings does?
> 
> Also clicking on copy raw gives me this string: [object Promise] (I don't know if it's related to the previous issue)

and here

> Hi, I have noticed the same behavior in Tor Browser and Android Mull browser. Tried upgrading from 1.7 to 2.0.0/clean install of 2.0.0 , tried with reset, always with the same result. In addition, the instance list is disappearing, redirection sometimes goes, sometimes not, and specifically for Instagram, sometimes the on/off state is not saved.

remains the same after the reset as before.

**Comment by kalekad** [comment]
And a page pops up that says Initializing Cookies and won't go away.

**Comment by ManeraKai** [comment]
@ThracianKnight1907 your problem with LibReddit appeared to be an optimization problem and you closed the popup too early. Fixed it now and it's much much faster.

**Comment by ManeraKai** [comment]
Fixed everything for incognito, though Tor is really weird, I can't even initialize settings after installing the extension for the first time.

**Comment by ThracianKnight1907** [comment]
Hello,

I've tried it right now and it doesn't seem to work :( also the tab with initializing cookies shows up every time i open a new tab (albeit briefly). Shouldn't it open once per session?

**Comment by ManeraKai** [comment]
Version 2.1?

**Comment by EdwardLangdon** [comment]
@ThracianKnight1907 I am in v2.1, If you mean that, I would suggest reinstalling because, the Initializing Cookies windows instantly closes for me.

**Comment by ThracianKnight1907** [comment]
Version is 2.1. Yes, unify doesn't work. The cookie tab closes instantly as well, with the aforementioned issue.

**Comment by EdwardLangdon** [comment]
We actually didn't fix unify in Incognito in v2.1, IIRC. So, Please wait. Maybe I am wrong.

cc @ManeraKai

**Comment by arty-name** [comment]
Apparently https://github.com/libredirect/libredirect/commit/ff9d4b0a9dee856b400cae7b2d8b38997d27f0cf added `privacy` to the requested permissions. Could someone please update the FAQ on why it is needed?

**Comment by EdwardLangdon** [comment]
@arty-name , You can read it here why : https://codeberg.org/LibRedirect/libredirect/issues/3

By the way, Please create an issue separately or hangout in the matrix room instead of asking questions in the existing one.

**Comment by ManeraKai** [comment]
Will close this issue as settings from normal windows shouldn't be applied to incognito as it's literally incognito in the first place.

I may just support incognito because the Tor browser only runs incognito windows. So I'll separate incognito cookies from normal window cookies.
