### ISSUE TITLE
Unify Settings option unavailable for Bibliogram

### ISSUE THREAD

**Issue by vairag22** [libredirect/libredirect#298]
After configuring a Bibliogram instance when I click the Libredirect icon, Unify Settings option is visible for like a second then it vanishes. I also tried right-clicking the icon and selecting Unify from the drop-down menu but it doesn't work, settings are not saved.

**Comment by ManeraKai** [comment]
There's no Unify for Bibliogram. Bibliogram stores cookies server side and you can't just unify the cookie token, There's also no way to read cookie content from the server as a JSON, only the settings page. This is possible at the end but it requires time to be implemented.

**Comment by AidanGG** [comment]
Are any settings working for Bibliogram? When I try to toggle any instances or add my own custom instance, the entire Instagram redirection is disabled.

How to reproduce (after a clean install of the latest version of libredirect): Go to Instagram tab in preferences, toggle any instance, go to any Instagram page and not get a redirect.

**Comment by ManeraKai** [comment]
@AidanGG was a small typo, sorry for being late...

**Comment by AidanGG** [comment]
Not a problem, thank you very much!
