### ISSUE TITLE
Reddit redirect adds "undefined" to URL if instance is offline

### ISSUE THREAD

**Issue by remyabel2** [libredirect/libredirect#299]
For example:

1. Visit reddit.com/r/some_subreddit
2. It goes to teddit.pussthecat.org/r/some_subreddit
3. It's offline, goes to teddit.net/r/some_subredditundefined
4. If multiple instances are offline, it appends more undefined

**Comment by ManeraKai** [comment]
Just a small typo. Fixed 👍️
