### ISSUE TITLE
Add Beatbump as an alternative for Youtube Music

### ISSUE THREAD

**Issue by IronMaltese** [libredirect/libredirect#30]
[Beatbump.ml](https://beatbump.ml) is a great alternative for youtube music

https://github.com/snuffyDev/Beatbump here's the Github

**Comment by ManeraKai** [comment]
It's not because you tube links are shared. It's like finding your artist and having your favorite music private. If it wasn't popular, google will cancel the project like many other projects in the past. What do you think @alefvanoon?

**Comment by ManeraKai** [comment]
> I think it should be implemented to let people know about the project and start listening to music privately

correct

> also idk if this can be implemented

I don't thing it's unimplementable, it's just redirecting after all, but may have some bugs in the beginning.

> but maybe redirect Spotify and Apple Music links through to Beatbump

hmm... Does it support spotify and Apple Music?

**Comment by IronMaltese** [comment]
> hmm... Does it support Spotify and Apple Music?

It only supports YouTube music, but I was just throwing ideas out there

**Comment by IronMaltese** [comment]
Commenting on this issue again, Beatbump only has a small GitHub with one developer, and one instance of this frontend, adding Beatbump to libredirect would allow more people to start running instances, supporting the project, and prevent the project from dying. I hope this issue gets implemented, Thank you for your great work on this amazing project

**Comment by ManeraKai** [comment]
@IronMaltese is there any links that still don't work from YouTubeMusic to Beatbump? Till now I've added `videos`, `channels`, `playlists`

**Comment by IronMaltese** [comment]
Thank you so much for implementing this issue, this project is truly amazing 

here's a few notes about the implemented pull requests
1. Youtube Music is still redirected to piped, freetube or invidious when youtube music redirects are disabled
2. Redirecting albums doesn't work 
3. When Youtube Music is selecting in settings, the yellow highlight goes over Twitter
4. Writing out "Youtube Music" changes the size of the extension, and leaves a lot of blank space, there are multiple potential solutions to this, but I think it should be renamed YT Music so it doesn't take up as much space
5. Here's the Youtube Music logo
![image](https://user-images.githubusercontent.com/89056889/155558022-cee00876-9baa-4936-9d6f-072d453dbff5.png)
6. I'm not sure if you would need a third party database to do this, or if it can work without one, but I still think Spotify, Apple Music, and other music streaming service redirects should be considered because music links are commonly shared online/over text

**Comment by ManeraKai** [comment]
> Youtube Music is still redirected to piped, freetube or invidious when youtube music redirects are disabled

This is on purpose because they're still regular YouTube videos.

> YT Music

That's a nice idea.

**Comment by IronMaltese** [comment]
> This is on purpose because they're still regular YouTube videos.

I thought this was a bug because artist page redirects are inconsistent in Piped, and redirects to the artist’s topic, which doesn’t include albums, playlists and music

**Comment by ManeraKai** [comment]
I see. I'll remove YouTube Music from piped and invidious.

**Comment by IronMaltese** [comment]
There’s no need to remove them, since everything else works, and I just checked YouTube and on YouTube.com, artist’s topics show up with videos and playlists, but on the front ends they don’t show up because they’re not uploaded by the topic channel

**Comment by ManeraKai** [comment]
example?

**Comment by IronMaltese** [comment]
https://user-images.githubusercontent.com/89056889/155567608-76bcbb5b-c8fe-442e-b5c1-b8d02b2914cc.MOV

Even  though this is a problem with the front ends, I’m saying that if there is an easy way to redirect to the artist’s YouTube account instead, that would be cool

https://user-images.githubusercontent.com/89056889/155568154-bb0cf08a-4fb0-47f8-96fb-84e85474fdab.MOV

**Comment by ManeraKai** [comment]
> I'm not sure if you would need a third party database to do this, or if it can work without one, but I still think Spotify, Apple Music, and other music streaming service redirects should be considered because music links are commonly shared online/over text

This needs a separate project like beatbump. A program that fetches from those sites.

**Comment by ManeraKai** [comment]
> Even though this is a problem with the front ends, I’m saying that if there is an easy way to redirect to the artist’s YouTube account instead, that would be cool

That link should be on invidious and piped like the `View channel on YouTube` button on invidious.

**Comment by ManeraKai** [comment]
> Redirecting albums doesn't work

I failed miserably with that. Opened an issue: https://github.com/snuffyDev/Beatbump/issues/33

**Comment by IronMaltese** [comment]
> This needs a separate project like Beatbump. A program that fetches from those sites.

I find this interesting, since [Nuclear](https://github.com/nukeop/nuclear) scrapes data from iTunes and plays it through youtube, but I don't know how Nuclear would be able to link the data from iTunes and youtube together

**Comment by ManeraKai** [comment]
It may be possible but you should connect directly to iTunes or Spotify to get some metadata. The opposite of what this extension is about and that is to get away from even connecting to those websites directly with your IP address.
What do you think @IronMaltese?

**Comment by IronMaltese** [comment]
I agree completely, unless there’s a project that scrapes metadata from Spotify, Apple Music, etc. or Beatbump starts scraping metadata from these sources, this shouldn’t be implemented

**Comment by IronMaltese** [comment]
This issue can be closed now, but make sure to add Beatbump to libredirect.github.io and change the YouTube music icon when the extension is clicked, again thank you so much for implementing this change, and keep up the great work

**Comment by ManeraKai** [comment]
> and change the YouTube music icon when the extension is clicked

?

**Comment by IronMaltese** [comment]
<img width="1440" alt="Screen Shot 2022-02-25 at 16 04 27" src="https://user-images.githubusercontent.com/89056889/155802958-b37a1a97-d6e6-427e-acfd-437ab7cef56f.png">
<3
