### ISSUE TITLE
Proxitok redirect does not seem to work

### ISSUE THREAD

**Issue by remyabel2** [libredirect/libredirect#300]
Example URL: https://www.tiktok.com/t/ZTd7UosgH -> https://proxitok.pussthecat.org/t/ZTd7UosgH/, blank page
https://vm.tiktok.com/ZTd7UosgH -> https://proxitok.herokuapp.com/@honkhonktiddiebitch/video/7103230757694475563 also a blank page.
If you manually search for the video ID, it leads to https://proxitok.herokuapp.com/@placeholder/video/ZTd7UosgH which does work.

Legacy API is on (which is the default), but turning it off seem to have made no difference.

**Comment by ManeraKai** [comment]
And how will I be able to detect that username? ProxiTok was like the old legacy style before then it changed. I think it's ProxiTok's job if it wants to support that legacy link.

**Comment by remyabel2** [comment]
I'll open an issue there.
