### ISSUE TITLE
FreeTube setting is broken

### ISSUE THREAD

**Issue by catwithbanana** [libredirect/libredirect#303]
I noticed today that YouTube embeds were no longer replaced. After trying several things (including resetting my settings) I narrowed it down to setting FreeTube as the front end. No matter what options I select for the embeds if FreeTube is set as the front end embeds are not replaced. 

Furthermore, clicking a YouTube link with FreeTube set as the front end now produces this error:
![image](https://user-images.githubusercontent.com/75995110/171447709-c48a2628-f02b-408f-9a58-e2fff9685603.png)

Embeds and redirects work as expected if Invidious or Piped are selected. The FreeTube app itself continues to work as expected.

Please let me know if I need to provide any more information to restore FreeTube functionality.

**Comment by Victor239** [comment]
Yeah getting the same issue here.

**Comment by ManeraKai** [comment]
Try this zip: [libredirect-2.1.0.zip](https://github.com/libredirect/libredirect/files/8837802/libredirect-2.1.0.zip)

**Comment by catwithbanana** [comment]
> Try this zip: [libredirect-2.1.0.zip](https://github.com/libredirect/libredirect/files/8837802/libredirect-2.1.0.zip)

This seems to work as expected. Embeds are again replaced, and clicking YouTube links opens FreeTube.

**Comment by ManeraKai** [comment]
Does pages with multiple embeds work fine?

**Comment by catwithbanana** [comment]
> Does pages with multiple embeds work fine?

Yep, pages with multiple embeds seem to work just as they did before
