### ISSUE TITLE
Initializing Cookies Popup When Opening Incognito Mode

### ISSUE THREAD

**Issue by Jrawke** [libredirect/libredirect#306]
Hello, when using incognito mode I get the same popup shown in issue #291 :

![initializing cookies](https://user-images.githubusercontent.com/64692701/170839581-55a72269-1cfb-4067-bb4a-e22d5d65065f.png)

The popup does not go away until the window is closed manually.

This javascript error is in the console:

```
Uncaught (in promise) TypeError: url is undefined
    protocolHost moz-extension://acbfa361-32a2-4816-889e-bcaa8dbc9040/assets/javascripts/helpers/utils.js:59
    initPipedLocalStorage moz-extension://acbfa361-32a2-4816-889e-bcaa8dbc9040/assets/javascripts/helpers/youtube/youtube.js:371
utils.js:59:7
```

Please let me know if I can provide any additional information

**Comment by ManeraKai** [comment]
Well thanks for the JavaScript error. I now know where the problem is 👍️

**Comment by ManeraKai** [comment]
Disabled Piped

**Comment by Jrawke** [comment]
Thanks for the quick response! When should I expect to have the fix delivered to my browser? I downloaded the extension via the mozilla website

**Comment by ManeraKai** [comment]
It will be in the next release 2.1, I think it will be the upcoming week.
