### ISSUE TITLE
Twitter twimg redirects

### ISSUE THREAD

**Issue by austinhuang0131** [libredirect/libredirect#307]
`https://pbs.twimg.com/media/<ID>?format=<format>&name=orig` should be redirected to `https://nitter.instance/pic/media%2F<ID>.<format>%3Fname%3Dorig`

**Comment by ManeraKai** [comment]
Example?

**Comment by austinhuang0131** [comment]
https://pbs.twimg.com/media/FJYvLdfXMAIcs4n?format=jpg&name=orig

https://nitter.net/pic/media%2FFJYvLdfXMAIcs4n.jpg%3Fname%3Dorig

Though this will also work:

https://nitter.net/pic/pbs.twimg.com%2Fmedia%2FFJYvLdfXMAIcs4n%3Fformat%3Djpg

But since Libredirect leaves out the query string, this does not work:

https://nitter.net/pic/pbs.twimg.com%2Fmedia%2FFJYvLdfXMAIcs4n

**Comment by squeak9** [comment]
Is it just me or does this not work: https://pbs.twimg.com/media/FcJ7Wr8X0AcHyKe.jpg

**Comment by EdwardLangdon** [comment]
Fixed in https://codeberg.org/LibRedirect/libredirect/commit/04fd2de0bb051a9cde33095f0d338f4700c335ce
