### ISSUE TITLE
[Support] Where is the redirection to old reddit for reddit?

### ISSUE THREAD

**Issue by pitsi** [libredirect/libredirect#310]
I have been using privacy redirect for almost a year now and I discovered your fork ~1 week ago, so I decided to give it a try.
I use privacy redirect to only redirect reddit to old reddit, twitter to nitter, instagram to bibliogram and youtube to invidious, nothing more than those 4. 

And, to be honest, the extra options for tiktok and imgur your addon provides seem appealing to me, so I installed the addon on my brave installation (and firefox will follow). However, I see no option to redirect reddit urls to old reddit, just the instances for teddit and libreddit. I read past issue reports about reddit, just in case old reddit was an option that was removed, but I could not find any. So, what gives?

Brave 1.39.x, which is chromium 102 based, on debian testing and the addon was installed with the procedure for chromium based browsers that is described here
https://github.com/libredirect/libredirect/blob/master/chromium.md

**Comment by ManeraKai** [comment]
In the FAQ page it has been explained why it got removed: https://libredirect.github.io/faq.html#suggest_frontend

**Comment by pitsi** [comment]
No offence, but I think keeping ONE (two if you count i.reddit.com) extra "instance" wouldn't be much of a hussle.
Plus, I think I had that (or at least a similar) redirection addon for reddit only and I ditched it because privacy redirect could do all the redirects I wanted, from one addon. I won't be adding it again now or anytime soon.
And because I visit reddit 10x times more than the other sites, I think there is no reason for me to keep libredirect installed too, sorry.

Thank you for the clarification though :)

**Comment by ManeraKai** [comment]
Even i.reddit.com was there but got removed. I removed both of them to not make the extension bloated as the existing extension already has 32k users. I want LibRedirect to focus as much as possible on privacy friendly stuff like how the requirements said.

**Comment by pitsi** [comment]
To be honest, on my end, teddit is slow and libreddit breaks the appearance of some subreddits (especially on mobile browsers), so I avoid them both
I use the main instances for both, but I think libreddit's issue is irrelevant of the instance.

**Comment by theuser18** [comment]
> In the FAQ page it has been explained why it got removed: https://libredirect.github.io/faq.html#suggest_frontend

I find this a poor reason. Why have two extensions when one would suffice? Having it be an option doesn't hurt anyone.

**Comment by EdwardLangdon** [comment]
@pitsi I would suggest your to use Old Reddit via Custom Instances in your case.

**Comment by pitsi** [comment]
I thought of that, but I was doing it the wrong way. You have to first enter the url and then click the plus sign for it to work, but I was doing it the other way round :D 

However, I am having a small issue and I want you all to tell me if it happens on you as well, regardless of the instance.
When clicking a link that leads to a subreddit, e.g. google's first result when searching for "reddit debian", it gets straight to the new reddit and stays there no matter if I refresh the page. As it seems, the addon's redirection does not happen. On the other hand, when opening it to a new tab, the redirection to old.reddit does happen.
Does this apply to you as well when using teddit or libreddit instances? Or is it an issue that will be solved in the future?

Privacy redirect does the redirection with no issues.

**Comment by ManeraKai** [comment]
you mean when accessing a link through a libreddit instance?

**Comment by pitsi** [comment]
No, I mean when accessing a regular link like `www.reddit.com/r/whatever `. I am now making a simple html page to test if the issue is google related.

**Comment by ManeraKai** [comment]
oh your adding as a custom instance and having issues with it, I suggest not doing this as libreddit's pathnames are different from old.reddit.com

**Comment by pitsi** [comment]
Actually I have added it as a teddit instance. Let me delete it and try it as a libreddit one.

**Comment by ManeraKai** [comment]
It will break on some link up to you.

**Comment by pitsi** [comment]
Well, so far the only things the redirection (of privacy redirect) has broken is on links that have slashes on the url like "my_\new_\project" (the slashes may be the other way) and on gallery links.

**Comment by ManeraKai** [comment]
Here is the redirection function and you can see some links will get converted to libreddit or teddit and won't be understood by old reddit: https://github.com/libredirect/libredirect/blob/cd285222c76e864387d4bb74df6aeb64b61d9363/src/assets/javascripts/reddit.js#L225-L288

**Comment by pitsi** [comment]
So this means it will break on any gallery, poll, rpan, settings and topics url? Of all 5, I only come accross galleries, so I think I can tolerate that :P

**Comment by pitsi** [comment]
For the ones that use a libreddit instace for redirection, how does the addon behave on reddit's images, i.e. urls from the domain `i.redd.it`?
I opened such a url earlier, this one
`https://i.redd.it/vpxmlbziyc591.png`
and it got redirected to 
https://old.reddit.com/img/vpxmlbziyc591.png
which is just a transparent square :D

**Comment by pitsi** [comment]
The solution to the above issue with images is to add `https://i.redd.it/` as a url exception in the addon's settings.

**Comment by pitsi** [comment]
I bring this back to the surface because I am having this annoying problem.

![2023-01-03-094351_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/211763927-82b3444c-d958-4c82-8d4f-7e51e83611ba.png)

It happens only on firefox, but it works as it should on brave. They use the exact same settings, exported from the one, imported on the other. 
I still use old.reddit for reddit redirection as I described above and I have third party cookies and other trash blocked completely on both browsers, yet nothing changes if I enable (= switch from the strict tracking settings to the standard ones) in firefox. Long story short, the only way to use reddit there is to disable the addon's redirection and manually type old.reddit in the address bar.

If any of the devs thinks that redirection issue is irrelevant to my original issue, I will open a new one.
