### ISSUE TITLE
Use Weblate for i18n

### ISSUE THREAD

**Issue by realpixelcode** [libredirect/libredirect#313]
I think using a service like [Weblate](https://weblate.bubu1.eu) would make i18n much easier and potentially attract more translators.

**Comment by ManeraKai** [comment]
This isn't [hosted.weblate.org](https://hosted.weblate.org)?

**Comment by realpixelcode** [comment]
weblate.bubu1.eu is just the Weblate server that I use for my own projects, but any server will do :)

**Comment by realpixelcode** [comment]
weblate.bubu1.eu is just the Weblate server that I use for my own projects, but any server will do :)

**Comment by ManeraKai** [comment]
Problem is:
![image](https://user-images.githubusercontent.com/40805353/172051596-e640af08-c54e-43af-9855-b8aed0c98502.png)

**Comment by realpixelcode** [comment]
Well, their ToS don't say anything about the kind of projects that are allowed (there aren't even any actual ToS). Also, I'm using the server myself for both my Firefox addons and a desktop program, and noone has ever complained. 🤷 But using the “official” server at hosted.weblate.org would really be okay too (or even a completely different i18n service altogether). ☺️

**Comment by ManeraKai** [comment]
I can switch to it anytime from the official one anytime 👍️

**Comment by comradekingu** [comment]
I left 3 suggestions in https://hosted.weblate.org/translate/libredirect/extension/en/?q=has%3Asuggestion
Would be nice to have the website strings available too, but that needs some conversion and vetting.

**Comment by ManeraKai** [comment]
I can't have it as YouTube Music as the popup will be too wide for this
![Screenshot_20220606_001239](https://user-images.githubusercontent.com/40805353/172070817-38a045bb-7f3a-46f2-bd14-b23c463c9d7d.png)

**Comment by ManeraKai** [comment]
@comradekingu  I'll add this additional string but in the next release i.e v2.2.

**Comment by comradekingu** [comment]
One idea
```
YouTube
    ∟ Music
```

**Comment by ManeraKai** [comment]
? Really no need to complicated it.

**Comment by ManeraKai** [comment]
An it's become approved for Libre hosting!
