### ISSUE TITLE
Add a new Invidious instance

### ISSUE THREAD

**Issue by AVeryNormalGuy** [libredirect/libredirect#314]
### Links

Clearnet: https://yt.beparanoid.de/
Tor: http://yt.prnoid54e44a4bduq5due64jkk7wcnkxcp5kv3juncm7veptjcqudgyd.onion/
I2P: http://gv2c4pc3zxgubsaujc46vpmmxiebczk27d7umy6dpsu25ftq77aa.b32.i2p/

### Cloudflare: Disabled

**Comment by ManeraKai** [comment]
Open an issue in this [Invidious Documentation Repo](https://github.com/iv-org/documentation/) and it will then be automatically fetched in our side.
From where we fetch those instances lists: https://libredirect.github.io/faq.html#where_the_hell_are_those_instances_coming_from
