### ISSUE TITLE
redirecting from an offline libreddit instance adds "undefined" to the end of the URL 

### ISSUE THREAD

**Issue by polak14** [libredirect/libredirect#315]
libredirect Version: 2.0.0

When getting redirected from an offline libreddit/teddit instance it adds "undefined" to the end of the URL.
To reproduce
find an offline instance and go to any forum (/r/whatever) https://reddit.phii.me/technology as an example as of writing.
this gets redirected to xyz/r/technologyundefined

Here is a short demonstration.
https://user-images.githubusercontent.com/76823966/172036726-784cf321-4880-4c19-8d87-33fb71fd5439.mp4

d

**Comment by Dyras** [comment]
https://github.com/libredirect/libredirect/issues/299

**Comment by ManeraKai** [comment]
We'll release 2.1 soon 👍️
