### ISSUE TITLE
Youtube redirect does not appear to work on invidious page when clicking on youtube link

### ISSUE THREAD

**Issue by remyabel2** [libredirect/libredirect#318]
https://www.youtube.com/channel/asdf does not redirect
https://youtube.com/channel/asdf does

**Comment by remyabel2** [comment]
I am suddenly no longer able to reproduce this. Going to keep this open until I encounter the issue again and try to have more exact reproductive steps, but it's unreliable.

**Comment by remyabel2** [comment]
The issue actually appears to be if I **click** on a link that contains https://www.youtube.com/channel/asdf, the problem does not occur if I enter it in the address bar.

**Comment by remyabel2** [comment]
Going to close this for now.

**Comment by ManeraKai** [comment]
Paste the link in a new tab and it will redirect properly, When you click **View channel on YouTube** it will bypass every single request in that tab and won't start redirecting properly unless you start using another tab.
