### ISSUE TITLE
Infinite tab loop with Multi Account Container extension when offline redirection is turned on

### ISSUE THREAD

**Issue by bbhtt** [libredirect/libredirect#320]
Steps to reproduce:

1. Install Libredirect and turn on offline instance redirection
2. Install MAC https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/ and disable "Replace tab instead of creating new one" in about:addons>Preferences
3. Create a container and click on the link of an offline instance within that container
4. LIbredirect creates an endless loop of new tabs

Now per the code it is supposed to stop after 5 redirections  https://github.com/libredirect/libredirect/blob/8c1b5509c01e045edcbc5d396928b7879e77c345/src/pages/background/background.js#L185-L193 but it doesn't. So maybe the counter is firing continuously due to the partitioning between the tabs? 

Video:

https://user-images.githubusercontent.com/62639087/172519535-4469b651-bcb9-4c1b-a0f0-cd07810e3b04.mp4

Libredirect 2.0.0

**Comment by ManeraKai** [comment]
It's not because of that, it's because of the incognito mode: https://github.com/libredirect/libredirect/blob/v2.0.0/src/pages/background/incognito.js#L15

**Comment by bbhtt** [comment]
I'm not using incognito mode?

**Comment by ManeraKai** [comment]
This "Container" thing is opening as incognito.

**Comment by bbhtt** [comment]
Still not sure what are you trying to mean.

Containers don't open in incognito mode, localstorage is usable within a container.

Are you saying it's beacuse localstorage is partitioned by containers and it is happening because of that?

**Comment by ManeraKai** [comment]
> Are you saying it's beacuse localstorage is partitioned by containers and it is happening because of that?

Containers apparently use incognito mode to separate cookies and from other containers, normally if you launch an incognito window, it will fire those windows to set localStorage, though here seems to be a problem where it think every new tab is a new incognito window so it starts again.

**Comment by bbhtt** [comment]
> Can you see if it's present v2.1? I failed to reproduce the bug in v2.1: [libredirect-2.1.0.zip](https://github.com/libredirect/libredirect/files/8868764/libredirect-2.1.0.zip)

Yep, seems to be fixed in 2.1. Thanks.

**Comment by bbhtt** [comment]
Hmm, I can reproduce again when I updated to 2.1 today from AMO. Can you? Maybe temporary addons have some limitation..
