### ISSUE TITLE
Doesn't support the & character in searches

### ISSUE THREAD

**Issue by Oreolek** [libredirect/libredirect#321]
You can't use & because libredirect search strips everything after the symbol.

**Comment by ManeraKai** [comment]
example?

**Comment by EdwardLangdon** [comment]
I think he means about searching 'HTML & CSS' in google when redirect to searx it strips the search and just shows 'HTML CSS'

That's what I understand.

But it doesn't happen.

**Comment by Oreolek** [comment]
"HTML & CSS" turns into just "HTML" for me (Firefox 101)

**Comment by EdwardLangdon** [comment]
Weird, Is that specific to an Instance or every instance ?

**Comment by ManeraKai** [comment]
Found the problem. Fixed it 👍️
