### ISSUE TITLE
Feature Request: Auto Enable/Disable instances based on criteria. 

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#322]
When I test the latency of different instances, I like to enable instances that are "Green" (that is have the best latency) and disable others. I also like to enable cloudflare instances if they are "Green".

It would be handy if there was an option for the extension to auto enable/disable instances after a latency test based on criteria like "what's the quality of the latency", "does it use cloudflare", etc. 

Alternatively, it would also be nice to have the option to blacklist certain instances from not getting a latency test at all (IE: Instances that require authentication).

**Comment by ManeraKai** [comment]
There's a similar issue opened in the Codeberg repo and you can read there: https://codeberg.org/LibRedirect/libredirect/issues/2
