### ISSUE TITLE
Enhancements for Proxitok

### ISSUE THREAD

**Issue by EdwardLangdon** [libredirect/libredirect#326]
Add `Switch Instance` and `Unify Settings` for Proxitok in the Popup when in the respective pages.

Fix Instance Fetching.

**Comment by ManeraKai** [comment]
Added Switch Instance.
Fixed Instance Fetching.

We discussed this before I believe. Unify Settings are working correctly.

**Comment by EdwardLangdon** [comment]
Indeed, We did and We shall test it before release. That's it.
