### ISSUE TITLE
Fixing Medium when viewing from Blog's Home.

### ISSUE THREAD

**Issue by EdwardLangdon** [libredirect/libredirect#327]
Currently there are some caveats with Medium redirection.

Such as going to onezero.medium.com a Subdomain where when you click on a post link from the blog. It loads in medium rather than redirecting to scribe. This happens when you click a post from any medium blog.

Note : As scribe doesn't support homepages only articles. So, It's excluded.

I can only view in Scribe, When I open the post in a New Tab.

When you compare this with imgur, Go to imgur.com, click on a image it's redirected to rimgo.

**Comment by ManeraKai** [comment]
I'm deleting the fact that the home page will be bypassed as people are thinking that it's not working. imo Rimgo and Scribe should add a home feed to start with.

**Comment by ManeraKai** [comment]
Try this, is the problem still there?
[libredirect-2.1.0.zip](https://github.com/libredirect/libredirect/files/8883887/libredirect-2.1.0.zip)

**Comment by EdwardLangdon** [comment]
Well, I tested the Zip file, As you stated it's now not showing the homepage of the blog rather the Scribe's error page.

On a note, Imgur redirection is now not working.

**Comment by EdwardLangdon** [comment]
Actually, The Old way is better until scribe/rimgo introduces Homepage. With this error page, People need to turn off redirection and turn it on again to read Blog posts from the Blog's Home.

**Comment by ManeraKai** [comment]
> On a note, Imgur redirection is now not working.

Imgur redirection is working?

**Comment by EdwardLangdon** [comment]
It wasn't when I tested the Zip. We will test during the release.

But what do you think about bringing back the Old thing ?

**Comment by ManeraKai** [comment]
well no one vists the homepage unless he wants something from the homepage, I think I will revert it back, though I really want them to add a home feed and I know it's hard.

**Comment by EdwardLangdon** [comment]
I agree with you. We shall implement it once Homepage is available by the respective projects.

But was my Issues stated in the commit ?

**Comment by ManeraKai** [comment]
You're issue seems to be fixed before someway.

**Comment by EdwardLangdon** [comment]
Okay, We shall see during the testing of Next release.

**Comment by ManeraKai** [comment]
Yes 👍️
