### ISSUE TITLE
Why "Read and modify privacy settings"

### ISSUE THREAD

**Issue by thjderjktyrjkt** [libredirect/libredirect#329]
Latest extension update on Firefox, new permission required.
Care to explain the use of this permission?

**Comment by EdwardLangdon** [comment]
Explanation can be found here : https://codeberg.org/LibRedirect/libredirect/issues/3

The Wiki on the Website will be updated sooner.

**Comment by ManeraKai** [comment]
The FAQ has been updated: https://libredirect.github.io/faq.html#why_all_those_permissions
