### ISSUE TITLE
Google's subdomains are getting treated as search pages

### ISSUE THREAD

**Issue by napca** [libredirect/libredirect#33]
play.google.com , drive.google.com , and any other subdomain that isn't defined in libredirect ( translate.google.com is defined for example ) are getting treated as a search page

**Comment by ManeraKai** [comment]
I think I've fixed this problem: https://github.com/libredirect/libredirect/blob/master/src/assets/javascripts/helpers/search.js#L6
This is a Regex code that detects which URLs are for search and which are not. You can use https://regex101.com/ and paste the Regex to test it. Be sure to select `ECMAScript (JavaScript)` as the Regex syntax:
![image](https://user-images.githubusercontent.com/40805353/153747447-27d4b3ba-56f7-4e99-a2aa-326df71bfe4e.png)
We will release a new version soon 👍

**Comment by ManeraKai** [comment]
@parsarch A new version was released https://github.com/libredirect/libredirect/releases/tag/v1.3.2. update your extension on Firefox and hopefully it will work.
