### ISSUE TITLE
Firefox: New Pravacy permission explanation.

### ISSUE THREAD

**Issue by ReprovedC0medown1nch1ng** [libredirect/libredirect#332]
Hi, could you please explain the need for the new permission needed in Firefox "Read and modify privacy settings"? 
Is it the same privacy permission that was added to the FAQ just some hours ago?

**Comment by silverwings15** [comment]
https://github.com/libredirect/libredirect/issues/329

**Comment by ManeraKai** [comment]
>  Is it the same privacy permission that was added to the FAQ just some hours ago?

Yes.
