### ISSUE TITLE
Redirects are Not working on these twitter url. Please resolve it 

### ISSUE THREAD

**Issue by rakitanc** [libredirect/libredirect#339]
https://twitter.com/AskAnshul/status/1507751538621489158

https://twitter.com/venkateshvtn

**Comment by ManeraKai** [comment]
both of them are working correctly for me

**Comment by rakitanc** [comment]
For me it says..

"Something went wrong. Try reloading."

**Comment by ManeraKai** [comment]
There's an internet connection error, can you show me a screenshot?

**Comment by rakitanc** [comment]
I am using this Chrome Version 99.0.4844.82 (Official Build) (64-bit) on Linux

**Comment by ManeraKai** [comment]
LibRedirect doesn't have those messages in it. Are you sure nothing is wrong with the instance you're using?

**Comment by rakitanc** [comment]
![Screenshot from 2022-06-14 22-44-08](https://user-images.githubusercontent.com/64612555/173637672-a3e84d65-4eec-48cf-9a10-79986d8b32ce.png)

**Comment by ManeraKai** [comment]
I see, what path does it redirect to?

**Comment by rakitanc** [comment]
i am using minimal theme for twitter extension and ulbock too

Turned both off..Doesn't seem to solve the issue

**Comment by ManeraKai** [comment]
which version of LibRedirect are you running?

**Comment by rakitanc** [comment]
![Screenshot from 2022-06-14 22-48-58](https://user-images.githubusercontent.com/64612555/173638201-6089757e-c7ed-45b9-b59d-d4fa1bbad19b.png)

**Comment by rakitanc** [comment]
I am using 2.1.0

**Comment by ManeraKai** [comment]
Is there any `Errors` button here?
![image](https://user-images.githubusercontent.com/40805353/173638504-6cfc9d55-5df4-4326-b9da-b2aa3c72c9bf.png)

**Comment by rakitanc** [comment]
![Screenshot from 2022-06-14 22-52-19](https://user-images.githubusercontent.com/64612555/173638799-8c329b6a-b7fb-4eff-8f9e-8a08e0ffee71.png)

**Comment by ManeraKai** [comment]
oh because you installed it through .crx. Is there any errors in the console in `inspect views:`?

**Comment by ManeraKai** [comment]
This problem may be the same as with a previous problem with brave: https://github.com/libredirect/libredirect/issues/110

**Comment by rakitanc** [comment]
How do i confirm it?

**Comment by rakitanc** [comment]
I see these kinf of errors

Refused to load manifest from 'https://nitter.sethforprivacy.com/manifest.json' because it violates the following Content Security Policy directive: "manifest-src 'self'".

**Comment by rakitanc** [comment]
![Screenshot from 2022-06-14 23-56-32](https://user-images.githubusercontent.com/64612555/173662326-e9b54c2f-a437-4017-ab7b-ce522c26a93f.png)

**Comment by ManeraKai** [comment]
Maybe the problem has been solved with newer versions of chrome as it's like with Brave. The latest Flatpak version of chrome is 102.0.5005.115-1: https://flathub.org/apps/details/com.google.Chrome

**Comment by rakitanc** [comment]
When is it releasing as crx? As i am not using chrome on flathub

**Comment by ManeraKai** [comment]
This issue is not about LibRedirect rather a bug in chromium browsers.

**Comment by rakitanc** [comment]
> @ManeraKai He means when are we releasing `crx` for v2.3 and states that He isn't using Flatpak version of chrome rather some other package like Debian.

Thanks brother for clarifying. Please help what can i do at this stage?

**Comment by ManeraKai** [comment]
You can download the source code, then do the same instructions as here to install it on chrome: https://github.com/libredirect/libredirect#install-in-chromium-browsers

**Comment by ManeraKai** [comment]
Just update your chrome version to a newer one.

**Comment by rakitanc** [comment]
> Just update your chrome version to a newer one.

Using Chrome Version 103.0.5060.114 (Official Build) (64-bit)

The twitter issue still not fixed
