### ISSUE TITLE
Unticking "Toggle All" freeze the browser

### ISSUE THREAD

**Issue by TheFrenchGhosty** [libredirect/libredirect#34]
If the user untick "Toggle All" (instances), the whole browser will freeze, and basically crash.

This makes it impossible to choose a specific instance.

Recording of the issue (on an almost "stock" Firefox ESR, after a fresh install of the addon):

https://user-images.githubusercontent.com/47571719/153759394-d7896fd7-4b89-4b66-b63a-33f822535b76.mp4

**Comment by ManeraKai** [comment]
Seems this isn't happening with everything, `Translate`, `Imgur` work fine.

**Comment by ManeraKai** [comment]
Found it, calling function inside itself. 
![image](https://user-images.githubusercontent.com/40805353/153761270-8f98dc3d-e1c6-4896-baec-eb03fb3f8ef6.png)
