### ISSUE TITLE
Private window new tab opens extension's internal page in main window

### ISSUE THREAD

**Issue by japkov** [libredirect/libredirect#340]
In last release (2.1.0) opening new tab in private window, moves focus to the main window for a second then returns to private window. At random, focus will remain in main window after opening new tab in private window. For a brief second you can see extension's tab with "Initializing cookies" title leading to chrome-extension://oladmjdebphlnjjcnomfhhbfdldiimaf/pages/background/incognito.html internal page.

https://user-images.githubusercontent.com/69731550/173777811-41cac36e-7001-4668-98ce-4add45985fad.mp4

Video above shows latest Vivaldi on Linux Mint and same thing happens in Chromium. On Gecko-based browsers (Watefox, LibreWolf and even plain Firefox), mentioned page also appears but it stays within the private window without moving focus to the main window.

**Comment by ManeraKai** [comment]
oh that's a stupid bug 🤦‍♂️. I know why it's happening. I'll fix it

**Comment by japkov** [comment]
Ha! :D Thank you!
