### ISSUE TITLE
Exceptions not so easy to spot/understand?

### ISSUE THREAD

**Issue by slrslr** [libredirect/libredirect#345]
Hello,
new user. From time to time i am using https://**yandex.com/images**/search reverse image search service to upload image and discover details about the image.
Libredirect seems to **redirected it to https://searx.prvcy.eu/ which does NOT seem like reverse image search alternative**. https://tineye.com can be also used for this purpose (but often finds less images, so i need to use both services).

At first look i seen no way to prevent this "wrong redirect". Search section has no option for that, but General tab yes, but the **"Exceptions" maybe was not enough intuitive** for me? ideas:
1)
A) Exceptions -> Excluded from redirecting (addresses/regex)
B) Exceptions -> Exceptions (excluded from redirecting - addresses or regex)
2)
A) link from Search section to General section exclude list (not so easy to spot currently)
B) create separate Exceptions section

maybe You will take something from this feedback

**Comment by ManeraKai** [comment]
apart from your suggestion, I myself don't like the current implementation and always close off redirections for only too look at a feature search in google that is not present in SearXNG. So I think I'll disable all redirections from google, yandex, bing and will just make it redirect search.libredirect.invalid while setting it as a default search engine in the settings. but I can't do so because chromium doesn't support adding custom search engines through an extension anymore :/

**Comment by vairag22** [comment]
> I think I'll disable all redirections from google, yandex, bing and will just make it redirect search.libredirect.invalid while setting it as a default search engine in the settings. but I can't do so because chromium doesn't support adding custom search engines through an extension anymore :/

Then why don't you stop supporting Chromium-based browsers? Almost all of the LR userbase uses Firefox-based browsers. Both Google and Microsoft have removed LR from their stores.

**Comment by ManeraKai** [comment]
> Microsoft have removed LR from their stores.

We're still waiting for a response from Microsoft. And there are users that install with a way that we can't count how many are using it, but the issues that are opened state clearly that people are using it in chromium browsers.

**Comment by vairag22** [comment]
> We're still waiting for a response from Microsoft.

Okay.

**Comment by ManeraKai** [comment]
It's like this right now:
![image](https://user-images.githubusercontent.com/40805353/199291918-662d83d9-7d21-4182-815f-dbd33ad76beb.png)

I already removed google, yandex, and bing so no need for the second option. Sorry for the very very late response...
