### ISSUE TITLE
What is "First-party isolation"?

### ISSUE THREAD

**Issue by m3thm4th** [libredirect/libredirect#349]
In version 2.2.0 a new setting popped up `First-party isolation (Enable for Tor)`
What is it? Is it cookie first-party isolation? Tor Browser has it enabled by default.

**Comment by ManeraKai** [comment]
Yeah it's for cookies. Tor won't accept any cookies unless this is enabled.

**Comment by BobIsMyManager** [comment]
First party isolation is refering to an option in firefox where cookies, cache, etc from each domain are isolated from each other, meaning that they cannot be accessed by other domains, which significantly reduces their tracking capabilities.

**Comment by vairag22** [comment]
Should I enable it on my normal browser? Will it break something?

**Comment by ManeraKai** [comment]
I actually didn't try it on a normal browser. Though I will also make more changes if this was enabled. Those changes will be specific to the Tor browser so I don't advice enabling it for normal browsers.

**Comment by BobIsMyManager** [comment]
> Will it break something?

Probably not, considering it is now [enabled by default for all firefox users](https://blog.mozilla.org/en/products/firefox/firefox-rolls-out-total-cookie-protection-by-default-to-all-users-worldwide/)
