### ISSUE TITLE
[Feature Request] Redirect link of other instances to the chosen instance

### ISSUE THREAD

**Issue by TheFrenchGhosty** [libredirect/libredirect#35]
*Copied from https://github.com/SimonBrazell/privacy-redirect/issues/50*

Invidition support a feature (only for Invidious) named "Always use prefered", it's a feature that redirect every Invidious links of public instances to the chosen instance.

It would be really nice if it was possible to do in Libredirect, either using regex (preferable but might cause some issue in website using the same URL format) or using the list of public instance of each service (how it's implemented in Invidition) either by scraping the list (how it's implemented in Invidition) or by having the list directly in the code.

**Comment by ManeraKai** [comment]
Added the first try of it. Tell me if anything breaks plz. Hopefully nothing will.
