### ISSUE TITLE
IMDb toggle in the pop-up menu is not working properly

### ISSUE THREAD

**Issue by vairag22** [libredirect/libredirect#352]
Even when IMDb redirects is enabled, its corresponding toggle in the pop-up menu stays disabled.

![image](https://user-images.githubusercontent.com/71322586/174483774-ed654ed8-2d6d-41eb-a398-edc6b4a60fdf.png)

**Comment by ManeraKai** [comment]
Don't worry, fixed it here #348

**Comment by vairag22** [comment]
Just saw #348. My bad.
