### ISSUE TITLE
Fails on link.medium.com

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [libredirect/libredirect#353]
Example: https://link.medium.com/tuOvL6v2Zqb

This is [a redirect](https://wheregoes.com/trace/20223217235/) to https://medium.com/p/a-note-to-the-celsius-community-e5af1f5a7998 which is itself a redirect. Clicking the `link.medium.com` link with libredirect enabled will fail, because it tries to load the post `tuOvL6v2Zqb` but that's not a post.

**Comment by ManeraKai** [comment]
There's an issue about this opened in Scribe's repo here: https://todo.sr.ht/~edwardloveall/Scribe/23
