### ISSUE TITLE
Exception for Links to External Sites?

### ISSUE THREAD

**Issue by bayazidbh** [libredirect/libredirect#354]
Hi, I've been using Libredirect for a while, but one thing I noticed is that when I sent a link to an external site from my phone to my browser (via KDE Connect - which immediately opens the site on the PC) or directly open certain links that the alternative front-ends doesn't support, the extension still try to redirect them and results in the final target not being opened, opening either the front-end's front page or an Undefined page.

I propose adding exceptions to URLs such as https://www.youtube.com/redirect and https://t.co or have a way to unwrap the links so it opens the final destination correctly.

**Comment by vairag22** [comment]
LR's job is to redirect certain websites to their respective FOSS frontends, like `youtube.com -> invidious.snopyta.org`, not unwrapping links. For that you'll have to use [Skip Redirect](https://github.com/sblask/webextension-skip-redirect).

**Comment by BobIsMyManager** [comment]
^ or [FastForward](https://fastforward.team/)

**Comment by vairag22** [comment]
Skip Redirect: For URL "lengtheners", eg: YouTube and Mozilla Add-on Store redirect links.
FastForward: For URL shorteners, eg: Twitter and Bitly links.

**Comment by BobIsMyManager** [comment]
Oh, I didn't know that, thanks!
