### ISSUE TITLE
My reddit instance is wrong

### ISSUE THREAD

**Issue by tio-trom** [libredirect/libredirect#355]
In your list you have https://trom.tf/  for reddit instead of  https://rdt.trom.tf/ - here in the official list it is correct https://codeberg.org/teddit/teddit

Please change. Thanks!

**Comment by ManeraKai** [comment]
Well in the README it's correct, but not in the json file: https://codeberg.org/teddit/teddit/src/commit/0863c841e4c1654dea28366a08c0ef15374cc0e0/instances.json#L74

**Comment by tio-trom** [comment]
Ah I will report to them. OK. Thanks!
