### ISSUE TITLE
Anti-Cloudflare Protection isn't implemented effectively

### ISSUE THREAD

**Issue by vairag22** [libredirect/libredirect#357]
[piped.kavin.rocks ](https://piped.kavin.rocks)- Untoggled by default since it uses Cloudflare.
[nitter.kavin.rocks](https://nitter.kavin.rocks) - Toggled by default even though it uses Cloudflare but is not marked as such.

All `*.example.com` must be untoggled by default if `a.example.com` is marked.
A new script should be added or existing ones needs to be modified to handle these things before publishing the final instance list.

**Comment by FireMasterK** [comment]
Maintainer of services on kavin.rocks here. 

nitter.kavin.rocks does not use cloudflare.
