### ISSUE TITLE
Keyboard shortcut to change instance

### ISSUE THREAD

**Issue by Llamach** [libredirect/libredirect#360]
A keyboard instance to change instance would be convenient. Some instance would take longer to load or some might show "Rate limit exceeded". So if theres a keyboard shortcut it would remove the trouble of going to the menu.

Thanks

**Comment by Llamach** [comment]
Thanks, sorry for noticing it before

**Comment by yuuyins** [comment]
> in the settings page

agreed

**Comment by ManeraKai** [comment]
There's now an "About" page and there's the docs [link](https://libredirect.github.io/docs) their.
