### ISSUE TITLE
imgur.com redirects not working.

### ISSUE THREAD

**Issue by wrhou** [libredirect/libredirect#361]
1. Disable all other extensions
2. Reset libredirect settings
3. Navigate to libredirect's Imgur settings and make sure the redirect has been enabled and working instances are selected
4. Go to imgur.com. The original website loads.

Happens with libredirect 2.2.1 on Windows 11, Chromium 103.0.5060.53 and Firefox Nightly 103.0a1 (2022-06-21) (64-bit). Youtube, Twitter, Reddit etc. seem to be working though.

**Comment by ManeraKai** [comment]
if you click on an image. Does it not redirect?

**Comment by wrhou** [comment]
Just tried this. Picked a post on the front page of imgur.com, clicked into the post, then opened the direct image link in a new tab, the redirect worked then and there. But anything with imgur.com entered into the address bar doesn't seem to work for me. I assume Imgur redirects are supposed to work for album links too and not just direct image links?

**Comment by wrhou** [comment]
Sorry... not sure why but I reset libredirect's settings for the second time and I can no longer reproduce it this time. Aside from the homepage, everything else seems to be redirecting properly. I assume that it's intended that the homepage doesn't redirect?

**Comment by ManeraKai** [comment]
Yes, till rimgo adds a homepage feed, we'll not redirect the home page of imgur.
