### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [libredirect/libredirect#366]
I am not so sure the GPLv3-only of the extension is good.
The main app is AGPLv3-or later.

https://hosted.weblate.org/projects/libredirect/#information

I am no expert, but making it GPLv3-or-later (compatible) and getting the consent of translators would fix this.

**Comment by ManeraKai** [comment]
Man I didn't mean the main app to be AGPL 🤦‍♂️

**Comment by ManeraKai** [comment]
Fixed it, here in the Repo it's stated properly that it's GPLv3. So just small mistake.
