### ISSUE TITLE
Error [v2.2.1] Unrecognized manifest key'browser_specific_settings'

### ISSUE THREAD

**Issue by johnwaldo** [libredirect/libredirect#367]
Hello, I pulled the chromium file of 2.2.1 and installed. Browser flags two errors.

Browser specific settings (gecko related?)
` "browser_specific_settings": {
    "gecko": {
      "id": "7esoorv3@alefvanoon.anonaddy.me",
      "strict_min_version": "67.0"
    }`
I think this issue is related to: https://github.com/libredirect/libredirect/issues/18#issuecomment-1028179250

As a note/unrelated, browser also flags that 
`Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.`

Thank you for the great work.

**Comment by EdwardLangdon** [comment]
For the first thing, As you said, It is releated to Firefox.

Second thing, Libredirect uses Mv2. So, It shows the error.

We can support Mv3 of Firefox but not chromium's.

**Comment by AlyoshaVasilieva** [comment]
`browser_specific_settings` is used by some non-Chrome browsers. It doesn't have any negative effect on Chrome, it just gets flagged as a warning.

**Comment by EdwardLangdon** [comment]
Yep. That's it. I hope you got the answers you need.
