### ISSUE TITLE
Recommendation for UI Change

### ISSUE THREAD

**Issue by IkelAtomig** [libredirect/libredirect#369]
![image](https://user-images.githubusercontent.com/101938856/175763788-c87c5b4f-5a1e-4603-abbd-f636c458d54f.png)

As you see in the above image, The Space is wasted unnecessarily on Left, Removing that space and moving Customize popup there would be easier for usage.

When Moving Customize Popup to the Right, Split the Contents into Half divided by a Separator with the heading `Customize Popup` in the center.

Or as belows :

![image](https://user-images.githubusercontent.com/101938856/175763963-6e39b2b5-821c-4fca-bd75-ad699e4809ef.png)

This way it is easier or better to do things instead of scrolling things long and long.

**Comment by ManeraKai** [comment]
I know this could be a better logical design, but the problem is there's no other page that has "2 columns" in it. So if one went to the General tab, the page will suddenly widen to be able to fit 2 columns, then it will get suddenly narrower when going into any frontend's settings.

**Comment by ManeraKai** [comment]
More discussion through DMs and we agreed that we will start categorizing the side bar and will also do the same for the popup.

**Comment by ManeraKai** [comment]
We agreed on not categorizing it :'D as it will make things more complex, but the sidebar will now be a multi column one. And the customize popup will be separated to each frontend's settings page:
![image](https://user-images.githubusercontent.com/40805353/199284838-7d22bb66-ca68-468d-ac45-0d98ef24e390.png)
