### ISSUE TITLE
[Suggestion] Option to redirect only non-embedded YouTube videos

### ISSUE THREAD

**Issue by Cade66** [libredirect/libredirect#37]
_LibRedirect_ includes the option to redirect _**only embedded videos**_.
I believe an option to redirect _**only non-embedded videos**_ would be pertinent.

Why?

Redirected embedded videos, at the best, aren't displayed as promptly as when non-redirected.
Several redirected embedded videos connect nevertheless the user's device to YouTube servers (see https://github.com/TeamPiped/Piped/issues/786#issuecomment-1038833203)

My approach is that I see little advantage of redirecting _embedded_ YouTube videos (sluggish quite often, non 100% privacy reliability).
But I do enjoy all the advantages of redirecting all _non-embedded_ videos to either _Invidious_ or _Piped_ instances (speed, 100% privacy).

Personally I continue to redirect non-embedded YouTube sites to _Invidious_ or _Piped_ instances via the _Redirector_ extension because at this point neither _LibRedirect_ nor _Privacy Redirect_ offer the option to handle only non-embedded YouTube videos.

**Comment by ManeraKai** [comment]
Sounds cool. We will try to know every little YouTube domain name and will add this option.

**Comment by Cade66** [comment]
> We will try to know every little YouTube domain name and will add this option.

I wouldn't have imagined redirecting only non-embedded (non IFramed) videos would require an extra layer of work. I conceived that if LibRedir offers the option to redirect only embedded videos then the option to redirect only non-embedded would require only a mirror logic... obviously I didn't think right.

Redirect only embedded videos : code defines what embedded videos are, Libredirect has that code implemented.
Redirect only non-embedded videos : all that is not concerned by above code...

Formal logic apparently doesn't always apply to code, I guess.

**Comment by ManeraKai** [comment]
> I wouldn't have imagined redirecting only non-embedded (non IFramed) videos would require an extra layer of work.

no no. I meant we will try to improve the privacy of embeds while at the same time adding your suggested option as an exception.

**Comment by Cade66** [comment]
Great! and already available on AMO (1.3.3). I think it's a valuable new option (or extended option, rather).

**Comment by ManeraKai** [comment]
I'll release a new version after checking the extension for bugs.

**Comment by Cade66** [comment]
My mistake, I checked AMO too quickly and had 1.3.2 as reference.
OK, staying tuned for 1.3.4 :=)
