### ISSUE TITLE
odysee  and quora doesn't redirect

### ISSUE THREAD

**Issue by rezad1393** [libredirect/libredirect#370]
odysee and quora doesn't redirect

**Comment by ManeraKai** [comment]
Are you sure they're not disabled or something? give me example links.

**Comment by rezad1393** [comment]
any link from quara and odysee dotn redirect.
this is the setting.
[libredirect-settings.zip](https://github.com/libredirect/libredirect/files/8985689/libredirect-settings.zip)

**Comment by Mrnofish** [comment]
I was having a similar problem with Wikipedia: been working for a while and all of a sudden it stopped. It was enabled in the settings previously.

I had to reset the settings yet again, then switch it on, and now redirects are back to working.
