### ISSUE TITLE
Extension stops working randomly

### ISSUE THREAD

**Issue by AntoLiguori** [libredirect/libredirect#373]
Libredirect just doesn't redirect to anything after a while. It just randomly stops working and I have to reinstall it everytime

**Comment by TheKevJames** [comment]
I might be having the same issue. If there's any debugging info that'd be useful for me to grab before I reinstall, please let me know!

**Comment by TheKevJames** [comment]
No data is shown in the `Console` tab. Loading various Twitter tweets continues to go to the twitter page rather than a redirect, and still loads no output. Loading the twitter homepage seems to have output the following warning, but did not redirect:

```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.
```

Anything else I can try to help debug?

**Comment by ManeraKai** [comment]
Try to disable it, then re-enable it to get and then open the console quickly for it to be fresh and see if you can spot any errors.

> This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.

not related

**Comment by ManeraKai** [comment]
btw I closed it by mistake.

**Comment by AntoLiguori** [comment]
Just happened again. 

No data is shown in the Console tab. Disabling and re-enabling it makes no difference.

`about:debugging#/runtime/this-firefox` shows these two warnings though `Reading manifest: Warning processing update_url: An unexpected property was found in the WebExtension manifest.` and `Reading manifest: Warning processing key: An unexpected property was found in the WebExtension manifest.`

**Comment by Cwpute** [comment]
Libredirect would stop redirecting for me too.
So I reinitialized the parameters in the extension's options and the redirecting worked again... though i don't remember doing anything fancy in these parameters other than changing the theme to Obscur :thinking: 

Maybe it has something to do with unsaved or wrongly saved preferences ? or the preferences being altered later on by something else... ? Maybe it's a specific parameter in the extension that prevents everything from working after some time ?

**Comment by ManeraKai** [comment]
We'll try to simplify and lessen the code to minimize this behavior hopefully.
