### ISSUE TITLE
Have you thing to move out github after copilot incident ?

### ISSUE THREAD

**Issue by ghost** [libredirect/libredirect#378]
Like have asked [Software Freedom Conservancy](https://sfconservancy.org/) to opensource project to move out from github

Source : [SFC Urges developers to quit Github](https://linuxiac.com/sfc-urges-developers-to-quit-github/)

**Comment by ManeraKai** [comment]
I may move away and we already have a Codeberg mirror, you can see it in the README.
However, what's wrong with copilot?

**Comment by ManeraKai** [comment]
It's not copy paste, it's a person learning from examples on the internet. People do this normally and I do it too when I can't find an answer on the internet but I know an opensource app or extension who implemented the feature.

**Comment by ManeraKai** [comment]
There's a whole difference between copy paste the source code of a licensed app and learning how to code from it.

**Comment by ManeraKai** [comment]
It's becomes different when it's about learning by looking at other peoples code. Almost everyone is doing it and so little has a problem with it. It's just that this time it's a robot doing it, and people aren't comfortable with it.

**Comment by ManeraKai** [comment]
> They use the open source code to train it in total violation of the licences of the code (no credit and added to copilot who is not open totally source)

You said it even, they use it to train. Training is learning. It's an AI that can learn like humans.
