### ISSUE TITLE
Toggling sites in "search" causes CPU usage spike?

### ISSUE THREAD

**Issue by Latrolage** [libredirect/libredirect#38]
Is it just me or toggling a whoogle search site lags and causes firefox to use 100% CPU

**Comment by rimthekid** [comment]
Does this happens when you are using the extension? or it happens for whoogle only

**Comment by Latrolage** [comment]
it happens when i toggle any whoogle instance in libredirect settings

**Comment by ManeraKai** [comment]
Does this happen to any thing else like searx?

**Comment by ManeraKai** [comment]
Reading the code, there's an infinite loop. Some functions are misplaced. Will fix that.

**Comment by ManeraKai** [comment]
Related #34
