### ISSUE TITLE
[Bug]mobile version of imgur not getting redirected

### ISSUE THREAD

**Issue by openwick** [libredirect/libredirect#380]
`m.imgur.com` is not getting redirected on mobile. Tested on both Kiwi and Fennec Fdroid. Please add the url to imgur redirect options.

**Comment by openwick** [comment]
Yes I am sure. Not just home page but everywhere else too. Tested on Mull and Fennec from fdroid.

**Comment by ManeraKai** [comment]
If you're launching the browser by a url, then maybe this is the problem #158.

**Comment by openwick** [comment]
No  I copy pasted imgur link in a new taband it is still not redirecting.

**Comment by ManeraKai** [comment]
give me a link as an example

**Comment by openwick** [comment]
Nvm it is redirecting now but for some reason it didn't before.
