### ISSUE TITLE
Setting to only use Invidious proxies for video

### ISSUE THREAD

**Issue by umbralOptimatum** [libredirect/libredirect#381]
Just learned that Invidious defaults to loading videos directly from google. Could we get a setting to automatically use the server's proxy? Just needs to add `&local=true` to the video URL, so should be straightforward to implement? Individual Invidious instances can disable proxying though, so a "no proxy" label like the existing cloudflare label would be very helpful too.

**Comment by ManeraKai** [comment]
You can change that in the settings and then press Unify Settings.

**Comment by EdwardLangdon** [comment]
![image](https://user-images.githubusercontent.com/101938856/178442712-642aff86-8070-4d53-b118-57e9b0e7148e.png)

Just enable this and save your Invidious Prefrences by scrolling down to end of page. After that press unify. That's it.

Private Browsing has errors. We are working on fixing it.

**Comment by ManeraKai** [comment]
I can't create cookies without the user's consent first. The proxy check can only be checked through either URL parameters or cookies and now we're using cookies so we don't bloat the url addresses.

For the "proxy disabled", It's really hard to check if it supports it or not, the [invidious instances list](https://api.invidious.io/) doesn't provide that information or the default settings for each instance and disabled features.

**Comment by EdwardLangdon** [comment]
> And is adding a single URL parameter a significant concern?

Well, It isn't but if we use URL parameter for every feature it would bloat the address bar.

>can't the user consent to creating cookies when they enable the option?

Libredirect is just a redirection plugin with some additional functionalities that would help the user in regards to using it.

The user should know about the service (in this case invidious) before using it.
