### ISSUE TITLE
IDEA - non-200 instances should be declared as offline and switched to online one

### ISSUE THREAD

**Issue by SoftwareRat** [libredirect/libredirect#382]
Hello,
I really love the "Auto-redirect offline instances to online ones" feature, which auto-switch the instance if the instance is offline. Sadly it just works when the server is really offline, sites like https://libreddit.notyourcomputer.net/ having a 404 error, doesn't get switched.

My idea is, if a instance is online, the HTTP Statuscode is 200. Else it would be moved or offline, so you could make a statuscode check, if it's not 200, then it counts as offline. This also helps for parked domains like https://libreddit.awesomehub.io

**Comment by bayazidbh** [comment]
Alternatively, some sort of way to upvote good instances would be nice. I think making the default instance use be "everything that isn't Cloudflare" is fine (though some sort of auto-check if they take extraordinarily long compared to other instances would be better) but if there's enough offline or bad instances for a service, then some sort of "Use only community-voted reliable instances" would be nice.

**Comment by ManeraKai** [comment]
I can't redirect off of 404 instances because that means that the page isn't found. Sometimes if you look for a post that has been deleted or doesn't exist, you'll get 404 and it doesn't matter what instance it it. And then we'll redirect of that and we'll get into an infinite loop.

**Comment by ManeraKai** [comment]
> Use only community-voted reliable instances

@bayazidbh This won't be so easy and won't have a good benefit. I can just give the user an option to uncheck the offline instance before he gets auto redirected.

**Comment by SoftwareRat** [comment]
> @SoftwareRat I can't redirect off of 404 instances because that means that the page isn't found. Sometimes if you look for a post that has been deleted or doesn't exist, you'll get 404 and it doesn't matter what instance it it. And then we'll redirect of that and we'll get into an infinite loop.

@ManeraKai I see what you mean. Maybe you could auto-uncheck non-200 instances when you press "Test Instances Latency"?

**Comment by ManeraKai** [comment]
Added it in the latency tester.
