### ISSUE TITLE
Can't permanently remove LibRedirect from search shortcuts

### ISSUE THREAD

**Issue by umbralOptimatum** [libredirect/libredirect#385]
Firefox 102. In the search shortcuts options, I can uncheck LibRedirect as shown in the searchbar, but if I try to remove it entirely it just reappears on restart. I don't even have search enabled inside LibRedirect.

**Comment by ManeraKai** [comment]
It's only present in the manifest file. It's doing that automatically: https://github.com/libredirect/libredirect/blob/468f9ff12cb88cf67ce14aa533f8c1c709923ff7/src/manifest.json#L48-L57

**Comment by ManeraKai** [comment]
Hello?
