### ISSUE TITLE
permissions issue

### ISSUE THREAD

**Issue by stunlocked94** [libredirect/libredirect#39]
Hello,

this addon seems like a great extension of the one its forked from, but the permission to access all data on all websites seems a bit overkill imo.

Wouldnt asking for permission for the specific sites it wants to redirect from (wikipedia, twitter etc.) be more privacy friendly?

Greetings

**Comment by ManeraKai** [comment]
This was possible before when the extension only checked on `targets` e.g: https://github.com/libredirect/libredirect/blob/master/src/assets/javascripts/helpers/youtube/youtube.js#L7-L18, but now it also checks on instances and auto redirects if a 500+ error happened meaning the instance is offline. There's also now a [User Always Preffered](#35) feature that redirects publicly available invidious and piped instances to only your preffered instances. So not just redirecting YouTube here, but redirecting every other instance if you don't trust them.
All those things add so much things that are dynamic and can't be static in the [manifest.json](https://github.com/libredirect/libredirect/blob/master/src/manifest.json)

**Comment by Loki-L1130** [comment]
If so, Why not make the permission to those sites and update it on a regular basis.

**Comment by ManeraKai** [comment]
Because the user can add a custom instance that's needs to be redirected if it had 500 error. The settings aren't grabbed from a list, but are different from user to user.
