### ISSUE TITLE
SearXNG instance list has Tor service in normal category

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [libredirect/libredirect#391]
https://github.com/libredirect/libredirect/blob/a02cd3cceedd7eed62062aa0932cbf57ac2adb25/src/instances/data.json#L532-L534

on searx.space it's correctly listed in the Tor category

**Comment by ManeraKai** [comment]
[BobIsMyManager](https://codeberg.org/BobIsMyManager) is fixing this.
