### ISSUE TITLE
When it redirects, the landed instance doesn't have the correct settings

### ISSUE THREAD

**Issue by PrincessMiki** [libredirect/libredirect#394]
I'll set the quality to medium via the gear menu in the top right. I'll redirect to the same instance to try it out. Quality back to the default hd

**Comment by PrincessMiki** [comment]
Update, if i refresh the vid page it retrieves the correct settings. But this has to be done for every video.

**Comment by ManeraKai** [comment]
Invidious is acting weirdly that it doesn't accept settings if it got redirected from youtube.com, this issue is the same as this one #319. It also happens with embeds. The happened recently as invidious changed a little bit
