### ISSUE TITLE
Strip ref_src and ref_url when redirecting to Nitter

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [libredirect/libredirect#395]
When clicking a Twitter embed, it tries to open a page such as `https://twitter.com/user/status/id?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5Eid%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Ffull_url_of_page_the_embed_is_on`. LibRedirect will redirect to a Nitter instance but keeps the query string intact. It would be nice if it was removed.

(I'm browsing a site that uses JS to turn Twitter links into Twitter embeds; enabling the Nitter embed option just breaks these embeds, rather than converting them from Twitter embeds.)

**Comment by ManeraKai** [comment]
> (I'm browsing a site that uses JS to turn Twitter links into Twitter embeds; enabling the Nitter embed option just breaks these embeds, rather than converting them from Twitter embeds.)

well a classic issue...
