### ISSUE TITLE
Add Hyperpipe for YouTube Music

### ISSUE THREAD

**Issue by IronMaltese** [libredirect/libredirect#398]
https://codeberg.org/Hyperpipe/Hyperpipe is a frontend for YouTube Music hosted at https://hyperpipe.surge.sh and it's still in development, but it's pretty good

**Comment by EdwardLangdon** [comment]
I agree with adding Hyperpipe cuz it's better than Beatbump for now in my usage. Such as I can't even find a Popular Track in Beatbump while I could do find it on Hyperpipe and it's better and usable. I think it's better we swap Beatbump to Hyperpipe or make Beatbump secondary and provide Hyperpipe as the primary redirect.

**Comment by EdwardLangdon** [comment]
Adding Hyperpipe, Totally depends on this one - https://codeberg.org/Hyperpipe/Hyperpipe/issues/3

**Comment by IronMaltese** [comment]
This was closed so quick, solid job🤙🤙🤙🤙🤙
