### ISSUE TITLE
Allow FreeTube redirects alongside Invidious/Piped Embeds

### ISSUE THREAD

**Issue by catwithbanana** [libredirect/libredirect#40]
Currently, setting FreeTube as a redirect for YouTube videos means that embedded videos simply do not show up.

In the original Privacy Redirect extension one could have YouTube redirect to FreeTube while still replacing embedded videos with Invidious/Piped with the "Use FreeTube over Invidious when possible" option. Without this option FreeTube isn't really usable, since it breaks all embeds.

Thank you for your hard work -- this extension is indispensable.

**Comment by ManeraKai** [comment]
Added it. You can now choose the frontend type for embedded videos for freetube: `Invidious` `Piped` `Youtube`
![image](https://user-images.githubusercontent.com/40805353/154353435-7f454c98-d74e-4726-b9e5-7e92aee0a05a.png)
Hopefully there's no bugs.

**Comment by catwithbanana** [comment]
Will that "Embedded Videos Frontend" still allow access to the full list of embedded video settings, like format, quality, and whether to proxy?

**Comment by ManeraKai** [comment]
You can apply the settings to embedded videos too. I kept the settings for that purpose. Maybe not all of them, but a big amount of them.
