### ISSUE TITLE
Add alternative frontends for for Pixiv

### ISSUE THREAD

**Issue by quazar-omega** [libredirect/libredirect#401]
I have found two frontends, but currently I don't know how many instances are available, could you consider them?
- [journey-ad/pixiv-viewer](https://github.com/journey-ad/pixiv-viewer)
  - https://pixiv.obfs.dev/
  - https://lab.getloli.com/pixiv-viewer/
- [YieldRay/pixiv-viewer](https://github.com/YieldRay/pixiv-viewer)
  - https://pixivviewer.netlify.app/

(I'll avoid comments on the first one's choice of branding, let's just say I politely distance myself from it)

**Comment by EdwardLangdon** [comment]
We are unsure of adding these frontends. If some better and actual Privacy Frontends means we might look on. But this doesn't seem to be. Just feels like an successor to pixiv.moe in some other language.

**Comment by quazar-omega** [comment]
I understand, I felt that it could be similar to that one, but I wanted to hear your opinion first.
I guess we can close this for now

**Comment by EdwardLangdon** [comment]
Thanks for understanding. Closing this.
