### ISSUE TITLE
No Default Instances

### ISSUE THREAD

**Issue by TheFloatingBrain** [libredirect/libredirect#403]
When I download libredirect I have no default instances for anything, for example [reddit redirect settings](https://ibb.co/x5nThNG)

This is the version that is available on the firefox addons page, perhaps I have another addon interfering with it? But its never been an issue with any previous version. In fact I am using an older version elsewhere

**Comment by ManeraKai** [comment]
try reset the settings in it

**Comment by EdwardLangdon** [comment]
Probably an Upgrade conflict. As Kai said reset it.

**Comment by EdwardLangdon** [comment]
Probably an Upgrade conflict. As Kai said reset it.

**Comment by TheFloatingBrain** [comment]
I feel silly now haha, thanks it worked
