### ISSUE TITLE
Errors after loading unpacked extension - brave

### ISSUE THREAD

**Issue by quartztester** [libredirect/libredirect#406]
I want to make aware for the maintainers these two errors after loading the unpacked file for Chromium. These errors do not appear to impact current functionality. My OS is windows 10 and I am currently using Brave browser.

`Unrecognized manifest key 'browser_specific_settings'.` - marked with a *
`Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.` - marked with $
```
{
  "name": "__MSG_extensionName__",
  "description": "__MSG_extensionDescription__",
  "version": "2.2.1",
$  "manifest_version": 2,
*  "browser_specific_settings": {
*    "gecko": {
*      "id": "7esoorv3@alefvanoon.anonaddy.me",
*      "strict_min_version": "67.0"
    }
```

**Comment by ManeraKai** [comment]
They're more of warnings rather than errors.

> Unrecognized manifest key 'browser_specific_settings'.

This is a manifest key that is only supported by firefox.

> Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

Read more here: https://libredirect.github.io/faq.html#chrome_web_store

**Comment by quartztester** [comment]
Thank you. I was not looking up the proper terms within closed issues and this problem has already been made aware. That was lack of due diligence on my part.
Feel free to close this issue due to duplication.

**Comment by ManeraKai** [comment]
np :+1: I'm happy you now know what they mean now :)

**Comment by ManeraKai** [comment]
For manifest v3: https://libredirect.github.io/faq.html#why_not_manifest_v3
