### ISSUE TITLE
Remove invidious instance

### ISSUE THREAD

**Issue by rwjack** [libredirect/libredirect#407]
Hey,

tube.cthd.icu is no longer active, can it be removed from the list of recommended invidious instances?

**Comment by ManeraKai** [comment]
We fetch instances automatically. Just tell the invidious team to remove it and the updated list will automatically fetch within 3 days or less.

**Comment by rwjack** [comment]
It's been offline for a month at least. I know because I ran it :)

Where do you fetch it from? I don't seem to see it anymore:
https://api.invidious.io/

**Comment by ManeraKai** [comment]
oh xD
Did you click Update Instances?

**Comment by rwjack** [comment]
Yeah, and oddly, it's still there.

**Comment by ManeraKai** [comment]
I can't see it in our `.json` file: https://github.com/libredirect/libredirect/blob/master/src/instances/data.json

**Comment by rwjack** [comment]
![image](https://user-images.githubusercontent.com/59068073/182020974-03975287-482b-47c3-8891-1152a3485cac.png)

Anyways that's all right, just wanted to let you know.
It'll probably get resolved over time.
Might be a caching issue on either mine, or the browser extension end.

**Comment by ManeraKai** [comment]
or an intruder or something in your laptop. idk
