### ISSUE TITLE
Setting Twitter to embedded only breaks Twitter

### ISSUE THREAD

**Issue by CaptainFrosty** [libredirect/libredirect#410]
I put Twitter on embedded only, and after logging in I could not access account settings and some other things. Took me some process of elimination to identify this as the problem. My browser configuration could be involved as well, I am not sure.

OS: Win11 21H2 .832
Browser: LibreWolf 103.0-3

**Comment by ManeraKai** [comment]
This option doesn't make any sense. Removed it.

**Comment by ManeraKai** [comment]
I added it just for making the three options complete, but more thinking and I don't think it has a use case.
