### ISSUE TITLE
property (update_url, key)  used in manifest  for amo build

### ISSUE THREAD

**Issue by igorlogius** [libredirect/libredirect#411]
![ksnip_20220804-142611](https://user-images.githubusercontent.com/67047467/182846576-0424b233-05b9-4589-b789-283fe8f2ceea.png)

Found in `libredirect 2.2.1`
with Firefox 103.0.1

Only a minor issue, but would make the addon look a little nicer in about:debugging
ref. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json

**Comment by ManeraKai** [comment]
Those are meant for chromium browsers. You can ignore them they're ok.

**Comment by ManeraKai** [comment]
For manifest v3: https://libredirect.github.io/faq.html#why_not_manifest_v3
