### ISSUE TITLE
Addon makes an automatic connection

### ISSUE THREAD

**Issue by Albusvesuvius** [libredirect/libredirect#412]
Libredirect makes an automatic connection to raw.githubusercontent.com every time the browser is started. There is no option to turn it off.

The option to turn off automatic connection needs to be added.

**Comment by ManeraKai** [comment]
I think that it's the icon in the manifest file: https://github.com/libredirect/libredirect/blob/2a0596f08fb54e2faef4bcb4548a28f5837fc067/src/manifest.json#L43
There also other "update requests" for chromium only: https://github.com/libredirect/libredirect/blob/2a0596f08fb54e2faef4bcb4548a28f5837fc067/src/manifest.json#L70

**Comment by ManeraKai** [comment]
It's not up to us in manifest v2: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/chrome_settings_overrides
![image](https://user-images.githubusercontent.com/40805353/183017529-482bb236-7383-4f6f-8420-9403a6886d00.png)

**Comment by ManeraKai** [comment]
> I don't know where this manifest file is. Is there a way to delete a line to prevent this? I want to see if the addon still makes a connection after I remove it.

Remove all this: https://github.com/libredirect/libredirect/blob/2a0596f08fb54e2faef4bcb4548a28f5837fc067/src/manifest.json#L39-L48
And remove this for chromium: https://github.com/libredirect/libredirect/blob/2a0596f08fb54e2faef4bcb4548a28f5837fc067/src/manifest.json#L70

> Also, this addon is for privacy so automatic connections are kind of a big deal for users, do you consider using manifest v3 for next releases?

We will change to manifest v3 but the one the Firefox one. See this question in the FAQ page: https://libredirect.github.io/faq.html#why_not_manifest_v3

**Comment by EdwardLangdon** [comment]
We are fixing a lot of things in the extension internally. So, Please wait and comment here later.
