### ISSUE TITLE
Some links take the user to Youtube page instead of Redirecting to Piped

### ISSUE THREAD

**Issue by Albusvesuvius** [libredirect/libredirect#413]
Clicking on a channel link such as this one "https://m.youtube.com/c/shellshelladventures" which is the mobile link URL, takes the user to Youtube without redirecting it to the selected Piped instance. 

In my case, one piped instance is selected in addon's settings and redirect type is "both".

It would be better to include mobile links for redirection.

**Comment by ManeraKai** [comment]
Can you screen record? We already support YouTube mobile links.

**Comment by ManeraKai** [comment]
Hello?
