### ISSUE TITLE
Add right click option to redirect

### ISSUE THREAD

**Issue by brendenhoffman** [libredirect/libredirect#414]
Sometimes its nice to go to youtube for video suggestions, but I still watch everything on piped, so its a bit annoying to have to toggle the extension every time.

**Comment by catwithbanana** [comment]
This is a great idea!

**Comment by EdwardLangdon** [comment]
By right click do you mean on a url or on the extension icon?

**Comment by EdwardLangdon** [comment]
Probably a duplicate of #464 ?

**Comment by brendenhoffman** [comment]
I would like to right click a link and open it instead of toggling the extension at the top of the screen, then click the link

So on YouTube, right click a video, "open with libredirect", then it opens in a new tab

Sorta similar to #464, I think they would like to open their current page and replace it with libredirect. Both could be accomplished with a context menu.

**Comment by EdwardLangdon** [comment]
Completed in https://codeberg.org/LibRedirect/libredirect/commit/be78f86a67458208279b8cb51b2c6fab4491244c
