### ISSUE TITLE
Some YouTube shortlinks fail to open in FreeTube

### ISSUE THREAD

**Issue by PAI5REECHO** [libredirect/libredirect#416]
Opening https://youtu.be/jWhLEhSnS6g for example causes a 404:
![image](https://user-images.githubusercontent.com/96688573/185393969-8cbc70fd-590c-4a14-97dd-c0a5da9d0edc.png)
Pasting the link directly into FreeTube works though. Other shortlinks do open without 404ing so Idk what the issue is with some particular short links. I'm on latest FreeTube (`v0.17.1 Beta`)

**Comment by Dyras** [comment]
Yup, I can confirm this happens. I'm sent to https://youtu.be/jWhLEhSnS6g and then nothing happens. IF I switch to Piped-Material and press F5 it instantly loads.

Latest Firefox
Windows 10 64-bit

**Comment by catwithbanana** [comment]
I encounter the same issue.

**Comment by ManeraKai** [comment]
This has been fixed here: https://github.com/libredirect/libredirect/pull/393 but we still didn't release
