### ISSUE TITLE
Is there a way to use libredirect on mobile?

### ISSUE THREAD

**Issue by sbutler-gh** [libredirect/libredirect#417]
I'd like to use libredirect on mobile, especially given the research of how invasive in-app browsers are from popular apps (e.g. TikTok, Facebook).

Is there a way to use libredirect on mobile?  Or, could there be a simple way to create a mobile-oriented version of libredirect like an APK?

**Comment by ManeraKai** [comment]
Someone wrote a post about it: https://mike.sg/2022/07/10/how-to-use-libredirect-on-android/

**Comment by ManeraKai** [comment]
And no it can't be APK. It should be a full featured browser first to make it an APK.

**Comment by abdulisik** [comment]
Yes, this is the current way. Don't hesitate if it seems a difficult process, it's not. Spend 10-20 mins setting up mobile extensions with Firefox Nightly, then you can use whatever add-on you want. Another reason to switch to Firefox!

**Comment by najodleglejszy** [comment]
I think it's worth adding that if you don't want to run potentially unstable Nightly branch that gets updates twice day, you can install Fennec from F-droid and follow the exact same steps afterwards. it's based on Stable branch.

https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/

**Comment by nickelswitte** [comment]
I understand the possibility to use the methods described above, but I am thinking about non-tech-savvy users. Would it also be possible to put this addon into the official _mobile addon store_ of firefox, so people can just download it normally like, e.g. uBlock Origin?

**Comment by noodlejetski** [comment]
> Would it also be possible to put this addon into the official _mobile addon store_ of firefox, so people can just download it normally like, e.g. uBlock Origin?

it's up to Mozilla to decide which addons to allow on mobile, and they're taking their sweet time to add any new entries to the existing short list.

**Comment by krystian3w** [comment]
Now should be enough update Firefox to 120+.

**Comment by krystian3w** [comment]
Mainly to fanatics what sit further on ESR 68 and issues 79-119.
