### ISSUE TITLE
When redirect does not work or trigger a privacy warning

### ISSUE THREAD

**Issue by slrslr** [libredirect/libredirect#420]
Hello,

i think that it is not the first time i have found that i was redirected to alternative a page that not worked or my AdBlocker extension warned me about it:

> uBlock Origin has prevented the following page from loading: http://btpnav.com/
> Because of the following filter: ||btpnav.com^$document
> Found in: uBlock filters – Badware risks

I think that i was trying to access Wikipedia.

Maybe there should be some log of last redirects so one knows which one failed so he can report the issue or decrease its priority or quickly disable it until next update etc.

This would be useful also to quickly spot alternative sites which turned to be malicious or privacy data harvesting?

**Comment by ManeraKai** [comment]
you mean a specific instance did that?

**Comment by slrslr** [comment]
@ManeraKai Possibly, i do not know which (i just ended on mentioned URL), that is why i written what i have written.

**Comment by ManeraKai** [comment]
It's like a dead instance and another person bought the domain name and made it another website (mostly ads...). So I actually don't have a way of telling is that instance dead or not bc it does give me a response.
The main fix to this is to update instances frequently so dead ones and zombie ones (another person bought the domain name) will removed.
