### ISSUE TITLE
OSX Chomium Errors, Linux Ok.

### ISSUE THREAD

**Issue by juanpc2018** [libredirect/libredirect#421]
Gives Errors but work.

Unrecognized manifest key 'browser_specific_settings'.
```
"browser_specific_settings": {
    "gecko": {
      "id": "7esoorv3@alefvanoon.anonaddy.me",
      "strict_min_version": "67.0"
    }
  },
```

--------
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

` 
"manifest_version": 2,
 `

![imagen](https://user-images.githubusercontent.com/33388902/186059849-e213c279-a186-42b8-a015-bccf1a61d22f.png)
![imagen](https://user-images.githubusercontent.com/33388902/186059920-08c86aa4-7bdb-4a81-ae73-59fa9026d111.png)
![imagen](https://user-images.githubusercontent.com/33388902/186059966-c02dbbce-11a2-495b-97a4-aa0e901cec1f.png)
![imagen](https://user-images.githubusercontent.com/33388902/186059995-8344d22d-7cfb-4b49-9193-523b73e8bffd.png)

https://download-chromium.appspot.com/
https://www.chromium.org/getting-involved/download-chromium/

**Comment by ManeraKai** [comment]
https://github.com/libredirect/libredirect/issues/406

**Comment by ManeraKai** [comment]
For manifest v3: https://libredirect.github.io/faq.html#why_not_manifest_v3
