### ISSUE TITLE
Add wolfree alpha

### ISSUE THREAD

**Issue by cc713** [libredirect/libredirect#425]
WolframAlpha is a computational knowledge engine.
WolfreeAlpha unlock free access to Wolfram|Alpha APIs.
All instances can be found at https://wolfreealpha.glitch.me/#Web-App

**Comment by brendenhoffman** [comment]
I just started using wolfreeapha, huge help. Would love to see it be added.

**Comment by EdwardLangdon** [comment]
We will add this but this will take time because we are trying to make things bug free and stable in the existing redirection and codes.

This is a good one. But will be disable by default, probably. Unsure though.

**Comment by ManeraKai** [comment]
The project is nice, but it doesn't need redirection? Like you just start using it instead of Wolfram and you won't need automatic redirection for that.

**Comment by brendenhoffman** [comment]
That's a really silly comment. Couldn't you say the same for any site on this extension? Also, it's mirrors have been issued dmca takedowns before, so it would be pretty nice for something to redirect to a working mirror.

**Comment by ManeraKai** [comment]
It's that people normally share YouTube links to each other but not wolfram links. We stopped support redirect from google, yandex, bing search links bc of that.
It's about how will you use this site. If it's about visiting it directly and finding the result of the formula you want by typing inside the search bar, rather than your friend sending you a YouTube video sometimes or having an embed in a site that requires automatic redirection.

**Comment by ManeraKai** [comment]
> Especially since I could bookmark wolframalpha and then use the extension to redirect to the best mirror.

Alright, this is logical.

But what about that it's bypassing paywalls? This will destroy LibRedirect in github.

**Comment by ManeraKai** [comment]
> Potentially, I can ask some of my friends to set up new mirror sites with the bypassing functionality disabled. To avoid receiving DMCA notices, Libredirect can redirect users to the mirror sites incapable of bypassing the paywall by default.

This is much better, have them in a separated list where I will use it for our [script](https://github.com/libredirect/instances).

**Comment by ManeraKai** [comment]
I'll add it for the time being but without instances till @Lin2Jing4 provide a one without passing the paywall.

**Comment by ManeraKai** [comment]
https://github.com/libredirect/instances/commit/ca2483146e301a0f2ae13ba686b95b4573991e3e

**Comment by cafuneandchill** [comment]
Is this some kinda joke? The mirrors do nothing but show the white-on-black Paywall-Respecting Instances message.

**Comment by ManeraKai** [comment]
Well I agree, there's no point in using the paywall-respecting instances really.

**Comment by cafuneandchill** [comment]
I mean, if they don't present an actual Wolfram/Wolfree front-end, then they *technically* don't bypass the paywall lol

I guess the mirrors are WIP, 'cause I don't really see the point of them otherwise

**Comment by ManeraKai** [comment]
They were there a long time ago. idk if we should remove Wolfree or add the normal instances.
