### ISSUE TITLE
Test instances

### ISSUE THREAD

**Issue by mid-kid** [libredirect/libredirect#427]
Testing for latency helps a little in figuring out which instances are still alive, as some of them never resolve or return an HTTP error code. However, I've noticed while testing for latency on the libreddit instances, that the ones that are *too fast* tend to be broken too, as they return static pages for unused domains, https://libreddit.autarkic.org/ and https://libreddit.awesomehub.io/ among them.

Since it's impossible to keep track of all working instances at all times, I'd like a proper "test instance" button, that not only measures the latency of the HTTP request, but also looks for some static text or code in the resulting page, to make sure it's actually working. This would make it easy for people to spot instances that are broken on their end (maybe due to ISP blocks even) and disabling them, before the instance randomizer puts them through a blank page.

**Comment by EdwardLangdon** [comment]
This has been completed here : https://codeberg.org/LibRedirect/libredirect/issues/2

**Comment by mid-kid** [comment]
Thanks a ton!
