### ISSUE TITLE
Unfork repository

### ISSUE THREAD

**Issue by deathtrip** [libredirect/libredirect#429]
Now that this project has outgrown the original repo, it would be a good time to unfork it.
It will increase the visibility of this project, as forks are not included in github search results.
It's hard enough to find it already, with it not being in the chrome webstore.

**Comment by EdwardLangdon** [comment]
This is a great request. But this totally depends on the maintainers and main devs of LR.

**Comment by ManeraKai** [comment]
I'm with it, we're now a separate entity.

**Comment by alefvanoon** [comment]
https://ralphjsmit.com/unfork-github-repo
