### ISSUE TITLE
Firefox 99.0.1 default instances issue

### ISSUE THREAD

**Issue by Gottarocket** [libredirect/libredirect#431]
None of them show default instances and ones added under custom instances doesnt save. Privacy redirect works on this version . Cant update firefox due to restrictions on pc I use.

**Comment by Dyras** [comment]
Off-topic but can't you install Firefox from the Microsoft Store and get updates that way?

**Comment by Gottarocket** [comment]
Not sure if its Firefox version issue. It was just mentioned to narrow down why there is no default instances.  I have set the flag to false in about:config. Just wanted to know if anything else needs to be done

**Comment by EdwardLangdon** [comment]
Is the version you are using a ESR version or out-of-date version ?

Latest Version is 103. Please Update to it and try.

**Comment by ManeraKai** [comment]
Is this issue still happening? Did you try to reset settings one time?

**Comment by IkelAtomig** [comment]
This issue shouldb't be happening as it is fixed in v2.3.1. The Issue has no response from author and stale. So Closing.
