### ISSUE TITLE
YouTube subscription 

### ISSUE THREAD

**Issue by D3FALT404** [libredirect/libredirect#437]
Is there any way to sync YouTube subscription between instance?

**Comment by ManeraKai** [comment]
For invidious?

**Comment by ManeraKai** [comment]
For invidious?

**Comment by D3FALT404** [comment]
Yeah for example, BTW THIS PROJECT IS BRILLIANT IDEA,!! Great job

**Comment by ManeraKai** [comment]
For libreddit you can "Unify" the subscription list as it's stored in the cookies, but for invidious it's stored on the server for each account. We can't Unify that to other instances.

**Comment by EdwardLangdon** [comment]
This is now implemented with piped as they added account-less subscriptions, which will come with v2.3.0. But will not be availble in Invidious as it is totally server-side.
