### ISSUE TITLE
Youtube Redirect Bugs

### ISSUE THREAD

**Issue by SD745** [libredirect/libredirect#44]
When trying to modify the settings for Piped and Invidious, the options for Theme, Autoplay Video and Always proxy videos don't seem to save and persist after changing them from default, leaving the page then returning to it.

**Comment by ManeraKai** [comment]
Example, I think it does that if the server redirects you in invidious case?

**Comment by SD745** [comment]
Another big issue however seems to be the with the Persist preferences (as cookie) parameter which doesn't work at all, I have tested both with a link to a video and YouTube/Invidious homepage with neither resulting in a PREFS cookie being generated.

**Comment by ManeraKai** [comment]
> Persist preferences (as cookie) parameter which doesn't work at all

It's literally isn't implemented. I forgot whether I disabled it intentionally or not. Will add it.

**Comment by ManeraKai** [comment]
Fixed all the issues. If you want to test it before release, the steps are in the README.

**Comment by ph00lt0** [comment]
Configuring "Always proxy videos" -> true always resets to false on reload of the settings page.

**Comment by SD745** [comment]
> Configuring "Always proxy videos" -> true always resets to false on reload of the settings page.

I have also noticed this behaviour in testing it seems a PREFS cookie is being generated now, however the "local" variable never gets created in order to set videos to proxy.

**Comment by ManeraKai** [comment]
> I have also noticed this behaviour in testing it seems a PREFS cookie is being generated now, however the "local" variable never gets created in order to set videos to proxy.

I was changing `sync` to `local` on all the files. Then reverted back. I replace all `local` words with `sync` you even can see a weird `sync` setting in your cookies. Fixed.

**Comment by ManeraKai** [comment]
The others issues I think they've been fixed before.
