### ISSUE TITLE
Remove Bibliogram 

### ISSUE THREAD

**Issue by SoftwareRat** [libredirect/libredirect#440]
The project is discontinued, and many instances are already not working

**Comment by kadogo** [comment]
In my opinion, disable by default would be better.
People can still setup their own instance if they want.

Where did you read that it was discontinued?

**Comment by EdwardLangdon** [comment]
@kadogo The Maintainer published a reddit post recently about the announcement.

@SoftwareRat We will make LR to redirect posts only and place a HTML page why we can't redirect to accounts.

We don't plan of removing Bibliogram unless a viable alternative is found out.

**Comment by pitsi** [comment]
I was about to open an issue with the same request, but I waited for today and someone beat me to it :p
Here is the official announcement from bibliogram's dev
https://cadence.moe/blog/2022-09-01-discontinuing-bibliogram

As for alternatives, there are a lot of sites that scrape instagram, but their code is not opensource and neither they follow a specific pattern that would allow easy redirections.

**Comment by EdwardLangdon** [comment]
There is a certain named Imginn (Imginn.com) that follows the exact URL scheme AFAIK. But I don't know what's the take by the team to do it.

**Comment by AlyoshaVasilieva** [comment]
Bibliogram can't load user pages, but it still works to load posts for now.

**Comment by ManeraKai** [comment]
It's still used by many, so we'll keep it for the mean time and maybe for more in the future until Instagram itself gets replaced...

**Comment by pitsi** [comment]
Which instances of instagram do work today, excluding any instance that someone may run in private? The only one that I have found running is the one from domain.glass, but this one has been broken before instagram's changes, along with almost every other service hosted by the same page!

Moreover, cadence has even deleted the table of available instances from his page.
https://git.sr.ht/~cadence/bibliogram-docs/tree/master/docs/Instances.md

**Comment by AlyoshaVasilieva** [comment]
`bibliogram.froth.zone`, `ig.tokhmi.xyz`, `ig.beparanoid.de` all could load a post when I checked just now. Also my private instance. No instance can load user pages, of course.

**Comment by pitsi** [comment]
I never knew those instances, sorry :(

**Comment by MintMain21** [comment]
This really should be re-opened and renamed "Find alternative to Bibliogram".

The issue really is something that deserves attention.

**Comment by ManeraKai** [comment]
All the other alternatives are worse in terms of privacy. There's no instagram privacy focused frontend other than BIbliogram.
