### ISSUE TITLE
Feature Request: Redirect other frontends too

### ISSUE THREAD

**Issue by thecashewtrader** [libredirect/libredirect#441]
I wonder if it could be possible to have libredirect redirect other frontends of a service too.

For example:
Say I have YouTube set up to redirect to Piped.
- YouTube redirects to Piped
- Invidious doesn't redirect to Piped
- Invidious should be redirected to Piped too.

In case I commit https://xyproblem.info, the use case that propped this feature request is (some of this is irrelevant but I'm mentioning it just in case):
- I have subscriptions to YouTube using feeds.
- Since Piped doesn't have feed proxying, I use Invidious for the feeds for privacy.
- The Invidious feeds have a link to the invidious instance and not YouTube (if it was YouTube libredirect would kick in)
- Now I have to manually copy and change the links or open the libredirect extension menu and click "Change Instance"

A bit nitpicky but would nevertheless be a nice addition to an already amazing extension :)

**Comment by EdwardLangdon** [comment]
The Feature you request was already present in Libredirect named as 'Redirect to Preferred Frontends'. But due to Code Complexity, it was removed in later versions.

But you can force Invidious to Piped. If you want - https://libredirect.github.io/preferred_instance

**Comment by thecashewtrader** [comment]
> The Feature you request was already present in Libredirect named as 'Redirect to Preferred Frontends'. But due to Code Complexity, it was removed in later versions.
> 
> But you can force Invidious to Piped. If you want - https://libredirect.github.io/preferred_instance

How did I forget to check the docs! Sorry!
