### ISSUE TITLE
Remove 076.ne.jp

### ISSUE THREAD

**Issue by pjalsGit** [libredirect/libredirect#442]
076.ne.jp is extremely toxic, transphobic, homophobic, and all the other bad stuff.

Proof: (CW, obviously)
https://pleroma.envs.net/notice/AKlwYT7CdT1gfhKKum
https://pleroma.envs.net/notice/AMDeyg4xakMyfkqfPk (literally by the admin)

**Comment by pjalsGit** [comment]
Yup

**Comment by ManeraKai** [comment]
We don't control the public lists: https://libredirect.github.io/faq.html#where_the_hell_are_those_instances_coming_from
If you want to remove any instance from lets say nitter's list, then you should go to nitter's repository and tell them. If they happened to modify the list, it will be updated from our side in 3 days or less.
