### ISSUE TITLE
some weird shit going on

### ISSUE THREAD

**Issue by thiccelf83** [libredirect/libredirect#447]
Hi, first this quit working for firefox, and then, it would randomly redirect to various malware or adware sites instead of any of the given mirrors, when I went to a given mirror manually it did not redirect to bad sites.

This went on until libredirect quit working on firefox entirely.

Then, several months later it is now doing the same damn thing  on chrome

**Comment by thiccelf83** [comment]
I know I am going to get gate keeped by some backseat moderator who doesnt give a shit and just wants to pretend to be powerful, whoever that ends up being, you can suck my balls

**Comment by ManeraKai** [comment]
It's bc some instances were outdated and they're became ad websites. Just press "Update Instances" in the settings.
