### ISSUE TITLE
Make it easier to remove an instance from random pools

### ISSUE THREAD

**Issue by Huy-Ngo** [libredirect/libredirect#449]
In many occasions, the instances the addon redirects to is dead or blocked for various reasons. The user may want to remove such instances from the random instance pool, or even report it upstream.

I suggest below the "Switch Instance" button, there is also a "Remove this instance" one.

**Comment by EdwardLangdon** [comment]
It would make the `data.json` (file containing all instances and up-to-date) change and other selected instances keep on resetting, When you remove one from the list.

The best way to avoid dead instances is updating them every week.

Even if you want to want to remove them, it can only be done after v2.3 is released and dependent on this PR : https://github.com/libredirect/libredirect/issues/334

> I suggest below the "Switch Instance" button, there is also a "Remove this instance" one.

We will add the `Disable instance` button in the popup.

**Comment by ManeraKai** [comment]
More of thought and using this button will be so rare on the fact that it will use so much space in the popup. So we won't add it.

**Comment by Huy-Ngo** [comment]
I think this is already implemented (with the toggle at top, can't screenshot), so probably should've been closed as such.

**Comment by ManeraKai** [comment]
No we'll remove that toggle as the design of it is really bad.
