### ISSUE TITLE
LibReddit breaks Reveddit

### ISSUE THREAD

**Issue by iblowmymind** [libredirect/libredirect#453]
Having Reddit redirection on will break Reveddit, as, even when you're not logged into Reddit, Reveddit will attempt to POST https://www.reddit.com/api/v1/access_token and wait as the URL gets redirected to a LibReddit instance, and eventually fails.

A potential workaround to this would be to disable Reddit redirection each time when loading Reveddit but that's not really ideal. Maybe add an exclusion for this URL?

NOTE: On Firefox, having Enhanced Tracking Protection would block this URL, however this issue is not related to that.

**Comment by ManeraKai** [comment]
Try having:
- https://reveddit.com
- https://www.reveddit.com
as exceptions in the general page in the settings

**Comment by iblowmymind** [comment]
Don't think that would work, as Reveddit isn't the thing being redirected, the actual API request URL is.

**Comment by iblowmymind** [comment]
And note: I can't add any specific URL paths in exceptions, it strips them down to their domains.

**Comment by iblowmymind** [comment]
Solution: Add "https:\/\/www\.reddit\.com\/api\/v1\/access_token" add a REGEX in exceptions.

I still believe that full URL paths should be accepted as exceptions, not just domains.
