### ISSUE TITLE
Problem with Twitter redirect

### ISSUE THREAD

**Issue by heywolf15** [libredirect/libredirect#454]
Windows 10, Firefox 104.0.2
When not on any instances (twitter.com) but Redirect enabled for twitter and the redirect type on both

- trying to follow or unfollow, it will look succeed visually but after reload it just back unchanged
- Notifications will not work even when the push notification has been enabled

All of that problem can be solved by disabling redirect or change redirect type to "only not embedded". This should be noted somewhere for everyone to know that the disadvantage for using redirect type on both

**Comment by EdwardLangdon** [comment]
This is fixed in an upcoming release.

**Comment by heywolf15** [comment]
Thanks

**Comment by heywolf15** [comment]
I forgot, it also applies to notification bell

**Comment by ManeraKai** [comment]
Fixed,
