### ISSUE TITLE
Exporting Libredirect Settings

### ISSUE THREAD

**Issue by fastcat001** [libredirect/libredirect#455]
Hello, please give an option to export Libredirect settings.

I put many hours to my preferred instances and sometimes
updates break my settings.

**Comment by EdwardLangdon** [comment]
You can export it already. Just Open settings, you can see it under General and you can also import it.

**Comment by EdwardLangdon** [comment]
![image](https://user-images.githubusercontent.com/101938856/191295381-4716c7be-1b07-43c8-9fd6-eabdcd1c078f.png)
