### ISSUE TITLE
Unify Settings not working on some frontends

### ISSUE THREAD

**Issue by umbralOptimatum** [libredirect/libredirect#457]
Firefox 105. Unifying settings isn't working for me on some sites. On Invidious and Nitter, changing a setting on one instance and unifying has no effect on the other instances I checked. However, unifying worked just fine on Teddit.

**Comment by EdwardLangdon** [comment]
Just be sure that the instances you need to be unified are selected in Instance list. Both of the instances should be selected in order to unify.

Note that, Only settings are unified between instances that are selected not for unselected ones.

**Comment by EdwardLangdon** [comment]
1. You changed settings on Instance 1
2. Ensure you have selected other Instances
3. Clicked on Unify, It doesn't work ?

If clicking doesn't work, Maybe you could try the clipboard shortcut ?

**Comment by EdwardLangdon** [comment]
That doesn't do anything, the extension just copies the settings stored and paste it under the other selected Instance's domain name.

> Exactly. What's the clipboard shortcut?

https://libredirect.github.io/docs.html#Keyboard_Shortcuts

**Comment by EdwardLangdon** [comment]
We think that v2.3 might fix your issue.

**Comment by EdwardLangdon** [comment]
This is an upstream issue.
For some reason Invidious makes the cookies' url `.<domain>` instead of `<domain>`.

Unify settings for other frontends are fixed in upcoming release.

**Comment by EdwardLangdon** [comment]
What Device and Browser are you using ?

**Comment by EdwardLangdon** [comment]
Go to `about:debugging`, click this firefox, inspect libredirect, go to console, try it again and then send screenshot.

**Comment by EdwardLangdon** [comment]
Can you show the cookies of the site unified from in the console and the other enabled instance ?

**Comment by EdwardLangdon** [comment]
Better make an issue. I will update it on free time or PRs are welcome too.

**Comment by wrhou** [comment]
Hello. First of all thank you for making this extension. I can't imagine browsing the web without it anymore!

> Go to `about:debugging`, click this firefox, inspect libredirect, go to console, try it again and then send screenshot.

I have a similar issue where I also cannot unify settings for Nitter and Libreddit. This is the output I got when I followed the above steps:

```
Uncaught (in promise) TypeError: can't access property Symbol.iterator, cookies is undefined
    copyCookie moz-extension://19ede322-c19d-40ea-9c86-5b30c1dcc387/assets/javascripts/utils.js:302
10 utils.js:302:25
    copyCookie moz-extension://19ede322-c19d-40ea-9c86-5b30c1dcc387/assets/javascripts/utils.js:316
    apply self-hosted:2874
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:625
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:827
    withLastError resource://gre/modules/ExtensionCommon.jsm:746
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:815
```

Screenshot: https://ibb.co/TtZ1p7z

I'm using Firefox Nightly 108.0a1 (2022-11-10) (64-bit) on Windows 11 Enterprise 22H2. All 3rd party browser extensions were disabled.
