### ISSUE TITLE
Unify Settings not working in Firefox private windows

### ISSUE THREAD

**Issue by umbralOptimatum** [libredirect/libredirect#458]
Unify settings does not work in Firefox private windows. Doesn't change settings, the unify settings button doesn't appear, nothing.

I expect this is known behavior but I couldn't find a corresponding issue.

**Comment by ManeraKai** [comment]
Yes, Unify doesn't support incognito mode. It did before but it was a hassle and illogical to the idea behind incognito windows so we removed support for it.

**Comment by ManeraKai** [comment]
@EdwardLangdon

**Comment by MintMain21** [comment]
So.... we're never going to see Unify Setting Support in Private Browsing ever again?
