### ISSUE TITLE
[Enhancement] Option to disable Piped/Invidious embeds in some sites

### ISSUE THREAD

**Issue by stephenhawk8054** [libredirect/libredirect#46]
Because of how each site implementing YouTube Player API, there might be some sites that can't play Piped/Invidious embedded videos. In this case, I think we could implement an `Exceptions` part in YouTube section so users can add their own whitelisted sites that are not compatible to Piped/Invidious embeds.

URL to test (I'm not sure if the site could be region-blocked or not):

```
https://xahoingaynay.com.vn/video/bi-quyet-xem-bong-da-cua-blv-quang-huy.html
```

Configuration: enabling Piped with `both` or `Only Embedded Videos`
Behavior: clicking on the button to play cannot trigger the video player to play.

Users can input the site `https://xahoingaynay.com.vn` as an exception to not redirecting that embedded video to Piped/Invidious.

---

Approach: with `onBeforeRequest` API, we can extract `frameAncestors` attribute which indicate the `main_frame` of the site (in this case `https://xahoingaynay.com.vn/video/bi-quyet-xem-bong-da-cua-blv-quang-huy.html`).

When I edited the code in `background.js` like below and rebuilt the extension, I can force Libredirect to not using redirections on this site, but still work normally on other sites, for example `https://developers.google.com/youtube/iframe_api_reference`:

<details><summary>background.js</summary>

```js
"use strict";

import youtubeHelper from "../../assets/javascripts/helpers/youtube/youtube.js";
import twitterHelper from "../../assets/javascripts/helpers/twitter.js";
import instagramHelper from "../../assets/javascripts/helpers/instagram.js";
import redditHelper from "../../assets/javascripts/helpers/reddit.js";
import searchHelper from "../../assets/javascripts/helpers/search.js";
import translateHelper from "../../assets/javascripts/helpers/translate.js";
import mapsHelper from "../../assets/javascripts/helpers/maps.js";
import wikipediaHelper from "../../assets/javascripts/helpers/wikipedia.js";
import mediumHelper from "../../assets/javascripts/helpers/medium.js";
import imgurHelper from "../../assets/javascripts/helpers/imgur.js";
import tiktokHelper from "../../assets/javascripts/helpers/tiktok.js";
import exceptionsHelper from "../../assets/javascripts/helpers/exceptions.js";

// Adding exception URLs
var exceptionUrls = [
  "https://xahoingaynay.com.vn",
];

window.browser = window.browser || window.chrome;

function wholeInit() {
  mapsHelper.init()
  searchHelper.init()
  translateHelper.init()
  instagramHelper.init()
  mediumHelper.init()
  redditHelper.init()
  twitterHelper.init()
  wikipediaHelper.init()
  youtubeHelper.init()
  imgurHelper.init()
  tiktokHelper.init()
  exceptionsHelper.init()
}

wholeInit();

browser.storage.onChanged.addListener(wholeInit);

browser.webRequest.onBeforeRequest.addListener(
  (details) => {
    const url = new URL(details.url);
    let initiator;
    if (details.originUrl)
      initiator = new URL(details.originUrl);
    else if (details.initiator)
      initiator = new URL(details.initiator);

    var newUrl;

    if (exceptionsHelper.isException(url, initiator)) newUrl = null;

    else if (youtubeHelper.isYoutube(url, initiator)) {
      newUrl = youtubeHelper.redirect(url, details.type);
      // Check if frameAncestors is in exception lists or not
      for (const except of exceptionUrls) {
        if ((details.frameAncestors.length !== 0) && details.frameAncestors[0].url.startsWith(except))
          newUrl = null;
          break;
        }
      }
    }
    // ...
  });
// ...
```

</details>

I'm not good at coding so this is the best I can do to describe it. Hope it helps.

**Comment by ManeraKai** [comment]
Isn't the general exception list sufficient for this?

**Comment by ManeraKai** [comment]
oh sorry, ofc it can't. The exceptions should be every url that is a `sub_frame` in a url.

**Comment by ManeraKai** [comment]
This is my first try. I didn't test it much yet.

**Comment by stephenhawk8054** [comment]
Oh tks, I'll test it when I'm back to my computer.

**Comment by stephenhawk8054** [comment]
I confirm it works for me so far 👍 Tks a lot for adding this feature.
