### ISSUE TITLE
Feature Request: Redirect YouTube videos to LBRY/odysee

### ISSUE THREAD

**Issue by Raj2032** [libredirect/libredirect#462]
There is a feature on odysee that allows the content creator to sync their videos from YouTube to [LBRY](https://lbry.com/)/[odysee](https://odysee.com/)

I was wondering if I clicked on a YouTube link, if the video was available it would redirect me to Odysee, otherwise to an of the open source front end client of YouTube.

This is to try and help people move away from YouTube even further.

**Comment by ManeraKai** [comment]
There's already an extension for this though: https://addons.mozilla.org/en-US/firefox/addon/watch-on-odysee/
