### ISSUE TITLE
Re-Add Redirection to old.reddit.com

### ISSUE THREAD

**Issue by fastcat001** [libredirect/libredirect#463]
Hello, I remember you had redirection to old reddit dot com.

Please, add again in the new release and do not remove.

**Comment by ManeraKai** [comment]
Read this: https://libredirect.github.io/faq.html#suggest_frontend

**Comment by fastcat001** [comment]
@ManeraKai , I read, but I do not want to install extra add-on, I prefer have only one - Libredirect

**Comment by EdwardLangdon** [comment]
Old reddit attempts to extract canvas data which is a way of tracking. So, We won't add it back.

**Comment by pflanzenandi** [comment]
But shouldn't it be possible for the user to add a custom instance like `https://old.reddit.com`?
For me it doesn't work in FF . Either I get a blank error page or my custom instance is getting ignored completely by 
LibRedirect addon.

**Comment by EdwardLangdon** [comment]
If you want old reddit, Why not use Teddit ?

---

It is because of the word `reddit.com` which caughts in the RegEx `old.reddit.com` doesn't redirect.
You are trying to redirect to a site which is already needs to be redirect causing a loop to redirect again and again.

**Comment by fastcat001** [comment]
@EdwardLangdon Teddit does not allow log in

**Comment by EdwardLangdon** [comment]
It is no longer private as you login. Libredirect redirects from sites to its alternnative frontends which respects and gives user's privacy.

**Comment by ManeraKai** [comment]
That old reddit extension has already 36,500+ users on FF and 90,000+ on chrome. There's just no need to replicate it here.
