### ISSUE TITLE
Feature Request: Go to frontend from original site

### ISSUE THREAD

**Issue by Seercat3160** [libredirect/libredirect#464]
It would be great if the extension menu also had the "Switch Instance" button available when the current tab is the original website. This would be helpful in situations when one doesn't want to always use an alternative instance, but wants to sometimes quickly switch to one.

**Comment by EdwardLangdon** [comment]
I am unsure with description. Could you explain it ?

**Comment by Seercat3160** [comment]
Ok, here's an example:

1. The user browses to `youtube.com`, and because they have redirecting disabled for YouTube, they load `youtube.com`.
2. They go to a video, and then wish they had it open in Invidious instead. 
3. Currently, they would have to manually open one of the Invidious instances and navigate to the same video. I propose that they should be able to click the LibRedirect icon in their browser, and click the `Switch Instance` button to be redirected to an Invidious instance, just like someone already on one could do to move to another.

**Comment by EdwardLangdon** [comment]
I understand now. Thanks for the clarification. It would be better to have the feature named as "Go to frontend"

**Comment by ManeraKai** [comment]
You can just refresh when you enable the redirection for YouTube and it will redirect properly.

**Comment by EdwardLangdon** [comment]
But the user wants to go the frontend without enabling the redirect function.
