### ISSUE TITLE
Firefox Send

### ISSUE THREAD

**Issue by TechnologyClassroom** [libredirect/libredirect#466]
This is a little different of a request.

It would be nice if libredirect could redirect https://send.firefox.com/ to one of the [Send instances](https://gitlab.com/timvisee/send-instances).

Firefox Send was discontinued and picked up by Tim Visée currently being maintained on [GitLab](https://gitlab.com/timvisee/send).

https://send.firefox.com/ currently just redirects to https://www.mozilla.org/ which isn't helpful.

**Comment by ManeraKai** [comment]
We're doing it in this issue: https://github.com/libredirect/libredirect/issues/466 👍️
