### ISSUE TITLE
Alternative Logo Proposal

### ISSUE THREAD

**Issue by SecularSteve** [libredirect/libredirect#468]
It took me a minute to make in Inkscape.
It could be used for the nightlies, or for user preference. Depending on what they think looks best with their browser. Like a skin add-on or something.

Or maybe if they want to turn on a "safe mode" or something pre-configured for beginners.

But those are just my suggestions. It's your software.

![libredirect_alt](https://user-images.githubusercontent.com/33793273/192765827-41e60de3-a9c9-4094-972a-fe78028db1d1.svg)

**Comment by EdwardLangdon** [comment]
I think we could use this for Libredirect Lite which Mv3 version of Libredirect like uBO lite.

**Comment by ManeraKai** [comment]
It's so different though from the original logo. Even the colors are different. Tbh I really like the current logo. I want it to stay to and be stable so we it will be knowable among internet users.

**Comment by SecularSteve** [comment]
> It's so different though from the original logo. Even the colors are different. Tbh I really like the current logo. I want it to stay to and be stable so we it will be knowable among internet users.

I never tried to insinuate it as a replacement, just an alternative for the "Lite" or the "Nightly" versions of this fantastic software.
Maybe LibRedirect can come with a "Safe Mode" for people who want either the barest minimum in setting it up, or to disable all of the Cloudflare instances completely, or something.

But those are just my minor suggestions, it's CC BY-SA 4.0 anyway, and your software. Do whatever comes naturally.

**Comment by ManeraKai** [comment]
See my [last comment](https://github.com/libredirect/libredirect/issues/510#issuecomment-1296196121) about LibRedirect Lite and you may add this logo like that.
