### ISSUE TITLE
Whoogle redirects back to google.

### ISSUE THREAD

**Issue by Latrolage** [libredirect/libredirect#47]
I've found that the search redirects are inconsistent and sometimes it will redirect from whoogle to google.

I went from:
https://search.albony.xyz/search?q=search&cookies_disabled=1
To:
https://google.com/element?url=gAAAAABiEQAQQshQKeyzl2Z30Z0rL-_IE4uZO73YViugqIiL6s-o-2XACFhT8WlAHVQJhn_qSWcCOhAT_nquKOV_M9FRW6CrrNwugIypKGetc1MhmDcK6MFsgr7tNvM0L1HppooLsxP4Vl6NHy0A_qjLxUdBSuTj4xgVjwZYne3GdGVnf9mICq-lniuP42WsdQh-IuvRmwAqVg1h2_y-s5Ae5iwZAExqAkHT6H5-LPbg7NLbGuqwWEk=&type=image%2Fpng

Disabling libredirect fixed it, disabling just redirects for "search" in libredirect didn't do anything

**Comment by ManeraKai** [comment]
Which version you're running? Does it happen every time you type that url?

**Comment by Latrolage** [comment]
libredirect version 1.3.4 But not i've found that it doesnt' happen on another browser. And it doesn't redirect me if i remove the `&cookies_disabled=1` portion of the URL. I'm guessing it's a problem with my browser settings in combination with libredirect. I'm not too sure though. My cookie settings are default on both browsers

**Comment by Latrolage** [comment]
It also seems to be just that instance of whoogle. I'll just disable it on my list to workaround it

**Comment by ManeraKai** [comment]
Why you closed the issue if it's not just one instance?

**Comment by Latrolage** [comment]
Well i restarted my ff profile in the end which fixed it, so im not sure. sorry....

**Comment by ManeraKai** [comment]
> restarted my ff profile

what's that exactly?

**Comment by Latrolage** [comment]
Yes

**Comment by ManeraKai** [comment]
I'll close the issue then.
