### ISSUE TITLE
Feature Request: Copy RSS links for private frontends as "Raw URL links" (YouTube, Twitter etc) from the Context Menu.

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#471]
With the latest update to LibRedirect, I can see that the Context Menu is now being used more extensively. 

I figured this would be a good opportunity to recommend a feature that may sound contradictory, but I think would be helpful all the same.

In Invidious, there's a way to easy copy the YouTube link for either videos you are watching or videos you are searching, helpful predominantly as a backup option if the current instance isn't working or you need to use the default YouTube UI, but equally helpful for sharing links on social media with people who would not be familiar with the front-end of your choice (not to mention, preserves the link in the event of the instance going down).

While this feature is recreated natively in other front-ends like Nitter, it's not a universal feature. 

So I think it would be nice if there was a context menu option in LibRedirect to copy the URL of a redirected page _as the URL of the original site_.

It might also be helpful when copying RSS links for channels in Invidious to also have the option to copy it's respective YouTube URL, as YouTube RSS feeds are generally more reliable than the RSS feeds for the private front-end. 

I would not be suggesting this feature if I did not believe in this extension's capabilities to redirect any and all YouTube/Twitter etc links to the appropriate site, as I believe it's easier to recommend this extension to people who want to try private front-ends than it is to recommend individual instances in themselves. You have come a long way from being a mere Privacy Redirect fork.

**Comment by MintMain21** [comment]
Uhhh... so for funsies I decided to browser the official FAQ, and I found this under keyboard shortcuts.

![image](https://user-images.githubusercontent.com/91362684/194775346-c31c5986-dfa2-4c50-a799-14547a766b94.png)


So the feature to copy the original link is already built into the extension as a keyboard shortcut. I guess I'm the fool for not catching up on the documentation. 

Nevertheless, a UI option like a context menu as proposed above would still be welcome.

**Comment by ManeraKai** [comment]
Copy Raw

**Comment by MintMain21** [comment]
> Copy Raw

I beg your pardon?

**Comment by ManeraKai** [comment]
![image](https://user-images.githubusercontent.com/40805353/194775755-aaa57fdf-dc18-49f3-85f6-67c67bfeb791.png)

**Comment by MintMain21** [comment]
Ooooooh!

I see.
Well, all that leaves now is, I'd like a context menu option to "Copy Raw" RSS URLs.

And maybe just a "Copy Raw URL" option for the context menu too.

**Comment by ManeraKai** [comment]
![image](https://user-images.githubusercontent.com/40805353/194776424-04f98908-9153-4498-b8c4-1b1544e74dfa.png)

**Comment by MintMain21** [comment]
At this point all I want then is to copy RSS urls as "Raw URLs".

**Comment by MintMain21** [comment]
Oh, and another thing, "Copy Raw" is not a option on Wiki-Less, which is the front-end that inspired this request in the first place.

**Comment by ManeraKai** [comment]
Can you give me an example please of an RSS url?

**Comment by MintMain21** [comment]
I have a rule set up in redirector that is as follows.

Redirect: https://[Instance Domain Here]/feed/channel/*

To: https://www.youtube.com/feeds/videos.xml?channel_id=$1

Example: https://[Instance Domain Here]/feed/channel/UCOkL7q2SeGZeZuj22njMYEA → https://www.youtube.com/feeds/videos.xml?channel_id=UCOkL7q2SeGZeZuj22njMYEA

**Comment by ManeraKai** [comment]
One second, you can't actually copy the raw of that bc it directly downloads the file without letting you go to a specific page:
![image](https://user-images.githubusercontent.com/40805353/206842607-7f5677ca-997e-4c24-acf0-f3934d2bea25.png)

**Comment by MintMain21** [comment]
Have you tried using it with an extension like FeedBro installed?

**Comment by ManeraKai** [comment]
Ok? the behavior doesn't change.

**Comment by ManeraKai** [comment]
I'm gonna close this issue as you can't enter the page without it downloading automatically and the use case for copying a raw invidious rss link is very little.

**Comment by MintMain21** [comment]
@ManeraKai 

My Invidious Preference Userscript (the same one I keep mentioning in #491 etc) now has the feature to copy Feed URLs as YouTube URLs instead of Invidious URLs. 

[Take a look for yourself](https://github.com/MintMain21/Invidious-Preferences-Userscript). By all means, borrow and apply the code for LibRedirect if you wish.
