### ISSUE TITLE
LibRedirect Settings Page freezes Android (Firefox).

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#472]
Using Firefox on Android, LibRedirect works fine so long as you use it "as is", but attempting to open the settings page to toggle anything will cause the entire browser to freeze.

With the latest update fixing nearly everything on Desktop, I'm eager to use the extension on Android as well. This bug is the only thing keeping me from adopting the extension completely.

**Comment by EdwardLangdon** [comment]
Libredirect is not officially supported by us or tested for android. So, It is expected.

**Comment by MintMain21** [comment]
Nevertheless, reporting these issues is the beginning of improving compatibility and reaching official support.

**Comment by ThracianKnight1907** [comment]
As a workaround, exporting settings on desktop and importing them on mobile seems to work.

**Comment by EdwardLangdon** [comment]
I think this can be closed as a workaround seems to be there.

**Comment by Generator** [comment]
@IkelAtomig not really. If the user is outdoor or don't have access to a desktop at the moment and needs to make changes, like some instances are offline some sites became unusable, the only way to use them is disabling the app.

**Comment by IkelAtomig** [comment]
> the only way to use them is disabling the app.

App ?

**Comment by ManeraKai** [comment]
> Nevertheless, reporting these issues is the beginning of improving compatibility and reaching official support.

The main problem is that no browser app supports extensions, just a very little amount. Some of them are just beta versions even. It would be just a waste of time to support Android bc of that.
