### ISSUE TITLE
Option to remove the context menu item

### ISSUE THREAD

**Issue by AliRezayiNejad** [libredirect/libredirect#474]
Great if it was possible to remove "Toggle redirects in this tab" for those that enjoy a decluttered context menu.
Same thing with the "LibRedirect" option on the Firefox search engine list. As hiding or removing it is temporary even if you do not use LibRedirect for web search.

**Comment by MintMain21** [comment]
I was actually thinking there are a lot of ways to expand options for the context menu, but a good place to start would be whether users actually want the context menu enabled or not.

**Comment by ManeraKai** [comment]
I think it should be only shown on only supported sites.

**Comment by SkMyPP** [comment]
No, there should also be an option to completely disable it.
