### ISSUE TITLE
Can't open the original link from permalink provided by Frontends

### ISSUE THREAD

**Issue by HDark15** [libredirect/libredirect#475]
When on Nitter clicking or open it on the new tab "open in Twitter"  it always goes back to the instances
I don't know if this supposes to be like this, but it's not the case from previous version

**Comment by EdwardLangdon** [comment]
This is verifiable and will be possibly made into v2.3.1 (Hotfix)

**Comment by AliRezayiNejad** [comment]
This issue is not exclusive to Nitter, libreddit's "reddit" button also redirects to another instance instead of the original Reddit page.

**Comment by EdwardLangdon** [comment]
Try using the toggle redirects in tab context menu.

**Comment by MintMain21** [comment]
Any update?

**Comment by EdwardLangdon** [comment]
Did you try toggling as said ?

**Comment by EdwardLangdon** [comment]
@Impeta I did so but could you use the context menu for now while we work on a smart auto bypass detection ?

**Comment by dvoraking** [comment]
I have the same problem with Youtube/Invidious. On 2.3.1 Firefox and Chromium.

**Comment by EdwardLangdon** [comment]
I see it is still there. I could replicate too.

It is because we are going to work on `Smart Bypass Redirection` for this, A better way to allow Bypass and not let something accidentally bypass LR. Currenlty using Toggles via Context menu or temporarly disabling redirects is better one.

**Comment by gokberkgunes** [comment]
This problem appears to be still prevalent, but the issue is closed. Did https://github.com/libredirect/libredirect/commit/4625aa07feb647ecbaa9a2316e778a7bcc01c605 genuinely fix redirect to original website bug?

**Comment by IkelAtomig** [comment]
@gokberkgunes It did fix. It was assigned to the milestone. We will release once all others in milestone is finished.
