### ISSUE TITLE
Indicate libreddit instances with and without video sound

### ISSUE THREAD

**Issue by JediMaster25** [libredirect/libredirect#477]
There are some instances that don't have sound enabled even when I check `Use HLS for videos`. I would like to see which instances are those that have video sound enabled from the select instance list in libredirect.

**Comment by EdwardLangdon** [comment]
Any Example Instances ?

**Comment by JediMaster25** [comment]
[libreddit.pussthecat.org allows it](https://libreddit.pussthecat.org/r/funny/comments/y19kmc/happiest_dad_in_the_world/), and [lr.riverside.rocks doesn't](https://lr.riverside.rocks/r/funny/comments/y19kmc/happiest_dad_in_the_world/)

**Comment by ManeraKai** [comment]
Nope:

https://user-images.githubusercontent.com/40805353/196034187-f5ae4fa4-8b8e-4b4a-b2bd-a0819a271cb1.mp4

**Comment by JediMaster25** [comment]
You were right. I hadn't enabled javascript in all the instances I was using. My bad.
