### ISSUE TITLE
Bug when adding a new exception

### ISSUE THREAD

**Issue by ownchoice** [libredirect/libredirect#478]
Hi, I updated Libredirect to 2.3 and now I can't add an exception.

If I put `https://old.reddit.com`, the exception added shows up as `undefined//old.reddit.com` and the extension keeps redirecting `old.reddit.com` URLs.

![image](https://user-images.githubusercontent.com/22414323/195328296-c93e25b2-c6db-4d3b-8a0c-fe83b68298e2.png)

I'm using Brave on Windows 11.

Version 1.44.108 Chromium: 106.0.5249.103 (Official Build) (64-bit)
Microsoft Windows 11 Pro 10.0.22621 Build 22621

**Comment by EdwardLangdon** [comment]
Verifiable, WIll be worked in Hotfix.
