### ISSUE TITLE
YouTube embedded player frame broken after updating to 2.3.0

### ISSUE THREAD

**Issue by xfzv** [libredirect/libredirect#481]
[Link to reproduce](https://deathgrind.club/posts/77632) (click on "Open YouTube Player": ![image](https://user-images.githubusercontent.com/78810647/195445968-36a1a997-be9a-4b13-bd27-2f804a3d4624.png))

- With 2.2.1 :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/78810647/195445493-15b01ed4-54cf-4fc9-93f4-9cdf75395846.png)

- With 2.3.0: :x: 
![image](https://user-images.githubusercontent.com/78810647/195445777-a07b9434-25e8-43ae-b297-07ae56bcc04c.png)

**Comment by MintMain21** [comment]
I got a few broken embeds, but I wasn't sure if that was because of a broken instance or not.

Sounds like there's a lot to repair with the upcoming hotfix.
