### ISSUE TITLE
Allow mixed networks

### ISSUE THREAD

**Issue by m3thm4th** [libredirect/libredirect#486]
Settings changed and now it is possible to select clearnet only or Tor only or I2P only. Revert back to make it possible to select both clearnet and Tor or I2P for selected services.

**Comment by EdwardLangdon** [comment]
It doesn't make any sense.

**Comment by EdwardLangdon** [comment]
How do you get to use Both Tor & i2p/Clearnet working in the same browser ?

Don't tell that you use Tor Browser. It is strictly adviced to Tor Browser as is by the community.

**Comment by EdwardLangdon** [comment]
> So basically before it was possible to select a Tor instance for a service and a clearnet one for another. Now it's impossible, it's all clearnet or all Tor. This doesn't make any sense, why force it this way?

Maybe Network Fallback could help ya.

This is to make it less tedious for users who just installed libredirect and use mixnets to set it up for that network with just one switch, rather than having to go through every service, and also have to check on every update.

**Comment by m3thm4th** [comment]
I want to connect to Invidious instances on the clearnet, and to Nitter instances on I2P. This is impossible as of now because I can only choose one or the other in the General settings tab. It was not the case before when I could choose Clearnet, Tor or I2P for each different service. Please revert this setting as it was before. The setting could be switched in the General tab or made an advanced setting and everyone would be happy.

**Comment by EdwardLangdon** [comment]
Use network fallback, and if you really want to always use clearnet (for whatever reason ?), you can just disable all i2p instances, then it will always use clearnet.

**Comment by m3thm4th** [comment]
No, that's not how the fallback option works, plus this is not its purpose.

**Comment by EdwardLangdon** [comment]
Yes, it is how it works, and yes, it is on purpose

**Comment by m3thm4th** [comment]
Fallback is there in case there are no I2P or Tor instances, not for what wrote. Maybe @ManeraKai can look into this.

**Comment by ManeraKai** [comment]
Tbh this new way does limit the freedom of the user and is a bit unnatural to use.

**Comment by linsui** [comment]
> How do you get to use Both Tor & i2p/Clearnet working in the same browser ?

With another extension you can choose the proxy setting based on the url.

I would also hope that I can use mixed networks for each service. I want to use i2p for nitter doesn't mean that I don't want to use the clearnet nitter instances.

**Comment by EdwardLangdon** [comment]
From Hygna :

What is the actual usecase for using onion services/i2p sites for some frontends, but not wanting to use them for others even when there are instances avaliable.
