### ISSUE TITLE
Disable auto-adding the LibRedirect search engine

### ISSUE THREAD

**Issue by jamesWalker55** [libredirect/libredirect#492]
Whenever I restart the Libredirect extension, it keeps re-adding the search engine to my list of search engines. I have to manually navigate to the settings page and remove the search engine every time this happens.

This happens when I disable then re-enable the extension (which I often do because the sites may be down and I need access to the actual site), and it also happens after an extension update.

I'm using Firefox 105.0.3.

**Comment by MintMain21** [comment]
I hate that LibRedirect Search Engine. It should be Opt In from the get-go instead of opt-out.

**Comment by IkelAtomig** [comment]
It is not possible to add new search engine if you want to use Libredirect as one without asking new Permission.

It just adds to the list. Not even default. You could just ignore it.

**Comment by ManeraKai** [comment]
I think if I found a way then I should get the "browserSettings" permission which will allow me to modify the browser settings. It will get worse than more beneficial. LibRedirect isn't set up as the "default" search engine but it's just in the list bc it is a search engine theoretically
