### ISSUE TITLE
Any URI starting with t.co gets redirected to a twitter alternative

### ISSUE THREAD

**Issue by msvar** [libredirect/libredirect#493]
URIs starting with the string "t.co" are matched as twitter domains, most of them being false positives.
This affects any subdomain that starts with "t.co", including : 

```
t.co.example.com
t.contact.example.com/XXXXXXXXXX
```

I'm guessing the matching rule in `src/config/config.json` matches a bit too much: `"^https?:\\/{2}t\\.co"`, but I did not investigate further.
Tested with version 2.3.1.

**Comment by EdwardLangdon** [comment]
But t.co is a tracker link for the URLs in a tweet. There is no use for it other than it.
