### ISSUE TITLE
Piped shows up in the menu when it shouldn't 

### ISSUE THREAD

**Issue by helpthemfix** [libredirect/libredirect#494]
Only Youtube should be there, so I believe it's a bug. It only occures when the tab is on Piped, i.e `https://piped.kavin.rocks`

![Capture](https://user-images.githubusercontent.com/92321993/196797595-a8d44149-e86b-47dc-81e5-eb0f868a3f26.PNG)

**Comment by EdwardLangdon** [comment]
It is just the URL of the Instance when you are in that page. If you toggle it, The instance will be unchecked and will not be available for redirection next time.

**Comment by helpthemfix** [comment]
> It is just the URL of the Instance when you are in that page. If you toggle it, The instance will be unchecked and will not be available for redirection next time on toggling back it will be available for redirection again.
> 
> This will be added to FAQ shortly.

It's confusing design wise and I think it should be left to the settings page to disable unwanted instances.

**Comment by ManeraKai** [comment]
I'll remove it and switch to `Disable Button` design. We'll complete discussion here: https://github.com/libredirect/libredirect/issues/449
