### ISSUE TITLE
Settings aren't applied correctly after importing / won't stick

### ISSUE THREAD

**Issue by Lyceris-chan** [libredirect/libredirect#495]
libredirect version: 2.3.1
Chromium: Version 106.0.5249.119 (Official Build, ungoogled-chromium) (64-bit)

I've setup my settings earlier today and I exported them, after restarting the browser it seems like my settings have been reverted and importing my settings I just exported doesn't seem to change anything (it appears as if all settings are reverted to their defaults)

libredirect settings json: https://katb.in/oravupuyabe.json

**Comment by EdwardLangdon** [comment]
Can you download the source Code as `zip` and load `src` via Developer mode ?

**Comment by Lyceris-chan** [comment]
Downloaded the source code based on https://github.com/libredirect/libredirect/commit/1ce6a16686b9dc7c0624a9f586ec77ff8267a04b and that seems to have fixed the issue thanks !

libredirect json: https://katb.in/riwipuhumoq.json
