### ISSUE TITLE
Lots of random errors popping up

### ISSUE THREAD

**Issue by kirkas** [libredirect/libredirect#498]
It seems this extension has a few errors, here what I see when I load the extension:

![image](https://user-images.githubusercontent.com/1159783/197176527-8e5e78f9-a7c4-4e97-8b8e-89f38d303b6b.png)

```
Error handling response: TypeError: Cannot read properties of undefined (reading 'autoRedirect')
Error in event handler: TypeError: Cannot read properties of undefined (reading 'url')
Error: <path> attribute d: Expected number, "… 4 8.65 4 12q0 3a.35 2.325 5.675…".
Error: <path> attribute d: Expected number, "… 4 8.65 4 12q0 3a.35 2.325 5.675…".
Error handling response: TypeError: Cannot read properties of undefined (reading 'value')
Error handling response: TypeError: Cannot read properties of undefined (reading 'value')
```

**Comment by EdwardLangdon** [comment]
They are mostly fixed. Is it latest version ?

They could be ignored mostly, If redirects are working as usual.

**Comment by kirkas** [comment]
I am using the latest version (2.3.2) on MacOS (Big Sur) and Chromium (build: ungoogled-chromium, version: 106.0.5249.119).

Redirects seem to be working fine, with the exception of instagram (no redirect is happening).

Th SVG errors lead to some minor display issues:

![image](https://user-images.githubusercontent.com/1159783/197221111-674a126a-00d9-4a2e-acea-f2a415bd6f9a.png)

**Comment by EdwardLangdon** [comment]
Instagram Posts works. Accounts does not because Bibliogram is now discontinued project.

There is no display issues, Chromium can't read the SVG code as HTML.
