### ISSUE TITLE
Don't re-enable all redirects on Updates

### ISSUE THREAD

**Issue by 0lhi** [libredirect/libredirect#499]
Sometimes, the LibRedirect Alternatives get all re-enabled again. My guess is this happens when the Add-On updates. This is undesirable behavior.

Using Firefox for Linux Mint:

![Firefox](https://user-images.githubusercontent.com/74732674/197177434-7047605e-3553-4e3e-b265-87d69351b1e1.png)

**Comment by EdwardLangdon** [comment]
Is wikipedia, reuters and peertube enabled after the update?
