### ISSUE TITLE
Not working on Ubuntu 22.04/22.10 in Tor Browser v11.5.4?

### ISSUE THREAD

**Issue by PeterDaveHello** [libredirect/libredirect#503]
- OS: Ubuntu 22.04 & 22.10 (Using live DVD in VirtualBox for a clean environment to reproduce the issue)
- Browser: Tor Browser v11.5.4 (based on Mozilla Firefox 91.13.0esr)

I installed the latest, enabled with the permission to run in Private Windows, but it just doesn't work, tried to enabled the redirect in both menu and settings, but everytime when the menu/settings closed and opened again, the "enabled" setting is gone. Not sure if it's related, but looks like the setting can't be saved somehow.

Using Twitter as an example, it's enabled here:

| Toolbar menu | Settings |
| ------------ | -------- |
| ![image](https://user-images.githubusercontent.com/3691490/197337487-be932554-8299-4204-88d6-2bd899561027.png) | ![image](https://user-images.githubusercontent.com/3691490/197337439-c393d590-b493-4243-b63e-d6f97854864c.png) |

Still disabled if close the menu/settings and check again:

![image](https://user-images.githubusercontent.com/3691490/197337450-d5e14ddd-15a2-4dd2-94ef-54144f6405bf.png)

**Comment by ManeraKai** [comment]
Tor is giving me a hard time in initializing the settings. Try to "reset" the settings and see.

**Comment by PeterDaveHello** [comment]
hmmmm ... I can say that the same thing seems to happen on macOS, too.

Reproduced on Tor Browser 12.0.2 (based on Mozilla Firefox 102.7.0esr) (64-bit) with the same result. There might be some interesting thing in it, because I tested some famous plug-ins like [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) and [AdGuard AdBlocker](https://addons.mozilla.org/en-US/firefox/addon/adguard-adblocker/) works perfectly without the missing "settings" issue.

**Comment by PeterDaveHello** [comment]
@ManeraKai @IkelAtomig is it possible that we can reopen this issue? Thanks.

**Comment by ManeraKai** [comment]
This is on the latest version (not released yet): https://youtu.be/oCKZdp1CAnk

**Comment by PeterDaveHello** [comment]
Okay, maybe I can try the next release!

**Comment by PeterDaveHello** [comment]
I also got a video record that I tested the latest stable version of LibRedirect on the latest Tor Browser, but looks like the file is too big for GitHub, let's wish it all works with v3 😃
