### ISSUE TITLE
Twitter redirects not working on Chromium 106.0.5249.119

### ISSUE THREAD

**Issue by alex8065** [libredirect/libredirect#505]
All other redirects work, Instagram, Youtube, Medium, Google Maps, Quora.

```
Linux 5.15.74 #1-NixOS SMP Sat Oct 15 06:06:06 UTC 2022 x86_64 GNU/Linux
```

On my laptop, with 105.0.5195.125, Twitter redirects work fine. Both using libredirect 2.3.3.

**Comment by ManeraKai** [comment]
Are "all" urls for twitter not redirecting or a specific one? If so write me the specific url that doesn't redirect.

**Comment by alex8065** [comment]
I can't find a URL that works.
`https://twitter.com/` does not redirect, nor does `https://twitter.com/bbc`.

**Comment by EdwardLangdon** [comment]
We tested in the version of extension it just works fine.

**Comment by alex8065** [comment]
@EdwardLangdon can confrim that on my laptop with Chromium version 106.0.5249.119, redirects work correctly. So this is just an issue with Chromium on my desktop running NixOS. I can try to get a MRE up on a LiveCD maybe, but any steps for me to debug locally?

**Comment by EdwardLangdon** [comment]
Just drag and Drop the `crx` in a fresh profile and see if it works. If not, Then there is a problem in your installation probably.

**Comment by alex8065** [comment]
The `.crx` never works (always  gives `CRX_REQUIRED_PROOF_MISSING`). I'm closing this and we can investigate whatever went wrong with the install if ever anyone else runs into this.

**Comment by vsr3y** [comment]
#556
