### ISSUE TITLE
redirect crates.io to lib.rs

### ISSUE THREAD

**Issue by pabs3** [libredirect/libredirect#507]
[crates.io](https://crates.io/) is the website for all Rust crates (their packaging format). Unfortunately it requires JavaScript to view any of the website. An alternative that doesn't require JavaScript is [lib.rs](https://lib.rs/about). It also has a safer ranking algorithm which hides abandoned and spammy crates and has more accurate information about crates. Unfortunately I can't find any other instances, but as a developer site I doubt crates.io folks will try to shut down lib.rs. I think that LibRedirect should redirect people using crates.io to lib.rs.

**Comment by ManeraKai** [comment]
The [about](https://lib.rs/about) page seems pretty convincing.

**Comment by ManeraKai** [comment]
Look, lib.rs seems very nice, but it's for developers only. Mostly people who wanna redirect it will use [Redirector](https://addons.mozilla.org/en-US/firefox/addon/redirector/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) than LibRedirect.
LibRedirect is for simple people to make them get out of popular sites like YouTube, Twitter, etc...
