### ISSUE TITLE
Redirect mobile IMDb site

### ISSUE THREAD

**Issue by chrisgix** [libredirect/libredirect#508]
Hello.

I know that the extension on Android is not officially supported, however it would be nice if the mobile version of IMDb (m.imdb.com) would redirect to libremdb. Other sites seem to redirect fine but IMDb only redirects if I force desktop pages first.

**Comment by EdwardLangdon** [comment]
Though we don't official support firefox android we are taking this into account as it is also one of the sites we need to cover.
