### ISSUE TITLE
LibRedirect Lite?

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#510]
I've heard rumblings, specifically in the thread on the alternative logo (https://github.com/libredirect/libredirect/issues/468) of a "lite" version of LibRedirect made with Manifest 3 in mind, and I think that this would make an excellent opportunity to create a lighter, "stable" equivalent to LibRedirect ideal not just for Chromium use, but for Mobile Use as well.

There are a few key differences I'm imagining in functionality. 

1. LibRedirect Lite should not auto-fetch instances, nor test them for latency. Instead, there should be (akin to Privacy Redirect) a pool of instances manually edited by the user, with links to official documentation to find additional instances, and maybe a secondary text-box to test the latency of an individual instance. This way, it is entirely up to the user to seek out, test, add, and remove instances for their preferred front-ends. 

So for example, let's say I'm a first-time user, and Invidious Redirects are turned on with a default pool that includes [invidious.snopyta.org](https://invidious.snopyta.org/), [yewtu.be](https://yewtu.be/), and [invidious.kavin.rocks](https://invidious.kavin.rocks/), but for whatever reason I prefer smaller and more obscure instances like [yt.artemislena.eu](https://yt.artemislena.eu/), [inv.privacy.com.de](https://inv.privacy.com.de/), or [invidious.dhusch.de](https://invidious.dhusch.de/). Then not only could I use the official documentation or other resources to find the instances I prefer, but I can override the default pool of instances should I wish. And with the handy textbox for testing individual domains at will, I can test a domain before adding it or replacing it. 

None of this should require any automated behaving, including fetching instances, testing instances, or auto-pruning instances.

2. LibRedirect Lite should not even bother with any equivalent to Unify Settings, except in perhaps allowing for URL Parameters as detailed in #491. There is no reason to save user-preferences as cookies in a lite version, and it would be easier simply to include (for instances that allow URL Parameters) a textbox for adding them, and a link to official documentation. Like the default instance pool, a default URL Parameter may be set as an example, but users should be able to replace them as easily as they would the default instance domains. 

3. LibRedirect Lite should not feature a "LibRedirect Search Engine" akin to LibRedirect, especially since even users of LibRedirect Proper would rather do without it (#492). If the user's "default search engine" is Google in the browser, and they have Google/Search redirects enabled, then the redirects should happen anyway. A dedicated search engine is redundant. 

And finally 4. And additional complex features planned for the main branch of the extensions should obviously not be added to LibRedirect Lite until they are proven both stable and lightweight enough to justify their inclusion. 

A good basis may be the abandoned Privacy Redirect, with care to not hardwire any instances/domains into the code as Privacy Redirect did, nor any substantial dependency on any front-end specific options outside of the accommodation of URL Parameters. Users should be able to configure what redirects they want, what frontends are redirected to, what domains belong to the appropriate redirect pools, and what URL Parameters are added to the services that welcome them. Nothing more, nothing less.

I am unaware of any development on a Mv3 equivalent to Redirect, so for all I know all of the above has already been taken into consideration,  but I am nevertheless sharing this for posterity, in the belief that it could be beneficial not just to Chrome Users, but to experienced users of these frontends who merely want an easy way to swap out instances and URL Parameters without much dependency on automation or frequent updates. 

You might even go so far as to add a sort of "debug" mode where users can add their own redirects as a sort of "proof on concept" so that they might present their work to support on Github and Codeberg so that they might be properly intergrated into future releases. Just so long as the process remains lightweight and straightforward.

**Comment by ManeraKai** [comment]
I myself can't be responsible to 2 extensions right now. It's a really deep idea and I don't have time for it. If anyone else wants to make a lite version supporting mv3 etc. Then he's welcome to do under his own name, but I myself can't :/

**Comment by bingoxo** [comment]
https://github.com/libreom/predirect is coded for mv3 , hopefully libredirect will be too before browsers drop the support entirely
