### ISSUE TITLE
Support Wikiwand for Wikipedia Instances

### ISSUE THREAD

**Issue by RuthlessRuler** [libredirect/libredirect#511]
Maybe against the whole Libre Idea, but tbh I have setup for Wikiwand on FF and I find it much pleasant to use than others. Wanted to know if it can be supported in Wikipedia redirect as wikiwand needs some changed URL parameters and I can do away with its extension.

**Comment by ManeraKai** [comment]
Not many users seem to ask for this and yes it's proprietary. I suggest you use [Redirector](https://addons.mozilla.org/en-US/firefox/addon/redirector/)?
