### ISSUE TITLE
Add custom urls and redirects

### ISSUE THREAD

**Issue by RuthlessRuler** [libredirect/libredirect#512]
So basically, I wanted to if we can create a new pair of Website and their redirect which we want.

Like let's say there I visit yyyy.zzz but in my country that domain in blocked but another domain aaa.zzz is not blocked and is mirror/replicate/etc of the website. 

So a feature to add such custom redirects can be added?

**Comment by ManeraKai** [comment]
You really want: [Redirector](https://addons.mozilla.org/en-US/firefox/addon/redirector/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)

We designed LibRedirect so it will be the easiest way to switch to those alternative frontends. We're trying to not make it as less technical as possible. Use Redirector for more advanced stuff.
