### ISSUE TITLE
"Copy Raw" missing from Breeze Wiki.

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#513]
Same as #501, but Breeze Wiki (the Fandom frontend) instead of Wikiless. 

Edit: I've noticed that unlike Wikiless, Breeze Wiki actually has a "raw url" on the bottom of each page, so consider this less an essential addition and more something to consider for posterity.

**Comment by ManeraKai** [comment]
I didn't add much as it's already there at the bottom. Though now the feature is there for the wiki pages in BreezWiki.
