### ISSUE TITLE
Provide instance order instead of connecting to random instances

### ISSUE THREAD

**Issue by JediMaster25** [libredirect/libredirect#514]
I usually prefer to connect to the instance with the best latency. But some people might prefer to use a specific instance as the default that isn't the one with the best latency. So I think the best thing to do would be to provide an order for the enabled instances, to connect in that order instead of in a random order. So by default the way to choose the instance would be random but if there is a provided order then that would be the way to choose the instance.

Right now I have to disable all but one instance to accomplish this.

**Comment by SecularSteve** [comment]
Ironically, enough, I think #516 is very similar to this, but just explained a bit more in detail.

**Comment by ManeraKai** [comment]
This is a nice idea, but it will make the instances list much more complex.
We don't want to make the theory of the instances list a complex thing. At the end it's just a starting point list for users to start using that frontend.
