### ISSUE TITLE
Ability to move the instance rows in the options menu to prioritise which instance to open first.

### ISSUE THREAD

**Issue by SecularSteve** [libredirect/libredirect#516]
Basically, the ability to move, and sort, the rows in the options menu of the various instances in a specific order to prioritise which one to open first in case you want them to open in a specific order should one of them not work.

![Knipsel](https://user-images.githubusercontent.com/33793273/199112571-589e64b7-8517-43d4-b81c-1b0021379809.PNG)

This is especially useful in case an instance is down, if you have a "favourite with a second favourite" instance or if one of the primary instances doesn't use the version that you like. But that's just a suggestion.

Have a nice day, and my regards,

**Comment by ManeraKai** [comment]
Hmm, this will work so nice with this issue too: #514

**Comment by ManeraKai** [comment]
We'll complete discussion there.
