### ISSUE TITLE
More instances of Nueters?

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#517]
The one instance of Nueters in LibRedirect (https://neuters.de/) has proven to have just enough inconsistent latency to where it frequently disables itself. I say that if there are any other instances that they should be added to Libredirect by default.

**Comment by ManeraKai** [comment]
It's mentioned as a "sample" in the [README](https://github.com/HookedBehemoth/neuters). Idk I don't think we should take it as a public instance. Should I disable neuters then?

**Comment by MintMain21** [comment]
By Default? Maybe.

Shouldn't be removed, it's very handy.

**Comment by ManeraKai** [comment]
Alright, then disable by default.

**Comment by ManeraKai** [comment]
but man it's already disabled by default...
Alright, I'll close the issue xD
