### ISSUE TITLE
Feature request: Toggle for enabling Auto-updating instances list

### ISSUE THREAD

**Issue by graynk** [libredirect/libredirect#521]
As discussed in #225, it would be a good thing to have to avoid the problem of instances getting stale over time, without user having to manually update the list

**Comment by IkelAtomig** [comment]
Blocked by https://github.com/libredirect/libredirect/issues/334

**Comment by ManeraKai** [comment]
More and more we will not do this. Instead we're gonna make the update instances button in each frontend's page. Auto updating may lead the user to using instances he doesn't even know and that isn't a good habit to do.

**Comment by IkelAtomig** [comment]
We fetch from actual data source. So, Instance being dead is not a problem of the extension.

**Comment by graynk** [comment]
> So, Instance being dead is not a problem of the extension.

That depends on what kind of UX you want to provide :)
The fact the the instance exists is in the data source doesn't automatically mean that you should use it. That would me my suggestion, at least.

**Comment by ManeraKai** [comment]
Look, the lists we provide are just "starting points" for the user, I want to put the instance updater in each frontend's page so the user will see any new instances and will choose the ones he want "himself". We won't choose for the user, he will choose.
