### ISSUE TITLE
Reddit search URLS arer no longer redirecting

### ISSUE THREAD

**Issue by Andrewskiz** [libredirect/libredirect#522]
So I have a Firefox search engine for reddit that I got from Mycroft Project, and it used to redirect to a teddit or libreddit instance but now searches are going to reddit.com search results. One day it just stopped working, and I don't know if Mozilla changed something or libredirect. I tried it on a fresh install with a new profile and the result was the same. Reddit links and URLs are still redirected as usual.

I realize I could just add a teddit instance search engine, but I've always used it this way to balance the load among instances.

**Comment by ManeraKai** [comment]
Can you show me example urls/

**Comment by Andrewskiz** [comment]
https://www.reddit.com/search/?q=libredirect
