### ISSUE TITLE
"Search" needlessly removes url parameters unlike some of the other frontends

### ISSUE THREAD

**Issue by gitterspec** [libredirect/libredirect#523]
I would expect
`https://search.libredirect.invalid/?q=my+keyword&language=en-us&safesearch=0`
to redirect to:
`https://searx.random.instance/?q=my+keyword&language=en-us&safesearch=0`
but instead it goes to (lopping off parameters):
`https://searx.random.instance/?q=my+keyword`

Whereas:
`https://en.wikipedia.org/wiki/index.php?title=Special:Search&search=my+keyword`
redirects to:
`https://wiki.random.instance/wiki/index.php?title=Special:Search&search=my+keyword&lang=en`
thus preserving any and all parameters (though appending `lang=en`).

I don't see a use case where it's beneficial for the Search frontend to lop off these parameters, but it very much limits functionality for some users like myself.

I know there's a feature request https://github.com/libredirect/libredirect/issues/491 to actually append extra parameters, but this is more just fundamental to base functionality.

**Comment by ManeraKai** [comment]
How did you actually end up with those extra parameters?

**Comment by gitterspec** [comment]
When setting up my browser's default search and search keyword shortcuts, I typed in the desired searx parameters.
