### ISSUE TITLE
Add these sources

### ISSUE THREAD

**Issue by S-Sajith** [libredirect/libredirect#524]
BiblioReads => GoodReads ( Book manager )
Source : https://github.com/nesaku/BiblioReads
Dumb => Genius ( Lyrics site )
Source : https://github.com/rramiachraf/dumb
Simple Amazon => Amazon ( Shopping )
Source : https://codeberg.org/SimpleWeb/SimpleAmazon
Instances : https://simple-web.org/projects/simpleamazon.html

**Comment by IkelAtomig** [comment]
We won't add PornInvidious. We are against it. Extension could be blocked from Firefox store for promoting pornography.

I will update the FAQ not to suggest again.

Will see and check about the others.

**Comment by ManeraKai** [comment]
It's not against exactly, just that it's risky, read this: https://codeberg.org/LibRedirect/libredirect/issues/11#issuecomment-630922

**Comment by privacytime101** [comment]
@ManeraKai Any update on "dumb" being added? Thanks.

**Comment by ManeraKai** [comment]
No still we didn't add it.

**Comment by ManeraKai** [comment]
About SimpleAmazon: https://codeberg.org/LibRedirect/libredirect/issues/49

**Comment by NunoSempere** [comment]
Hey, what is up with dumb (https://github.com/rramiachraf/dumb)?

Last time I brought dumb up:

1. There weren't many open endpoints. There are a few more now, available here: <https://github.com/rramiachraf/dumb>
2. I was redirected to this issue from codeberg (https://codeberg.org/LibRedirect/libredirect/issues/59), and the codeberg issue is closed,

Poke @ManeraKai

**Comment by ManeraKai** [comment]
@NunoSempere We added it.
