### ISSUE TITLE
imgur <img>s aren't redirected

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [libredirect/libredirect#525]
Test page: https://alyoshavasilieva.github.io/lr-repro/

Opening that page with imgur redirects enabled and devtools open shows my browser connecting directly to imgur's CDN, not redirecting like I expect it to. Opening the image itself in a new tab *does* redirect. I have imgur redirect type set to "Both". I've also verified on my instance that my browser is not connecting to it.

**Comment by IkelAtomig** [comment]
This will be fixed in the next Version.

**Comment by ManeraKai** [comment]
It's so weird, I'm "not able" to detect `<img>` connections:
![image](https://user-images.githubusercontent.com/40805353/201466446-cf8758c2-13b0-4def-9ee3-b52eacc1a2f9.png)
The main url is detected, also the favicon, but not the `<img>` href.
Though `<iframe>`'s are detected normally:
![image](https://user-images.githubusercontent.com/40805353/201466484-5b1301e4-cc7f-4bcc-9854-dccfc3520092.png)

This wasn't like this before though. Weird

**Comment by ManeraKai** [comment]
Fixed :)
