### ISSUE TITLE
Website incorrectly redirected if URL path includes redirectable site

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [libredirect/libredirect#527]
Example URLs:
1. https://web.archive.org/web/*/https://medium.com/@mickgordon/my-full-statement-regarding-doom-eternal-5f98266b27ce
2. https://archive.ph/https://medium.com/@mickgordon/my-full-statement-regarding-doom-eternal-5f98266b27ce

Neither of these URLs are medium.com URLs, but both are redirected as if they are. The resulting URL is bogus; I get a "The page isn’t redirecting properly" error from Firefox after the extension throws me through like 5 redirects.

**Comment by ManeraKai** [comment]
It was a small missed character, fixed now 👍
