### ISSUE TITLE
Updates to whatever.social instances

### ISSUE THREAD

**Issue by privacytime101** [libredirect/libredirect#529]
We went through a bit of a privacy overhaul.

### No more Cloudflare
whatever.social services no longer use Cloudflare. As far as I know, we're now one of the only instances to use a CDN that isn't Cloudflare (this is the case for Piped). See the new https://whatever.social/privacy and https://whatever.social/transparency if needed.

Affected sites listed in Libredirect and the blacklist:

- https://watch.whatever.social
- https://listen.whatever.social
- https://read.whatever.social

### New Libreddit instance

Now found at https://discuss.whatever.social

**Comment by ManeraKai** [comment]
Don't worry they will automatically be removed by our script. It runs every 3 days or so.

**Comment by ManeraKai** [comment]
> New Libreddit instance
>
> Now found at https://discuss.whatever.social/

Tell [LibReddit](https://github.com/libreddit/libreddit-instances) directly about it and they will add it hopefully ok?

**Comment by privacytime101** [comment]
> Tell [LibReddit](https://github.com/libreddit/libreddit-instances) directly about it and they will add it hopefully ok?
> 
> 

Did it already, it's there https://github.com/libreddit/libreddit-instances/commit/4c977658b2c7c38238c884bbe11d1dbf39d9b563

**Comment by ManeraKai** [comment]
Then it will be fetched within at most 3 days.
