### ISSUE TITLE
Remove privacytools.io instances

### ISSUE THREAD

**Issue by privacytime101** [libredirect/libredirect#530]
I was just looking through the instance list of the community, and I was pretty surprised to see privacytools.io listed. 
Unless I'm missing something, privacytools.io has basically sold itself out in favor of monetization (see https://www.privacytools.io/privacy-vpn for an example).

This, in my opinion, is not the type of service that should be relied upon for private frontends, especially since privacytools's own staff left to found https://privacyguides.org.

If I'm somehow not reading something correctly or misinterpreting something - apologies, a little low on sleep.

**Comment by ManeraKai** [comment]
I don't modify the instances list, here's why: https://libredirect.github.io/faq.html#why_not_using_a_single_reputable_instance
