### ISSUE TITLE
Improvements to Latency Threshold

### ISSUE THREAD

**Issue by IkelAtomig** [libredirect/libredirect#533]
- [ ] Enable disabled instances if the instance is within threshold limit.
- [ ] Give the users to enable automatically checking latencies but for separate frontends and as a whole because some might use one specific instance they like and some prefer randomized instances.

**Comment by IkelAtomig** [comment]
I think this is separate and an improvement to the feature and not being linked with it.

**Comment by ManeraKai** [comment]
We're gonna remove Latency Threshold.
