### ISSUE TITLE
Auto Select Best Instances 

### ISSUE THREAD

**Issue by RuthlessRuler** [libredirect/libredirect#534]
Introduce settings that will auto-select best instances (based on Latency, Cloudflare support) from the list.

This will reduce the hassle of manually combing through the instances and selecting them. 

The number of instances can be flexible like Top 5 Instances with Least latency and with/without Cloudflare support.

**Comment by RuthlessRuler** [comment]
Alternatively, Filtering & Sorting on list page on be introduced too.

**Comment by SecularSteve** [comment]
https://github.com/libredirect/libredirect/issues/514

**Comment by RuthlessRuler** [comment]
> #514

Not exactly that as I'm looking for more of default option that will auto select best instances matching some criteria.

**Comment by ManeraKai** [comment]
We won't decide for the user, and there are other factors to trust an instance than just Cloudflare or latency. This will teach a bad practice to the user we won't add it.
