### ISSUE TITLE
Wikiless link broken

### ISSUE THREAD

**Issue by holmesrichards** [libredirect/libredirect#536]
https://codeberg.org/orenom/wikiless in README is broken; see https://orenom.fi/: "Wikimedia Legal Enforcement team has contacted Codeberg - the repository has been made private (only contributors will be able to access the repo for now)."

**Comment by IkelAtomig** [comment]
What was your issue about actually ?

**Comment by holmesrichards** [comment]
I am reporting a broken link in the README.

**Comment by IkelAtomig** [comment]
Well, Thing is it's related to the project. Unfortunately it is taken down. We can't remove it either. I think it better be like it is as of now.
