### ISSUE TITLE
The instance list needs a sort menu

### ISSUE THREAD

**Issue by opusforlife2** [libredirect/libredirect#537]
Some services have such a huge number of instances that it makes it difficult to make sense of the whole thing. A sort menu would really help here.

Some options:
- Alphabetical order (instance name)
- Alphabetical order (country of the instance)
- Presence/absence of Cloudflare CDN
- Latency (after test done)

**Comment by opusforlife2** [comment]
Ideally, this info should be provided by upstream, I think? It would be pretty inefficient to have to ping instances to find out their countries. But I'm not sure if all services' instance APIs provide country info.

**Comment by opusforlife2** [comment]
Thanks for adding the feature!

> But will not be sorted by latency.

The option could be greyed out until the user manually performs a latency test? From what I've seen, the extension permanently saves that info until the test is done again.

**Comment by ManeraKai** [comment]
No, bc we removed Latency Test.
