### ISSUE TITLE
An option to add a custom frontend

### ISSUE THREAD

**Issue by ndvarn** [libredirect/libredirect#538]
It would be nice if it was possible to add custom frontends, via a menu of some kind

**Comment by ManeraKai** [comment]
Our goal is to make the extension as easy to use as possible, if you want to be more advanced with custom frontends, then I suggest you use: https://addons.mozilla.org/en-US/firefox/addon/redirector/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search next to LibRedirect.

**Comment by ndvarn** [comment]
Okay, well, thanks!
