### ISSUE TITLE
Google redirects are inconsistent. Sometimes don't redirect even when enabled

### ISSUE THREAD

**Issue by Latrolage** [libredirect/libredirect#54]
The below video shows a fresh firefox profile installing libredirect as the first and only plugin, but google searches are not redirected.

https://user-images.githubusercontent.com/67372293/154843012-ea17b9b5-d67b-4e38-bbb1-9e5299b1945d.mp4

**Comment by ManeraKai** [comment]
go to `about:debugging#/runtime/this-firefox` and click on the `inspect` button on the extension and then go to the `console` tab. Is there any errors?

**Comment by ManeraKai** [comment]
Does the same happen when you visit https://google.com ?

**Comment by ManeraKai** [comment]
Fixed it. Will release a new version soon.
