### ISSUE TITLE
Redirect all frontends to the one I have configured

### ISSUE THREAD

**Issue by JediMaster25** [libredirect/libredirect#543]
This is related to issue #514. If I have a preferred instance, I want to use it even when I use a link to another instance. So for example, people keep sending links to yewtu.be and I like to use piped instead, so I always have to manually change the link.

**Comment by IkelAtomig** [comment]
Read -https://libredirect.github.io/preferred_instance

**Comment by JediMaster25** [comment]
Please send the correct link.

**Comment by IkelAtomig** [comment]
![image](https://user-images.githubusercontent.com/101938856/203979010-d293fcc9-fdd1-46d3-a54e-db31f9c4c21a.png)

It is in https://libredirect.github.io/docs.html.

I will fix links as soon as possible.
