### ISSUE TITLE
Redirect reddit gallery links

### ISSUE THREAD

**Issue by 2084x** [libredirect/libredirect#547]
Please add support for redirecting gallery links.

Currently links in this format do not redirect: 
https://www.reddit.com/gallery/yvdrzj/

If the domain is changed to a teddit instance: 
https://teddit.bus-hit.me/gallery/yvdrzj/

Teddit can resolve the link itself: 
https://teddit.bus-hit.me/r/Animals/comments/yvdrzj/pic_i_just_took_of_a_squirrel/

Libreddit can't do this though. Changing only the domain will show an error page: 
https://libreddit.de/gallery/yvdrzj/

I think that's an issue they should solve on their end, but for now, if 'gallery' is changed to 'comments' as well it can open the page: 
https://libreddit.de/comments/yvdrzj/

**Comment by IkelAtomig** [comment]
It's an upstream issue in Libreddit. They are still working on supporting Gallery links.

**Comment by 2084x** [comment]
I know libreddit can't do it. Perhaps I should've worded my post better:

I'm asking for gallery links to redirect if you are using teddit, since it's possible for teddit to resolve them.

Or is this just going to be on hold until both frontends can handle gallery links?

**Comment by IkelAtomig** [comment]
It's an upstream issue that the frontend doesn't support it. We can't just fix for now and later revert it. I think it is better as it is right now. Ask Libreddit to add support for it.

The Libreddit team is back and actively working on it. So, better luck there to prioritze it.

If you wanna see gallery in Libreddit just remove the `gallery` part from URL. To see the post along with gallery.

Sorry, mate :(
