### ISSUE TITLE
Support for redirecting publications to doi.org, oadoi.org, scihub, etc

### ISSUE THREAD

**Issue by advait404** [libredirect/libredirect#548]
The [searx](https://github.com/searxng/searxng) metasearch engine has an option for 'Open Access DOI rewrite' which avoid paywalls by redirecting to open-access versions of publications when available. It can use many 'Open Access DOI resolver' such as doi.org, oadoi.org, sci hub. Can Libredirect implement redirecting for publications?

**Comment by IkelAtomig** [comment]
But first you need to list the Publications from which you want to redirect from ?

**Comment by advait404** [comment]
@IkelAtomig I think it can use the popular ones, like google scholar, springer, IEEE explore, Microsoft academic, etc.

However, Based on the searx doi rewrite, it dynamically gets the doi from the URL.

https://github.com/searxng/searxng/blob/master/searx/plugins/oa_doi_rewrite.py

**Comment by ManeraKai** [comment]
I think there is some extension for this though I don't remember, but this isn't the goal of LibRedirect, LibRedirect's main focus is on redirect popular websites to their privacy friendly frotnends, not getting through scientific articles' paywalls.
