### ISSUE TITLE
Document who has permissions to push to this repository and Firefox addon

### ISSUE THREAD

**Issue by e00E** [libredirect/libredirect#550]
The security of this project is important because it gets the browser permissions to access data for all websites. If it had specialized permissions like what a pure nitter redirect addon could do, this wouldn't be important. I understand why you request permissions the way you do but it does mean that a malicious update to the addon could take over all of my browser accounts.

I would like there to be documentation about the people who are trusted enough to push to master and update the Firefox addon. I'm not saying you need to reveal your real name. I just want it to be documented in some way who and why has access.

Here is what I manually gathered.

The members of the [libredirect Github organisation](https://github.com/orgs/libredirect/people) are:

- https://github.com/alefvanoon
- https://github.com/IkelAtomig
- https://github.com/ManeraKai

Out of these ManeraKai has by far the most [contributions](https://github.com/libredirect/libredirect/graphs/contributors) to the repo so they appear to be the main developer. It would be nice to clarify why each of these people have access.

- Manerakai has no real name identity, has a PGP key.
- alefvanoon has no real name, no PGP key (link on website is 404).
- IkelAtomig has no real name, no PGP key.

The Firefox addon is [owned by](https://addons.mozilla.org/en-US/firefox/user/17252891/):
- https://addons.mozilla.org/en-US/firefox/user/17252891/ (alefvanoon)
- https://addons.mozilla.org/en-US/firefox/user/17283164/ (ManeraKai)

I cannot verify whether these accounts correspond to the Github accounts but you link the Firefox addon from the Readme so they probably do.

**Comment by IkelAtomig** [comment]
Well, I have a PGP key for my Contact email and use SSH for authentication and Signing commits.

@ManeraKai Will answer this for you.

**Comment by IkelAtomig** [comment]
All the three members you listed has Full write access to this repository.

There are memebers you don't see but inactive.

Both Alefvanoon and Kai can only publish Addon.

**Comment by IkelAtomig** [comment]
I have a PGP key for Contact email but use SSH for signing and authentication.

**Comment by ManeraKai** [comment]
> https://addons.mozilla.org/en-US/firefox/user/17283164/ (ManeraKai)

Yes this account is for me, you can actually see the "Homepage" link linking to my website, and I reference that website on my github account too.
I removed alefvanoon from the ownership in Firefox Addons, he was uploading the versions before but I'm now doing.

**Comment by IkelAtomig** [comment]
Manerkai as the main dev has access to it.

Me, a collaborator needs write access to do certain stuff such as editing Issue titles, etc. I don't push stuff other than editing readme or Syncing between Codeberg and Github and publish releases ocasionally.

Alefvanoon is the one who started this project but inactive.

We planned internally not to allow write access to anyone further. So, you are good to go. Only Manerakai can publish the extension.

I think I have up cleared your questions.
