### ISSUE TITLE
Add links to alternative frontend websites

### ISSUE THREAD

**Issue by e00E** [libredirect/libredirect#552]
For example, for Youtube I can choose between Invidious, Piped and so on but it is hard to find out what my choice means.  I have to manually search the internet for the name libredirect shows and find the project's website. libredirect should link the official website or source code repository of the frontends.

**Comment by IkelAtomig** [comment]
Our webpage is already linked scrolled down or check for `About` in Popup menu.

**Comment by e00E** [comment]
It makes sense to also link it in the options. But you are right that the list on the website is mostly good enough.

**Comment by IkelAtomig** [comment]
I think I have a mockup on how to link in the extension. Will share it later.

**Comment by IkelAtomig** [comment]
![Untitled](https://user-images.githubusercontent.com/101938856/206081409-79b8202c-ccfd-4550-ab43-20123909d202.png)

This is how it will be, The hyperlink will be dynamic, On Hovering, It will display a mini popup "Go to Project"

This is just a design !

**Comment by ManeraKai** [comment]
Let it be simpler, when you are in the settings page, you will have at the bottom some info about both the frontend and the website it's proxying.

**Comment by IkelAtomig** [comment]
I think my mockup design would be minimal and efficient than making the user to scroll all the way down.

**Comment by ManeraKai** [comment]
I just did it now by making the "Frontend" word as a link, bruh...
