### ISSUE TITLE
Show source URLs that will be redirected

### ISSUE THREAD

**Issue by e00E** [libredirect/libredirect#553]
I would like to see what URLs a given alternative frontend applies to. For example, for "Maps" it is not obvious which maps services are redirected to the alternative frontend.

**Comment by ManeraKai** [comment]
We already have all this information in the home page of the website, though it's better to write `Google Maps` instead of just `Maps`:
![image](https://user-images.githubusercontent.com/40805353/206418373-e51f67b0-66b7-433e-a96c-2ede170bde54.png)
