### ISSUE TITLE
Please remove "NerdVPN.de" instance from assign list, due to discrimination

### ISSUE THREAD

**Issue by FuccDucc** [libredirect/libredirect#555]
I suggest that you remove the "NerdVPN.de" invidious instance from your YouTube redirection lists, so no one can get it dynamically assigned by querying YouTube through LibRedirect.

Because they are discriminating users on the basis of nationality/country of residence, as written out here: [https://github.com/Sommerwiesel/invidious/issues/6](https://github.com/Sommerwiesel/invidious/issues/6) - this repo is the only known point of contact with the owner of said instance (NerdVPN.de), even though the instance owner didn't intend for it to be. However, they still never reply to users.

My proposal to remove them serves a dual purpose:
- Avoid having LibRedirect users waste their time (if their country is blocked by this instance)
- Avoid LibRedirect users coming into contact with discriminatory, unpleasant behavior from this instance operator, and/or impact the user experience while using this plugin. LibRedirect may want to take distance from instance operators exhibiting anti-user behavior.

In case the instance owner soon decices to censor the critics by modifying/deleting said issue link, here's an image backup of its contents:
![nerdvpn_discrimination_issue_backup](https://user-images.githubusercontent.com/61570793/204129464-fd9c18ff-f25a-4086-8125-6cb9156c2bdb.png) + `https://i.imgur.com/TS217MD.png`

**Comment by ManeraKai** [comment]
We don't modify the instances list: https://libredirect.github.io/faq.html#why_not_using_a_single_reputable_instance

**Comment by FuccDucc** [comment]
> We don't modify the instances list: https://libredirect.github.io/faq.html#why_not_using_a_single_reputable_instance

Quoted from it:
______________________________________________
**Why not using a single reputable instance?**

LibRedirect is just a tool. We're not here to choose for you. It's your own choice. The default setting selects all instances except those using Cloudflare, but you can change it yourself.

We can't know which instances are reputable for you and which aren't. Every person has a different point of view. LibRedirect should follow your point of view, not ours.
_______________________________________________


It really baffles me that you want to use this policy against behavior that is such a blatant violation of social norms & values, and entirely not accepted within modern society. Do not fall back on your texts, for not having to deal with inconvenient realities. Every thing or platform will face its own types of potential abuse, for which readiness to fight it is desired by the community. In this case, someone is using LibRedirect as a platform for discrimination on the basis of nationality/country of residence, please don't look away and protect your users that would rather not feel insulted, offended, or even emotionally unsafe on the internet. As LibRedirect, be a facilitator of emotional aggression on the internet. Encourage positive vibes, and if you need to add another category to the [instances blacklist](https://github.com/libredirect/libredirect/blob/master/src/instances/blacklist.json) against behavior and attitudes that are widely disapproved (and also have nothing to do with providing internet users useful privacy functionality. Privacy fighting individuals releasing instances or other tooling should have the mindset everyone deserves to use it, not on the basis of nationality or ethnicity)

I will stop using LibRedirect and tell my communities. There may also be like-minded people. I don't like organisations/people that allow themselves to become a platform for unethical behavior/discrimination, and not take action or efforts to limit their userbase from facing that. Do you want that?

**Comment by ManeraKai** [comment]
> I will stop using LibRedirect and tell my communities. There may also be like-minded people. I don't like organisations/people that allow themselves to become a platform for unethical behavior/discrimination, and not take action or efforts to limit their userbase from facing that. Do you want that?

Wow wow wow, not to this extent. We are just a tool and it's up to invidious's team to decide which instances are there. We just fetch these instances to give a starting point to beginner users. I'm closing the issue.

**Comment by FuccDucc** [comment]
> If you believe this to be a problem, you should bring it up to Invidious instead, and see if they'd agree to take it off their instance list.
> 
> ~https://github.com/iv-org/documentation~
> 
> e: I've brought it up with them. From there on it's up to them. Please don't open duplicate issues with them.

I don't see any issue that was created by you or around the time of your comment. Can you link it?

Also, im not focussed on entitlement, but third parties taking their responsibility to isolate any instance which engages in non-accepted behavior like discrimination of this type. I didn't realize the exact nature of LibRedirect and that i should knock on another door, my bad.

**Comment by Sommerwiesel** [comment]
Cheers everyone,
I tried to explain what happened please read my comment on the issue on my github page
https://github.com/Sommerwiesel/invidious/issues/6

Agan, I'm very sorry for this mess. It was a really dumb and insensitive mistake...
