### ISSUE TITLE
could not redirect twitter 

### ISSUE THREAD

**Issue by whyjxz14** [libredirect/libredirect#556]
chrome 105.0.5195.127
version 2.3.4

nothing happens if I just write twitter.com in address bar ，but it could be redirect to nitter if I change twitter language settings and press save . And if I press browser back button,it could still be redirect to nitter again.However,if I open a new window and twitter.com in address bar,it still could not be redirected so this might not related to language

**Comment by tinglycraniumplacidly** [comment]
it doesn't work for https://twitter.com links. 

it does work/redirect for https://www.twitter.com and https://mobile.twitter.com

So there's something wrong with the regex.

**Comment by ManeraKai** [comment]
It's working for all three of them.

**Comment by IkelAtomig** [comment]
> It's working for all three of them.

Yep

**Comment by ManeraKai** [comment]
I think it's bc of your browser or some extensions you installed. I'm closing this issue as regex is working correctly.

**Comment by tinglycraniumplacidly** [comment]
I have the latest version of Brave. I disabled all other extensions. Can anyone else reproduce?
