### ISSUE TITLE
Redirecting to down instances

### ISSUE THREAD

**Issue by DogCatPuppyLover** [libredirect/libredirect#557]
I was told to bring this here, as it seems to be an issue with LibRedirect: https://github.com/TeamPiped/Piped/issues/1828

It's also strange how, when using piped.kavin.rocks, the requests are getting redirected to pipedapi.moomoo.me.

**Comment by Cwpute** [comment]
It may be an instance or front-end based feature. Either way, i'm pretty sure it doesn't depend on LibRedirect :)

**Comment by FireMasterK** [comment]
> It may be an instance or front-end based feature. Either way, i'm pretty sure it doesn't depend on LibRedirect :)

Changing the backend is indeed a front-end feature.

Looking at
https://github.com/libredirect/libredirect/blob/4625aa07feb647ecbaa9a2316e778a7bcc01c605/src/assets/javascripts/services.js#L576-L580
I think that this may not be entirely true. However, I'm not sure where/how libreddit sets preferences. This can be used to override the backend used.

**Comment by DogCatPuppyLover** [comment]
I think that the problem is that LibRedirect is syncing the "Instance" preference across instances when you select "Unify Settings", which should be unique to each instance. So, when the instance you unified from goes down, it appears to affect all instances.

**Comment by IkelAtomig** [comment]
The last comment is exactly right. But closing this as we are going to remove support for Unify Settings in Next release.
