### ISSUE TITLE
Instagram reels (/reels) not redirected

### ISSUE THREAD

**Issue by Rathmox** [libredirect/libredirect#559]
It started a few monthes ago, when Bibliogram got discontinued, instagram redurection stopped working, leading me to the real instagram website.
It's only on Instagram, other redirections work fine
Do you understand the issue ?

**Comment by Dyras** [comment]
Hmm. Instagram started redirecting for me just now. I'm using Firefox.

Is it working for you now?

**Comment by AlyoshaVasilieva** [comment]
Instagram redirection targets:

* The front page
* Posts

It doesn't redirect user pages because Bibliogram can't load users anymore.

**Comment by Rathmox** [comment]
my friend always send reels, when I translate the url to bibliogram, it works

**Comment by AlyoshaVasilieva** [comment]
Oh, they have their own URL format. libredirect needs to redirect URLs such as `/reel/ClEkOfor84R/`

**Comment by Rathmox** [comment]
it's exactly like that

**Comment by ManeraKai** [comment]
Can you send me examples of Instagram reels links to redirect them?

**Comment by Rathmox** [comment]
@ManeraKai this one for example: https://www.instagram.com/reel/Cl5G0YtgdoM/

**Comment by ManeraKai** [comment]
It was actually supported, but there was a typo in a place. Fixed it now and improved a little on it.
