### ISSUE TITLE
Clicking a direct linked video for a Libreddit instance leads to a loop

### ISSUE THREAD

**Issue by Dyras** [libredirect/libredirect#560]
Hello! It would seem Libredirect doesn't take direct linked videos on Libreddit into account when it comes to the "Auto-redirect offline instances to online ones" feature. Specifically, it leads to an almost endless loop.

How to reproduce:
- Firefox
- Latest Libredirect
- Enable "Auto-redirect offline instances to online ones"

1. Click this link https://libreddit.privacy.com.de/vid/kr6783bjzu2a1/1080.mp4
2. Watch the magic happen

**Comment by meatspinner** [comment]
Same thing happens with Rimgo.

**Comment by ManeraKai** [comment]
We're gonna remove Auto-redirect in the upcoming days.
