### ISSUE TITLE
Issues with Amazon login page

### ISSUE THREAD

**Issue by holdit** [libredirect/libredirect#562]
I'm having some issues with the Amazon login page when LibRedirect is active.

With the extension enabled, the login page always takes longer to load. Sometimes it takes a really long time and when that happens, parts of the browser seem to lock? For example, on Brave every tab stops loading and only gets fixed after I restart the browser. It's not as bad on Firefox as it eventually gets working again, but it's still bad. The page loads normally when LibRedirect is disabled.

**I'm using:**

LibRedirect 2.3.4; Firefox 108 and Brave 1.46.140 (Chromium 108); M1 Macbook Pro running macOS 13.0.1 (latest).

**To reproduce:**

Go to amazon.co.uk and click on login. Try with the extension enabled and disabled (browser reboot recommended). Compare the loading speeds between both.

**Video:**

https://user-images.githubusercontent.com/23439751/206916314-19058871-bd91-44a0-8e9f-161c7ca0764b.mp4

**Comment by IkelAtomig** [comment]
I replicated the same on a fresh profile. I could access though. Could you check again ?

**Comment by ManeraKai** [comment]
I want you to show me the console page of LibRedirect while you're signing in to Amazon. LibRedirect is redirecting something it's not supposed to:
![image](https://user-images.githubusercontent.com/40805353/213875692-d462af22-25a2-46f5-adce-270fb1e96055.png)

**Comment by holdit** [comment]
I stopped using this extension (these issues, plus no old.reddit.com redirect... using individual extensions now), so I'm not able to test over a long period and on different sites, but I installed 2.5.0 on Brave and the Amazon login page seems to load fine.

I also tested with the previous 2.3.4 again and the problem is there. Probably no longer useful, but here's the screenshot you asked for:

<img width="745" alt="Screenshot 2023-02-03 at 14 52 53" src="https://user-images.githubusercontent.com/23439751/216635305-a6fc5a69-eace-47e9-a49b-0adee094c38b.png">

While 2.5.0 doesn't block the loading of that page, there's still some errors there. In case it's useful:

<img width="820" alt="Screenshot 2023-02-03 at 14 59 13" src="https://user-images.githubusercontent.com/23439751/216635612-7d54eb24-9eec-426b-aa56-be45f4c3c4c5.png">

Since 2.5.0 seems to work fine, maybe this issue can be closed.

**Comment by ManeraKai** [comment]
> While 2.5.0 doesn't block the loading of that page, there's still some errors. In case someone wants to have a look:

This is a bug but doesn't crash the extension, I will try to fix it though.

> Since 2.5.0 seems to work fine, maybe this issue can be closed.

Alright, thanks for the screenshots.
