### ISSUE TITLE
Completely prevents tabs from loading in firefox

### ISSUE THREAD

**Issue by hippopotamusgoldfish** [libredirect/libredirect#564]
repo seems to be more active on github, mirror of https://codeberg.org/LibRedirect/libredirect/issues/61

# What happened?

Whenever I try to open a new tab or open a new website it refuses to load and only works when I disable the extension, regardless if it is a page to redirect or not.
# What did you expect to happen?

To let me on the website
# Steps to reproduce:

    Go to a website
    See it refuse to load
    Disable Libredirect

Debug information:

Browser and version number: Firefox 107
Libredirect version: 2.3.4
Screenshots/Videos
![image](https://user-images.githubusercontent.com/104040739/206923943-75f453c6-8347-4266-bf1d-a0d3219047f0.png)
![image](https://user-images.githubusercontent.com/104040739/206923939-c1e4e3cc-db98-4867-8a14-151c9b51e33f.png)
![image](https://user-images.githubusercontent.com/104040739/206923949-875fb42e-8e9f-48a4-864d-0dea27ac4a78.png)
![image](https://user-images.githubusercontent.com/104040739/206923951-98f19fc0-2e89-49ce-adc3-a3f82c9a8932.png)

**Comment by holdit** [comment]
I think this is the same problem I'm having ( #562 ), but in my case it's Amazon. Not sure why.

**Comment by ManeraKai** [comment]
There are some conflicts in the requests both you @hippopotamusgoldfish and @holdit are experiencing apparently. It's also happening to me with a specific website. The solution would be to minimize our url targets as much as possible.

**Comment by ManeraKai** [comment]
Is the same happening in v2.5.0?
