### ISSUE TITLE
error in edge and chrome

### ISSUE THREAD

**Issue by ghorbat** [libredirect/libredirect#566]
**hi
after load unpack in edge or chrome show error**

**"browser_specific_settings": {
		"gecko": {
			"id": "7esoorv3@alefvanoon.anonaddy.me",
			"strict_min_version": "67.0"
		}
	},**

![Untitled](https://user-images.githubusercontent.com/23626707/207258571-ac69d6bc-1ec9-4a5b-8596-f14c219100e2.png)

**Comment by ManeraKai** [comment]
It's normal, firefox uses this data but chromium browsers don't like edge and chrome.
