### ISSUE TITLE
[Feature Request] Ignore redirects for bookmarks or certain urls

### ISSUE THREAD

**Issue by Terkyz** [libredirect/libredirect#568]
First, thank you very much for developing this great extension.

Would it be possible, or useful to consider adding the ability to ignore redirects from certain URLs or bookmarks, so that from that specific URL or bookmark no redirects are made?

For example, suppose I touch a Twitter link, LibReddirect will redirect me to Nitter, but with the function that I propose if I touch a specific URL (suppose, the URL of my Twitter profile) the redirections to Nitter are disabled only and specifically this in the same window that I enter with the URL of my profile, if I enter to Twitter normally this would not apply and the redirections of Nitter would work.

Why? Because even if I don't want to use Twitter and therefore use Libredirect, maybe I still want to comment on a tweet but I only want to comment, I don't want to browse Twitter without Libredirect, so I would press the URL of my profile (which would be ignored according to the proposed function) or the Twiiter bookmark I have on my homepage, and I would browse Twitter without Libredirect, and if I press for example on a tweet, libredirect would not redirect me to Nitter.

I know there is the "exceptions" function but maybe I'm doing something wrong because if for example I add my Reddit profile as an exception, once I leave that URL I will be redirected, and my point is that I want to navigate through that URL as if I had the redirects disabled for the entire URL, in case I want to comment on any post, plus I think it would help to improve the workflow a little to not have to be disabling the redirects manually.

**Comment by IkelAtomig** [comment]
I think, `Toggle redirects in this tab` option in Context menu could help your case.
