### ISSUE TITLE
Add Gothub

### ISSUE THREAD

**Issue by Adi1200** [libredirect/libredirect#569]
Gothub is a frontend for GitHub hosted at gothub.vern.cc 
Source code: https://codeberg.org/gothub/gothub

**Comment by IkelAtomig** [comment]
It's still an Alpha and don't support stuff such as Issues, Commits, etc. which is main thing. After they are added, we will work on this.

**Comment by codenyte** [comment]
Thanks, was just about to open an issue for that

**Comment by Crystal-RainSlide** [comment]
If their progress is slow & libredirect is growing fast, I think libredirect may add a Experimental Settings, or custom redirections, to include or allowing the usage of those usable but not mature frontends.

**Comment by ManeraKai** [comment]
@Crystal-RainSlide all frontends are disabled by default and it's up to the user to enable the ones he wants.

**Comment by throwaway-d** [comment]
> he wants.

"They" pronoun should be used for any people we haven't known their pronouns yet.
