### ISSUE TITLE
Feature request | Add support for Yattee

### ISSUE THREAD

**Issue by ph00lt0** [libredirect/libredirect#57]
Please consider the option to allow opening links in [Yattee](https://github.com/yattee/yattee)

It supports the opening of youtube links on yattee:// see: https://github.com/yattee/yattee/blob/main/Open%20in%20Yattee/content.js

**Comment by Loki-L1130** [comment]
similar to freetube.

**Comment by ManeraKai** [comment]
@ph00lt0 like this?

old: `https://www.youtube.com/watch?v=djJVePeqC4s`

new: `yattee://www.youtube.com/watch?v=djJVePeqC4s`
OR 
new: `yattee://https://www.youtube.com/watch?v=djJVePeqC4s`

**Comment by ManeraKai** [comment]
I have no iOS or MacOS to test it though.

**Comment by Loki-L1130** [comment]
Maybe @ph00lt0 could do that.

**Comment by austinhuang0131** [comment]
It works only for video URLs. It does not work for search or playlists.

Also it's Yatte**e**, not "Yatte"

**Comment by austinhuang0131** [comment]
probably? but i downloaded it only to use it, i don't use it usually

**Comment by ph00lt0** [comment]
> Maybe @ph00lt0 could do that.

well the links i provided do work for sure.

**Comment by ManeraKai** [comment]
Is there anything I should do on my side for it to work?

**Comment by ph00lt0** [comment]
@ManeraKai try opening this random playlist: yattee://youtube.com/s/playlist?list=PLDIoUOhQQPlXr63I_vwF9GD8sAKh77dWU for me this works fine.

**Comment by ph00lt0** [comment]
@ManeraKai not sure why this is closed? 
I see i tagged the wrong person @austinhuang0131 please check the playlist above.

**Comment by ManeraKai** [comment]
I saw no one is talking about it. I can't test it myself so I closed it, I'll open it again.

**Comment by ManeraKai** [comment]
So playlists work but search isn't working right?

**Comment by ph00lt0** [comment]
@ManeraKai I just noticed the feature is integrated, works!

**Comment by ph00lt0** [comment]
@ManeraKai yes search doesn't but that's a yattee bug, will report it

**Comment by austinhuang0131** [comment]
still does not work for playlists, even if i directly input `yattee://`, but that's probably their problem

**Comment by ManeraKai** [comment]
@austinhuang0131 give your playlist example for the others to test if you have one.

**Comment by austinhuang0131** [comment]
the one @ph00lt0 gave

i directly input it in safari and chromium, neither works

**Comment by ManeraKai** [comment]
@austinhuang0131 Does this one work? `yattee://youtube.com/playlist?list=PLDIoUOhQQPlXr63I_vwF9GD8sAKh77dWU`

**Comment by ManeraKai** [comment]
I just took of the `/s/`

**Comment by JanOstrowka** [comment]
> @austinhuang0131 give your playlist url for the others to test if you can.

Sorry, playlist links do not work. They are being successfully open in Yattee. However, as @austinhuang0131 has just suggested, it is a problem of Yattee, as they do not support playlist yet -> https://github.com/yattee/yattee#availability

**Comment by ManeraKai** [comment]
@JanOstrowka It's not mentioning YouTube. It says that it's supported on invidious though?

**Comment by JanOstrowka** [comment]
@ManeraKai  I've been trying to see if Yattee opens playlist link after switching redirect settings, but I had no luck.

Maybe #itjustworks for @ph00lt0

**Comment by ManeraKai** [comment]
Maybe a version problem. Can everyone say his version?

**Comment by austinhuang0131** [comment]
latest, v1.3.2

**Comment by JanOstrowka** [comment]
*update*
I've tried this link `yattee://youtube.com/watch?v=q6EoRBvdVPQ&list=PLFsQleAWXsj_4yDeebiIADdH5FMayBiJo`
using Piped
and it did work

**Comment by JanOstrowka** [comment]
@ManeraKai `yattee://youtube.com/playlist?list=PLDIoUOhQQPlXr63I_vwF9GD8sAKh77dWU` did not work

What Invidius instance are you using @ph00lt0 ?

**Comment by austinhuang0131** [comment]
@JanOstrowka for once it loaded only the video, then it stopped working

but this is a yattee problem, why are we even discussing it here

**Comment by ph00lt0** [comment]
> @ManeraKai `yattee://youtube.com/playlist?list=PLDIoUOhQQPlXr63I_vwF9GD8sAKh77dWU` did not work
> 
> What Invidius instance are you using @ph00lt0 ?

Tried a with https://invidio.xamh.de/

**Comment by ManeraKai** [comment]
> but this is a yattee problem, why are we even discussing it here

You're right, if anyone opens an issue on Yattee, mention it's link here plz so we will know about any updates.
