### ISSUE TITLE
Fonts and icons are far too big

### ISSUE THREAD

**Issue by glocalglocal** [libredirect/libredirect#571]
Fonts and icons in the toolbar menu and addon options are far too big. The fonts are even bold. It doesn't affect functionality but it looks completely out of place. I am not sure if I am the only one seeing it so here is a screenshot for reference: 

![image](https://user-images.githubusercontent.com/16408198/209199735-42574132-5d36-46b4-93bc-5055e0bad6a2.png)

**Comment by ManeraKai** [comment]
Weird:
![Screenshot_20221227_180326](https://user-images.githubusercontent.com/40805353/209684857-febc0f44-2dfb-4bb0-a83f-f4c387ebb8ac.png)

**Comment by ManeraKai** [comment]
What browser and OS are you using?

**Comment by glocalglocal** [comment]
> What browser and OS are you using?

Firefox 108.0.2 64-bit, Win 10 64 bit.

**Comment by ManeraKai** [comment]
Those are from windows 10 with LibRedirect v2.5.0. It seems there's another extension disabling fonts such as NoScript.
![libredirect-popup](https://user-images.githubusercontent.com/40805353/216597952-388652df-3f56-4722-94d1-94047518d83f.png)
![libredirect-settings](https://user-images.githubusercontent.com/40805353/216597964-de902aae-b9e4-4523-9644-710f039d16d2.png)

**Comment by ManeraKai** [comment]
Similar to this issue: https://github.com/libredirect/libredirect/issues/608

**Comment by glocalglocal** [comment]
For the record, I don't have noscript or similar addon that is likely to interfere with fonts. I switched to the default Firefox theme and switched off Dark Reader and uBlock Origin just in case, and the problem persists. Libredirect is the only addon I have ever seen behaving like this. Anyway, it doesn't affect functionality. It just looks odd (and may unsettle some users).

**Comment by ManeraKai** [comment]
Is the settings page the same? Can you open dev tools and shoe me?

**Comment by glocalglocal** [comment]
The settings page for Libredirect always shows huge fonts. 

![image](https://user-images.githubusercontent.com/16408198/216607125-e1f1b481-eee0-42a2-b12b-b2910d5d1517.png)

> Can you open dev tools and show me?

I don't know how to do this.

**Comment by ManeraKai** [comment]
> The settings page for Libredirect always shows huge fonts.

well technically they are good size, "readable" you can say.

> I don't know how to do this.

I don't think there's a need bc the fonts are applying correctly to the settings page, but not the popup apparently.

**Comment by ManeraKai** [comment]
Is it still happening in the new version btw?

**Comment by glocalglocal** [comment]
They are definitely 'readable'. Too readable. :) I left the toolbar and URI address in the screenshot for reference. The fonts really look massive compared to any other settings page I've seen, but fair enough. I suppose it's a matter of preference.

Big fonts on popup still happens in recent v2.5.

**Comment by ManeraKai** [comment]
> I suppose it's a matter of preference.

I think so xD

> Big fonts on popup still happens in recent v2.5.

So you are seeing scrollbars even, the exact same as the first picture you sent about the popup?

**Comment by glocalglocal** [comment]
> So you are seeing scrollbars even, the exact same as the first picture you sent about the popup?

Ah, sorry. No scrollbars. Just the biggest sliders and fonts I have even seen in a popup. 

![image](https://user-images.githubusercontent.com/16408198/216610946-c70ba750-2e8f-4ea1-a780-0b2a62c0a0b5.png)
