### ISSUE TITLE
Used proxitok instance down

### ISSUE THREAD

**Issue by Modusmundi** [libredirect/libredirect#572]
https://proxitok.dhusch.de/

Resolves to an admin page, I assume the instance was taken down.  I contacted the owner at dhusch.de to let them know, but figured I'd let you know too.  If you want I can probably make the change and submit a PR.

**Comment by IkelAtomig** [comment]
Please report to the proxitok project. We fetch instances from them, Once they remove, we remove in Libredirect. It's all automatic, We don't interfere.
