### ISSUE TITLE
Add alternatives for Instagram | Remove Bibliogram (for now)

### ISSUE THREAD

**Issue by snocodile** [libredirect/libredirect#573]
Bibliogram was discontinued in September 2022 and I currently know of no effort to revive it.

Therefore it would be best to remove the Bibliogram instances for now and replace them with some of the following alternatives:

- [Imginn](https://imginn.com) 
- [GreatFon](https://greatfon.com) 
- [Dumpor](https://dumpor.com) 
- [Pixwox](https://pixwox.com) 
- [Gramhir](https://gramhir.com) 
- [StoriesIG](https://storiesig.app)

**Comment by jahtnamas** [comment]
imginn is already listed as a "bad example" of a redirection request per [the project's FAQ](https://libredirect.codeberg.page/faq.html) because it contains many trackers.

**Comment by IkelAtomig** [comment]
We might consider Dumpor and Pixwox but we prefer no trackers at all.

**Comment by candroid-man** [comment]
Bibliogram is pretty much gone for good, It would be best to remove it next update

**Comment by PeterDaveHello** [comment]
People don't like censorship might have concerns that all of the listed alternatives are hosted behind a single large CDN provider.

**Comment by Crystal-RainSlide** [comment]
Maybe there can be some infomation about the tracker and CDN thing shown for the current selected frontend, like what F-droid does for the apps: https://f-droid.org/en/docs/Anti-Features/

**Comment by ManeraKai** [comment]
Even with F-Drdoid the apps have to be FOSS in the first place and other things.

Most of the mentioned alternavives are basically the same entity even: https://storiesig.app/
![image](https://user-images.githubusercontent.com/40805353/216553768-8268d44c-fbc3-4ed4-86ab-11e735074a3b.png)

I know you want an alternative for Instagram, but Instagram is making itself like a paywall with requiring accounts all the time. There could be a way of using fake accounts and binding it with bibliogram and maybe also shuffling it with other instances so those fake accounts won't be detected, but mind you that would not be easy to make.
