### ISSUE TITLE
Unable to manually install on Kiwi browser (Android chromium)

### ISSUE THREAD

**Issue by gitterspec** [libredirect/libredirect#574]
I zipped just the contents of the src folder from the repo and tried adding it manually. Fails to install without error message. Have tried various combinations of including the parent directory vs not in the zip file.

This method has worked fine for other extensions. Anyone else having the same issue?

**Comment by MicroBeast** [comment]
I don't really use Kiwi, more a Firefox person. It just here on my device to play with.

Anyway, I add libredirect.zip (as the official way suggested), it installed with error msg about deprecated things & other stuff. Libredirect just work here, which surprised me.

Maybe there're will be leaks issues or other things, it Chromium & unsupported by Libredirect after all.

**Comment by gitterspec** [comment]
> I don't really use Kiwi, more a Firefox person. It just here on my device to play with.
> 
> Anyway, I add libredirect.zip (as the official way suggested), it installed with error msg about deprecated things & other stuff. Libredirect just work here, which surprised me.
> 
> Maybe there're will be leaks issues or other things, it Chromium & unsupported by Libredirect after all.

It sounds like you got it to work? If so, can you please share the zip file you used?

**Comment by MicroBeast** [comment]
I just download from https://github.com/libredirect/libredirect/releases.

I use that verbatim, no changes. I never thought it would work in beginning.

**Comment by gitterspec** [comment]
Thanks for reporting! It worked. Thought I had tried it without changes before, but maybe not.

**Comment by IkelAtomig** [comment]
For the record, We don't support Mobile browsers, yet officially.

**Comment by MicroBeast** [comment]
Yes, I am aware of that. Hence I mentioned I never expected it to just work when I randomly throw it to both Browsers. Even Youtube Embedded work. I won't bother the dev for my own play thing.

Issue on opening Settings page on Firefox might be Firefox issue on uAsset. Firefox also has issue opening/viewing uBlock0 filter (big text). I mean, seem not Libredirect issue.
