### ISSUE TITLE
Add Wayback Classic

### ISSUE THREAD

**Issue by ghost** [libredirect/libredirect#578]
https://wayback-classic.net/
The goal is to get rid of JavaScript when using the Wayback Machine

**Comment by ManeraKai** [comment]
If those "old browsers" can't run the wayback JavaScript. Then they already won't be able to run LibRedict's JavaScript??

**Comment by PoorPocketsMcNewHold** [comment]
> [**@ManeraKai**](https://github.com/ManeraKai) commented on [Feb 1, 2023, 7:11 AM GMT+1](https://github.com/libredirect/libredirect/issues/578#issuecomment-1411519528):
> 
> > If these "old browsers" can't run the wayback JavaScript. Then they already won't be able to run LibRedict's JavaScript?
> > 
> > _Originally posted by @ManeraKai in https://github.com/libredirect/libredirect/issues/578#issuecomment-1411519528_

That the main focus of the website, but others could be interested into having a lighter Wayback Machine interface, which those are the one using LibRedirect for sure.
