### ISSUE TITLE
Switch to Codeberg completely

### ISSUE THREAD

**Issue by nvidiaLinuxUser** [libredirect/libredirect#579]
Why is this repository not a mirror of the Codeberg repository? It would be nice to leave GitHub completely. The fact that this project has two separate repositories is very confusing
**Libre**direct.

**Comment by ManeraKai** [comment]
We won't switch completely for the time being as we want to reach out to users as much as we can.

**Comment by nvidiaLinuxUser** [comment]
@ManeraKai Okay, I got it. Thanks for the reply
