### ISSUE TITLE
Export settings to a JSON file

### ISSUE THREAD

**Issue by SD745** [libredirect/libredirect#58]
Adding a button to reset options to default/clear extension data may be beneficial, especially when dealing with issues such as #55 or helping users who want to fix something they misconfigured.

**Comment by ManeraKai** [comment]
Problem is, the console didn't even start. Even the regular startup warnings didn't show up.
Ex:
![image](https://user-images.githubusercontent.com/40805353/155007244-61d88d78-c17b-418d-8f16-858be6e502c8.png)

**Comment by SD745** [comment]
To tie in with this enhancement, a backup and restore function for saved preferences could also be implemented

**Comment by ManeraKai** [comment]
You mean to export settings to a json file as an example?

**Comment by SD745** [comment]
> You mean to export settings to a json file as an example?

Yes
