### ISSUE TITLE
Randomly causes all page loading to hang until extension is disabled

### ISSUE THREAD

**Issue by gitterspec** [libredirect/libredirect#580]
Don't know exactly how to reproduce this, but it happens maybe once every 1-2 days. URLs just keep trying to load forever, regardless of the URL and even for local files. Affects all tabs. Only solution is to disable libredirect and then they instantly load and the problem goes away. Then I re-enable libredirect and problem is still gone until it comes up next time. So basically, I am disabling and instantly re-enabling libredirect each time this happens.

Using 2.3.4 with latest Brave.

**Comment by tokkusu** [comment]
Can confirm, happens to me like every 1-2 days, exactly like OP explained.

I'm using Libredirect 2.3.4 with Ungoogled Chromium version 109.0.5414.75 (64-bit)

**Comment by omar-mohy** [comment]
Can reproduce on developer.android.com, it happens quite frequently but not 100% of the time - the extension's process (visible through the browser's task manager) indicates 100.0 CPU utilization, all tabs can't load, and the only solution is to either disable the extension or end its process, adding this domain to exceptions doesn't seem to help.

(Libredirect v2.3.4 - Brave v1.47.186)

**Comment by omar-mohy** [comment]
Can reproduce on developer.android.com, it happens quite frequently but not 100% of the time - the extension's process (visible through the browser's task manager) indicates 100.0 CPU utilization, all tabs can't load, and the only solution is to either disable the extension or end its process, adding this domain to exceptions doesn't seem to help.

(Libredirect v2.3.4 - Brave v1.47.186)

**Comment by omar-mohy** [comment]
Tried again with v2.5.0, the issue seems to be resolved (even after removing the problematic domain from exceptions).

**Comment by ManeraKai** [comment]
@gitterspec and @tokkusu?

**Comment by gitterspec** [comment]
@ManeraKai I am trying now and will report back if any errors. Thanks!
