### ISSUE TITLE
New frontend: Rural Dictionary

### ISSUE THREAD

**Issue by trueauracoral** [libredirect/libredirect#581]
Rural Dictionary is a fronted for Urban Dictionary.

Source Code: https://codeberg.org/zortazert/rural-dictionary/

It is relatively new and a small project, because urban dictionary is not that complicated.

Instances: https://codeberg.org/zortazert/rural-dictionary/src/branch/master/instances.json or in the README

Except for pages for users on urban dictionary all routes are supported.

**Comment by ManeraKai** [comment]
> Except for pages for users on urban dictionary all routes are supported.

No, just `/`,  `/define.php`, `/random.php` are supported.
