### ISSUE TITLE
LibRedirect

### ISSUE THREAD

**Issue by pH142857** [libredirect/libredirect#586]
Sometimes embedded videos autoplay with Invidious. I can't find the Invidious setting for autoplay in LibRedirect. I read the FAQ, no clue.

**Comment by ManeraKai** [comment]
video embeds are having some problems especially in Firefox if I remember correctly, it's about cookies. Either way, LibRedirect will stop modifying cookies (instances settings) bc it gave a lot of problems and we will stick to just focusing on redirection.

**Comment by pH142857** [comment]
So, can you confirm that to get that solved, I should open a ticket in the Invidious repo?
