### ISSUE TITLE
Add option to redirect to Troddit

### ISSUE THREAD

**Issue by blakegearin** [libredirect/libredirect#587]
Source: [burhan-syed/troddit](https://github.com/burhan-syed/troddit#readme)

Website: https://www.troddit.com

**Comment by obj-obj** [comment]
@blakegearin you can also work around this for now by just adding troddit as a custom frontend

**Comment by dtantono** [comment]
I second this. troddit experience is way better than libreddit & teddit

**Comment by IkelAtomig** [comment]
I vote for this. Being a reddit user. I love this one.

**Comment by ManeraKai** [comment]
It's a reddit client not a "frontend", similar to `Pinafore`'s case: https://libredirect.github.io/faq.html#suggest_frontend
