### ISSUE TITLE
Replacement for Scribe - Libmedium

### ISSUE THREAD

**Issue by IkelAtomig** [libredirect/libredirect#588]
https://github.com/realaravinth/libmedium

**Comment by ManeraKai** [comment]
Why a "replacement" though?

**Comment by IkelAtomig** [comment]
It proxies every content. But scribe don't do it as of now or Add it to the top of the list. Do as you wish.

I think making them available side by side is better but what you keep in the top of the list might matter for some people.

**Comment by ManeraKai** [comment]
Scribe supports third party medium websites, but LibMedium doesn't yet. So I will keep Scribe as the default option and make LibMedium as the secondary one.
