### ISSUE TITLE
Skip redirection for the current website

### ISSUE THREAD

**Issue by JediMaster25** [libredirect/libredirect#590]
Visit raw link for the current website with as few clicks as possible.

**Comment by nickelswitte** [comment]
Would it be possible to redirect all requests to the alternative frontend, e.g. `reddit.com -> libreddit.domain.tld`, **except** redirecting the other way round: `libreddit.domain.tld -> reddit.com `.

Sometimes I want to check out the original reddit site, and would like to use the buttons in invidious or libreddit to go there, without having to disable the redirect in libredirect everytime. That would be great!

**Comment by JediMaster25** [comment]
> Would it be possible to redirect all requests to the alternative frontend, e.g. `reddit.com -> libreddit.domain.tld`, **except** redirecting the other way round: `libreddit.domain.tld -> reddit.com `.
> 
> Sometimes I want to check out the original reddit site, and would like to use the buttons in invidious or libreddit to go there, without having to disable the redirect in libredirect everytime. That would be great!

Forget what I said. That is a better way to put what I want.

**Comment by ManeraKai** [comment]
Right click on the LibRedirect icon a click `Redirect to original`
