### ISSUE TITLE
Weird behaviour in custom FF profile - does not work

### ISSUE THREAD

**Issue by Megver83** [libredirect/libredirect#592]
I tried Libredirect in my custom FF profile and it behaves weird. The switches list is duplicated, toggles do not work and the theme is hard-coded to dark. However, on the default profile it works fine.

Here's a video were I tried my custom profile first and then the default one.

https://user-images.githubusercontent.com/22277674/212502385-f33493e9-2492-4ed4-bde8-d786e9464c52.mp4

**Comment by ManeraKai** [comment]
I think you may be having same issue with Tor browser, try resetting to see if it will work properly. I want you to reset so it will "initialize" the settings since in Tor it's not allowing LibRedirect to do so automatically on installation.
