### ISSUE TITLE
Extension doesn't work in the MyPal Browser

### ISSUE THREAD

**Issue by SecularSteve** [libredirect/libredirect#596]
At least the 32-bit version anyway.

Tested on a Windows XP machine, and the extension doesn't work at all.
MyPal is basically a Firefox fork modified and optimised to work on old deprecated Windows Operating Systems. 

https://github.com/Feodor2/Mypal68/

First off, it's in permanent dark mode, the site redirect switch tab is duplicated, and none of the buttons at the bottom work.

Was this add-on never meant to work on a modified 32-bit version of Firefox meant to run on XP and older OSes? Or is this something that needs some attention?

**Comment by ManeraKai** [comment]
> Was this add-on never meant to work on a modified 32-bit version of Firefox meant to run on XP and older OSes?

no xD

> Or is this something that needs some attention?

Our most attention is for most up-to-date Windows, Linux, and Mac OS's. Many of the extension's features in the extension API aren't supported in previous versions.
