### ISSUE TITLE
Auto-updating for Chromium on Windows/Mac.

### ISSUE THREAD

**Issue by dtantono** [libredirect/libredirect#597]
Hi
I know chrome store is unsupported atm https://github.com/libredirect/libredirect/issues/18. Is it possible to support Edge/Opera store?

**Comment by IkelAtomig** [comment]
Opera store is still under review for months.

We got booted off Microsoft store as we redirected Bing Search and affected MS's revenue. So, We trying to release for next release. Hope it is back in there.

**Comment by techgamers2** [comment]
yes pls try to add in edge store i ws able to install it but every time new update comes i hav to do the installation process all over again and every time my browser bugs me to turn off developer mode atm i m back to privacy redirect extension ... i also tried to install via foxified extension but didnt work :(

**Comment by IkelAtomig** [comment]
The Auto-update works for Any other Chrome browsers too ?

Any idea about MacOS.

**Comment by IkelAtomig** [comment]
@Ammako Doesn't the CRX Proof thing affect here when using your method for Windows/Linux ?

**Comment by chiefy** [comment]
I looked into this on MacOS `12.6.1` but I think you're going to have the same issue elsewhere, at least with Chrome. The instructions @Ammako provided re: extension allow lists etc. only pertains if your instance of Chrome is managed by Google Admin Console or Microsoft Active Directory etc. Most people don't have this ability.

I also don't think that Chrome allows you to auto-update any side-loaded extensions, the mechanism only works if you install extensions from the store or your Chrome is policy-managed per above. I could be wrong here, but that's what I gathered from my hour of trying to get it work locally (`109.0.5414.119 (Official Build) (x86_64)`)

**Comment by ManeraKai** [comment]
I see, I hope a way comes out at some times. Till that time I'll close the issue. And thanks for your help :)

**Comment by chiefy** [comment]
Well something that did work with Chromium latest (`Version 112.0.5592.0 (Developer Build) (x86_64)`) is:

* install Chromium / start / quit
* `mkdir ~/Library/Application Support/Chromium/External Extensions`
* `echo "{\"external_update_url\":\"https://raw.githubusercontent.com/libredirect/libredirect/master/src/updates/updates.xml\"}" > oladmjdebphlnjjcnomfhhbfdldiimaf.json`
* start Chromium
* an "error" will appear telling you something added the extension, click "enable extension" and it downloads and installs latest, no idea if it will auto-update after this but it seems though it will

**Comment by ManeraKai** [comment]
In the downloads section it's a version prior to the latest one, press Update and see if it will change from 2.5.1 to 2.5.2

**Comment by chiefy** [comment]
@ManeraKai in Chromium if I install using the `.crx` drag+drop method, the `2.5.1`->`2.5.2` auto-update worked! So there's that :)

**Comment by ManeraKai** [comment]
oh :), so

**Comment by ManeraKai** [comment]
So convert the terminal commands you documented to a one file like how it is with windows (`.reg`), and then document the process step by step and keep it as simple as possible. If you can record a video with clear sound then that will be a nice bonus.

**Comment by ManeraKai** [comment]
@chiefy plz?

**Comment by chiefy** [comment]
@ManeraKai I didn't realize you could do the drag-and-drop w/ Chromium so it's kind of pointless to do that way since it won't work in regular Chrome.

**Comment by IkelAtomig** [comment]
State that, 'You will see "Your Browser is managed by your Organization" since the registry entries modify the browser's policies as an Administrator. There is no need to worry as the registry entry you are going to add just allows Libredirect to be used without any restriction".

I don't know about MacOS. So, I didn't write for it.
