### ISSUE TITLE
Change instance with the context menu

### ISSUE THREAD

**Issue by user451421541757324** [libredirect/libredirect#598]
Let's suppose I'm currently browsing piped.video but videos wont load. Since libredirect can't detect that, I must manually change the instance.

It would be nice to quickly do that with the context menu, it would be faster than doing it with the extension button.

**Comment by ManeraKai** [comment]
You can right click the extension button click Switch Instance or press SHIT + ALT + L

**Comment by Andrewskiz** [comment]
The hotkey is super useful, didn't know about it but I will be sure to use it. Is there any way to remap it?

**Comment by ManeraKai** [comment]
Yes: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

**Comment by ManeraKai** [comment]
and @user451421541757324, I think you don't have piped.video in your instances selection, if so then do as follows: https://libredirect.github.io/docs.html#preferred_instance
