### ISSUE TITLE
[Feature Request]:- Change UI/UX of libredirect extension settings

### ISSUE THREAD

**Issue by m77e4t** [libredirect/libredirect#60]
To change to UI/UX of the libredirect settings.

![Screenshot from 2022-02-24 (1)](https://user-images.githubusercontent.com/96620334/155570838-2c4df513-5ecc-41ea-8f83-b86690b31e8d.png)

The left-hand side rows with all the tech products listed does not look appeasing to the eye (according to me). Other settings UI looks normal (to me).

**Comment by IronMaltese** [comment]
Do you have a recommended alternative design?

**Comment by ManeraKai** [comment]
I've made it like firefox's settings design.

**Comment by m77e4t** [comment]
For start, the size of the letters can be reduced to match the size of all other letters. It can match firefox letter size (from their menu/settings/etc) and the other letters from the extension settings itself, like 'Theme, Dark, Exception' as seen in the above photo.

**Comment by IronMaltese** [comment]
I also think the Wikipedia logo should be added and grouped at the bottom of the websites with thumbnail icons, and the medium logo should be implemented, but change to white in dark mode, and change to black in light mode

**Comment by ManeraKai** [comment]
btw, Thanks @asaaki for the [Siplified Medium SVG Logo](https://markentier.tech/posts/2020/10/medium-icon-svg/). It really helped me 👍

**Comment by ManeraKai** [comment]
This is how it look now:
![image](https://user-images.githubusercontent.com/40805353/155886316-cb25d3ca-b607-4ad6-8a5c-fa61150904f2.png)

**Comment by m77e4t** [comment]
Looks pretty good compared to previous one :)

**Comment by asaaki** [comment]
> btw, Thanks @asaaki for the [Siplified Medium SVG Logo](https://markentier.tech/posts/2020/10/medium-icon-svg/). It really helped me 👍 I mentioned you in the code.

I'm glad I could be of help, and for a nice project even.

**Comment by IronMaltese** [comment]
> This is how it look now:
This looks 10x better than before, but Wikipedia should be moved just under Imgur since it has a logo and Medium should be under Wikipedia, since it's technically has a logo, but it's either an all-black or an all-white design, and moving forward, redirects with logos should stay on the top half, and ones that don't should be on the bottom

**Comment by ManeraKai** [comment]
Resorted them:
![image](https://user-images.githubusercontent.com/40805353/155923606-cbba69b8-6b4d-46d5-8185-6a11f4f9c6f5.png)

**Comment by m77e4t** [comment]
New instances, some other new products, were added to the list. The UI/UX has again become unappealing/unattractive.

![Screenshot from 2022-03-26](https://user-images.githubusercontent.com/96620334/160224624-27963244-14a4-400a-ad48-354d385b9468.png)
1.) Change the font, the current font has quite a large width. Use some other font which has normal width (eg, github font itself or Ublock-origin etc) (do not actually use their fonts, there might be a copyright issue, only gave as an example)
2.) Lower the size of letters (the left column where all products are listed). Make that size similar to the other letter in the extension (the right column of actual settings).
3.) Lower the size of yellow toggle. It looks too big.


1.) Again, lower size of letter.
2.) Lower the yellow toggle and match the size of letters.
![Screenshot from 2022-03-26 (1)](https://user-images.githubusercontent.com/96620334/160224648-4e8456f4-c3c1-4316-9797-b4d82e79f58a.png)

**Comment by ManeraKai** [comment]
![image](https://user-images.githubusercontent.com/40805353/160908150-648c0519-7309-47aa-a9fc-c3d11ab3944f.png)

**Comment by m77e4t** [comment]
It looks good to me than the before one. But, I am not able to see it on my end. I think it might be not able for end users, but only on your end.

I would say make the UI the way you want, no force from my side. If you want it to look like as it was in the starting, so be it.

**Comment by ManeraKai** [comment]
> It looks good to me than the before one. But, I am not able to see it on my end. I think it might be not able for end users, but only on your end.

I just didn't publish the modified code yet.

> I would say make the UI the way you want, no force from my side. If you want it to look like as it was in the starting, so be it.

I like your suggestions but not all of them. The font is actually good specially when now the sidebar is smaller. I also lowered the size of the toggles too.
