### ISSUE TITLE
auto-redirect loops with YT paywalled videos

### ISSUE THREAD

**Issue by WAZAAAAA0** [libredirect/libredirect#600]
Enabling "Auto-redirect offline instances to online ones" from the settings and trying to visit paywalled YouTube links results in fast endless redirect loops.

The loop happens with the Invidious and CloudTube frontends, not Piped/Piped-Material.

SAMPLE LINKS:
https://www.youtube.com/watch?v=vL7twY-S2jc "This video is not available" (purchasable movie)
https://www.youtube.com/watch?v=ajnrYkeJmcY "This video is only available to Music Premium members"

(tested with version 2.3.4 on both Firefox and Chrome)

**Comment by ManeraKai** [comment]
This is bc Invidious and CloudTube give a 500 server error code, which shouldn't be so. Either way, we removed Auto-redirect from the next release.

**Comment by WAZAAAAA0** [comment]
> we removed Auto-redirect from the next release.
...wait really? Auto-redirect is the single most useful function to come from this fork, what's the harm in keeping it in but OFF by default, like it has always been?

**Comment by ManeraKai** [comment]
Things should be controllable. The philosophy of LibRedirect isn't to have many unreliable instances selected, it's to have one to three trusted instances selected. If one failed, you can right click on LibRedirect icon and press Switch Instance or do the same from the popup.
