### ISSUE TITLE
Being redirected to an instance that's not in the settings

### ISSUE THREAD

**Issue by Kerobyte** [libredirect/libredirect#602]
Has happened infrequently for over a month with different sites. I usually add the instance manually but at this point I'd rather find a fix because the switch instance feature doesn't work while the instance isn't in the settings.
Update Instances doesn't add the instance.
Reset Settings doesn't add the instance.
Reinstalling doesn't affect it.
Happening with mint.lgbt right now but has happened with others in the past.

**Comment by ManeraKai** [comment]
This is fixed in the next release.
