### ISSUE TITLE
Mouse2 options for copy-raw and switch instance

### ISSUE THREAD

**Issue by Invertisment** [libredirect/libredirect#603]
Hey. Thanks for the plugin.

I use the keyboard most of the time instead of using the mouse. The plugin works great but sometimes there is a need to copy the original URL and then I have to reach for the mouse. Also you have the "toggle redirects" option in mouse2 menu but I almost never use it.
I would like that you would refactor that menu into a list of three items: toggle redirects, copy raw and switch instance. 
It could also work if you would add some kind of shortcut key or something. But I think the most non-intrusive option is to add it to the already existing menu item.

Do you think it's a good idea? I think I could maybe even submit a PR for this as this shouldn't be a hard feature to do.

**Comment by IkelAtomig** [comment]
Please check the FAQ for Shortcuts.

**Comment by Invertisment** [comment]
Alright. That also works.
