### ISSUE TITLE
Please put back latency test.

### ISSUE THREAD

**Issue by Impeta** [libredirect/libredirect#605]
Why was it removed? It was the best form possible to determine which instance is best for you based on your locality. I don't recall seeing any open issues here or so that would ask for you to remove it.

Please put it back. :cry:

**Comment by compaq213** [comment]
%100 agree

**Comment by cinatime** [comment]
Please bring it back

**Comment by ManeraKai** [comment]
Alright I'm thinking of a way of adding them where they do NOT interfere local storage, meaning that the ping results will vanish as soon as you reload or close your settings page. This is a better approach bc we already have the public list now dynamic and fetched every time you open the settings page.

**Comment by ManeraKai** [comment]
ok, I liked the implementation so much I will share a video of it xD:

https://user-images.githubusercontent.com/40805353/217369163-058e0a1b-64b3-44c0-bf1b-c0c557a32bc9.mp4

**Comment by ubergeek77** [comment]
@ManeraKai Apologies for the ping, but is a release version with this feature planned soon? It looks like this commit was made _just_ before the latest release.

I was actually going to build and install the extension myself while I waited, but I didn't realize how strict Mozilla was about unsigned extensions. So unfortunately I cannot make use of this feature until the next official release :/

**Comment by ManeraKai** [comment]
Yes a new version will be released within this or the next weak.

**Comment by IkelAtomig** [comment]
@ubergeek77 Probably this week. Internal testing is done. Some bugs showed their face which is causing the delay.
