### ISSUE TITLE
This new update feels like a downgrade.

### ISSUE THREAD

**Issue by Kostrol** [libredirect/libredirect#606]
Why all these changes? Was more than happy with previous options before last update.

Good old checkboxes replaced with awkward UX to navigate for instances. Update instances is gone, same with measure latency. Auto redirect gone too? so many features now gone..

**Comment by stemy2** [comment]
Additionally, the wikipedia redirection is gone too. Plz give us the ancient version back !

**Comment by ManeraKai** [comment]
I know, me and @IkelAtomig don't have much time (university and school) to maintain all of the so buggy and even questionable features LibRedirect had:
- Removed Update instances bc the logic behind it got so [complex](https://github.com/libredirect/libredirect/issues/334).
- Removed Latency test bc it made the code so complex and hard to maintain. Also, people started caring about latency instead of the trustworthiness of the instance owner which is very very wrong.
- Removed Auto redirect bc of Invidious's giving 500 for unavailable videos. Also, it's so uncontrollable and should have a waiting countdown page even. In theory, you should have selected good trustworthy instances instead of just picking all the lousy and good ones and slapping an auto redirection logic. If an instance is dead or something, press Switch Instance.
- Removed Unify Settings bc of the so many problems it gave us. We took a really stupid responsibility of "maintaining cookies" which should be none of LibRedirect's business.
- 

Yes LibRedirect has less features, but is now less buggy, faster, smaller in size, and easier to maintain. I know many of you won't like this, but this was the least harming decision we could take.

**Comment by stemy2** [comment]
Why did you removed the wikipedia redirections ?

**Comment by mid-kid** [comment]
Thanks for the clarification, indeed, testing instances was broken, and enabling them all out of the box was a bad user experience. I'm just glad someone's maintaining the program at all.
However, I'll mention I really liked being able to toggle the specific instance from the addon menu. Especially given many instances go down and up at irregular intervals, and I prefer rotating to slightly lesser used instances, being able to disable one whenever it didn't work was great.

**Comment by mativiters** [comment]
I am heartbroken. In my country of Iran many websites are slowed down by the government in addition to the original websites being outright blocked, so I used latency tests to find nice piped/invidious/libreddit/etc alternatives. I had introduced this extension to many people I knew because of this feature in particular. Also wikiless and neuters were both nice, as Reuters is banned in Iran and I used it to read news. I'll either have to manually open it or perhaps downgrade the extension manually.

**Comment by ManeraKai** [comment]
@mativiters If you can it's better to recommend a specific instance you trust for them that you tested previously and trust t's instance owner.

**Comment by ManeraKai** [comment]
> Why did you removed the wikipedia redirections ?

https://discuss.privacyguides.net/t/more-alternative-privacy-frontends-for-popular-sites/14/3?u=ikel

**Comment by mativiters** [comment]
@ManeraKai Here we cannot even open the first page of most instances, I don't know what sorcery the government is up to. So we're forced to go with the fastest instance (beggars can't be choosers as they say)

Btw wikiless was nice as I edit on wikipedia with my account logged in and browse on Wikipedia anonymously on wikiless. It also has a nice dark theme. Also it would drop the occasional wikipedia messages popping up at the top of articles.

**Comment by IkelAtomig** [comment]
> That said, I'm confused by the changes to instance selection UI.

This is being discussed internally for a better way or reinstate the old one.

**Comment by IkelAtomig** [comment]
> i prefer to toggle the ones i wanted to be used instead of this plus, remove and yellow colored system.

Well, The problem is you have selected for example, piped.kavin.rocks instances. But the Official list removes them from the list. When you hit update next time, The logic is confused that whether it should be removed or not and stucks or break the instance. So, We reset all the selection during update. But now, When you open settings page, Instance list is fetched every time. So as to avoid this resets and preserve your settings. That's why, Custom Instance is also prioritized first.



> oggling off a specified instance from the page if it's offline, just a process of elimination.. i hope this can be brought back.

I think you mean option in the popup which was top of all the above. I literally forget about it when looking for bugs. Probably commented out or removed. Will look onto it.

**Comment by Oppen** [comment]
I feel a bit torn making this comment, as I value every open source contributor's time and don't want to be entitled to it. But at the same time, I'd much rather have those features be buggy/half-maintained than not have them at all. I sued all of those with the exception of toggle tab, and with many instances being rather unstable having auto redirect and unified settings feels like a must for the extension to actually be useful.

**Comment by Oppen** [comment]
> You can use Shift+Alt+L to instantly switch instance should there be something wrong. To be fair, auto redirecting was handy but was slow, this shortcut once you learn it is more practical.

Good to know, but it only solves a half of the issue. I still lose any customization For sites like Reddit is specially annoying as the most sensible usage (IMO) is to subscribe to a few topics, save an interesting thread, etc.

> Still leagues ahead in features than the other alternatives which are either dead or in a hiatus.

That's certainly true.

**Comment by shruuub** [comment]
> > Why did you removed the wikipedia redirections ?
> 
> https://discuss.privacyguides.net/t/more-alternative-privacy-frontends-for-popular-sites/14/3?u=ikel
> 
> > Wikiless - It was recommended [here 11](https://github.com/privacyguides/privacyguides.org/discussions/1791) but I currently don’t see the point. As far as I can tell, you can browser Wikipedia perfectly fine without JS (I tried with Tor Browser on safest setting). Browsing through the site also does not require an account. No ads aren’t really a privacy enhancement, and Wikipedia isn’t a exactly full of ads, so this is not a concern. Finally, and I should mention this now that I’m still looking at the first option, “proxying” to another service isn’t necessarily a privacy enhancement, or even desired by default. People can use other tools (Tor or a VPN) if they want to hide their IP. With a frontend, Wikipedia might not get your IP, but the Wikiless instance is. Why do you trust the instance operator more?

Trusting a massive company which nowadays almost has a information monopol known to have bad moderation (Removing articles, users, changes) is a bit diffrent to trusting yourself or a friend (or just another privacy advocate) hosting the instance.

**Comment by shruuub** [comment]
> > Trusting a massive company which nowadays almost has a information monopol known to have bad moderation (Removing articles, users, changes) is a bit diffrent to trusting yourself or a friend (or just another privacy advocate) hosting the instance.
> 
> I'm not saying to go directly to wikipedia.org with your raw IP address, I mean to use the Tor browser and then to Wikipedia, or a VPN you trust it's owner (could be a friend even).

Yup. But, that brings a bit more inconvenience, and libredirect is basically an addon that trys to bring more convenience (not having to copy a link, look for an instance and changing the url and then accessing it.

**Comment by ManeraKai** [comment]
> (not having to copy a link, look for an instance and changing the url and then accessing it.

There's no need to "copy" links if you're using the Tor browser and typing in wikipedia.org directly?

**Comment by shruuub** [comment]
> > (not having to copy a link, look for an instance and changing the url and then accessing it.
> 
> There's no need to "copy and modify urls" if you're using the Tor browser and typing in wikipedia.org directly?

Yes, but you do need to open the tor browser and establish a connection. (Not a big deal, but I'm trying to point the general "efford")

**Comment by ManeraKai** [comment]
> As to what sites to provide redirects for, why remove something a fraction of the users might be using when there are no downsides? (To the extent I can see at least, if I am missing something, please feel free to correct) Basically, when you can provide choice without making it too hard for yourselves, try to do it.

Technically the only "major" performance compromise to adding a lot more frontends even when they are disabled is this [function](https://github.com/libredirect/libredirect/blob/a3b2f52836142399c3a22dbc01591a16264671f8/src/assets/javascripts/services.js#L401-L423) which gets triggered every time you open the popup. Other than that, you are right there are no downsides to adding more frontends. Just that the settings sidebar will get a little long and might need a sorting design concept.

**Comment by Vendillah** [comment]
Hello; I would just like to mention that wikiless gives a very thorough list on why a proxy is considered appropriate in their [README](https://github.com/Metastem/wikiless). I did not read every single listed fact, but from my understanding, the proxy was made to hide users (' IP) _from the NSA_ mainly.

For example, you can read:
> One of the documents revealed by Snowden shows that both Wikipedia and Wikimedia has been listed as a so-called "Appid" in the XKeyscore – a program that covers "nearly everything a typical user does on the internet" – to identify web traffic, meaning that wiki related web traffic is something that NSA finds valuable.[6]

Not saying that the proxies are therefore more trustworthy, but just to add _why_ the proxy has been made in first-place, which can be useful for those people wondering who they're actually hiding from (and if needed at all).

For those who want to get auto-redirects to wikiless; [Privacy Redirect](https://addons.mozilla.org/en-US/firefox/addon/privacy-redirect/) still works with that and that's what I'm using right now.

**Comment by ManeraKai** [comment]
@Vendillah from where the hell you brought this read link? Is this a fork or something?

**Comment by meatspinner** [comment]
TBF, the original README on codeberg also says the same thing:
https://web.archive.org/web/20220915050914/https://codeberg.org/orenom/Wikiless/src/branch/main/README.md

**Comment by ManeraKai** [comment]
@meatspinner no no I agree with his point, I just want to know where did wikiless go. Like I can't even find the instances anymore.

**Comment by ManeraKai** [comment]
> The shortcut for switching the instance (typically Shift+Alt+L) also doesn't seem to be working anymore although it is still listed in the shortcut settings page.

@isuseterful it's working?

**Comment by ManeraKai** [comment]
> I used to use it to switch from Invidious to Piped for example, but that doesn't work anymore

This specific issue is answered in the Docs and there's a way to do it: https://libredirect.github.io/docs.html#preferred_instance

**Comment by ManeraKai** [comment]
@mojo-jojo-7 there were so many performance issues and storage issues with implementing this that's why we removed it.

**Comment by Terkyz** [comment]
What happened to the "Toggle Redirect" context button? No longer exists or was it changed places?

**Comment by ManeraKai** [comment]
It's now called `Redirect to original`, right click on the LibRedirect icon to see it.

**Comment by Terkyz** [comment]
Oh, I saw it, thank you, I didn't know that the addons had contextual menus.

**Comment by ManeraKai** [comment]
I may add it to the popup, but we'll see.

**Comment by Terkyz** [comment]
That would be great but there are really other methods on LibRedirect to fulfill this function, although a little more rustic. My advice is that don't complicate yourself by implementing it if it takes a lot of work, the main LibRedirect function it works as it should and that's what's important. 

And I would like to add that the button allows me to change from an instance to the original site but not on the contrary, if I'm on Reddit, there's no button to redirect to an instance, I don't know if this is a desired behaviour or it's a bug, but I think it's important to mention it.

**Comment by Vendillah** [comment]
> @Vendillah from where the hell you brought this README link? Is this a fork or something?

Ups, apologies, I should have checked. I saw the (official) README before (so remembered it existed), but forgot how I got there. I think I just searched for "wikiless github" through duckduckgo and stumbled on this one? ;p

To answer: I don't know! (still.) I has opened and closed issues. Someone's fork for their server? :o

**Comment by Mrnofish** [comment]
> Yes LibRedirect has less features, but is now less buggy, faster, smaller in size, and easier to maintain. I know many of you won't like this, but this was the least harming decision we could take.

It actually makes more sense than dev folks might have expected, however it does feel a little like the feature set has been pruned a touch too aggressively.

Getting rid of Wikipedia redirects altogether seems to me like a prime example of crossing some previously unseen line in the sand.

The other features listed in your post can be easily appreciated as excessively complicated and perhaps not all that useful to the wider user base, and Bibliogram's status make a case for its removal, however Wikipedia seems a bit gratuitous in my humble opinion.

I sincerely hope the dev team will be willing to reconsider the Wikipedia decision.

**Comment by throwaway-d** [comment]
I'm fine with removing other features but Unify Settings is the only reason I use LibRedirect instead of Redirector. So I will keep the old version 2.3.4 and use https://github.com/einaregilsson/Redirector for new frontends.

**Comment by mid-kid** [comment]
It's easy to talk when you don't maintain anything for free. It's much harder to stand up and do anything about it, however.

**Comment by KaKi87** [comment]
Automated redirect was the only reason why I was using LibRedirect.

> If an instance is dead or something, press Switch Instance.

This is bearable on desktop, but not on mobile.

**Comment by ManeraKai** [comment]
> This is bearable on desktop, but not on mobile.

You're right, will keep that in mind.

**Comment by Oppen** [comment]
@lmpeta take a chill pill. Your comment sounds like you're accusing of bad faith someone who _was donating their time all along_. Note I'm as frustrated as you at the extension not serving my needs as well as before (as I commented previously, the two features I found the most useful are gone), but I think you're going a bit too far. The maintainer did a lot for the community, not only with libredirect but maintaining some of the frontends AFAIR, and we should all be thankful. If you accuse someone of bad faith, the least you could do is fork and maintain those features for all of us, right?

**Comment by WAZAAAAA0** [comment]
Small guide on how to stay on LibRedirect version 2.3.4 forever.

ON FIREFOX-BASED BROWSERS:
1. uninstall the newer LibRedirect version
2. visit <https://addons.mozilla.org/firefox/downloads/file/4020597/libredirect-2.3.4.xpi> to install the correct one
3. navigate to LibRedirect's respective "Manage Extension" menu and turn off auto-updates for it (click puzzle icon -> click gear icon -> Settings -> Manage Extension -> Allow automatic updates: Off)

ON CHROME-BASED BROWSERS:
1. uninstall the newer LibRedirect version
2. download with right click -> Save link as... <https://github.com/libredirect/libredirect/releases/download/v2.3.4/libredirect-2.3.4.crx> and extract it to a newly created folder (crx is just a zip archive)
3. edit `manifest.json` to delete *line 70* in order to kill the update check mechanism `"update_url": "https://raw.githubusercontent.com/libredirect/libredirect/master/src/updates/updates.xml",`
4. navigate to `chrome://extensions/` -> enable Developer Mode -> F5 to refresh the page -> drag'n'drop the folder with the modded extension to install it

**Comment by compaq213** [comment]
> Small guide on how to stay on LibRedirect version 2.3.4 forever.
> 
> ON FIREFOX-BASED BROWSERS:
> 
>     1. uninstall the newer LibRedirect version
> 
>     2. visit https://addons.mozilla.org/firefox/downloads/file/4020597/libredirect-2.3.4.xpi to install the correct one
> 
>     3. navigate to LibRedirect's respective "Manage Extension" menu and turn off auto-updates for it (click puzzle icon -> click gear icon -> Settings -> Manage Extension -> Allow automatic updates: Off)
> 
> 
> ON CHROME-BASED BROWSERS:
> 
>     1. uninstall the newer LibRedirect version
> 
>     2. download with right click -> Save link as... https://github.com/libredirect/libredirect/releases/download/v2.3.4/libredirect-2.3.4.crx and extract it to a newly created folder (crx is just a zip archive)
> 
>     3. edit `manifest.json` to delete _line 70_ in order to kill the update check mechanism `"update_url": "https://raw.githubusercontent.com/libredirect/libredirect/master/src/updates/updates.xml",`
> 
>     4. navigate to `chrome://extensions/` -> enable Developer Mode -> F5 to refresh the page -> drag'n'drop the folder with the modded extension to install it

thanks a lot

**Comment by techgamers2** [comment]
the only reason i switched from privacy redirect extension to libredirect ws tht "latency checker" feature now it is also gone very disappointed :(

**Comment by ManeraKai** [comment]
@techgamers2 will be in the next release: https://github.com/libredirect/libredirect/issues/605

**Comment by techgamers2** [comment]
> @techgamers2 will be in the next release: #605

tysm man <3 really appreciate it

**Comment by KaKi87** [comment]
Hello,
Would anyone consider forking LibRedirect from v2.3.4 while importing future changes except feature removals, mostly to get an up to date instance list ?

Thanks

**Comment by IkelAtomig** [comment]
@Impeta - I agree with your Communication thing. We will do it. But before this, We actually thought of it. But users might regret it. The reason we straightly jumped to it.

**Comment by KaKi87** [comment]
> > This is bearable on desktop, but not on mobile.
>
> You're right, will keep that in mind.

Hi,

Do you still have this in mind and will you act on it ?

Thanks

**Comment by IkelAtomig** [comment]
We don't know we need a good logic that covers all errors and act on a right way. You are welcome to open a PR.
