### ISSUE TITLE
Optional Wikiless

### ISSUE THREAD

**Issue by r2fo** [libredirect/libredirect#612]
Hi,
I noticed that Wikiless has been removed from the latest update since Wikipedia doesn't have trackers anyway. But I (and I think others too) use this addon to consume content on big sites without coming into contact with them. Personally, I would trust a volunteer who is running a private instance more than a big company like Wikipedia (even though Wikipedia is non-profit).

I saw you mention in another issue that Wikiless' only benefit is proxying and that we can use a VPN/TOR for that. But Wikiless also makes tracking/fingerprinting harder, since requests from hundreds of people will come from one single user (the instance). And at the end of the day, the instance's details (not just IP, but also OS, Timezone, Useragent, Fonts, ...) will be leaked to Wikipedia. If we would use a VPN, our other details would still get leaked to Wikipedia.

I saw in another issue that you recommend using Tor browser for browsing Wikipedia, but that's a bit extreme for a threat model that consists of private front ends. 

My question is whether it's possible for Wikiless to be brought back but disabled by default?

Thank you in advance

**Comment by ManeraKai** [comment]
> but that's a bit extreme for a threat model that consists of private front ends.

I agree with this statement.

**Comment by ManeraKai** [comment]
@Metastem are you orenom.fi??

**Comment by NoPlagiarism** [comment]
@ManeraKai 
![image](https://user-images.githubusercontent.com/37241775/216555805-496c8491-2e1a-48e8-9e4f-9545dfee6e89.png)
https://github.com/Metastem/wikiless/issues/4#issuecomment-1401679347

**Comment by ManeraKai** [comment]
@NoPlagiarism yes I saw this but idk if I can trust this solely.

**Comment by kevtainer** [comment]
i concur, for those of us who'd like to redirect from wiki to alternative sites (not even wikiless) this tool lost a lot of value.

perhaps a "Custom" option that allows both the source->target to be defined, with some common shared functions that can be managed on-demand.

**Comment by ManeraKai** [comment]
> perhaps a "Custom" option that allows both the source->target to be defined, with some common shared functions that can be managed on-demand.

This is exactly what [Redirector](https://addons.mozilla.org/en-US/firefox/addon/redirector/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) does. If you want "advanced redirections" as an advanced user, then Redirector will be a really nice option next to LibRedirect.
