### ISSUE TITLE
Suggestion: option to revert old UI, restore removed features

### ISSUE THREAD

**Issue by Andrewskiz** [libredirect/libredirect#613]
Hey, just wanted to say I use this extension all the time and appreciate the work that goes into it. 

The new UI to me seems less intuitive and I think an option to go back would be very useful. Namely, the checkboxes made  it easier to see which instances were newly added and which I had disabled intentionally, vs the new UI which makes it hard to tell which is which.

Also, I found the features that allowed you to update the list of instances and test the latency an integral part of the extension and an option to renable them would be great.

**Comment by ManeraKai** [comment]
Those things and more were discussed in this issue: https://github.com/libredirect/libredirect/issues/606

**Comment by IkelAtomig** [comment]
@Andrewskiz Latency test is being readded. For the UI problem with choosing Instances. Maybe When you click the `+` to add a instance it turns ✔️ . So, you don't get confused on click on it again and again.
