### ISSUE TITLE
 Allow LibreTube/Newpipe redirects alongside Invidious/Piped

### ISSUE THREAD

**Issue by marc0x1** [libredirect/libredirect#615]
Since Libredirect works very well on Firefox for Android ( I'm using a fork called Mull ), It would be great to open youtube's links directly in a native app. 
While is already possibile to open youtube 's links in Newpipe/Libretube, android apps struggle to detect which links they can open.
Libredirect can fix that and be a useful backup.

**Comment by ManeraKai** [comment]
>  While is already possibile to open youtube 's links in Newpipe/Libretube, android apps struggle to detect which links they can 
open.

NewPipe for example hdoes supports youtube links, you can see the supported links if you go to:
NewPipe's `App Info` => `Advanced` => `Open by default`

Like there's no special NewPipe url, NewPipe is registered in the android system as "youtube.com reader" you can say.

**Comment by Bnyro** [comment]
Exactly the same applies for LibreTube btw
