### ISSUE TITLE
LibRedirect overriding homepage on Firefox and forced as search engine

### ISSUE THREAD

**Issue by kimimaru4000** [libredirect/libredirect#616]
As of the 2.5.0 update, LibRedirect automatically opens when I start up Firefox (version 109.0.1). I have a blank page set as my homepage on Firefox. Effectively, LibRedirect is overriding my homepage.

If I remove or disable LibRedirect, this no longer happens, so the issue lies in the plugin.

LibRedirect is also **force-added** as one of the search engines in the list:
![ForcedSearchEngine](https://user-images.githubusercontent.com/1388037/216762738-c819f212-f890-485c-9a81-fc31c33face9.png)

If I remove it as a search engine, it will just come back next time I launch Firefox. I would like LibRedirect to respect my search engine settings.

**Comment by ManeraKai** [comment]
> If I remove it as a search engine, it will just come back next time I launch Firefox. I would like LibRedirect to respect my search engine settings.

I agree and previous people mentioned this. Though I couldn't find a way to add the search engine without using the [manifest.json](https://github.com/libredirect/libredirect/blob/master/src/manifest.json#L46-L55) (manifest is a permanent setting).
Though I think I found this [BrowserSettings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings) API. Alright I will make this setting optional.

**Comment by ManeraKai** [comment]
> As of the 2.5.0 update, LibRedirect automatically opens when I start up Firefox (version 109.0.1). I have a blank page set as my homepage on Firefox. Effectively, LibRedirect is overriding my homepage.

> If I remove or disable LibRedirect, this no longer happens, so the issue lies in the plugin.

LibRedirect yes adds itself as a search engine in the list, but NOT as the default one (previously it did that but not in later versions).

**Comment by kimimaru4000** [comment]
Thanks so much for looking into this!

The most annoying part for me is this plugin overriding my homepage. Do you have any leads on that?

**Comment by ManeraKai** [comment]
LibRedirect doesn't have a homepage though? What are you seeing show me.

**Comment by kimimaru4000** [comment]
The settings page always pops up first when I start Firefox, but I have a blank page set as my homepage.
![LibRedirect Settings Always Showing Up](https://user-images.githubusercontent.com/1388037/218138387-4b4ae5a9-2f2a-4cea-aea9-454039f73000.png)

This started with version 2.5 of LibRedirect.

**Comment by ManeraKai** [comment]
> The settings page always pops up first when I start Firefox, but I have a blank page set as my homepage.

oh no... this was another issue and got fixed here: https://github.com/libredirect/libredirect/issues/625

**Comment by kimimaru4000** [comment]
Great, thanks for the quick reply!

**Comment by ManeraKai** [comment]
ok xD, I think I won't make the addition of LibRedirect as a search engine optional bc it's not forcing it anyway.
