### ISSUE TITLE
the addon redirect othe invidious instances to the main invidious page set in addon 

### ISSUE THREAD

**Issue by rezad1393** [libredirect/libredirect#62]
when I open a invidious page I get redirected to the invidious instance set in this addon page
for example this
https://invidious.namazso.eu/watch?v=XZNn2mO3dNQ
gets redirected to 
https://invidious.kavin.rocks/watch?v=XZNn2mO3dNQ

I thinks the new release introduced this regression.

**Comment by ManeraKai** [comment]
I think it's the `Always use Preferred Instances` option. What's wrong?

**Comment by rezad1393** [comment]
> I think it's the `Always use Preferred Instances` option. What's wrong?

yes.
I think this addon reset its option when it updated. I remember that last time and now this is the the second update that this happened.
