### ISSUE TITLE
Suggested url instance for OpenStreetMap is incorrect.

### ISSUE THREAD

**Issue by govvin** [libredirect/libredirect#620]
When you enable libredirect for Maps, and you choose OpenStreetMap, it will suggest that you add "http://osm.com" as a favorite instance.

"osm.com" is not affiliated with the OpenStreetMap project. The project only uses two top domains:
- openstreetmap.org
- osm.org

Perhaps this is a typo, and "osm.org" is what you intended to add?

**Comment by ManeraKai** [comment]
I'm thinking of removing this placeholder all together for all frontends. Or adding a constant one not related to the fronend.

**Comment by govvin** [comment]
FWIW, I think a few suggestions are nice to have, especially if the user is not familiar with alternatives.

**Comment by ManeraKai** [comment]
I see, then they should not be dynamic, I should choose the placeholder for each frontend.

**Comment by ManeraKai** [comment]
It's now like this:
![image](https://user-images.githubusercontent.com/40805353/217034870-052b6adf-e8b0-4925-8ce8-3098701e1820.png)

**Comment by govvin** [comment]
That looks great! Thank you.

In case you're looking for another suggestion, try Qwant.
Example: https://www.qwant.com/maps/place/latlon:12.915199449873198:124.12499963968993

**Comment by ManeraKai** [comment]
> In case you're looking for another front-end suggestion, try Qwant.

ohh xD, having to redirect to maps was a hassle let a lone add a new one. We were suggesting to add Qwant but we discarded it later and focused on other things.
