### ISSUE TITLE
Wireshark shows connections to GitHub, no way to disable

### ISSUE THREAD

**Issue by random452** [libredirect/libredirect#626]
Hello, guys. Thanks a lot for a great tool!
Just a small concern - extension makes connections to GitHub servers, I guess to update lists of instances.
Can you please add a checkbox to disable update checking (and other internet connections addon makes if any exist)?

**Comment by random452** [comment]
> How do you want to know new instances with it disabled?
Well, no way to know new instances, it's obvious. 
If someone will need to update their local instances list ofc he shouldn't tick this (new) checkbox

**Comment by ManeraKai** [comment]
Then I will add an option to not view public instances.

**Comment by random452** [comment]
> Then I will add an option to not view public instances.

That will be great, thanks
