### ISSUE TITLE
CORS requests fail on pages libredirect redirects to on LibreWolf

### ISSUE THREAD

**Issue by Killercat103** [libredirect/libredirect#627]
Browser: LibreWolf 109.0-1 (Firefox)
OS: Windows 11

Steps to reproduce:
Add https://troddit.com as a instance for reddit in firefox
Navigate reddit.com by any means.
Cross origin requests fail until you refresh the page
![image](https://user-images.githubusercontent.com/75360760/217795792-f0a95a28-016c-4b0c-9ada-f225f454d729.png)

**Comment by Killercat103** [comment]
![image](https://user-images.githubusercontent.com/75360760/217795792-f0a95a28-016c-4b0c-9ada-f225f454d729.png)

**Comment by ManeraKai** [comment]
I will support troddit but you can't just add it like that!

**Comment by ManeraKai** [comment]
Will be completed in this issue: https://github.com/libredirect/libredirect/issues/587
