### ISSUE TITLE
Custom instance subscription

### ISSUE THREAD

**Issue by linsui** [libredirect/libredirect#628]
Since the latency test and instance update are removed in recent versions, I feel that it's very difficult to maintain the large list manully. I can understand that it's hard to maintain those functions.

So I have an idea. Maybe you can provide a method to maintain the prefered instance list outside. uBO can subscript rules from many sources. Can libredirect update the list from a custom url similiarly? Then I can update the available instance list from https://github.com/libredirect/instances, do the latency test or add some filters, then serve it on a web server. Libredirect can update from the url regularly so that I don't need to click those buttons manully. Maybe someone would like to publish their selected instance so that other users can subscript it.

**Comment by ManeraKai** [comment]
> Since the latency test and instance update are removed in recent versions,

The instances list is updated automatically, and the Latency Test has been reimplemented: https://github.com/libredirect/libredirect/issues/605#issuecomment-1421476174

**Comment by linsui** [comment]
Wow, that's great! But it seems the function to disable intances based on the latency is not added back.

**Comment by ManeraKai** [comment]
> But it seems the function to disable intances based on the latency is not added back

Yes it won't be added again.

**Comment by linsui** [comment]
Then I still need to enable/disable instances one by one manully. When there are many instances it's pretty tiring. If I can sync it with a list hosted somewhere else I can apply any filters I want and update it with a script automatically.

**Comment by ManeraKai** [comment]
This might work in version 2.4.3 but now the public instances list has been fully separated from the custom list you have bc the concept got so complex.

**Comment by linsui** [comment]
How about simply importing settings from a url?

**Comment by ManeraKai** [comment]
You can import "settings", this is the nearest thing you can get to that.

**Comment by linsui** [comment]
Yes, but I'd like to have something more automatic.

**Comment by ManeraKai** [comment]
I know but it will make things complex that's why I'm trying to find alternatives.

**Comment by linsui** [comment]
Could it import the settings from a url regularly?

**Comment by ManeraKai** [comment]
It does so, but the list that it's fetching is just "read only", it's separated completely from the custom list.

**Comment by linsui** [comment]
I thought the imported setting is not a read-only list?

**Comment by ManeraKai** [comment]
The "imported settings" affect EVERYTHING, from custom instances to other settings.

**Comment by linsui** [comment]
For personal usage it's enough. For public list I guess some fields need to be blocked. I'd be happy to use it as synced settings though.

**Comment by ManeraKai** [comment]
https://youtu.be/8ofejhlZtps
