### ISSUE TITLE
What's exactly "Paste Text"?

### ISSUE THREAD

**Issue by darlopvil** [libredirect/libredirect#629]
Hi, so i've seen this option in the add-on page, but i'm not very sure what does it mean:

![imagen](https://user-images.githubusercontent.com/60988792/218329788-0d831dee-bdab-4d3f-b257-4502dd3906d3.png)

There it's privatebin, but that's a replacement of pastebin. Isn't there any instances? if tried to use privatebin.com, but the redirection doesn't work. idk if i'm missing something obvious, my apologies.

**Comment by ManeraKai** [comment]
There are instances and they were there before, but privatebin.info removed the json file so we should now scrap them instead of using a reliable json, and I was lazy to not do it yet.

**Comment by ManeraKai** [comment]
oh one second... https://github.com/PrivateBin/Directory/issues/23#issuecomment-898949689

**Comment by ManeraKai** [comment]
That wasn't working before wth, ok will enable it's instances fetching again.

**Comment by ManeraKai** [comment]
Press on the `Frontend` text to know more about PrivateBin
![image](https://user-images.githubusercontent.com/40805353/218332472-c39b1919-2f63-4ed9-94b6-97e496cdda12.png)

**Comment by m040601** [comment]
I confess, being a long time user and fan of Libredirect I still have the same question as the original poster.
