### ISSUE TITLE
[Request] Add Gothub as Github alternative

### ISSUE THREAD

**Issue by qube-03** [libredirect/libredirect#630]
Hey, this extension is very awesome and i love using it - showed me many alternatives i didnt even know existed

such as LibreX, which also showed me more. under those is Gothub as a Github frontend

i think adding a gothub option would be very cool and useful

thank you!

**Comment by ManeraKai** [comment]
Thanks! :), and already has been added :) https://github.com/libredirect/libredirect/issues/569

**Comment by qube-03** [comment]
oh sorry, didnt see there was already an issue, but thanks!!
