### ISSUE TITLE
Please allow the possibility to add custom settings URLs to redirects (Eg. libreddit custom settings)

### ISSUE THREAD

**Issue by rodllag** [libredirect/libredirect#632]
Nothing more to add.

**Comment by ManeraKai** [comment]
LibRedirect isn't for "advanced users", if you are an advanced user and want another frontend, then use [Redirector](https://einaregilsson.com/redirector/)

**Comment by ManeraKai** [comment]
or you're meaning queries?

**Comment by r7l** [comment]
I think he is talking about default URL parameters that would sync settings across instances. Some of these tools have pretty extensive settings (SearXNG for example). Without a way to keep settings sync, you'll either be forced to use a single instance or use some other way to manually sync it.

It would be awesome if libredirect would support this. But it's actually as easy as sending parameters with the request. On SearXNG you would need to do at least 2 requests. The first to set your preferences to a new instance (save to cookies) and the other with the actual search.

You can try by setting something here: https://search.unlocked.link/preferences and use the `Cookies` tab and copy the string to another site. You can actually append this string to any search result. It will work for this single request but it won't be saved that way.

**Comment by ManeraKai** [comment]
https://github.com/libredirect/libredirect/issues/491#issuecomment-1343128154
