### ISSUE TITLE
[Suggestion] Re-implement Unify settings

### ISSUE THREAD

**Issue by Opening-Button-8988** [libredirect/libredirect#633]
I would love for unify settings to be added back. I have been using Libredirect since before it was removed but didn't know what the setting did. Ironically I had the idea to have universal settings right around the time it was removed and thought it wasn't even a feature. I would like to see this because I would use it, the ability to have universal settings across sites allows me to save time configuring the settings for each site. Actually, I currently don't even bother changing most settings because it's just too time-consuming and annoying. I use arkenfox with permanent incognito, this means I can't save any settings and therefore cookies, so I have to change the settings every time I open my browser.

I understand that you are not full-time developers and adding this back would take time. I would appreciate any and all work you make to improve this extension, as I believe it's an extremely useful extension and a great privacy tool!

**Comment by ManeraKai** [comment]
I "may" look into it, but it requires some collaboration work from frontend developers too. Example, Invidious should have their "subscription list" as a cookie like how libreddit does it. And the idea of a "token" cookie for accessing your settings from the server is a HORRIBLE idea, I know it's for security reasons but it made our lives at LibRedirect hell xD.
If people want Unify, then the idea of "accounts and user data stored on the server" should become vanished overtime and migrated to cookies that we can Unify.

Also we should fix:
- Duplicate cookies problem (settings aren't being changed bc of this).
- Cookies not working properly on the Tor browser bc of some things Tor Browser changes in cookies.
- Not having Unify on incognito even that many people wanted so.
- Not initializing cookies on startup if the user has a setting to clear all the cookies after browsing and we should recreate them for him (this becomes a problem in the Tor browser bc it's default setting is to delete the cookies on quit xD).
- Having the settings for each frontend in LibRedirect settings page?? Or maybe having an html script from every instance developer that allows us to connect it with the LibRedirect settings page?? Or just go to an instance, change the settings, and then go to the popup and click Unify (this approach turned to be not convenient at all).
- The so many unused cookies problem where we should delete cookies from "removed instances", or we would trap ourselves bc we deleted cookies the user wanted??

So yeah... just "maybe"

**Comment by Opening-Button-8988** [comment]
@ManeraKai 

I can understand the security implications, but my suggestion was not so much about personal data or account settings. I personally wouldn't want cookies stored that contain that kind of data. Rather, I was focused more on the general settings that you can set for Invidious and Libreddit such as dark mode, default speed, use HLS (for audio), Dash for adaptive quality, disable autoplay, that kind of thing. Not subscriptions, not any kind of account data. 

It really sucks that I just have to deal with using whatever default settings frontend sites use. I don't even bother changing them anymore because it's such a hassle. Again, because I use arkenfox and refuse to disable RFP because it would reduce privacy significantly, I cannot use dark mode for all sites by default, and cookies will not persist between sessions.

Since the target audience for libredirect and arkenfox users would merge, I believe it would appropriate to have this kind of setting. I really hope you consider bringing this feature back. Thank you.

**Comment by oorzkws** [comment]
@Opening-Button-8988 Are you wanting this to persist between different frontends (i.e. invidious and piped) or just different providers for the given frontend (i.e. yewtu.be and vid.puffyan.us where both are invidious)?

**Comment by Opening-Button-8988** [comment]
@oorzkws I didn't think about different providers. Ideally both, but I imagine configuration for Invidious would have to be separate from configuration for Piped and other frontends. The suggestion was mostly focused on providers.

**Comment by throwaway-d** [comment]
Upvote for this! I might update LibRedirect after this!

**Comment by MintMain21** [comment]
I would just like to say that I believe using URL Parameters (#491) would make an excellent alternative to the old Unify settings, at least for Invidious.

Since this issue was closed, I have since adapted to using Tampermonkey scripts as alternatives to certain extensions like LibRedirect (https://github.com/dybdeskarphet/privacy-redirector). 

The following script (https://github.com/MintMain21/Invidious-URL-Parameters-Userscript) is what I use to enforce my preferred settings and in combination with the aforementioned Privacy Redirector script offers me the ideal experience in both standard and private browsing sessions without having to use cookies.

**Comment by Opening-Button-8988** [comment]
@MintMain21 Using URL parameters is not really an option in my case because I use multiple instances, and I don't know of any way to automatically append those parameters at the end of any Invidious instance. 

You mentioned that you use greasemonkey, but I don't believe greasemonkey is particularly private or secure, and it uses javascript which is not good for privacy. I tend to use Invidious with javascript disabled.

**Comment by MintMain21** [comment]
@Opening-Button-8988 I said I use Tampermonkey. I've never used Greasemonkey, so I can really compare the two. 

The URL Parameter Script works in two parts, by listing off various instances (ideally the same pool used in Libredirect or a similar extension) and the URL Parameter string. 

From my experience the script doesn't work with Libredirect, but it does work with the Privacy Redirector script I mentioned before.

**Comment by IkelAtomig** [comment]
We just want implement Unify in a way that doesn't break at all often.

Throw in your ideas. Maybe also bring in the Lead Devs of the project into the discussion.

**Comment by qrhfz** [comment]
@Opening-Button-8988 js is just another scripting language. if you dont trust it you can read it.

**Comment by Opening-Button-8988** [comment]
@qrhfz I don't know what you mean by "read it", but I would imagine seeing anything written in javascript would require allowing it, which again, allows your browser to be tracked more easily, and I don't want to use it if I don't need it.

**Comment by MintMain21** [comment]
Okay, I now use two, count-em, two userscripts to enforce preferences on multiple invidious instances. 

https://github.com/MintMain21/Invidious-URL-Parameters-Userscript

One controls Video Playback settings, the other controls sitewide theming options. 

Consider this proof that URL Parameters are a viable alternative to Unify settings.

**Comment by MintMain21** [comment]
@Opening-Button-8988 

Something to keep in mind is that javascript userscripts aren't the same as javascript on a website. You should be able to control how a userscript works on your end.

In fact, iirc, there's even a URL parameter for disabling javascript on Invidious (thin_mode).

**Comment by MintMain21** [comment]
Update, my script has gone from 2 to 1, as the one proves just as effective as the two. 

*Proof that this is a viable alternative to Unify Settings*

**Comment by ManeraKai** [comment]
This issue will be closed in favor of: https://github.com/libredirect/libredirect_os

**Comment by throwaway-d** [comment]
> This issue will be closed in favor of: https://github.com/libredirect/libredirect_os

I dont’t understand anything?😵‍💫

**Comment by ManeraKai** [comment]
@throwaway-d will explain it better it's still so new.

**Comment by throwaway-d** [comment]
> @throwaway-d will explain it better it's still so new.

My wild guess is that we have to install an entire operating system just to have Unify Settings?! If it was true, I would go against that!

**Comment by ManeraKai** [comment]
Not on your machine, and it's not just about Unify: https://github.com/libredirect/libredirect/issues/663

**Comment by Opening-Button-8988** [comment]
@MintMain21 

While userscripts might be an alternative for you, they are not a viable alternative for me. This means I have to install a potentially compromising add-on (tampermonkey). You're probably thinking "there's nothing wrong with tampermonkey". Every extension can be used against you. As someone with a relatively high threat model, and as someone who uses Arkenfox which necessarily requires that I install as few addons as possible, installing tampermonkey is not an option. Not to mention, tampermonkey is a particularly vulnerable extension given that it allows you to install user created scripts. It's permissions would be higher than that of other addons.

@ManeraKai @throwaway-d I have absolutely no idea what the purpose for a Libredirect operating system would be. Why would anyone need this? Using frontends like Invidious does not require "beefy hardware" nor does it require a specialized operating system. You can run Invidious using docker on your own personal machine with almost any modern CPU. Running privacy frontends does not require that you expose them to the internet. You can use them privately.

**Comment by ManeraKai** [comment]
Then the practical solution would be providing an easy to use GUI app for Linix, Windows, Mac that installs and runs invidious locally. This would be much better than running on a separate hardware.

**Comment by MintMain21** [comment]
@Opening-Button-8988 

I've been campaigning for a while now for extensions like LibRedirect to implement the functionality of my userscript so that people didn't have to use Tampermonkey, and as you can see it has gotten nowhere.

If anyone wanted to port my userscript as it's own extension, I would be enthusiastic to support it however I could, but I'm not holding my breath for Libredirect to do it, and neither should you.

**Comment by oorzkws** [comment]
I feel like the libredirect_os option solves this issue in the same way a chainsaw solves most problems, but it doesn't really address what folks here want *as a feature of the libredirect extension*. Would you be willing to leave the issue open in case someone has the time and skills to implement it?

**Comment by ManeraKai** [comment]
Alright, check this out: https://github.com/libredirect/frontends_manager

**Comment by Opening-Button-8988** [comment]
@ManeraKai @MintMain21 @oorzkws 

This is such a small, easily fixable problem that the solutions provided by @ManeraKai are convoluted and unnecessary. First of all, your solution https://github.com/libredirect/frontends_manager is literally just a docker image that hosts all the privacy frontends on a single container. While perhaps that might be more convenient than running different instances on different containers, you've just inserted yourself in between the user and the frontends, thus creating another entity to trust where it's not necessary. It's not a solution to this problem. It would be just as good, or better, to host your own docker containers and run the frontends in there. It does NOT require dedicated hardware. You can run docker on your own personal machine without exposing the containers to the internet, as I said before.

I just realized @ManeraKai is the maintainer of libredirect, which kind of surprises me. Your libredirect OS and frontends_manager solutions aren't very good, and they ignore the necessity of a unify option and replace it with something that is unnecessary. Excuse my ignorance, as I am not a developer, but what is so difficult about re-implementing the unify feature? It's been several weeks since I posted this, I am still being inconvenienced by having to adjust (or not) every instance I connect to, and I have had to disable some redirects (searxng in particular) because the management is so annoying. At the very least, give users an easily accessible URL parameters feature (which I believe would work for Invidious and Libreddit, not sure about SearXNG and others).

**Comment by ManeraKai** [comment]
> This is such a small, easily fixable problem that the solutions provided by @ManeraKai are convoluted and unnecessary. First of all, your solution https://github.com/libredirect/frontends_manager is literally just a docker image that hosts all the privacy frontends on a single container. While perhaps that might be more convenient than running different instances on different containers, you've just inserted yourself in between the user and the frontends, thus creating another entity to trust where it's not necessary. It's not a solution to this problem. It would be just as good, or better, to host your own docker containers and run the frontends in there. It does NOT require dedicated hardware. You can run docker on your own personal machine without exposing the containers to the internet, as I said before.

I first tried with "libredirect_os" to be just an OS for the raspberry pi, but yes it wasn't a good idea. Now with "frontends_manager" I'm trying to have a GUI app that enables all users to run frontends on their machines without the need of a special hardware or something. And no not all of them are docker images, I'm trying to use docker as little as possible bc it makes performance worse and uses more ram, I'm using docker only for the complex ones, you can see here: [config.json](https://github.com/libredirect/frontends_manager/blob/2e93df6b74d8a450d7f803838cfc37c6dce07569/src/config.json). And yes it's idea is basically pretty simple (just run frontends). I'm trying to achieve this and also make LibRedirect as simply designed as possible to make privacy as much convenient as possible.

> I just realized @ManeraKai is the maintainer of libredirect, which kind of surprises me. Your libredirect OS and frontends_manager solutions aren't very good, and they ignore the necessity of a unify option and replace it with something that is unnecessary. Excuse my ignorance, as I am not a developer, but what is so difficult about re-implementing the unify feature? It's been several weeks since I posted this, I am still being inconvenienced by having to adjust (or not) every instance I connect to, and I have had to disable some redirects (searxng in particular) because the management is so annoying. At the very least, give users an easily accessible URL parameters feature (which I believe would work for Invidious and Libreddit, not sure about SearXNG and others).

Yes I won't re implement Unify nor Url parameters bc both of them aren't a solution to the core problem, there's even an [issue](https://github.com/libredirect/browser_extension/issues/677) that wants to allow POST requests bc some SearXNG instances have this as their default setting, all of those will be automatically fixed if a person was just using his own personal instance, and ofc with loki or tor for anonymizing their IP address.

> By the way, the reason I am surprised that @ManeraKai is the maintainer is because I automatically expect some level of competence with the apps that I use, and when a developer refers to Linux as "Linix", it makes me question the quality of that app. I'm not trying to be an asshole, but please, learn to write properly, at least on your own project. It makes you look incompetent.

I'm not professional nor claiming to be. LibRedirect is also not a professional app nor claiming to be. Me and @IkelAtomig are contributing with our free time as much as we can to make LibRedirect as best as possible.

Man you made my mind check typos for this comment so many times xD

**Comment by Opening-Button-8988** [comment]
@ManeraKai If you're an amateur developer then I commend you for building this project. My intention with my previous post was not to demean you but to point out what I think could be improved. 

After using Libredirect for a few months I truly believe it's one of the most useful tools available for people who care about privacy. I'm a minimalist, and I keep as few addons as possible, and libredirect happens to be one of them. 

That being said, since I put quite a lot of trust in Libredirect, knowing that the lead maintainer is not a professional puts a small amount of doubt in my mind. Not enough to stop using it, but I would like to see Libredirect earn some reputation, in other words, I'd like to see it be adopted by more people and perhaps audited (an informal casual audit, perhaps in the form of an article written by a security professional, or even a shoutout by some trusted individual in the privacy community just to give it some credibility). I'm going off topic a bit here, sorry.

I'll look into https://github.com/libredirect/frontends_manager a bit more. The primary issue I see here is the fact that you're hosting the instances yourself, which means your traffic is coming from your own network, which doesn't provide the same privacy as using other instances where you blend in with the crowd and have the advantage of splitting your traffic among many instances. I understand that you encourage the use of Lokinet or Tor. I don't know how you'd use Tor with this tool except either using Whonix/Tails to provide system-wide Tor, or modifying the Tor browser to not use the tor network with localhost (modifying the tor browser defeats the purpose of it). I've never used Lokinet except with their session app, so I don't know how that could be implemented with your tool. @ManeraKai
