### ISSUE TITLE
Instance deactivation toggle disappeared

### ISSUE THREAD

**Issue by pH142857** [libredirect/libredirect#634]
For any service, for any alternative: when I find a defective instance, I used to deactivate it with a simple toggle button just like the deactivation of the whole service redirection. This toggle button doesn't appear anymore.

**Comment by ManeraKai** [comment]
It got removed, there are no "check boxes" now in the settings, if you wanna "deactivate" an instance then technically you will "permanently remove" it, on the next release though you will see "Ping Instances" back so it will be easier to know which instances are viable and which aren't.

**Comment by pH142857** [comment]
Okay thanks. Not sure it's appropriate because some instances answer to ping but aren't functional, perhaps temporarily (maintenance or temporary ban from the original service for example). So if I perma-remove them, the app will lose trace of them. That being said, I'm not sure how the list is updated and I trust you to make the right choices.
