### ISSUE TITLE
I have downgraded to 2.3.4 but Libredirect keeps updating automatically

### ISSUE THREAD

**Issue by mastazi** [libredirect/libredirect#637]
I wanted some functionality that was removed in 2.5.x so I downgraded manually to 2.3.4, by removing the most recent version and then dragging and dropping the 2.3.4 crx file to the "manage extensions" screen.

But every time I restart Brave, Libredirect updates automatically to 2.5.2 which is I believe the last version I was on before downgrading. 

Since Libredirect is not a store extension, the update must occur because Brave has the more recent version cached somewhere? If so, where do I find it? I am on Ubuntu 22.04.1 and I installed Brave following this https://brave.com/linux/#release-channel-installation

**Comment by ManeraKai** [comment]
Maybe this will help you? https://github.com/libredirect/libredirect/issues/606#issuecomment-1419633922

**Comment by mastazi** [comment]
you are right @ManeraKai, last night I disconnected the wireless and no update occurred so I realised it must be over the network. Thank you for that! Closing.
