### ISSUE TITLE
[Suggestion] Add gothub

### ISSUE THREAD

**Issue by TheHolyTachanka** [libredirect/libredirect#638]
Basically the title
Its an "Alternative front-end for GitHub written with Go."
Here is their repo
https://codeberg.org/gothub/gothub

**Comment by ManeraKai** [comment]
Duplicate of :https://github.com/libredirect/libredirect/issues/630

We already added it, wait for the next release :)

**Comment by TheHolyTachanka** [comment]
> We already added it, wait for the next release :)
> 
> Duplicate of: #630

Cool, srry for the issue then and thank you for making this
