### ISSUE TITLE
When only one instance is selected and it's down, extension goes into endless redirect loop

### ISSUE THREAD

**Issue by AbsurdlySuspicious** [libredirect/libredirect#64]
Probably same will happen even if selected instance count >1, but all of them is down. 
Possible solution: generate shuffled instance list beforehand, and show extension's own error page (e.g. all of instances were down, check settings) when it's exhausted. This would also ensure that each instance is tried only once in a row.

**Comment by AbsurdlySuspicious** [comment]
I'll send a PR once I familiarize myself with the code and if everyone is ok with proposed solution

**Comment by ManeraKai** [comment]
I think did fixed this.

**Comment by AbsurdlySuspicious** [comment]
I'm using latest version from addons.mozilla.org and haven't tested master already, but of course feel free to close this if it's already fixed
