### ISSUE TITLE
Request: instance order list cycle loop, from bottom to top again in repeat for offline/slow instances.

### ISSUE THREAD

**Issue by Kostrol** [libredirect/libredirect#641]
To clarify: current setup is instances will cycle through each as you switch to the end of your last instance selection/favorite in the list. But once you hit the end you will not be able to cycle to the top of your selected instances again, at least not from what I have tried with shift+alt+l. This can be a problem if the last instance you have selected is having problems.

**Comment by IkelAtomig** [comment]
Glad you noticed it but it will be on v2.5.4 though.

**Comment by ManeraKai** [comment]
@Kostrol what version are you using?

**Comment by ManeraKai** [comment]
I really didn't understand, bc the selection is a random one:

https://user-images.githubusercontent.com/40805353/224223101-c67bba4b-2a2c-4b34-8677-69a8b1c4ffc8.mp4
