### ISSUE TITLE
More information about instances

### ISSUE THREAD

**Issue by ManeraKai** [libredirect/libredirect#643]
The fetched list has just the raw links and cloduflare warning rn. It should be changed to include some other things like it's speed (ping, has been added already), and also from what country it is, and if able the owner's website for it.

**Comment by throwaway-d** [comment]
I don't think owner's website is needed. Since you just need to remove the subdomain behind the instance URL to go to the owner's webiste.

**Comment by ManeraKai** [comment]
@throwaway-d some instances don't have it as "subdomains", ex: il.ax,  yewtu.be etc...

**Comment by ManeraKai** [comment]
This is a bigger more general problem, will be completed in this issue: https://github.com/libredirect/libredirect/issues/663
