### ISSUE TITLE
libredirect asking for more permissions

### ISSUE THREAD

**Issue by bheeshmpita** [libredirect/libredirect#646]
The web browser auto disabled the extension because the extension was updated and requires extra permissions to function,
How to check these permissions are safe to accept?

![ksnip_06032023-105444](https://user-images.githubusercontent.com/90836004/223026538-a7b7ee53-9f8b-4cdd-909e-de4719e62815.png)

**Comment by 1muen** [comment]
Hi @bheeshmpita I only got the message that the new extension requires the bookmarks permission (Firefox): 
![grafik](https://user-images.githubusercontent.com/49640488/223049215-affbf9de-af47-4b2f-8df2-9639723eb9ea.png)

Its because of this commit: https://github.com/libredirect/libredirect/commit/b91ae8e81629536b8cd163c40951ec1a7ff48e0e

After I accepted the new permissions I didnt see any options if I right click on a bookmark:
![grafik](https://user-images.githubusercontent.com/49640488/223049874-75321072-8aec-4dfd-8e6f-2f8ec0b0a5de.png)

But as far as I understood the commit, there should be. Maybe I should restart Firefox.

You can always build the code yourself, if you dont trust the addon on the addon store enough: https://github.com/libredirect/libredirect#development

**Comment by io43** [comment]
Please can you make the bookmark permission to be requested only if we want to use that feature i think it may be possible no? thanks

**Comment by 1muen** [comment]
Yes, I think that would be possible:
Request permissions at runtime:
https://extensionworkshop.com/documentation/develop/request-the-right-permissions/#request-permissions-at-runtime

**Comment by deathtrip** [comment]
Does anyone know why does it need this bookmark permission?

**Comment by ManeraKai** [comment]
To have a context menu just like when you right click a link.

**Comment by ManeraKai** [comment]
![image](https://user-images.githubusercontent.com/40805353/223131308-e8e74b41-9dcd-40a6-80d6-c14774e8df90.png)

**Comment by deathtrip** [comment]
Not everybody likes extensions adding new context menu entries. So i think there should be an option to disable it, and then this permission wouldn't be needed.

**Comment by IkelAtomig** [comment]
Will be focused on next release.

**Comment by TheFrenchGhosty** [comment]
@ManeraKai @IkelAtomig  No, just no. I don't want an addon that is supposed to just redirects URL to have the permission to READ and MODIFY my bookmarks.
I really don't get why you keep adding permissions that shouldn't exist (like "Input data to the clipboard") for an addon that SHOULD just rewrite some URLs/redirect users.

The security implication of that is MASSIVE, you effectively have COMPLETE access to the bookmarks of ALL users.

**Comment by IkelAtomig** [comment]
https://fosstodon.org/@libredirect/109976625888898306 - This is the reason to do so.

The extension is Open source. We don't delete or add or alter the bookmarks. You could check the code yourself.

It's only for the sake of redirecting bookmark links as the users wish. This isn't something we did intentionally. Rather fulfilling the request of a fellow user here : #568.

It's my mistake that I didn't write about it in Release notes. Which was somehow missed out from my eyes.

Apart from that we are trying to explain in the best way when users are asking questions.

**Comment by ManeraKai** [comment]
> @ManeraKai @IkelAtomig No, just no. I don't want an addon that is supposed to just redirects URL to have the permission to READ and MODIFY my bookmarks.

> and borderline SHADY

This is the part of the code where it does so, it's just doing it's job nothing else.
https://github.com/libredirect/libredirect/blob/594b8e571fb65c38102626e84f7015c8e28940e8/src/pages/background/background.js#L143-L161
https://github.com/libredirect/libredirect/blob/594b8e571fb65c38102626e84f7015c8e28940e8/src/pages/background/background.js#L240-L266
You can also see the commits, Me and @IkelAtomig have all of our commits signed. You can see where the bug that made the bookmark not working in the change log between the two releases.
https://github.com/libredirect/libredirect/compare/v2.5.3...v2.5.4#diff-a68229f23586e2fb9354f62fea2613ff16d337ab20490663b3bd6031d9b19973R140-R161
It was bc I didn't know that firefox has the namespace "window.chrome", I thought it only had "window.browser".

>  I really don't get why you keep adding permissions that shouldn't exist (like "Input data to the clipboard") for an addon that SOLELY exist to rewrite some URLs/redirect users.

>The security implication of that is MASSIVE, you effectively have COMPLETE access to the bookmarks of ALL users.

> while ignoring EVERY single BASIC security practices.

We're trying to just use the permissions that are needed a feature, for example with clipboard, we just used the [`clipboardWrite`](https://github.com/libredirect/libredirect/blob/594b8e571fb65c38102626e84f7015c8e28940e8/src/manifest.json#L26) so we can just write some input nothing more.
Also, there are a ton of other users who want such features and others who don't. If I remove some features, many users will say that [This version feels like a downgrade](https://github.com/libredirect/libredirect/issues/606) and start using older versions of LibRedirect just to have those features, even if they were buggy. And if I add some features, other users will say that it's "Compromising security". It's ok both arguments are valid, but we here at LibRedirect need to balance out between both as much as possible.

> This is like the https://github.com/iv-org/documentation/issues/229#issuecomment-1295882087 that the people behind Libredirect proves themselves to be HIGHLY unprofessional

We never said we are. Me and @IkelAtomig are just normal people who work in their free time on LibRedirect. We are not a "Commercial Company" or something.

**Comment by samtygier** [comment]
> The extension is Open source. We don't delete or add or alter the bookmarks. You could check the code yourself.

There is more to the argument than that. There are also numerous ways a malicious 3rd party might try to sneak some malware into this extension or its entry on the addons site. A minimal permission list is a strong assurance that the damage that could be done in this case is limited.

**Comment by IkelAtomig** [comment]
@samtygier A balance between User convenience and Security is sort of hard to balance. If you want to strict security. You need to lose convenience by not having certain features and vice versa.

@bheeshmpita At a bare minimum, You need to enable Twitter and reddit redirection. If you want, no other features. You need to either modify code yourself or the best bet for you is Redirector extension.

**Comment by pm4rcin** [comment]
Excuse me but is it possible to make this feature optional or browsers are not that flexible?

**Comment by ManeraKai** [comment]
> Excuse me but is it possible to make this feature optional or browsers are not that flexible?

@pm4rcin The feature isn't in the [manifest.json](https://github.com/libredirect/libredirect/blob/master/src/manifest.json) but rather executed at runtime, so it's not hardcoded, meaning that it can be flexible. I'll try to figure it out.

**Comment by IkelAtomig** [comment]
@bheeshmpita - I never used Redirector for the full potential or only of little use.

If you need Regex Pattern for redirection. You could copy them from the source code or mail me. (Look for address in Profile)

**Comment by io43** [comment]
thanks for trying to figure out to just ask for it when we want to enable that feature, i saw an blog post today and it remembered me that once extensions get popular devs get multiple offers per year to sell their extensions to shady people who just want to siphon datas and do all kind of malicious activities, adding more and more permissions put everyone at risk, so for now it is safe but what if at one point the dev is offered few thousands to sell out, it happen to many extentions

**Comment by IkelAtomig** [comment]
This is a Community based project actually. But only 2 people maintaining as far as we can. Development might be stale. But we are sure, we won't sell.
