### ISSUE TITLE
right click search doesn't work on chromium

### ISSUE THREAD

**Issue by bingoxo** [libredirect/libredirect#647]
on 2.5.3 

![image](https://user-images.githubusercontent.com/49401307/223058698-fb85d5b7-6253-45f0-9bca-d80b633a300d.png)

gives (doesn't work even after refreshing)

![image](https://user-images.githubusercontent.com/49401307/223058841-a081c6cf-e345-47b3-9f0c-9bbcfaa7ff5f.png)

but if i search in taskbar it works fine 

![image](https://user-images.githubusercontent.com/49401307/223059105-75bcaec9-3bf0-47a2-a104-8f073948f7b7.png)

**Comment by ManeraKai** [comment]
Try changing the main instance.

**Comment by bingoxo** [comment]
issue persists after changing instance (whoogle) 

can you reproduce it on your end ?

**Comment by ManeraKai** [comment]
https://user-images.githubusercontent.com/40805353/223140675-e22417e8-7a47-4a4b-aeaa-5b60a73a81e1.mp4

**Comment by bingoxo** [comment]
i switched to searxng , issue still persists so it's not related to whoogle

the issue only affects chromium based browsers , i tried in librewolf and it worked like in your video demo

**Comment by ManeraKai** [comment]
Not fixable on my side, a "manual fix" would be to click on the address bar and then press Enter for it to try to load again. It's bc search.libredirect.inavlid is not a real domain name, seems chormium is making the request "before" LibRedirect can detect it and redirect it to a SearXNG or Whoogle or etc... instance.
