### ISSUE TITLE
Exclude imgur upload

### ISSUE THREAD

**Issue by mooreye** [libredirect/libredirect#649]
I sometimes use https://imgur.com/upload to upload an image to imgur. Using Libredirect it redirects me to a 404 of a random instance. Workaround is using private mode of Firefox for this.

Please add an option to exclude this URL from redirection.

**Comment by IkelAtomig** [comment]
![image](https://user-images.githubusercontent.com/101938856/223171517-0427b1dd-cb18-459b-a474-a9b4624a79b5.png)

Try using the exceptions in General settings.

**Comment by mooreye** [comment]
> ![image](https://user-images.githubusercontent.com/101938856/223171517-0427b1dd-cb18-459b-a474-a9b4624a79b5.png)
> 
> Try using the exceptions in General settings.
