### ISSUE TITLE
Every instance has disappeared

### ISSUE THREAD

**Issue by IronMaltese** [libredirect/libredirect#65]
I’m on the latest release, and Reddit was working before, and then I switched to Tor, then all instances have disappeared (I’m running latest Tor Browser release aswell)

https://user-images.githubusercontent.com/89056889/155851582-b767f89b-ab1e-40c4-8930-63a58ef79472.MOV

**Comment by IronMaltese** [comment]
Also maybe get rid of the protocol button altogether if Tor instances aren’t available

**Comment by IronMaltese** [comment]
There’s a lot of errors

![E540E20E-0012-43E5-81D1-D124C94BFAFE](https://user-images.githubusercontent.com/89056889/155851802-56d69e85-81db-49d8-9147-1608953a51ad.jpeg)
![64F01061-F39A-4A55-A208-22625646C4A2](https://user-images.githubusercontent.com/89056889/155851818-64088b7d-3193-4858-81ec-7277af003600.jpeg)
![BD2225D1-F26B-43FC-80C9-324270582DC7](https://user-images.githubusercontent.com/89056889/155851843-906b7fe7-993e-443e-93ef-a061b279ad6c.jpeg)

**Comment by ManeraKai** [comment]
I tried it on the Tor browser and it's working fine.
