### ISSUE TITLE
Global toggle for "Unsupported paths handling"

### ISSUE THREAD

**Issue by opusforlife2** [libredirect/libredirect#651]
For privacy-conscious users of the addon, having this toggle as a global setting would be better. The per-service toggles can be greyed out if this toggle is on.

**Comment by ManeraKai** [comment]
Not so necessary, bc this feature needs finer running and varies A LOT from different frontends. That's why it is per frontend in the first place.

**Comment by ManeraKai** [comment]
So? xD, no need to add 2 buttons that serve the same purpose. Plus the complexities under the hood of doing so.
