### ISSUE TITLE
Setting the Youtube redirect to FreeTube breaks manual redirects for all sites.

### ISSUE THREAD

**Issue by unchartedpopsicle** [libredirect/libredirect#653]
Finally tracked this down, huzzah!
Manual redirects, including "Switch Instance" and "Redirect to Original", as well as "Copy Original", stops working on (seemingly) all supported sites when FreeTube is selected, even if YouTube redirects are disabled. This goes for both the context menu and toolbar item. The normal "Redirect" context menu item still works.

I am using Flatpak Firefox on linux.

**Comment by ManeraKai** [comment]
Thanks :)
