### ISSUE TITLE
Concern about permissions

### ISSUE THREAD

**Issue by haluzpav** [libredirect/libredirect#654]
I've just read your explanation for the new bookmarks permission (https://github.com/libredirect/libredirect/issues/650) and the [explanations on your website](https://libredirect.github.io/faq.html#why_all_those_permissions) (the bookmarks are missing there btw), and it feels like you are overdoing it a bit.

I've never used "Copy Raw" or the "menus" features, and probably never will. Same for the new bookmarks menu.

I'm considering dropping or replacing your extension by an alternative because of privacy concerns, which is pretty ironic. What if you sell your extension one day, or it gets stolen? I'm not comfortable with a single extension having all these permissions.

I'm not sure what's my suggestion. Just drop these features? Create separate "light" version of the extension?

**Comment by ManeraKai** [comment]
https://github.com/libredirect/libredirect/issues/646#issuecomment-1461288841
Also: [Privacy-Policy](https://github.com/libredirect/libredirect/blob/master/Privacy-Policy.md)

**Comment by rizajur** [comment]
@ManeraKai  thanks for pointing out for what the permission was needed, i just refused to update so far.
