### ISSUE TITLE
This extension is not listed in the Brave Web Store and may have been added without your knowledge

### ISSUE THREAD

**Issue by f-x1-1** [libredirect/libredirect#655]
unable to install the latest version on brave

**Comment by ManeraKai** [comment]
What? There's no brave web store? And you can install it using the   [chromium](https://libredirect.github.io/download_chromium.html) way

**Comment by f-x1-1** [comment]
> What? There's no brave web store? And you can install it using the   [chromium](https://libredirect.github.io/download_chromium.html) way.



"This extension is not listed in the Brave Web Store and may have been added without your knowledge"

Is the error when I try to install the extension on brave.

**Comment by ManeraKai** [comment]
Are you on Windows?

**Comment by f-x1-1** [comment]
> Are you on Windows?

Yes. It worked perfectly before but suddenly stopped working as brave disabled it without my consent.

Here is an example of what it looks like on my end:

![image](https://user-images.githubusercontent.com/77340515/224553427-10559f33-13cc-468b-b853-28e1d7b7941b.jpeg)

**Comment by IkelAtomig** [comment]
Did you use the registry as stated in the page ?

If not, It will occur when you drag and drop `.crx`.

**Comment by f-x1-1** [comment]
> Did you use the registry as stated in the page ?
> 
> 
> 
> If not, It will occur when you drag and drop `.crx`.

Thank you! It worked.
