### ISSUE TITLE
Anonymous e-mail address in code - what is for?

### ISSUE THREAD

**Issue by dawidry** [libredirect/libredirect#656]
What this part code is for? This anonymous e-mail address?
```

	"browser_specific_settings": {
		"gecko": {
			"id": "7esoorv3@alefvanoon.anonaddy.me",
			"strict_min_version": "67.0"
		}
	},
```

**Comment by IkelAtomig** [comment]
Email ID used to sign the extension. The ID belongs to @alefvanoon. We could change it to the address of the project. But doing so, Will create it as a new extension.

We are thinking of a way to swiftly change this.
