### ISSUE TITLE
Search redirects are broken

### ISSUE THREAD

**Issue by Ringlings** [libredirect/libredirect#657]
The website https://search.libredirect.invalid/ (which appears to be the main gateway to the search redirects) appears to be down, and has been for a while. It's somewhat annoying that we can't use the searches conveniently and I don't see it talked about here, so I'll just drop it here and see if it'll get fixed.

**Comment by IkelAtomig** [comment]
It's intended. Check here : https://libredirect.github.io/docs.html#search_engine_chromium

**Comment by Ringlings** [comment]
What would these steps be for Firefox? There's already a preset for libredirect in the search engines (presumably extension-provided) that uses that endpoint and yet does not work

**Comment by ManeraKai** [comment]
Have you enabled Search redirection in Libredirect settings page?

**Comment by Ringlings** [comment]
![image](https://user-images.githubusercontent.com/110815694/224606809-f73010a7-aa27-4d1a-a96f-63d95b45c618.png)
Pretty sure I did

**Comment by ManeraKai** [comment]
You don't have any instance selected though, https://search.libredirect.invalid is NOT an instance, it's just a "link" that LibRedirect detects to be able to redirect it to an instance say to https://baresearch.org

**Comment by Ringlings** [comment]
After adding a few instances to the list, it seems to work now. Thanks for dealing with our very apparent silliness

**Comment by ManeraKai** [comment]
Np :)
