### ISSUE TITLE
Feature Request: Different Way of Adding or Removing allowed instances.

### ISSUE THREAD

**Issue by soulspark666** [libredirect/libredirect#660]
Since there are multiple instances that are going offline every day, pinging each instance and selecting one can be quite a cumbersome task. So I was suggesting 
- To add a multi-select of sort that lets you select multiple servers, based on [Green, Yellow, Red], or [ping < 20ms, between 20 to 40 ms]
![Location to add](https://user-images.githubusercontent.com/37495396/225272224-5b4851f5-074c-4e41-8eb3-758ec2b65087.png)
- Add a button with the switch instance to remove the instance from selected, since there are instances that are hosting a cease and deceit notice, require a login, or are rate limited and will not be able to work.
![Location to add](https://user-images.githubusercontent.com/37495396/225272151-09d009e6-8e55-4983-bf75-251783c508c5.png)

**Comment by glocalglocal** [comment]
I get a lot of dead redirects. Using ping times more dynamically to add, delete and re-order instances locally would be great. 

At the very least, the available and favorite lists should be merged with a toggle for each instance. At the moment, I have to initiate pinging manually, then compare the two lists, and add/remove favorites based on ping times displayed on the available instances list. This is very tedious, I end up getting dead redirects, and sometimes I have to switch off redirections completely to get the work done.

**Comment by glocalglocal** [comment]
> I don't think they liked the idea of people just going for whatever instance had the lowest latency in the moment.

I don't think most users know enough about different instances and their changing circumstances to make an educated decision over trust. Personally, I have to assume I can't trust any instances. To me the benefit of the addon is that there is no single surveillance point.   

But if users feel they trust some instances more than others, they could define them as their favorites and then the addon could just delete the dead ones and deprioritise the very slow ones.

**Comment by Sapiosenses** [comment]
> I feel the same way. I just distinctly remember this being listed as part of the reason the previous ping system got removed for, which worked in this way, it would ping and remove from favorites based on the latency.


The "meet-halfway" solution: just disable the instances that aren't responding at all, which are basically useless at that moment in time. Un-controversial.

Then the users can do further trimming as they see fit.

**Comment by glocalglocal** [comment]
> The "meet-halfway" solution: just disable the instances that aren't responding at all, which are basically useless at that moment in time. Un-controversial.

Disabled favorites would have to be retested periodically and re-enabled if they start responding again, otherwise the tendency will be to end up with no instances because of temporary glitches. 

I think re-prioritising a user's **favorites** in line with with latency remains desirable not just for users but for instances as well because it dynamically diverts traffic from struggling favorites to favorites with spare capacity at different times. And of course it improves the experience for users. A win-win.

**Comment by maxchristman** [comment]
Perhaps this is out of the scope of this issue, but it might be useful to have a mechanism that automatically determines what instance to use using ping. The user could first select (check off) the instances that are acceptable to them. Then, every 5-10 minutes or so, a background process could ping all of these selected instances and sort them by the ping time. Now whenever the user is redirected, the extension would select the lowest-ping instance, continuing to the second lowest and so on if there is a timeout.

Now if there is a straightforward way of measuring server load for each instance, this would be great to incorporate as well. In this case, the user could set a ping threshold, which would limit them to using instances under a certain ping time. Then, the extension would periodically check the server load and sort the low-ping servers by load, choosing the lowest one.

I feel like either of these would be a large improvement from the current implementation. There are a few other considerations, such as:

1. Is there a straightforward (and thus programmatic) way of extracting the status of an instance from its URL? It would be nice to be able to eliminate instances which are down or displaying error codes.
2. If the server load on an instance cannot be determined, is it possible/desirable to do privacy-preserving telemetry to determine the number of users accessing a particular instance at a particular time? This could then be used as a stand-in so users would be automatically redirected to instances with fewer users. Perhaps this could even be done in a decentralized way with extensions users directly communicating with each other. This would be an even larger change, but instances could also decide user caps that the extension would respect.

I'd love to hear what others think of this.

**Comment by maxchristman** [comment]
I think it would be reasonable to have an option for users to automatically prioritize instances by latency. This reprioritization could be done infrequently (maybe every 10-20 minutes) and it could still be done for just the subset of instances that the user trusts. I especially think this would be beneficial because it would help to distribute the load more equally across instances. I certainly don't think this feature would be harmful to privacy, especially if users are given the option to disable it.

**Comment by ManeraKai** [comment]
3rd party random instances are headache to manage the working ones let alone trusting them, the better solution is to have those "instances" installed on your own computer: https://github.com/libredirect/frontends_manager
