### ISSUE TITLE
Twitter: remove the instance nttr.stream

### ISSUE THREAD

**Issue by pivic** [libredirect/libredirect#661]
For Twitter, the instance https://nttr.stream redirects to an ad page that looks like this:

![image](https://user-images.githubusercontent.com/7044495/225337703-9f51a0d3-632a-4a9f-9df4-af897e595b4f.png)

Hence, the instance should be removed from the code, right?

Thanks for creating a beautiful extension.

**Comment by pivic** [comment]
@Kostrol Thanks! Is there a way for me to trigger a instance–list update?

**Comment by ManeraKai** [comment]
It's fetched every time you open the settings page. But your own custom list is completely independent from the fetched list. The fetched list is "read only" you can say.
