### ISSUE TITLE
bilibili MikuInvidious backend not redirecting user page correctly

### ISSUE THREAD

**Issue by zihu12** [libredirect/libredirect#662]
## What happened?
The `space.bilibili.com/<number>` link(user page) was rediected to `<instance url>/<number>`
## What did you expect to happen?
The link was redirected to `<instance url>/space/<number>`
## Steps to reproduce:

1.Install the extension and enable bilibili redirect
2.open someone's homepage like https://space.bilibili.com/1
3.check where it goes

## Debug information:

Browser and version number:CHROME/111.0.5563.65
Libredirect version:2.5.4

## Screenshots/Videos

https://user-images.githubusercontent.com/93234588/225366716-1e246188-fc4f-4bf6-8b42-9a095e9b33df.mp4

<br>

- [x] I have checked on codeberg and github and can confirm this issue is not a duplicate.

**Comment by ManeraKai** [comment]
Was a stupid typo xD
