### ISSUE TITLE
Trusting the owner of a random instance

### ISSUE THREAD

**Issue by ManeraKai** [libredirect/libredirect#663]
1. How can I trust a random instance not logging my traffic?
2. How can I trust a random instance not changing the JS of the frontend? (adding a tracking script to fingerprint me)
3. I want to have custom settings for my frontend, I want it across all my selected instances, but having custom settings or an account can identify me.

#### SimplyTranslate Mobile way
The android client [SimplyTranslate Mobile](https://manerakai.github.io/simplytranslate_mobile) treats this issue in it's own way, and I quote:
> Random Instance Each Request to prevent giving the full context of your translation to one instance

This idea let's you blindly trust random instances to some extent, giving some of your privacy away but not the whole context.

#### Freetube way
[Freetube](https://freetubeapp.io/) has it's own "local API". So it fetches directly from youtube.com, but how it it using instances now you might ask? Well it's by using a VPN. the VPN is an "instance" now, but this approach makes you using just one VPN "instance", not a "random selection of multiple instances" like how SimplyTranslate Mobile does. However, this approach has it's own advantage of that the VPN "instance" now can NOT decrypt your traffic. On the other hand, in SimplyTranslate Mobile, the random instance reads your request to be able to send a response back.

#### 3rd way (concept)
Make LibRedirect have "local frontends". So let's say you go to https://translate.google.com, you will get redirected to https://translate.libredirect.invalid, and then, this new "local frontend page" will be able to use JS comfortably bc it can be fully trusted, and will either use the API of SimplyTranslate, or more private, use SimplyTranslate instances as just VPNs so they won't see the traffic (requires making SimplyTranslate instances have the option to act as a VPN limited to the domain name translate.google.com). However, after some trying, this is an almost impossible thing to be implemented in a "browser extension".

#### 4th way, hosting your own instances
This won't require a beefy hardware since the only user is you and your family (your local network), and most instances are already written in fast compiled languages (Rust, Crystal, Go). The main problem in this is the huge experience required to know how to run and maintain a server.

**Comment by ManeraKai** [comment]
@FireMasterK what's your opinion on this?

**Comment by MintMain21** [comment]
Shouldn't this be a Wiki entry instead of a Issue?

**Comment by ManeraKai** [comment]
No I don't want this issue to be a "guide for newbie users", I wanna fix this issue (trying to implement the 4th way in an easy fashion).

**Comment by ManeraKai** [comment]
Alright, there's now a new repository called [LibRedirect OS](https://github.com/libredirect/libredirect_os). I'm still working on it but I got libreddit working.

**Comment by oorzkws** [comment]
I think SimplyTranslate's approach, or even the current extension approach offers more privacy than self-hosting (option 4). More detailed rationale is below, but the previous sentence says about the same thing in less words.

Note: `service` here refers to the source of the data (YouTube, Reddit, etc) while `instance` refers to the private frontend in use.

**When using a public instance, your requests are just a portion of the total traffic** the instance is requesting from the service. If we randomly select instances, even if we assume some instances are acting in bad faith and selling whatever data you send it, each instance only gets a small portion of the total picture. Conversely, **if you self-host an instance, your traffic is pretty easily correlated by the service to that single household or IP**.

My opinion is the negative impact to your privacy from self-hosting is worse than the possibility of malicious instances, when visits to such instances are handled with care (e.g. disabled JS, ublock, etc). The approach of having a frontend selecting a random instance for each request is the best choice of the above, but it would be a lot of burden to maintain outside of their respective projects.

P.S. I'm sorry for giving you walls of text in a few issues, I really appreciate the work the contributors here do. Your instance list repository has even enabled me to do [other privacy-related projects](https://github.com/oorzkws/PrivateLinksBot) without having to re-invent the tooling myself.

**Comment by ManeraKai** [comment]
For anonymizing the IP address, Lokinet should be used. So now I'm just sending encrypted traffic to "Loki instances" to randomize myself instead of sending my raw traffic to regular frontend instances.
