### ISSUE TITLE
What's the source of the "Available for Chromium" graphic?

### ISSUE THREAD

**Issue by kevinlul** [libredirect/libredirect#666]
Located at https://github.com/libredirect/libredirect/blob/master/img/badge-chromium.png

![Available for Chromium](https://github.com/libredirect/libredirect/raw/master/img/badge-chromium.png)

**Comment by ManeraKai** [comment]
We made it ourselves: https://github.com/libredirect/libredirect/blob/master/img/chromium-badge.svg
