### ISSUE TITLE
Where did the instance list go?

### ISSUE THREAD

**Issue by cashida** [libredirect/libredirect#667]
I looked at some commits and found that they were stored under [src/instances/data.json](https://github.com/libredirect/libredirect/pull/601/files#diff-53b81b78effe09e590c6b93929218db13fc06c5a545151d2a2bd51d484b20fdf) but the "instances" folder is gone. Neither can I find any instances through searching the whole repo which are hardcoded in the add-on.

Am I blind?

**Comment by ManeraKai** [comment]
It's now in a separate repo: https://github.com/libredirect/instances
