### ISSUE TITLE
Actively verify instances

### ISSUE THREAD

**Issue by jwh** [libredirect/libredirect#670]
I'm sure this has been mentioned before but libredirect is actively redirecting to drive-by malware delivery urls etc as instances are not verified either at update time or later on, it seems - it should be possible to test instances for expected responses etc which will rule out most drive-by attempts.

As an example, I just got given ww1.nttr.stream as an instance which does actually attempt to deliver malware.

**Comment by Kostrol** [comment]
Firefox has saved me from a few instances as well, either malicious or just misconfigured. It can be very sketchy, especially if you don't have the right protection, something like Safe Browsing or uBlock URL lists enabled for this.

I would not put all this responsibility on Libredirect, especially with how little time the people have to maintain it as it is. I feel like this it mostly up to the maintainers of instances like Nitter to make sure to validate better the people hosting, especially if they don't have a privacy respecting official instance to use.. The best way to use Libredirect is useful for spreading your data across many instances anyway where possible, but this is one of those cases where it can be detrimental with self hosted sites, there needs to be better audits.

**Comment by jwh** [comment]
Anyone can host an instance though, libredirect could be made to check the target for expected responses either in the background or when updating instance lists, it shouldn't be hard to do but I'm not at all versed on how browser extensions work - failing that, whatever generates the instance list could do the checks - which might be better

**Comment by ManeraKai** [comment]
This should be fixed by just hosting your own instances, there's a new repo now and I'm working on it: https://github.com/libredirect/libredirect_os
