### ISSUE TITLE
Problem redirecting when hosted search instances have force implemented their own configurations in SearXNG.

### ISSUE THREAD

**Issue by Kostrol** [libredirect/libredirect#674]
I'm not sure if this is already mentioned, forgive me if so. But I have an issue where certain SearXNG instances are forcing either their own preferred frontends within the code, making it very hard to for example redirect from teddit to libreddit, when they have implemented their own hosted instance of teddit or some other example, but i want it to redirect to my favorited instances of libreddit set in libredirect. The same goes for instances of invidious when i want to use Piped, but this is not as much of a problem because i can just use the "watch on youtube" option, but it's still a bit rough having to deal with it. Especially when i use privatebrowsing for most cases and saving local preferences for 10+ instances of SearXNG is not really something I'm looking for.

Much of the toolbar options does nothing (Redirect, Switch instance) if the search result set in the hosted instance is outside of the favorites you have it seems like, for example with redirect to original, should the desired effect be to go teddit -> redirect to original (reddit) -> libredirect to favorited random instance of libreddit. 

How would you get around this?

**Comment by ManeraKai** [comment]
Did you check to see an options in the SearXNG instance to disable those redirections?

**Comment by Kostrol** [comment]
I did. There is a "hostname replace" setting in SearXNG enabled for these by default, that seems to be the cause. Even so you would have to redo these changes every time for the affected instances, preferences do not save without allowing cookies. I would not want all these random private hosted instances storing cookies.

Is there any easy way to make libredirect bypass this and go to your preferred instance?

**Comment by ManeraKai** [comment]
Nope, there isn't a way to do so in LibRedirect.
