### ISSUE TITLE
[Suggestion] Allow the selection of multiple frontends simultaneously

### ISSUE THREAD

**Issue by sereksim** [libredirect/libredirect#676]
At the moment you have to select a specific frontend for a service, e.g. piped for youtube. It would be an improvement if I could choose multiple different frontends, if I want to.
For example, most people probably don't care if they get redirected to piped or piped-material (or even invidious), but at the moment it is not possible to simply allow both.

This option could theoratically also spread the traffic more evenly, which would reduce the load on each individual instance.

**Comment by MintMain21** [comment]
Eh, I feel like all three are just distinct enough to where people would prefer one over the other. 

I flip-flop myself on which I prefer, but I generally lean towards Invidious.

**Comment by ManeraKai** [comment]
This was in Privacy Redirect I believe, but we removed it. The experience should be consistent.

**Comment by sereksim** [comment]
The experience would be consistent as long as the user wouldn't actively and knowingly select multiple frontends... 
But anyway, thanks for your answer :)
