### ISSUE TITLE
Selecting a link and pressing open link ignores imgur redirects

### ISSUE THREAD

**Issue by Latrolage** [libredirect/libredirect#68]
If there is an imgur link a webpage, if you highlight link text and press open with, it goes to the imgur image on imgur's site even if you have redirects for imgur enabled.

`https://i.imgur.com/xxxxxx.jpeg`

For example, if you select the above text and right click it and press open link, it goes to `https://i.imgur.com/xxxxxx.jpeg` even if you have imgur redirects enabled. Copying it and open it by pasting it into the URL bar, it gets redirected.

I tested youtube links and those are still redirected properly either way

**Comment by ManeraKai** [comment]
An example would be useful plz.

**Comment by Latrolage** [comment]
https://user-images.githubusercontent.com/67372293/155933130-0d1b1919-c34c-4b01-a227-ffad301b6199.mp4

Though on further inspection, it seems to work on a new firefox profile

**Comment by Latrolage** [comment]
Ok, having the `privacy.resistFingerprinting` about:config option enabled messes with it

**Comment by ManeraKai** [comment]
So you're saying it's just because you've changed some settings on your browser?

**Comment by Latrolage** [comment]
Yes
