### ISSUE TITLE
Feature Request: Custom Query Params

### ISSUE THREAD

**Issue by duarm** [libredirect/libredirect#683]
Allow for custom query params to be appended at the end of the url like this:
 ?referer=%2F%3Fdark_mode%3Dauto%26hl%3Den-US&dark_mode=auto&hl=en-US

this allows me to share configuration between multiple instances without using cookies

**Comment by ManeraKai** [comment]
Custom Queries and Unifying cookies won't be added to LibRedirect, instead we will focus on [LibRedirect Frontends Manager](https://github.com/libredirect/frontends_manager).
