### ISSUE TITLE
Trouble in settings

### ISSUE THREAD

**Issue by m-koushan** [libredirect/libredirect#69]
Hello. I've had trouble with setting preferences in extension. Every time I set a thing (for example Dark theme for invidious) and then i refresh the options page it changes back to Default again.
In new update I exported the settings to see where is the problem and I got this:
```{
  "alwaysusePreferred": false,
  "bypassWatchOnReddit": true,
  "disableSearch": true,
  "disableYoutube": false,
  "invidiousAlwaysProxy": "true",
  "invidiousNormalRedirectsChecks": [],
  "invidiousPlayerStyle": "invidious",
  "invidiousVideoQuality": "dash",
  "persistInvidiousPrefs": false,
  "redditProtocol": "normal",
  "theme": "dark-theme",
  "youtubeEmbedExceptions": {
    "url": [],
    "regex": []
  },
  "youtubeFrontend": "invidious",
  "youtubeTheme": "dark",
  "youtubeVolume": "50"
}
```
![image_2022-02-27_21-10-21.png](https://user-images.githubusercontent.com/50526840/155898119-61d4c512-6333-46f2-ba02-7234f33601fd.png)

**Comment by ManeraKai** [comment]
I think I fixed it

**Comment by ManeraKai** [comment]
Released a new version as this is a serious bug.
