### ISSUE TITLE
Qwant Maps discussion 

### ISSUE THREAD

**Issue by IronMaltese** [libredirect/libredirect#70]
[Qwant Maps ](https://github.com/Qwant/qwantmaps) is open source, so are others able to create separate instances of Qwant Maps, effectively making it fit with this project? Also Qwant Maps should be implemented because I like the UI better than OSM

**Comment by ManeraKai** [comment]
This one too: https://github.com/SimonBrazell/privacy-redirect/issues/260

**Comment by sonalder-darlene** [comment]
I would also like to have Qwant Maps

**Comment by Mennaruuk** [comment]
Pattern:

From: `https://maps.google.com/maps?q=1+hacker+way+menlo+park+california+united+states&gs_lcp=DLgCQIgAHAABQgEBlggAEBhAEADDCxdROFC6hLgICDBAEJcYAIQADwHNBAEABAQgQAIBgxBCAy3BQlOGddBoOmDIDEACABQRyQhQSChgDABMMIAIgyAQhkAEAQeAgBCyUCMCFACIgk2AAzREAAQAECExSEA2jyLEcCCQhnJcMAsoBMAAgQtxIAQgTAI0GAFMAYAIEORQgEgXLBQAIgQQIBsggn9IHIGCAAFA4ADgEDUChjwQHGxDBDATEEAI2ABxoAEEg0gMDAhAdCCoMAEAIKQBBAB6vYAADAIDAAAORIxAC4CQKxAEAGwIBhwGwEqAGMIIABuxQAIwhEA2&um=1&ie=UTF-8&sa=X&ved=wJQh2wH_2UM8I-s0KvUAaAWdD2XAQxKE5oXBjCVhAEoAhU3`

To: `https://www.qwant.com/maps/places/?q=1+hacker+way+menlo+park+california+united+states`

**Comment by ManeraKai** [comment]
https://developers.google.com/maps/documentation/urls/get-started

**Comment by ManeraKai** [comment]
How much is this used?

**Comment by Mennaruuk** [comment]
DuckDuckGo gets about 1 billion visits a month. In contrast, Qwant gets around 36 million visits a month.

**Comment by ManeraKai** [comment]
Also, does redirecting really worth it specially for desktop? I may find a use case for it with mobile phones but not for desktop.

**Comment by ManeraKai** [comment]
I can squeeze my mind and do it, but would it be worth it?!

**Comment by Mennaruuk** [comment]
The original poster preferred Qwant Maps over OpenStreetMap. They also seem to imply there might be future instances of Qwant Maps (since it’s open source). I think it’s doable, but I’m not sure how many people will benefit. I didn’t know Qwant had a map service until I stumbled upon this issue. One thing to keep in mind is that Qwant uses WebGL, which makes users prone to fingerprinting and is potentially insecure.

**Comment by IronMaltese** [comment]
I wouldn't use this feature, but i do agree it would be better for phones

**Comment by ManeraKai** [comment]
Apple maps is another thing too #116. If there was really a need then a person should've done that before and had it as a project as Apple Maps is popular. but no one made a "convertor" as really there's no need for it. Specially for a browser extension

**Comment by ManeraKai** [comment]
> I posted this mainly because I wanted to see if people would be interested in it's implementation

Till now I didn't see a comment where someone was in the **need** for it.

**Comment by sonalder-darlene** [comment]
I would like to have more options for desktop !
For OpenGL it would be nice to mention

**Comment by ManeraKai** [comment]
Do you face a google maps link and you need a convertor for it. How often is that?

**Comment by IronMaltese** [comment]
I can see a need for this, if someone looks up a restaurant or some place in their search engine and the search engine or the place's website has a link to google maps, this will redirect the person away

**Comment by ManeraKai** [comment]
There is already FacilMap and OSM

**Comment by IronMaltese** [comment]
> There is already FacilMap and OSM

No worries, you don't have to implement it if you don't want to :)

**Comment by ManeraKai** [comment]
I already started, but then gave it a though and it's not worth it. Will close this and #116

**Comment by spacekookie** [comment]
Hello!

Just found this discussion today. I've been using qwant maps on/off recently (their search used to be quite awful but has been getting better and actually usable).

I understand if support for qwant maps isn't high on your priority list. But I just wanted to weigh in and say I'd really love support for it in libredirect.

Thanks and cheers :v:
