### ISSUE TITLE
Bookmark URL Automatically Changed For Redirects

### ISSUE THREAD

**Issue by trymeouteh** [libredirect/libredirect#74]
Not sure if this is possible but when adding or editing a bookmark, if the bookmark URL is this for example which is the Piped instance you have set in the extension settings...

`https://piped.kavin.rocks/watch?v=v2AC41dglnM`

It will change the bookmark URL to this...

`https://youtube.com/watch?v=v2AC41dglnM`

This will prevent any broken bookmarks since instances do go offline and the Privacy Redirect extension will prevent you from ever accidentally going to youtube.com

Such a feature should be a setting which can be enabled/disabled in the extension settings.

**Comment by IronMaltese** [comment]
I believe this should be disabled by default, but I like the feature

**Comment by ManeraKai** [comment]
You can right click on the `Watch on YouTube` and then `Bookmark link`:

![image](https://user-images.githubusercontent.com/40805353/156616456-8713bd8f-6985-4c2c-aa33-cfe89ea9d19f.png)

**Comment by trymeouteh** [comment]
When I right click on the Watch On Youtube button I do not see boommark link option

**Comment by ManeraKai** [comment]
You sure? what browser are you using?

**Comment by trymeouteh** [comment]
Now Piped does not even have a open on Youtube button. Please consider adding this feature for easy bookmarking.

**Comment by ManeraKai** [comment]
Now there's a "Copy Raw" feature in the popup.

**Comment by EdwardLangdon** [comment]
> Now Piped does not even have a open on Youtube button. Please consider adding this feature for easy bookmarking.

There is, Click share and then choose follow link. THe New implementation is weird though.
