### ISSUE TITLE
 Extend redirects for AnonymousOverflow to Stackexchange-based sites

### ISSUE THREAD

**Issue by julianfairfax** [libredirect/libredirect#750]
[StackExchange-based sites](https://stackexchange.com/sites) are also supported by AnonymousOveflow. Would it be possible to redirect questions on them to AnonymousOverflow?

**Comment by ManeraKai** [comment]
Show me a code example there isn't any in the README.

**Comment by soulspark666** [comment]
I think this already exists:
![untitled](https://github.com/libredirect/browser_extension/assets/37495396/47587ee0-03ca-46db-b9b7-916a739dda25)
[Link](https://github.com/httpjamesm/AnonymousOverflow#how-to-make-stack-overflow-links-take-you-to-anonymousoverflow-automatically)

**Comment by julianfairfax** [comment]
> Show me a code example there isn't any in the README.

Well I'm not sure what code or README you're referring to, but I don't actually know if this request is possible, since all the URLs of these sites are different. I'm sure AnonymousOverflow works with them, but it'd be a long list of sites to redirect.

**Comment by ManeraKai** [comment]
I'm referring to the their [README](https://github.com/httpjamesm/AnonymousOverflow#readme), and in that picture @soulspark666 there's nothing talking about how to redirect ex serverfault.com with AnonymousOverflow.

**Comment by ManeraKai** [comment]
Re-open the issue if there's any updates.

**Comment by KaKi87** [comment]
Hi,
This is now possible :
> e.g. to access superuser.com you would do `/exchange/superuser.com/q/...`.
— https://github.com/httpjamesm/AnonymousOverflow/issues/17#issuecomment-2040958638

Thanks

**Comment by ManeraKai** [comment]
I think it got implemented with this [PR](https://github.com/libredirect/browser_extension/pull/914).

**Comment by KaKi87** [comment]
Nice, thanks !

It tries to redirect `api.stackexchange.com`, though :sweat_smile:

**Comment by ManeraKai** [comment]
@NoPlagiarism

**Comment by KaKi87** [comment]
Also, it looks like only `stackoverflow.com` and `*.stackexchange.com` are working, while other non-subdomain sites aren't redirected properly, e.g. `askubuntu.com` is redirected to `/questions/` instead of `/exchange/askubuntu.com/questions/`. Thanks

**Comment by NoPlagiarism** [comment]
> only `stackoverflow.com` and `*.stackexchange.com` are working

Should be fixed with next release. Mentioned in #910 & fixed in #914
