### ISSUE TITLE
Incorrectly redirects when the domain is not the service to be redirected

### ISSUE THREAD

**Issue by austinhuang0131** [libredirect/libredirect#76]
eg. https://web.archive.org/web/20220224224407/https://twitter.com/AssociatedPress/status/1496923419799015443 somehow gets redirected to <nitter instance>/web/20220224224407/https://twitter.com/AssociatedPress/status/1496923419799015443

**Comment by ManeraKai** [comment]
That's why you should put `^https?` instead of `https?` for regex. Will fix it.
