### ISSUE TITLE
Donating on Liberapay with Paypal fails

### ISSUE THREAD

**Issue by miku86** [libredirect/libredirect#79]
Hey folks,

I just wanted to send you some money on Liberapay, but it fails with Paypal.

`COMPLIANCE_VIOLATION: Transaction cannot be processed due to a possible compliance violation. To get more information about the transaction, call Customer Support.`

I couldn't find anything about this error in the Liberapay issues,  but [this stackoverflow answer](https://stackoverflow.com/questions/63783745/paypal-checkout-compliance-violation/63784263#63784263) suggests to check the receiving account.

Did you ever receive money with your paypal account or is this a new one?

Would love to support your work.

Greetings
Michael

**Comment by ManeraKai** [comment]
Maybe because my papal email wasn't the right one. Does it work now?

**Comment by miku86** [comment]
Unfortunately not, still the same error.

Do you live in a country that is *not on this list*?
https://www.paypal.com/us/webapps/mpp/country-worldwide

**Comment by ManeraKai** [comment]
I'm in turkey. Paypal isn't supported, though my paypal account isn't connected to Turkey.

**Comment by ManeraKai** [comment]
I've changed the country to United Arab Emirates. I lived there before. Hopefully it will work.

**Comment by miku86** [comment]
Nope, still not working.

Another person should try it with liberapay, maybe it's on my side, but I actually never had problems using liberapay with paypal.

**Comment by miku86** [comment]
Any news?

**Comment by ManeraKai** [comment]
Really nothing has changed since. I asked @alefvanoon if he has a Liberapay account but he doesn't.

Now I'm seeing it and it told me that my paypal account can't receive money because it's not verified. It is verified though. Readded it and I'll see how it'll go. It's not giving me an error now.

**Comment by TechD123** [comment]
Hey, just tried donating via Liberapay + Stripe, but it won't go through.. :(
