### ISSUE TITLE
Add theme settings for every redirect that needs it

### ISSUE THREAD

**Issue by IronMaltese** [libredirect/libredirect#80]
I'm using Tor Browser, so I'm not able to save my settings with a cookie, but it would be great if I was able to change the theme to dark for each redirect, or there should be an option under the dark/light theme in general, where the user can decide if dark mode applies to each redirect

**Comment by ManeraKai** [comment]
For it being in the general tab is a better idea as you said. I'll do that and support dark theme for more frontends.

**Comment by ManeraKai** [comment]
Yeah I think I finished almost all of them. Some frontends don't have light theme support and some need more work the Whoogle, but we're almost done here.

**Comment by IronMaltese** [comment]
This feature has improved so quickly, you're doing a great job man

**Comment by ManeraKai** [comment]
I tried adding the feature to Whoogle another time but I wasn't able to do it. Man I hate when the cookies are on the server side and you should access them with tokens.
Anyway, I'll close this issue as I added dark theme for every service that supports it.
