### ISSUE TITLE
[bug] Search Engine Not Loading

### ISSUE THREAD

**Issue by TheFloatingBrain** [libredirect/libredirect#82]
Hello, like this extension, better than the original! It has more features for more sites, in particular, more options for watching videos/YouTube. I have the search engine feature turned on but it does not seem to override my default search engine, I'm not sure why

**Comment by ManeraKai** [comment]
Is your default search engine yandex?

**Comment by TheFloatingBrain** [comment]
> Is your default search engine yandex?

You mean in Mozilla Firefox settings or in the extension, in the extension it's DuckDuckGo, I would like to search with Searx

**Comment by ManeraKai** [comment]
You mean in your browser settings it's set to DuckDuckGo. anyway, the targets that triggers the redirection detect only Google domains. Switch your browser default search engine to google, and it will start redirecting you to SearX. We'll add more settings for those pages in the instance settings page.

**Comment by TheFloatingBrain** [comment]
> You mean in your browser settings it's set to DuckDuckGo. anyway, the targets that triggers the redirection detect only Google domains. Switch your browser default search engine to google, and it will start redirecting you to SearX. We'll add more settings for those pages in the instance settings page.
> 
> Just to clarify, I mean this to set it to Google: ![image](https://user-images.githubusercontent.com/40805353/156827553-f6370232-9597-4b4c-9f0a-6cd9893d85bc.png)

A bit counterintuitive but okay :laughing: , maybe update the description or clarify elsewhere?  
![image](https://user-images.githubusercontent.com/1550298/156832290-6ab560b9-3ddd-4dff-9837-a31225f50ccd.png)


Also does the query ever reach Google (assuming the following is not the case)?

Also it seems like this may compromise some user's privacy because search suggestions are sometimes automatically polled from the search engine if the setting is not manually turned off (opt-out).

Maybe libredirect could set itself as a search engine/ask to be default the search engine?

**Comment by ManeraKai** [comment]
I made it as just search because I will be redirecting more engines to SearX and Whoogle.

> Also does the query ever reach Google (assuming the following is not the case)?

I think you should disable `Provide search suggestions`

> Maybe libredirect could set itself as a search engine/ask to be default the search engine?

Interesting

**Comment by TheFloatingBrain** [comment]
> I made it as just search because I will be redirecting more engines to SearX and Whoogle.
> 
I can see the google url with query is in the URL bar, then libredirect changes it, does the original URL ever go to google?

> > Also does the query ever reach Google (assuming the following is not the case)?
> 

> I think you should disable `Provide search suggestions`
> 

I do, what I am saying is that users who are a bit less savvy may not realize this, having the engine still set to Google may end up causing them to violate their privacy (as opposed to sending the query to duck duck go or other privacy friendly search engine

> > Maybe libredirect could set itself as a search engine/ask to be default the search engine?
> 
> Interesting

I personally would like that as a feature, and I think it may solve the above problem (it would probably be best to walk a user through this so they understand whats going on).

**Comment by ManeraKai** [comment]
> I can see the google url with query is in the URL bar, then libredirect changes it, does the original URL ever go to google?

No, I have it as `onBeforeRequest`. It blocks and redirects connections before even sending the url.

> I do, what I am saying is that users who are a bit less savvy may not realize this, having the engine still set to Google may end up causing them to violate their privacy (as opposed to sending the query to duck duck go or other privacy friendly search engine

DuckDuckGo is still centralized and there will be no point of SearX if the data is being sent to them. I think I should add a Note of disabling `Provide search suggestions` or as you said make LibRedirect as a search engine. Idk how to do it though.

**Comment by TheFloatingBrain** [comment]
> > I can see the google url with query is in the URL bar, then libredirect changes it, does the original URL ever go to google?
> 
> No, I have it as `onBeforeRequest`. It blocks and redirects connections before even sending the url.
> 
> > I do, what I am saying is that users who are a bit less savvy may not realize this, having the engine still set to Google may end up causing them to violate their privacy (as opposed to sending the query to duck duck go or other privacy friendly search engine
> 
> DuckDuckGo is still centralized and there will be no point of SearX if the data is being sent to them. I think I should add a Note of disabling `Provide search suggestions` or as you said make LibRedirect as a search engine. Idk how to do it though. Will search about it.

I have poked around in FF a bit to side-load things and disable default search plugin's I would be willing to help.

**Comment by ManeraKai** [comment]
If you can create a pull request containing even the basic code that I will build on it will be great!

**Comment by TheFloatingBrain** [comment]
Cool beans!

**Comment by ManeraKai** [comment]
Great news! LibRedirect is now a `Default Search Engine`

**Comment by ManeraKai** [comment]
This fixes the problems in this issue too: https://github.com/SimonBrazell/privacy-redirect/issues/194
