### ISSUE TITLE
[question] Is LibRedirect seeking to become recommended

### ISSUE THREAD

**Issue by TheFloatingBrain** [libredirect/libredirect#83]
I would love to see this extension become an officially recommended extension, is it seeking that status? Thank you so much for providing this service btw @ManeraKai its really great!

**Comment by ManeraKai** [comment]
I see no problem and hope it might be that. Some more refining in it and adding more settings to other frontends than youtube and I think it should be good to go.

**Comment by TheFloatingBrain** [comment]
> I see no problem and hope it might be that. Some more refining in it and adding more settings to other frontends than youtube and I think it should be good to go.

What needs to be refined?

**Comment by ManeraKai** [comment]
Fixing bugs. Making it consistent by having settings for all the frontends instead of just one or two at the moment. Cleaning the code and stuff like that. Nothing serious.

**Comment by TheFloatingBrain** [comment]
I cant contribute much, but any way I can help?

**Comment by ManeraKai** [comment]
Reporting a bug if you find something in your way is the best way of contributing. Thanks!

**Comment by TheFloatingBrain** [comment]
Cool beans, thanks for your awesome work!

**Comment by m77e4t** [comment]
Slightly off-topic, but related to this issue.

Ghacks.net has posted an article on Libredirect https://www.ghacks.net/2022/03/16/libredirect-loads-privacy-friendly-sites-automatically-when-you-load-youtube-search-tiktok-and-other-sites/.
