### ISSUE TITLE
YouTube/Reddit settings won't stick after latest update + can't select preferred instances

### ISSUE THREAD

**Issue by catwithbanana** [libredirect/libredirect#85]
After the most recent update my inputted settings disappear as soon as I click away from the YouTube category. They revert to Invidious no matter what. Furthermore, I'm not able to select preferred instances...the checkboxes have been replaced by a series of text input fields whose functionality is not clear.

The Reddit tab has the same issue. Both are unusable at the moment since no settings persist.

I'm using LibRedirect 1.4.8 on the latest version of Firefox on both Mac and Windows.

**Comment by ManeraKai** [comment]
A screenshot?

**Comment by catwithbanana** [comment]
Here are three screenshots.

In the pop-out menu everything always shows as activated, even if once I dig into the full menu I have deactivated it. Any toggles I switch off switch back on again as soon as i close and re-open the menu. This doesn't actually affect anything -- the activation status reflects what the full menu is set to, no matter what this pop-out menu says. But it is bothersome and means I can't quickly toggle things off and on.
![libr1](https://user-images.githubusercontent.com/75995110/156892660-3ae0894d-3d53-4da2-b177-3b7be0627e85.png)

Once I go into the full menu, YouTube and Reddit no longer preserve my settings. No matter how I change the YouTube settings, when I click away and back into this menu they reset to this:
![libr2](https://user-images.githubusercontent.com/75995110/156892661-f238e892-e92a-4993-9190-7f7c91beeb25.png)
 YouTube and Reddit redirects also turn themselves back on if I turn them off. Or at least the switches turn themselves back to on...as of right now Reddit says it's turned on but ISN'T redirecting, so who knows.

Finally the section of the menu that usually has checkboxes of different instances has been replaced with this:
![libr3](https://user-images.githubusercontent.com/75995110/156892659-c8268dbb-39d5-4c86-9148-8b1b07ddd197.png)
I have no idea what this is.

Let me know if you need any more info...thanks for your help!

**Comment by ManeraKai** [comment]
There just one thing that's stopping the whole JavaScript from running. Go to the console tab in this url: about:devtools-toolbox?id=7esoorv3%40alefvanoon.anonaddy.me&type=extension
![image](https://user-images.githubusercontent.com/40805353/156892930-02c945f4-6064-4c6a-ba5c-c4614ecd57b4.png)
It will tell you if there's any errors.

**Comment by catwithbanana** [comment]
I'm not sure what I'm supposed to be looking for, but here's what it shows when I open the menu and try changing some settings:
![image](https://user-images.githubusercontent.com/75995110/156893027-4aa37cbb-69c8-4202-beaa-9b33e9788ea3.png)

**Comment by ManeraKai** [comment]
Look for red errors like this:
![image](https://user-images.githubusercontent.com/40805353/156893064-0ff14c9c-fc3c-4a53-9b66-73e4adba5913.png)

**Comment by ManeraKai** [comment]
I think you may just uninstall and reinstall it again.

**Comment by catwithbanana** [comment]
Uninstalling and reinstalling did not fix the issue, but clicking "reset settings" did. Thank you!
