### ISSUE TITLE
Piped Material preferences are broken

### ISSUE THREAD

**Issue by mmjee** [libredirect/libredirect#86]
The PM preferences are broken because of the [usage of encodeURIComponent](https://github.com/libredirect/libredirect/commit/3ef2aa7cc112a9c0dad8cf4dc71afcb657ba095d#diff-3345fbe328c9e1f9a6613a97482438eb2e94269be4ce6feaead6023784c39c12R21). PM doesn't URL encode JSON before storing it in Local Storage.

[Additionally, I'm not sure what this is supposed to do](https://github.com/libredirect/libredirect/commit/3ef2aa7cc112a9c0dad8cf4dc71afcb657ba095d#diff-3345fbe328c9e1f9a6613a97482438eb2e94269be4ce6feaead6023784c39c12R14) aren't JS objects always compared by reference and therefore line 21 will be universally true?

![image](https://user-images.githubusercontent.com/29047033/156896064-7d32133c-ccef-4fb6-955b-76b73ff75773.png) - Aforementioned issue leads to weirdness like this.

**Comment by ManeraKai** [comment]
It's disabled right now as I know it not working. I'll take not encoding the string in mind.

**Comment by mmjee** [comment]
If it's disabled then, any ideas about what could be causing the weird %7B%7D issue?

Regards,

**Comment by mmjee** [comment]
Seems like it's fixed with 1.4.9.

Regards,

**Comment by ManeraKai** [comment]
You're right, you seem to not encode URI components. It's working now, I'll refine it a little bit and commit the fix.

**Comment by ManeraKai** [comment]
Some settings like volume aren't functional yet. Though the base structure is there and working. I'll try to add all the settings for Piped-Material and Piped too this day.

**Comment by ManeraKai** [comment]
I'll close this issue as the bug has been fixed.

**Comment by mmjee** [comment]
Hmm what's causing volume settings to not work? It's just a number from 0.01 to 1, inclusive.

Regards,
