### ISSUE TITLE
Piped embeds autoplay, regardless of setting, once one vide on the page is played.

### ISSUE THREAD

**Issue by catwithbanana** [libredirect/libredirect#87]
When reading a long page with several embeds,[ like this one](https://famiboards.com/threads/kirby-and-the-forgotten-land-demo-available-now-new-overview-trailer-update-previews-are-out-see-threadmarks.2242/page-4#post-183422), video embeds only load once you scroll past their point on the page. Piped videos respect my "Autoplay: False" setting at first, but once I choose to play a single video any video embed that loads after that point will start autoplaying. This behavior persists until the page is reloaded.

In case that's not clear, here's how I can reproduce:
- Load the page linked above
- Scroll down until the first video embed, let it load, and then press play.
- Pause that video.
- Keep scrolling down the page. From that point on all embeds will autoplay once they load.

This only happens with Piped embeds. Invidious works as expected with no unwanted autoplaying.

Thank you for your tireless work! I plan on donating some money soon to support development -- the extension is fantastic, and it's getting better and better every week.

**Comment by ManeraKai** [comment]
I think this is a piped bug rather than LibRedirect bug. @FireMasterK
