### ISSUE TITLE
[Enhancement] Auto-redirect to youtube page if instances (Piped, Invidious) cannot get video data

### ISSUE THREAD

**Issue by stephenhawk8054** [libredirect/libredirect#88]
There are some cases that a video is region-restricted in a country, and if no instances are in that region, video cannot be loaded. I think we can redirect to the youtube page in that case (so users in that region can still watch the video)?

For example, with this video: [https://www.youtube.com/watch?v=yGqSlOPhNzg](https://www.youtube.com/watch?v=yGqSlOPhNzg)

The video loads normally on youtube:
![image](https://user-images.githubusercontent.com/66517106/156925465-4dc1b650-37f4-4339-93d1-9ca5d26a07d4.png)

This is the message when loading with any Piped instances:
![image](https://user-images.githubusercontent.com/66517106/156925577-7f1be2e4-2dad-4e26-a4c0-fc499e700e47.png)

The API also shows error result: [https://pipedapi.kavin.rocks/streams/yGqSlOPhNzg](https://pipedapi.kavin.rocks/streams/yGqSlOPhNzg)
![image](https://user-images.githubusercontent.com/66517106/156925426-66961e1d-1730-49da-8cb8-08c5ffaebc4e.png)

Looks like it's restricted to be allowed in just one country (Vietnam): 
[https://watannetwork.com/tools/blocked/#url=yGqSlOPhNzg](https://watannetwork.com/tools/blocked/#url=yGqSlOPhNzg)
![image](https://user-images.githubusercontent.com/66517106/156925519-a11920e6-d309-475c-a390-17049e022f07.png)

**Comment by ManeraKai** [comment]
Press the change instance button in the popup

**Comment by stephenhawk8054** [comment]
> Press the change instance button in the popup

Oh I already tried that, but all of the instances failed with the same error.

https://user-images.githubusercontent.com/66517106/156926214-0ba42dd7-480a-472b-ac8a-7d58dd5b7093.mp4

**Comment by ManeraKai** [comment]
I don't think there's an instance in Vietnam in the first place. The instance maintainers should make vpn or proxy requests to make their ip as from that country.

**Comment by ManeraKai** [comment]
Here are piped instances locations: github.com/TeamPiped/Piped/wiki/Instances
Here are invidious instances locations: https://api.invidious.io/

**Comment by stephenhawk8054** [comment]
Yup, I know about the instances' locations problems. What I mean is could we implement a function that if all of the instances can't get video data by using Piped or Invidious API, it will redirect to youtube page? Because I think it could happen to other region-restricted videos also.

Or at least there could be a button on the popup to load that youtube link without redirection.

**Comment by ManeraKai** [comment]
I don't want to make anything automatic with LibRedirect. It will get crazy sometimes and crash the browser. We had it crazy when changing the instance if it was offline was an automatic process. Anyway, you're using Piped as a frontend, Invidious on the other hand has a link in the errors page to open the video on YouTube and the extension will allow you to do so:
![image](https://user-images.githubusercontent.com/40805353/156926805-e97d0240-61a4-4e94-90fd-2ed614130c87.png)
This feature (that link) should be in Piped too imo.

**Comment by stephenhawk8054** [comment]
I see. In that case, I think it would be better to report to Piped instead. Tks a lot 👍
