### ISSUE TITLE
Redirect links from within Anonymous Overflow

### ISSUE THREAD

**Issue by opusforlife2** [libredirect/libredirect#895]
Currently, once you open an SE link with AO, trying to open any further SE links from within that page opens the original website. This is unlike Libreddit/Redlib, for example, where all further Reddit links are converted to that instance's URLs.

I'm not sure whether this feature request is meant for this repo or the AO repo, though. Please let me know.

**Comment by ManeraKai** [comment]
> I'm not sure whether this feature request is meant for this repo or the AO repo, though. Please let me know.

It should be in AO repo.
