### ISSUE TITLE
Watch on YouTube doesnt work anymore

### ISSUE THREAD

**Issue by rezad1393** [libredirect/libredirect#90]
[Watch on YouTube] link redirects back to the invidious page.

**Comment by ManeraKai** [comment]
Check `Bypass Watch on YouTube`

**Comment by rezad1393** [comment]
did you test before writing that ?
I did test with both on and off for "Bypass Watch on YouTube".
also using toggle from toolbar button always shows all of the redirects as on. thought they seems to not all apply.

**Comment by ManeraKai** [comment]
You're saying that if you disable youtube in the popup, it doesn't and stays on right?

**Comment by rezad1393** [comment]
ignore the popup. that is another separate issue.
right now in addon setting if I enable youtube redirect then I cant open youtube website itself ever.
it always redirect to invidious and clicking on watch on youtube still goes back to invidious.


the popup always shows all redirect as on, but the setting in addon shows correct state. so popup is useless for knowing the state of on/off.

**Comment by ManeraKai** [comment]
Yeah you have a bigger problem. Try to uninstall and reinstall it, maybe resetting the settings too in the settings page.

**Comment by rezad1393** [comment]
> Yeah you have a bigger problem. Try to uninstall and reinstall it, maybe resetting the settings too in the settings page.

yeah.
that seems to fixed a lot of issues :)
I think a lot of updates for this addon messed with setting.

**Comment by ManeraKai** [comment]
>  I think a lot of updates for this addon messed with setting.

Yeah I think so.
