### ISSUE TITLE
Missing GUI element to enable/disable in FireFox

### ISSUE THREAD

**Issue by hoijui** [libredirect/libredirect#93]
On my machine:
![2022-03-08-07-45-45-area](https://user-images.githubusercontent.com/42907/157182797-3230ea8d-3fd7-45eb-82bd-1d2410c9ea04.png)

How it should look like:
![official image](https://github.com/libredirect/libredirect/raw/master/img/1.png)

```
LibRedirect 1.4.9
FireFox 91.6.0esr (64-bit)
Debian testing
```

**Comment by ManeraKai** [comment]
Is this the same for all pages? This is really weird, Have you tried uninstalling and reinstalling it?

**Comment by hoijui** [comment]
yes, it is the same for all pages.
I have reinstalled it, and same.
How would I reset the settings?

**Comment by hoijui** [comment]
To me this looks like a problem with the GUI element. I imagine, the GUI element comes from firefox itsself, and you just use it.. right? but I never had this problem with any other addon.. is it a special/self-made element?

**Comment by ManeraKai** [comment]
>  How would I reset the settings?

Go to the generals tab in the settings:
![image](https://user-images.githubusercontent.com/40805353/157311061-8be896ef-d076-4ff9-a859-94f47926310e.png)

**Comment by ManeraKai** [comment]
> To me this looks like a problem with the GUI element. I imagine, the GUI element comes from firefox itsself, and you just use it.. right? but I never had this problem with any other addon.. is it a special/self-made element?

It's just plain HTML.

**Comment by ManeraKai** [comment]
It's weird because I can see there's the `Enable` text but just the switch isn't there

**Comment by hoijui** [comment]
resetting settings did not help.
When I am in the settings, and switching from general to YouTube or Twitter and back, It takes a split-second for the page to load/draw, and during that time, I can see the contour of the switch in black&white, but when loaded it is all grey.
Maybe it is really just the visuals that are bad.. not picking up the color, or using a wrong/incompatible palette or something? (I an not good with HTML/CSS).

**Comment by ManeraKai** [comment]
Try to inspect the page and see if there's an `<input>` element in the first place:
https://user-images.githubusercontent.com/40805353/157312882-45b29b59-7aa7-4ca6-bab3-16034c5b7c45.mp4

**Comment by hoijui** [comment]
oh wow! :D
I am never had such a multimedia-richt bug hunting.. and so competent.. thank you! :-)
.. yes, the input is there!

```
<input id="disable-invidious" type="checkbox" checked="">
```

**Comment by ManeraKai** [comment]
>  .. yes, the input is there!

Then I think there's an extension that is doing something with that styling or maybe your running an old version of Firefox.

**Comment by hoijui** [comment]
disabled all other addons, restarted firefox, and same. :/

**Comment by ManeraKai** [comment]
Does it happen with other browsers?

**Comment by hoijui** [comment]
let me try with chromium ...
ouh.. that seems not to be supported.. right?
which other browsers could I try?

**Comment by ManeraKai** [comment]
It's supported. Go to the [Releases page](https://github.com/libredirect/libredirect/releases) and download the `.crx` file

**Comment by hoijui** [comment]
sorry, that took a while.
It works in chromium.

**Comment by ManeraKai** [comment]
Then something is wrong with your browser, I really don't know what is it.

**Comment by hoijui** [comment]
mmm ok.
well, thanks for the help! :-)
great tool! :-)

**Comment by ManeraKai** [comment]
Maybe last try, allow the extension to be run in private windows and test it like that.

Go to [extensions](about:addons)
Click on LibRedirect
Allow `Run in Private Windows`

**Comment by hoijui** [comment]
same :/
but thanks for the try!

**Comment by ManeraKai** [comment]
idk, I'll close the issue.

**Comment by ManeraKai** [comment]
If you saved this page as an html file: https://github.com/libredirect/libredirect/blob/master/src/pages/options/youtube/youtube.html
Try to open it in Firefox, it's the youtube page.

**Comment by hoijui** [comment]
![2022-03-08-22-14-39-area](https://user-images.githubusercontent.com/42907/157326237-a880745c-6f97-437e-8f3a-0e32806b02b6.png)
:D
... half the way there!

**Comment by ManeraKai** [comment]
Man that is so weird

**Comment by ManeraKai** [comment]
I'll release a new version maybe this day or tomorrow. Because I see there are some bugs in the page.

**Comment by hoijui** [comment]
thank you for all the effort!

**Comment by hoijui** [comment]
ouhh I see you do 3D modelling.... can you use FreeCad?
We often have need for people with that skill. "We" being a group of people trying to advance open source hardware.

**Comment by hoijui** [comment]
then again, you might not be short of work. ;-)

**Comment by hoijui** [comment]
ahhh yeah.. sorry, I always mix the two up. ;-)
(CAD and modelling)

**Comment by hoijui** [comment]
![2022-03-10-08-00-19-area](https://user-images.githubusercontent.com/42907/157606794-7d7e6bd2-f2d8-44af-9da1-17ae08c32a48.png)

On this page, there is a similar GUI "switch" element:

https://github.com/features/codespaces

I see the same problem.

**Comment by ManeraKai** [comment]
There's really a problem with your browser.

**Comment by hoijui** [comment]
..jjjjup! :-)
