### ISSUE TITLE
Medium.com sites with custom domains

### ISSUE THREAD

**Issue by Mennaruuk** [libredirect/libredirect#94]
- **Problem**: Medium.com supports custom domains.
- **Why that matters**: Sites that use Medium but have a custom domain are not redirected to Scribe.
- **A potential solution**:  Include a list of popular custom-domain Medium publishers to redirect to Scribe. 
- **Any links you can provide**: Sure!
```
towardsdatascience.com
levelup.gitconnected.com
javascript.plainenglish.io
betterprogramming.pub
blog.bitsrc.io
itnext.io
codeburst.io
uxdesign.cc
infosecwriteups.com
blog.devgenius.io
uxplanet.org
writingcooperative.com
psiloveyou.xyz
```
- **Anything else you wanna say before you doze off**: Thanks for this wonderful addon!

**Comment by ManeraKai** [comment]
There was this list buy I disabled it as there problems with the main domain. I'll read them.

**Comment by Mennaruuk** [comment]
Yeah, if it's going to unnecessarily complicate things, feel free to close! It's just that custom domains are a pain when it comes to redirecting, the pattern is gone.

**Comment by m77e4t** [comment]
Does redirector work with them? Try to see if it works via the expression entry. As according to you, it might or might not work by libredirect.

**Comment by whatbh** [comment]
These custom-domain Medium response header always contain a few fingerprints, such as:

- **content-security-policy**: frame-ancestors 'self' https://medium.com 
- **medium-fulfilled-by**: [...]
- **medium-missing-time**: [...]
- **set-cookie**: [...]; Domain=medium.com; [...]

So instead of detecting base on domain name, maybe you can catch the response header object and redirect to scribe.rip. Just an idea.

**Comment by Mennaruuk** [comment]
Thanks a lot! If you want, you can stick to a list of the most popular custom domains, I think that should cover most users. But as @whatbh mentioned, you can also have LibRedirect submit a GET request for one of the parameters mentioned and formulate an `if` statement checking if the string contains `medium.com`. However, this would have to happen on all pages, and I don't know how much of a delay it would be.

**Comment by ManeraKai** [comment]
@Mennaruuk May I ask where did you find that list?

**Comment by ManeraKai** [comment]
> BuiltWith ([High Traffic](https://trends.builtwith.com/websitelist/Medium/High-Traffic-Volume)) and ([Very High Traffic](https://trends.builtwith.com/websitelist/Medium/Very-High-Traffic-Volume))

Really interesting. The custom domains are now added. I just needed to check their authenticity. I'll close the issue 👍

**Comment by Mennaruuk** [comment]
Correct, I tested the URLs with LibRedirect, and the ones below with asterisks are the ones where they didn't redirect to Scribe:

1. The Startup — 452,478 followers
https://medium.com/swlh/when-one-upvote-is-worth-a-thousand-visitors-3e8ed27bcd3e


2. Better Humans — 304,574 followers
https://medium.com/better-humans/write-for-better-humans-4c6c9884fc08


3. UX Collective — 262,434 followers
https://uxdesign.cc/submit-your-article-to-uxdesign-cc-abea95d3a1ba


**4. Towards Data Science — 215,152 followers
https://towardsdatascience.com/contribute/home

**5. UX Planet — 199,758 followers
https://uxplanet.org/how-to-publish-your-content-on-ux-planet-fd9dc99756db


**6. The Writing Cooperative — 156,985 followers
https://writingcooperative.com/the-writing-cooperative-submission-requirements-364b0fea36cd

**7. P.S. I Love You — 125,913 followers
https://psiloveyou.xyz/p-s-i-love-you-submissions-guidelines-9a7974fe532

8. Human Parts — 99,353 followers
https://humanparts.medium.com/the-mtg-color-wheel-c9700a7cf36d

9. Slackjaw — 88,711 followers
https://medium.com/slackjaw/guidelines-for-slackjaw-submissions-f720ea4e1dfe

~~10. The Ascent — 61,045 followers
https://www.notion.so/Ascent-Submission-Guidelines-08ce7f0d33044d6a8dd9b2d7533ffe84~~

_The Ascent_ has [closed shop recently](https://medium.com/new-writers-welcome/the-ascent-publication-is-closing-c46e6b0ee020).

**Comment by ManeraKai** [comment]
All of them work fine except that 10th one as it's closing so not added. I ddin't release a new version. The changes are just in the Repo. Build it from source to test it.

**Comment by Mennaruuk** [comment]
Works like a charm. Thanks, champ.

https://user-images.githubusercontent.com/52135169/158491676-2801fea4-c9b7-44a4-98d0-10e7b22f97e4.mp4

P.S. I made a small PR adding web-ext dependency, I got an error building because I didn't have it installed.
