### ISSUE TITLE
search in firefox android doesn't works 

### ISSUE THREAD

**Issue by rajarshikhatua** [libredirect/libredirect#946]
enabling search in firefox android app doesn't search through the selected search engine in libredirect, also the extension doesn't appear on search engine list in the setting menu. is it a limitation on the android app or a bug? is there any possible workaround to it. i managed add search engine though firefox's menu but it doesn't work with the extension. thanks

**Comment by ManeraKai** [comment]
Read this: https://libredirect.github.io/docs.html#search_engine_firefox_android

**Comment by ManeraKai** [comment]
You didn't read what I sent you xD. The url is different.
