### ISSUE TITLE
maps.google.com redirects to search engine

### ISSUE THREAD

**Issue by ph00lt0** [libredirect/libredirect#95]
Going directly to maps.google.com opens a search engine instead of a maps provider.

**Comment by ManeraKai** [comment]
oh I forgot I didn't add instances to that. I added FacilMap and will update the extension this day i think.

> but shouldn't redirect regardless.

You're right.

This is the regex for detecting google maps url: /^https?:\/\/(((www|maps)\.)?(google\.).*(\/maps)|maps\.(google\.).*)/

**Comment by ManeraKai** [comment]
I found the bug and fixed it.
