### ISSUE TITLE
Don't redirect from Piped to Invidious

### ISSUE THREAD

**Issue by suy** [libredirect/libredirect#96]
Hi, and thank you very much for the extension. ❤️ 

I have Invidious as frontend for YT. In part because habit, and in part because I have some issue with Piped's embeds in some cases.

Anyway, the problem is that manually browsing piped.kavin.rocks redirects to an Invidious instance. I'm just fine having YouTube redirected to Invidious, but when manually browsing a Piped instance by typing the URL, seems weird that I am redirected on Invidious instead.

Thank you!

**Comment by ManeraKai** [comment]
Found the bug and fixed it. Will commit it soon with another fix.
