### ISSUE TITLE
[Idea/Request] Sharing some cookies between instances.

### ISSUE THREAD

**Issue by kevinlekiller** [libredirect/libredirect#97]
I'm not sure if this is possible or simple to implement, if not, please close this issue.

The idea is to somehow have the addon optionally manage certain cookies, for example, on teddit `subbed_subrredits`, or on searx `enabled_engines`, so if for example, a user is redirected to `https://teddit.zaggy.nl` then the addon checks if `https://teddit.zaggy.nl` has a newer cookie than the one stored in the addon, if not, replace it with the cookie from the addon or if `https://teddit.zaggy.nl` doesn't have the cookie, then copy the one from the addon. This way all instances use that same specific cookie. Edit: And of course, if the the user changes the cookie, like enables or disables a engine in Searx, then copy the cookie to the addon.

I'm not sure about the complexity of the addon itself monitoring changes for the cookie, perhaps this is something to do when the tab or browser is closed (I don't know if addons have some kind of destructor function)?

**Comment by ManeraKai** [comment]
I changed the code to be like that. When a setting changes, it updates the cookie to all instances that are checked. Still didn't add a way to remove cookies from unchecked instances.
```js
let theme;
let applyThemeToSites;
function initNitterCookies() {
  let themeValue;
  if (theme == 'light') themeValue = 'Twitter';
  if (theme == 'dark') themeValue = 'Twitter Dark';
  if (applyThemeToSites && themeValue != 'DEFAULT') {
    for (const instanceUrl of [...nitterNormalRedirectsChecks, ...nitterNormalCustomRedirects, ...nitterTorRedirectsChecks, ...nitterTorCustomRedirects])
      browser.cookies.set({
        url: instanceUrl,
        name: "theme",
        value: themeValue
      })
  }
}
```

**Comment by ManeraKai** [comment]
This is a bit not what you asked. This is for supporting custom settings in the extension. The thing I fear with exchanging cookies is that there's some private things that can't be shared between instances. Bibliogram has the cookies stored on it's server locally so you need a different token for every instance. I fear some private information like login details might come. That's why I'll add this feature to frontend by frontend and only share appearance and general settings to other instances.

**Comment by ManeraKai** [comment]
I'll only share settings that can be changed from the extensions settings page. Ex, youtube:
![image](https://user-images.githubusercontent.com/40805353/157573236-e707a876-3143-4d6c-9b24-16ccca1cfe3b.png)
And I'll add support for more settings day by day.

**Comment by ManeraKai** [comment]
I have finished adding almost all the settings for Invidious, Piped, Piped-Material. I share settings that are not sensitive and can be public. I'll close this issue as it's been implemented and will complete working on it.
