### ISSUE TITLE
Change default redirections

### ISSUE THREAD

**Issue by IronMaltese** [libredirect/libredirect#98]
I find that Lingva is much more usable than Simplytranslate for the sole reason that it has an instant translate feature, and if that can be implemented as a setting in this extension and enabled by default, that would make translating by default 10x more useful

Also I think Whoogle should be the default instead of Searx for the sole reason that Searx instances are very unreliable with the search engines they choose, and using Searx without JavaScript is a mess navigating tabs and sometimes search results don't even show up without JavaScript

I think this would greatly improve usability of the extension for first time users

**Comment by ManeraKai** [comment]
you can press CTRL+ENTER on simplytranslate and it will submit the translation.

> Also I think Whoogle should be the default instead of Searx for the sole reason that Searx instances are very unreliable with the search engines they choose, and using Searx without JavaScript is a mess navigating tabs and sometimes search results don't even show up without JavaScript

Whoogle is much more simple. I think so.

**Comment by ManeraKai** [comment]
Hello @IronMaltese?

**Comment by IronMaltese** [comment]
Hello @ManeraKai I still think that Whoogle and Lingva should be defaults

**Comment by IronMaltese** [comment]
Idk how rate limiting exactly affects whoogle being set as default, but if you don't wanna do either, that's okay

**Comment by ManeraKai** [comment]
> Hello @ManeraKai I still think that Whoogle and Lingva should be defaults

bruh...

There's a feature that display alternative definitions and alternative translations coming to SimplyTranslate soon. This will just make it superior to Lingva

**Comment by ManeraKai** [comment]
Didn't find the full desktop screenshot, but here is the mobile preview:
![mobile_screen_simplyTranslate_css_grid](https://user-images.githubusercontent.com/40805353/158366654-dbb1232e-e3e6-4ac7-958b-206ecc8b4ff7.png)

**Comment by alefvanoon** [comment]
SimplyTranslate is better for me.

**Comment by IronMaltese** [comment]
I’m glad we discussed this since this extension should have the best settings by default, I’ll close this issue now

**Comment by ManeraKai** [comment]
?

**Comment by IronMaltese** [comment]
Should I not have closed the issue?

**Comment by ManeraKai** [comment]
No, about your opinion on SimplyTranslate. I think you may be facing issues because of instances not updating well?

**Comment by IronMaltese** [comment]
Oh, no I only prefer Lingva because of it's instant translate feature, using Simply without it feels very clunky and I don't want other people having a bad experience with this extension

**Comment by ManeraKai** [comment]
For me it really doesn't differ If I can just press a shortcut that is common with telegram and twitter to submit. You can write your input and erase any sensitive information before it's being automatically sent like with Lingva. Different preferences and opinions though. Thankfully anyone who doesn't like SimplyTranslate can change easily.
