### ISSUE TITLE
Add label for sites using Cloudflare

### ISSUE THREAD

**Issue by IronMaltese** [libredirect/libredirect#99]
Is there a way to automatically detect if a frontend uses Cloudflare and disable ones that do

**Comment by IronMaltese** [comment]
This should be a setting in general that's off by default

**Comment by ManeraKai** [comment]
You don't want support for Cloudflare?

**Comment by IronMaltese** [comment]
I'm just wondering if it would be possible to avoid frontends that use cloudflare

**Comment by ManeraKai** [comment]
For example of a url or details about a request?

**Comment by IronMaltese** [comment]
Any way to fix that problem would be fine

**Comment by ManeraKai** [comment]
Why though?

**Comment by IronMaltese** [comment]
<img width="1084" alt="Screen Shot 2022-03-09 at 21 21 19" src="https://user-images.githubusercontent.com/89056889/157575702-65635633-ee72-4945-b183-8233504979fe.png">

**Comment by IronMaltese** [comment]
This is a whoogle instance

**Comment by ManeraKai** [comment]
Does this setting help? Auto Redirect of offline instances

**Comment by IronMaltese** [comment]
It does not, it should detect that even when the cloudflare server is up, the main website has to be up aswell

**Comment by IronMaltese** [comment]
Even pressing update instances in settings doesn't fix it

**Comment by ManeraKai** [comment]
I think it detects that the page is offline but can't redirect as it has no url so you'll think it didn't detected it.

**Comment by IronMaltese** [comment]
But shouldn't the site go away when pressing Update instances

**Comment by ManeraKai** [comment]
oh you're right, the url hasn't changed. Is that instance in your custom list in the extension?

**Comment by IronMaltese** [comment]
It's not

**Comment by ManeraKai** [comment]
Added to the custom instances so it can detect that it's one of your instances.

**Comment by IronMaltese** [comment]
> Add to the custom instances so it can detect that it's one of your instances.

Why should I be adding it to custom instances and what do you mean that it's one of my instances

**Comment by ManeraKai** [comment]
How will LibRedirect know that this is a SearX instance otherwise? It should be in the list to declare that this is one of the SearX instances. If it became offline, LibRedirect will know that this offline site is in fact one of my SearX instances so I should redirect to another online instance.

**Comment by IronMaltese** [comment]
<img width="1074" alt="Screen Shot 2022-03-09 at 22 25 45" src="https://user-images.githubusercontent.com/89056889/157582623-5e0d9c83-699d-4cba-b45b-9cffe25bf8e3.png">
This instance was already listed as a Whoogle instance, so I shouldn't need to add it to my instances

**Comment by ManeraKai** [comment]
oh sorry, was looking at the SearX list instead of whoogle's. my bad

**Comment by ManeraKai** [comment]
I didn't get the cloudflare error until I added a search query, but it did auto redirect fine from it. This is from the last version 1.5.0

**Comment by whatbh** [comment]
I see this issue is about Cloudflare downtime, but I also have a small opinion on Cloudflare that I think I should say it out, despite not relating to the downtime. 

Tor and Cloudflare don't play nice with each other, they see each other as trouble (see [what Cloudflare say](https://blog.cloudflare.com/the-trouble-with-tor/) and [what Tor say](https://blog.torproject.org/trouble-cloudflare/)). And there are many people have written about their attitude toward CDNs. 

The point is, I see Libredirect has option to use Tor but currently no option to make it work with Cloudflare, so I'm not sure if this will burden @ManeraKai with too much work, but I can think of two ways to settle this down: 

- Add a label to indicate which instance is on Cloudflare so that people can make up their mind (Take Piped for example, mint.lgbt is hosted on Ovh while the rest are on Cloudflare) 
- Or integrate mutual exclusion of Cloudflare into the "Tor" option already in Libredirect, i.e. (1) use Tor and no Cloudflare, or (2) don't use Tor and allow Cloudflare, this will also needs to categorize instances into Clouflare/non–Cloudflare anyway.

**Comment by ManeraKai** [comment]
@whatbh  I may add this feature, but I should finish the other issues first 👍

**Comment by whatbh** [comment]
Cool! Take your time. Thanks a lot.

Maybe in the meantime I can help to filter the host in the following list. I dunno, hope it helps. 
<details>
  <summary>List of instances and hosting facilities</summary>

invidious
https://yewtu.be [Oracle Svenska Ab]
https://invidious.snopyta.org [Hetzner Online Gmbh]
https://vid.puffyan.us [Ovh Sas]
https://invidious.kavin.rocks [Cloudflare Inc]
https://invidio.xamh.de []
https://inv.riverside.rocks [Avaya Inc]
https://invidious-us.kavin.rocks [Cloudflare Inc]
https://invidious.osi.kr []
https://tube.cthd.icu [Serbia Broadband - Srpske Kablovske Mreze]
https://invidious.flokinet.to [Flokinet Ltd]
https://yt.artemislena.eu [Deutsche Telekom Ag]
https://invidious.weblibre.org [Zglobalhost Ltda]
https://youtube.076.ne.jp [Gmo Cloud K.k]
https://invidious.privacy.gd [Data Room, Inc]
https://invidious.esmailelbob.xyz [Ovh Hosting]
https://invidious.namazso.eu [Enzu Inc]
nitter
https://nitter.net [Henkel Ag & Co Kgaa]
https://nitter.42l.fr []
https://nitter.pussthecat.org [Mts]
https://nitter.nixnet.services [Celestica International]
https://nitter.fdn.fr [Association Gitoyen]
https://nitter.1d4.us [Ovh Hosting]
https://nitter.kavin.rocks [Oracle Public Cloud]
https://nitter.unixfox.eu [Oracle Public Cloud]
https://nitter.domain.glass [Cloudflare]
https://nitter.eu [Hetzner Online Gmbh]
https://nitter.namazso.eu [Enzu Inc]
https://nitter.actionsack.com [Cloudflare Inc]
https://birdsite.xanny.family [Cloudflare Inc]
https://nitter.hu [Atw Internet Kft]
https://twitr.gq [Cloudflare Inc]
https://nitter.moomoo.me [Cloudflare Inc]
https://nittereu.moomoo.me [Cloudflare Inc]
https://bird.trom.tf [Arapahoe School District #6]
https://nitter.it [Nexinto Gmbh]
https://twitter.censors.us [Ovh Sas]
https://nitter.grimneko.de [Hetzner Online Gmbh]
https://nitter.alefvanoon.xyz [Cloudflare Inc]
https://n.hyperborea.cloud [Bell Canada]
https://nitter.ca [Linode]
https://twitter.076.ne.jp [Gmo Cloud K.k]
https://nitter.mstdn.social [Dow Jones & Co]
https://nitter.fly.dev [Momax Network S.r.l]
https://notabird.site [Cloudflare Inc]
https://nitter.weiler.rocks [Netcup Gmbh]
https://nitter.silkky.cloud [Cloudflare Inc]
https://nitter.sethforprivacy.com [Hetzner Online Gmbh]
https://nttr.stream [Colocrossing]
https://nitter.cutelab.space [Eastex Telephone Cooperative, Inc]
https://nitter.nl [Liteserver Holding B.v]
https://nitter.mint.lgbt [Ovh Hosting]
https://nitter.bus-hit.me [Oracle Public Cloud]
https://fuckthesacklers.network [Cloudflare Inc]
https://nitter.govt.land [Cloudflare Inc]
https://nitter.datatunnel.xyz [Celestica International]
https://nitter.esmailelbob.xyz [Ovh Hosting]
https://tw.artemislena.eu [Deutsche Telekom Ag]
https://de.nttr.stream [Nexinto Gmbh]
https://nitter.winscloud.net [Cloudflare Inc]
https://nitter.tiekoetter.com [Mike Kaldig]
https://nitter.spaceint.fr [Brutele Sc]
https://twtr.bch.bar [Cloudflare Inc]
https://nitter.exonip.de [Boulder Valley School District]
https://nitter.mastodon.pro [Oracle Public Cloud]
https://nitter.notraxx.ch [University Of Winnipeg]
bibliogram
https://bibliogram.art [Prometeus Di Daniela Agro]
https://bibliogram.snopyta.org [Hetzner Online Gmbh]
https://bibliogram.pussthecat.org [Mts]
https://bibliogram.1d4.us [Ovh Hosting]
https://insta.trom.tf [Arapahoe School District #6]
https://bib.riverside.rocks [Avaya Inc]
https://bibliogram.esmailelbob.xyz [Ovh Hosting]
https://insta.tromdienste.de [Boulder Valley School District]
https://bib.actionsack.com [Cloudflare Inc]
https://biblio.alefvanoon.xyz [Cloudflare Inc]
teddit
https://teddit.net [Hetzner Online Gmbh]
https://teddit.ggc-project.de [Hetzner Online Gmbh]
https://teddit.kavin.rocks [Cloudflare Inc]
https://teddit.zaggy.nl []
https://teddit.namazso.eu [Enzu Inc]
https://teddit.tinfoil-hat.net [Boulder Valley School District]
https://teddit.domain.glass [Cloudflare]
https://snoo.ioens.is []
https://teddit.httpjames.space [Asiatech Dsl Broadband Services]
https://teddit.alefvanoon.xyz [Cloudflare Inc]
https://incogsnoo.com []
https://teddit.pussthecat.org [Mts]
https://reddit.lol [E - Vision Internet]
https://teddit.sethforprivacy.com [Hetzner Online Gmbh]
https://teddit.totaldarkness.net [Saginaw Valley State University]
https://teddit.adminforge.de [Hetzner Online Gmbh]
https://teddit.bus-hit.me [Oracle Public Cloud]
wikiless
https://wikiless.org [Critical Path]
https://wikiless.alefvanoon.xyz [Cloudflare Inc]
https://wikiless.sethforprivacy.com [Hetzner Online Gmbh]
https://wiki.604kph.xyz [Cloudflare Inc]
scribe
https://scribe.rip [Greenhost Bv]
https://scribe.nixnet.services [Celestica International]
https://scribe.citizen4.eu [Phu Hajdamowicz Miroslaw Hajdamowicz]
https://scribe.bus-hit.me [Oracle Public Cloud]
simplyTranslate
https://simplytranslate.org [Vocus]
https://st.alefvanoon.xyz [Cloudflare Inc]
https://translate.josias.dev [Frontier Communications Of America, Inc]
https://translate.namazso.eu [Enzu Inc]
https://translate.riverside.rocks [Avaya Inc]
https://translate.bus-hit.me [Oracle Public Cloud]
https://simplytranslate.pussthecat.org [Mts]
https://translate.northboot.xyz [Netcup Gmbh]
https://translate.tiekoetter.com [Mike Kaldig]
lingva
https://lingva.ml [Carolina Internet, Ltd]
https://translate.alefvanoon.xyz [Carolina Internet, Ltd]
https://translate.igna.rocks [Amazon.com]
https://lingva.pussthecat.org [Mts]
https://translate.datatunnel.xyz [Celestica International]
https://lingva.esmailelbob.xyz [Ovh Hosting]
https://translate.plausibility.cloud [Hetzner Online Gmbh]
searx
https://anon.sx []
https://darmarit.org/searx [Netcup Gmbh]
https://dynabyte.ca [Mts Inc]
https://engo.mint.lgbt [Ovh Hosting]
https://jsearch.pw [Choopa, Llc]
https://nibblehole.com [Softplus Entwicklungen Gmbh]
https://northboot.xyz [E - Vision Internet]
https://paulgo.io [Ovh Sas]
https://procurx.pt []
https://s.zhaocloud.net [Ovh Sas]
https://search.antonkling.se [Routelabel V.o.f]
https://search.asynchronousexchange.com [1&1 Internet Se]
https://search.bus-hit.me [Oracle Public Cloud]
https://search.disroot.org [Serverius Holding B.v]
https://search.ethibox.fr [Online S.a.s]
https://search.jpope.org [Qwest Communications Company, Llc]
https://search.mdosch.de []
https://search.neet.works [Frantech Solutions]
https://search.ononoki.org [Colocrossing]
https://search.snopyta.org [Hetzner Online Gmbh]
https://search.st8.at [Rh - Tec Business Gmbh]
https://search.stinpriza.org [Hetzner Online Gmbh]
https://search.trom.tf [Arapahoe School District #6]
https://search.zdechov.net [Internext 2000, S.r.o]
https://search.zzls.xyz [Zam Ltda]
https://searx-private-search.de [Mike Kaldig]
https://searx.bar [Oracle Public Cloud]
https://searx.be [Oracle Public Cloud]
https://searx.bissisoft.com [Linode, Llc]
https://searx.divided-by-zero.eu [Contabo Gmbh]
https://searx.dresden.network []
https://searx.ebnar.xyz [Hetzner Online Gmbh]
https://searx.esmailelbob.xyz [Ovh Hosting]
https://searx.everdot.org [Telia Company Ab]
https://searx.fmac.xyz [Exoscale Open Cloud Gv]
https://searx.fossencdi.org [Keyweb Ag Ip Network]
https://searx.gnous.eu [Hivane]
https://searx.gnu.style [Dansk Kabel Tv]
https://searx.hardwired.link [Netcup Gmbh]
https://searx.josie.lol [Cloudflare Inc]
https://searx.lavatech.top [Cloudflare Inc]
https://searx.mastodontech.de []
https://searx.mha.fi [Oracle Public Cloud]
https://searx.mxchange.org [Host Europe Gmbh]
https://searx.nakhan.net [Ovh Sas]
https://searx.netzspielplatz.de [Hetzner Online Gmbh]
https://searx.nevrlands.de [Netcup Gmbh]
https://searx.ninja [Linode, Llc]
https://searx.nixnet.services [Celestica International]
https://searx.openhoofd.nl [Zeelandnet Bv]
https://searx.operationtulip.com [Bahnhof Ab]
https://searx.org [Cloudflare Inc]
https://searx.prvcy.eu [Hetzner Online Gmbh]
https://searx.pwoss.org []
https://searx.rasp.fr [Free Sas]
https://searx.roughs.ru [Cloudflare Inc]
https://searx.ru [Hetzner Online Gmbh]
https://searx.run [Cloudflare Inc]
https://searx.sadblog.xyz [Choopa, Llc]
https://searx.semipvt.com [Ovh Sas]
https://searx.slash-dev.de [Host Europe Gmbh]
https://searx.solusar.de [Bsb Service Virtual Dedicated Server Hosting]
https://searx.sp-codes.de [1&1 Versatel Deutschland Gmbh]
https://searx.stuehieyr.com [Alabanza, Inc]
https://searx.theanonymouse.xyz [Hetzner Online Gmbh]
https://searx.thegreenwebfoundation.org [Hetzner Online Gmbh]
https://searx.tiekoetter.com [Mike Kaldig]
https://searx.tk [Cloudflare Inc]
https://searx.tux.land [Yellow Transportation]
https://searx.tuxcloud.net [Master Internet S.r.o]
https://searx.tyil.nl [Critical Path]
https://searx.webheberg.info [Ovh Sas]
https://searx.xkek.net [E - Vision Internet]
https://searx.xyz [Hostus]
https://searx.zapashcanon.fr [Main Ikoula Backbone Network]
https://searx.zecircle.xyz [Critical Path]
https://searxng.zackptg5.com [Shock Hosting Llc]
https://serx.cf [Colocrossing]
https://spot.ecloud.global [National Science Center Foundation]
https://suche.dasnetzundich.de [Critical Path]
https://suche.tromdienste.de [Boulder Valley School District]
https://suche.uferwerk.org [Hetzner Online Gmbh]
https://swag.pw [Linode, Llc]
https://sx.catgirl.cloud [Hetzner Online Gmbh]
https://timdor.noip.me/searx [At&t Services, Inc]
https://trovu.komun.org [Contabo Gmbh]
https://www.gruble.de [Hetzner Online Gmbh]
https://www.webrats.xyz [Oracle Corporation]
https://searx.roflcopter.fr [Institute Of Rhythmology Of Evdokiya Marchenko]
whoogle
https://gowogle.voring.me [Ministre Des Forests, Govt Of Quebec]
https://s.alefvanoon.xyz [Cloudflare Inc]
https://search.albony.xyz [Cloudflare Inc]
https://search.garudalinux.org [Alabanza, Inc]
https://search.sethforprivacy.com [Hetzner Online Gmbh]
https://whoogle.fossho.st [Legaco Networks B.v]
https://whooglesearch.net [Ginernet S.l]
https://www.whooglesearch.ml [Google Cloud]
https://whoogle.dcs0.hu [Liberty Global Operations B.v]
https://whoogle.esmailelbob.xyz [Ovh Hosting]
rimgo
https://i.bcow.xyz [Hewlett - Packard Company]
https://rimgo.bcow.xyz [At&t Internet Services]
https://rimgo.pussthecat.org [Mts]
https://img.riverside.rocks [Avaya Inc]
https://rimgo.totaldarkness.net [Saginaw Valley State University]
https://rimgo.bus-hit.me [Oracle Public Cloud]

</details>

<details>
  <summary>scraper.py</summary>

```python
#use API provided by myip.ms
import requests, json
res=requests.get('https://raw.githubusercontent.com/libredirect/libredirect/master/src/instances/data.json')
text=json.loads(res.text)
for item in text:
    print(item)
    for elem in text[item]['normal']:
        hexed=''.join(hex(ord(char))[2:] for char in elem)
        infoRes=requests.get('https://plugin.myip.ms/hex_'+hexed)
        if infoRes.text != "No Data":
            if infoRes.text != "Invalid Domain Name":
                infoText=json.loads(infoRes.text)
                print(elem+' ['+infoText['hosting']+']')
```

</details>

**Comment by ManeraKai** [comment]
Keep this open or open a new issue that has Cloudflare instances declaration feature.

**Comment by Elaborendum** [comment]
Is the first reported issue still present, or should the extension now redirect offline Cloudflare instances to a working instance and I should open a new issue about it not doing so on my end?

**Comment by ManeraKai** [comment]
What's the instance that it's not redirecting?

**Comment by Elaborendum** [comment]
So far, teddit.kavin.rocks. The extension sometimes redirects to it and just leaves it there.

**Comment by ManeraKai** [comment]
I was trying to strict this automatic function so I strict it to just `503` `504` status codes. I'll add `502` too.

**Comment by ManeraKai** [comment]
The only lists that add a declaration that if the instance is using cloud flare or not are bibliogram, libreddit.

**Comment by ManeraKai** [comment]
Though I found this website: https://cloudflare.hellafast.digital/

**Comment by ManeraKai** [comment]
Made this script:
is_cloudflare.py
```python
import socket
import subprocess

def isCloudflare(url):
    x = urlparse(url)
    ip = socket.gethostbyname(x.hostname)
    r = requests.get('https://www.cloudflare.com/ips-v4')
    myList = r.text.split('\n')

    for i in myList:
        out = subprocess.run(["sh", "./src/instances/get_possible_ips.sh", i], capture_output=True, text=True)
        if ip in out.stdout.splitlines():
            return True

    return False

print(isCloudflare('https://bib.actionsack.com'))
```
possible_ips.sh
```bash
nmap -sL -n $1 | awk '/Nmap scan report/{print $NF}'
```

**Comment by ManeraKai** [comment]
And it's working!
![image](https://user-images.githubusercontent.com/40805353/163678625-18d62f2d-3101-47a9-9195-1a486f4fa6f6.png)
